### ISSUE TITLE
<class 'TypeError'> on bulk edit of devices

### ISSUE THREAD

**Issue by robbagithub** [netbox-community/netbox#4188] opened 2020-02-18 04:45 UTC
### Environment
* Python version:   3.6.9
* NetBox version:   2.7.6

### Steps to Reproduce
1. Click on 'Devices' option in Devices drop down on home page
2. Select all devices for editing by choosing the tick box to the left of "Name" on device grid
3. Confirm that all devices are to be edited
4. Click the yellow/orange button called "Edit All"

### Expected Behavior
1. Click on 'Devices' option in Devices drop down on home page
2. Select all devices for editing by choosing the tick box to the left of "Name" on device grid
3. Confirm that all devices are to be edited
4. Click the yellow/orange button called "Edit All"
5. Be presented with Device Editing page

### Observed Behavior
1. Error page showed as below
![error](https://user-images.githubusercontent.com/22147754/74704709-83861b00-5265-11ea-8d05-0a939597847b.jpg)

**Comment by lampwins** [comment] 2020-02-18 04:50
Duplicate of #4175

**Closed by lampwins** 2020-02-18 04:50 UTC

**Comment by robbagithub** [comment] 2020-02-21 00:53
This is not fixed in 2.7.7
