### ISSUE TITLE
Multi-chassis Link Aggregation Group

### ISSUE THREAD

**Issue by mjf** [netbox-community/netbox#5916] opened 2021-03-03 11:22 UTC
### Environment
* NetBox version: 2.10.5 

### Proposed Functionality
Add support for [MC-LAG](https://en.wikipedia.org/wiki/Multi-chassis_link_aggregation_group), please.

### Use Case
To model MC-LAG.

### Database Changes
Dunno.

### External Dependencies
Dunno.

**Comment by jeremystretch** [comment] 2021-03-03 15:23
Duplicate of #2830

**Closed by jeremystretch** 2021-03-03 15:23 UTC
