### ISSUE TITLE
Ability to create "role-groups" 

### ISSUE THREAD

**Issue by AnthoBalitrand** [netbox-community/netbox#9643] opened 2022-07-01 08:30 UTC
### NetBox version

v3.2.5

### Feature type

Data model extension

### Proposed functionality

Add the ability to create "role-groups" to bundle several roles. 

### Use case

It would help to keep a good granularity in the roles assigned to the devices, while being able to bundle them if we have to match a lot of roles in config contexts.

**Comment by jeremystretch** [comment] 2022-07-27 15:33
> Add the ability to create "role-groups" to bundle several roles.

Is the proposal here to introduce a _new_ model to represent groups of roles, or to make the existing model(s) self-nesting?

Consider the following pretend hierarchy of device roles:

* Switch
  * Access switch
  * Distribution switch
  * Core switch
* Router
  * Edge router
  * Branch router
* Firewall

In this example, would Switch, Router, and Firewall be assignable as device roles, or would only their children be assignable?

**Comment by jeremystretch** [comment] 2022-07-27 18:36
Actually, this seems like a duplicate of #6290.

**Comment by jeremystretch** [comment] 2022-08-03 12:16
Agreed; let's role this into #6290. That FR is currently blocked pending investigation into a potential replacement for django-mptt.

**Closed by jeremystretch** 2022-08-03 12:16 UTC
Labels: type: feature, status: revisions needed
