### ISSUE TITLE
Get `Device` in REST API doesn't include `DeviceType.device_count` as described in Swagger schema

### ISSUE THREAD

**Issue by janhlavin** [netbox-community/netbox#16418] opened 2024-06-05 09:25 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.11

### Steps to Reproduce

1. create Manufacturer, Device type, Device role, Site and Device
2. call GET to /api/dcim/devices/$DeviceID/

### Expected Behavior

return:

```json
{
 "id": 1,
 "device_type": {
  "id": 1,
  "device_count": 1,
  "...": "..."
 },
 "...": "..."
}
```

### Observed Behavior

return:

```json
{
 "id": 1,
 "device_type": {
  "id": 1,
  "...": "..."
 },
 "...": "..."
}
```

### Narrative (from comments below, edited somewhat for clarity)
The main trouble is that there's an inconsistency between the Swagger schema and the actual API responses. The actual response fails to validate against the example schema provided by Swagger. This causes problems when using strongly-typed API client frameworks to generate code that talks to NetBox.

I don't need the property `device_count` as a child of `device_type`. A change in the Swagger definition, declaring `device_type` to be of type `NestedDeviceType` is fine and will fix this bug for my purposes.

**Comment by tgoodsell-tempus** [comment] 2024-06-05 18:55
I'm seeing similar behavior for the `prefix_count` attribute embedded in the `vrf` object of a Prefix:

1. Call `GET https://hostname/api/ipam/prefixes/`

Return:
```
{
    "count": 4,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 3,
            "url": "https://hostname/api/ipam/prefixes/3/",
            "display": "10.64.0.0/11",
            "family": {
                "value": 4,
                "label": "IPv4"
            },
            "prefix": "10.64.0.0/11",
            "site": null,
            "vrf": {
                "id": 1,
                "url": "https://hostname/api/ipam/vrfs/1/",
                "display": "ZRO",
                "name": "ZRO",
                "rd": null,
                "description": ""
            },
            "tenant": null,
            "vlan": null,
            "status": {
                "value": "container",
                "label": "Container"
            },
            "role": null,
            "is_pool": true,
            "mark_utilized": false,
            "description": "ZRO",
            "comments": "",
            "tags": [],
            "custom_fields": {},
            "created": "2024-05-14T00:26:48.400795Z",
            "last_updated": "2024-05-14T00:26:48.400812Z",
            "children": 1,
            "_depth": 0
        },
        ...
```

Expected schema (from https://hostname/api/schema/swagger-ui/#/ipam/ipam_prefixes_list):
```
{
  "count": 123,
  "next": "http://api.example.org/accounts/?offset=400&limit=100",
  "previous": "http://api.example.org/accounts/?offset=200&limit=100",
  "results": [
    {
      "id": 0,
      "url": "string",
      "display": "string",
      "family": {
        "value": 4,
        "label": "IPv4"
      },
      "prefix": "string",
      "site": {
        "id": 0,
        "url": "string",
        "display": "string",
        "name": "string",
        "slug": "lt35brDofIze9mWTFO78eHPXsP-lqRLkbhUxRluQT66YdsdBXIAAdM1ZAIKNO_f-mR7PM5GDcKzhfsnZE-6kuX0W6MzqH",
        "description": "string"
      },
      "vrf": {
        "id": 0,
        "url": "string",
        "display": "string",
        "name": "string",
        "rd": "string",
        "description": "string",
        "prefix_count": 0
      },
```

Causes issues with strongly typed SDKs like the `go-netbox` sdk (ref: https://github.com/netbox-community/go-netbox/issues/177)

**Comment by jeffgdotorg** [comment] 2024-06-06 21:44
Thanks for reporting a problem you've encountered in NetBox.

Do I understand correctly that you expect to see `device_type.device_count` in the response to `/api/dcim/devices/{id}/` because the example schema produced by the Swagger UI specifies its presence?

If so, please update the issue body to clarify the reason for your expectation. As a person who's only somewhat familiar with OpenAPI, understanding why this is a problem took me quite some time.

**Comment by janhlavin** [comment] 2024-06-07 07:01
main trouble is in inconsistency Swagger schema and real API responses - I don't need property "device_count" in "device_type" => change in Swagger definition, where "device_type" is type of "NestedDeviceType" is fine and fix this bug

**Comment by jeffgdotorg** [comment] 2024-06-07 13:46
Thanks for clarifying the practical impact. I've adapted your previous comment and included it at the bottom of the issue body.

**Comment by jeffgdotorg** [comment] 2024-06-07 20:36
I just spotted #16085 which captures the same underlying problem as this issue. Resolving this one as a duplicate.

**Comment by jeffgdotorg** [comment] 2024-06-07 20:37
Duplicate of #16085

**Closed by jeffgdotorg** 2024-06-07 20:37 UTC
Labels: type: bug, status: needs owner, severity: medium
