### ISSUE TITLE
Limit clickable width of filter form row

### ISSUE THREAD

**Issue by julianstolp** [netbox-community/netbox#15678] opened 2024-04-10 07:16 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta1

### Python Version

3.10

### Steps to Reproduce

1. Go to any model
2. Open the `Filters` tab
3. Every field is clickable to the most left side of the card

Similar issue https://github.com/netbox-community/netbox/issues/15620

### Expected Behavior

The filters should be styled like any other edit form in NetBox for consistency reasons.
At least dropdown fields should not be clickable the full row like in 3.7.x realeases. 

### Observed Behavior

1. Clickable on full row width which is rather annoying if dropdown gets opened if you did not even click near the field or label.
![image](https://github.com/netbox-community/netbox/assets/41152397/659227cc-f920-4b49-bee3-043213a128b2)

**Comment by aryansanchiya** [comment] 2024-04-11 06:27
I think not every field is clickable from the left side of the card, there is only one field is clickable from the left side of the card and its "search" field.

**Comment by arthanson** [comment] 2024-04-30 22:41
Actually this is the way bootstrap works, if you go to other forms the form width is narrower so the clickable area on the left is narrower, if you click on the far-left side it doesn't select, but if you click further to the right it will select just like on the filters form (see red block in screenshot).  You can actually see the same behavior with the bootstrap examples (but to the right of the label as they are left aligned) at https://getbootstrap.com/docs/5.3/forms/layout/#horizontal-form-label-sizing

Closing as by design.
![Monosnap Add a new device | NetBox 2024-04-30 15-38-10](https://github.com/netbox-community/netbox/assets/99642/d93b2966-94c0-4922-83f3-88812b2d9f95)

**Closed by arthanson** 2024-04-30 22:41 UTC
Labels: type: bug, beta, severity: low

**Comment by julianstolp** [comment] 2024-05-01 13:53
@arthanson I agree with you the device creation form is fine. In this issue I was talking about the filter forms. The picture displays the clickable width.
![grafik](https://github.com/netbox-community/netbox/assets/41152397/4ba44cd0-2498-4857-8298-fa3d03ac702f)
