### ISSUE TITLE
Export Templates - missing some fields in export

### ISSUE THREAD

**Issue by Joelp** [netbox-community/netbox#11761] opened 2023-02-16 09:40 UTC
### NetBox version

v3.4.4

### Python version

3.10

### Steps to Reproduce

I created export template  for Exporting cables. This is my jinja:
```side_a_device, side_a_type, side_a_name, side_b_device, side_b_type, side_b_name, status, tenant, color, length, length_unit, id
{%- for cable in queryset %}
{{ cable.side_a_device }}, {{ cable.side_a_type }}, {{ cable.side_a_name }}, {{ cable.side_b_device }}, {{ cable.side_b_type }}, {{ cable.side_b_name }}, {{ cable.status }}, {{ cable.tenant }}, {{ cable.color }}, {{ cable.length }}, {{ cable.length_unit }}, {{ cable.id }}
{%- endfor %}```

It returns no values for some fields:
```
side_a_device, side_a_type, side_a_name, side_b_device, side_b_type, side_b_name, status, tenant, color, length, length_unit, id
, , , , , , connected, Rack S07, 111111, 5.00, m, 15
, , , , , , connected, Rack S07, 111111, 5.00, m, 16
, , , , , , connected, Rack S07, 111111, 5.00, m, 17
, , , , , , connected, Rack S07, 111111, 5.00, m, 18
```

### Expected Behavior

I should return values for `side_a_device`, `side_a_type`, `side_a_name`, `side_b_device`, `side_b_type`, `side_b_name` too

### Observed Behavior

Some fields are empty even if the cable is connected properly

**Comment by kkthxbye-code** [comment] 2023-02-16 10:53
`side_a_device`, `side_a_type`, `side_a_name`, `side_b_device`, `side_b_type` and `side_b_name` are not fields on the Cable object.

Closing as this is not a bug. Create a discussion if you need help.

**Closed by kkthxbye-code** 2023-02-16 10:53 UTC
Labels: type: bug
