### ISSUE TITLE
Config context on 'Tag' does not appear on tagged VMs

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#4483] opened 2020-04-14 11:07 UTC
### Environment
* Python version: 3.7.7
* NetBox version: 2.8.0

### Steps to Reproduce
1. Create a device with a tag 'tag1'
2. Create a VM with a tag 'tag1'
3. Create a config context that applies to tag 'tag1'
4. Examine the rendered config context for the device
5. Examine the rendered config context for the VM

### Expected Behavior
The same rendered config context should appear in both the device and the VM.

### Observed Behavior
The config context appears only for the device and not the VM

**Comment by jeremystretch** [comment] 2020-04-14 13:29
I'm not able to replicate this on v2.8.0. The config context is applied to both the device and the VM. Both models use the same underlying view (ObjectConfigContextView) to render the config context.

**Comment by cpmills1975** [comment] 2020-04-14 14:02
Could it be a caching issue? I've just created a new VM named 'A', added the tag (during creation) and the config context does appear. Now, if I edit that VM and remove the tag, the config context doesn't immediately disappear. If I clone it to a VM called 'B', that DOESN'T show the config context (expected). Editing 'B' to add the tag, also doesn't show the config context but if I clone it again to a VM called 'C' (c HAS the tag) the config context is visible on C.

A simpler way to demonstrate this is to create two VMs, one with and one without the tag on creation, then add the tag to the one that doesn't have it. The config context remains visible only on the device that had the tag on creation.

Does Django/Netbox cache the rendered objects internally? What I am seeing in the web interface is reflected in the API too (tag1 has an applicable config context defined): 

```{
<snip>
  "tags": [
    "tag1"
  ],
  "custom_fields": {},
  "config_context": {}.
<snip>
}```

FWIW, I am running a dev instance of NetBox using netbox-docker. My prod instance is older and running as a dedicated install (without docker atm).

**Comment by jeremystretch** [comment] 2020-04-14 14:04
> Could it be a caching issue?

Can you reproduce it with caching disabled?

**Comment by cpmills1975** [comment] 2020-04-14 14:06
Sorry, how do I disable caching? I'm assuming it is not browser end caching due to it being reflected in the API output and I've gone in to the developer view to make sure the web requests are getting proper status 200 responses.

**Comment by jeremystretch** [comment] 2020-04-14 14:11
Set `CACHE_TIMEOUT = 0` in configuration.py, then restart the NetBox service.

**Comment by cpmills1975** [comment] 2020-04-14 14:17
Yep. That's it. I actually noticed (at least I thought I did - now confirmed), that the config context corrected itself around the same time as the device said 'Updated 15 minutes ago'. I can see the default cache timeout is 900 seconds which is either entirely coincidental or Django was indeed caching the device for 15 minutes. Disabling the caching has 'fixed' my problem. I'll happily close this issue.

Many thanks.

**Comment by jeremystretch** [comment] 2020-04-14 14:23
I'm glad this is a suitable workaround for you, however we (the maintainers) still need to address the root issue, so I'm going to re-open this.

**Comment by jeremystretch** [comment] 2020-04-15 15:49
I played around with this for a bit but have not been able to replicate it with caching enabled. Updating a config context or creating a new one always results in a new query being issued by the next request for a device/VM.

@cpmills1975 can you take another look at the exact steps needed to reproduce on v2.8?

**Comment by jeremystretch** [comment] 2020-04-21 16:53
I'm going to close this out as I have been unable to reproduce it on v2.8, but please comment here if you are able to and I'll re-open it.

**Closed by jeremystretch** 2020-04-21 16:53 UTC
Labels: status: revisions needed, type: bug

**Comment by 1977er** [comment] 2020-09-03 09:45
I can reproduce this on a Netbox v2.8.9. 
Tagged VMs/devices do not get the config context assigned until I make an (empty) update on the ConfigContext object. When I set `CACHE_TIMEOUT = 0` the config contexts get assigned immediately (without edit-save cycle on the CC object).

Sorry, cannot test on 2.9 yet.
