### ISSUE TITLE
NetBox 2.10.0 - Adding Interface to Device Type Succeeds but Returns <class 'django.urls.exceptions.NoReverseMatch'> Error

### ISSUE THREAD

**Issue by lastwednesday** [netbox-community/netbox#5467] opened 2020-12-15 20:13 UTC
### Environment
* Python version: 3.8.3
* NetBox version: 2.10.0

We have upgraded to Netbox 2.10.0 this morning and restarted services and rebooted the server as well just to be sure everything is up to date.

### Steps to Reproduce
1. Create a new Device Type or edit an existing Device Type
![image](https://user-images.githubusercontent.com/579420/102266918-baa57700-3ede-11eb-81e2-43196f969f45.png)

2. Choose option to add an Interface, either a single interface or using a pattern to add multiple
![image](https://user-images.githubusercontent.com/579420/102266968-d27cfb00-3ede-11eb-8453-24b4b5aad178.png)

3. Click on Create button and observe the following error
![image](https://user-images.githubusercontent.com/579420/102267114-0821e400-3edf-11eb-8be4-06bbb4ab10cf.png)

URL:
netbox/dcim/interface-templates/add/?device_type=&return_url=%23tab_interfaces
```
 Server Error
There was a problem with your request. Please contact an administrator.
________________________________________
The complete exception is provided below:
<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for '#tab_interfaces' not found. '#tab_interfaces' is not a valid view function or pattern name.

Python version: 3.8.3
NetBox version: 2.10.0
If further assistance is required, please post to the NetBox mailing list.
```

4. Return to Home Page and then return to Device Type and find that the Interfaces were created even though an error was given
![image](https://user-images.githubusercontent.com/579420/102267239-3c95a000-3edf-11eb-8730-1815b81c513b.png)

### Expected Behavior
When user adds an Interface to a Device Type, if it is successfully added user should not expect to see any errors presented.

### Observed Behavior
User observes that an exception error is reported, however the action is successfully performed.

**Comment by DanSheps** [comment] 2020-12-15 20:47
Duplicate of #5458

**Closed** 2020-12-15 20:47 UTC
Labels: status: duplicate, type: bug
