### ISSUE TITLE
FQDN is dropped from device links in rack elevation views

### ISSUE THREAD

**Issue by moobys** [netbox-community/netbox#4657] opened 2020-05-18 14:17 UTC
### Environment
* Python version: 2.7.17
* NetBox version: 2.8.4

### Steps to Reproduce
1. Open any rack elevation view:
   Organization > Elevations
   -or-
   Organization > Racks > [select a rack]
2. Click the link on any device in the rack

### Expected Behavior
URL should be https://netbox.FQDN.com/dcim/devices/xxxx/

URL changes to https://netbox/dcim/devices/xxxx/ and FQDN is dropped on further browsing

**Comment by jeremystretch** [comment] 2020-05-18 14:29
Duplicate of #4526

**Closed by jeremystretch** 2020-05-18 14:29 UTC
