### ISSUE TITLE
Reuse button show_available for VLAN Groups

### ISSUE THREAD

**Issue by jjeganathan** [netbox-community/netbox#4827] opened 2020-07-06 16:38 UTC
### Environment
* Python version: 3.6.9
* NetBox version: 2.8.7

Import the same toggle button 'Show available/Hide Available' as in the pages aggregates and prefixes but for vlan groups.
This feature adds more visibility to the table of vlans.
[Commit for pull request](https://github.com/jjeganathan/netbox/commit/8ae3a32d446cfa142e7b21be7b5d99665e6a0f4d)

**Comment by jeremystretch** [comment] 2020-07-06 17:42
Duplicate of #4126

**Closed by jeremystretch** 2020-07-06 17:42 UTC

**Comment by jjeganathan** [comment] 2020-07-07 08:44
I think you misunderstood my request :thinking: (or not ?)

The ticket seems to be a "toggle button "Show VLANs" into device view"
In my case it's in VLAN Groups view (/ipam/vlan-groups/1/vlans/) to hide all green lines which says the number of VLANs available between two lines of the table.

**Comment by jeremystretch** [comment] 2020-07-07 12:46
My mistake; this is not a duplicate issue. However, the VLAN group view is slated to be removed as it does not conform to standard view set for an organizational object. I'm not sure yet whether or how the "available VLANs" view will be replicated, but this is something that will be considered as part of that work.

**Comment by jjeganathan** [comment] 2020-07-07 13:43
Oh alright, thanks for your feedback
