### ISSUE TITLE
Prefix with role container does not show child prefixes correctly

### ISSUE THREAD

**Issue by ziggekatten** [netbox-community/netbox#3554] opened 2019-09-29 10:33 UTC
### Environment
* Python version:  3.7.4 
* NetBox version:  2.6.5

### Steps to Reproduce
1. Add a prefix of type container 192.168.125.0/24 
2. Add a prefix of type Active 192.168.125.0/26
3. Add a prefix of type Active 192.168.125.64/26
4. Edit prefix 192.168.125.0/26 and assign to a VRF
5. Edit prefix 192.168.125.64/26 and assign to another VRF

### Expected Behavior
Adding two prefixes with assignment to separate VFRs:

192.168.125.0/24 and 192.168.125.64/26

In the prefixes UI I should now see the 192.168.1.0/24 with an small arrow indicating child prefixes

Klickin on the container prefix, i should have twe child prefixes

![Capture1](https://user-images.githubusercontent.com/55629049/65830986-a878f200-e2b4-11e9-9558-c6c27ef18ced.PNG)

### Observed Behavior
As soon as I add one or the other prefix to a VRF, the prefix are not hidden under the container, it shows directly in the UI. Klicking on the container prefix however, shows (correctly) that there are two child prefixes.
![Capture2](https://user-images.githubusercontent.com/55629049/65830991-b6c70e00-e2b4-11e9-98e3-20b1c6c9f594.PNG)

![Capture3](https://user-images.githubusercontent.com/55629049/65830992-bc245880-e2b4-11e9-85d1-e3c2460284ed.PNG)

**Comment by kobayashi** [comment] 2019-09-30 15:04
Allow indicator for child prefixes appears in prefixes list when same VRF is assigned to them.
What you want to do can be defined in Aggregate menu.
Try to create Aggregate with 192.168.125.0/24. Then assign 192.168.125.0/26 as VRF 10700 and 192.168.125.64/26 as VRF 10710 in the aggregate.

**Comment by ziggekatten** [comment] 2019-09-30 19:08
No, that does not solve the issue. As a service provider, we have several clients using the same 10.0.0.0/8 and 192.168.0.0/16, and aggregates can NOT have the same prefix more than once.

**Comment by kobayashi** [comment] 2019-10-01 02:21
Thanks to let me know about the detail.
I tested today with netbox version 2.6.5 and found that worked well.
![Screenshot from 2019-09-30 22-20-45](https://user-images.githubusercontent.com/8712070/65929561-9b512580-e3d0-11e9-96a2-25a8a2b5606d.png)

Which netbox version are you using right now? So I can try with your version.

**Comment by ziggekatten** [comment] 2019-10-01 03:53
I’m running 2.6.5

**Comment by kobayashi** [comment] 2019-10-01 14:22
OK, I found this is reproduced not by one by one each but only by bulk importing.
Also found the same issue is already opened #2562. Please track that case.

**Comment by kobayashi** [comment] 2019-10-01 14:23
closed this issue due to duplication. Please refer #2562

**Closed by kobayashi** 2019-10-01 14:23 UTC
