### ISSUE TITLE
Viewing prefix ip addresses results in server error

### ISSUE THREAD

**Issue by ognjen011** [netbox-community/netbox#8256] opened 2022-01-06 11:23 UTC
### NetBox version

v3.1.4

### Python version

3.7

### Steps to Reproduce

1. Create ip prefix. in My case 192.168.0.0/22.  Larger subnet. 
2. From the screen of ip prefix details click on ip addresses tab
3.  Results in server error.

### Expected Behavior

I should see a list of ip's for that prefix.

### Observed Behavior

Server Error 

<class 'ValueError'>

'role' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().

Python version: 3.7.5
NetBox version: 3.1.4

**Comment by kkthxbye-code** [comment] 2022-01-06 12:09
Duplicate of https://github.com/netbox-community/netbox/issues/8213

Will be fixed in next version.

**Closed** 2022-01-06 13:39 UTC
Labels: type: bug, status: duplicate
