### ISSUE TITLE
Interfaces view: Search field being ignored

### ISSUE THREAD

**Issue by dreng** [netbox-community/netbox#6565] opened 2021-06-08 10:58 UTC
### NetBox version

v2.11.6

### Python version

3.7

### Steps to Reproduce

1. Jump to view "devices -> interfaces"
2. Enter search term on the right hand side
3. Press enter or click magnifier glass

### Expected Behavior

The table should be filtered by the entered search term.

### Observed Behavior

The table is always empty, no matter what search term has been entered.

**Comment by jeremystretch** [comment] 2021-06-08 18:02
I'm not able to reproduce the reported behavior on v2.11.6. Searching and filtering the interfaces list works as expected. This was also confirmed on the [public demo instance](https://demo.netbox.dev/). Please elaborate on your initial post above to specify exactly what you're doing and what values you are searching for.

**Comment by dreng** [comment] 2021-06-09 05:20
I think I know what the misunderstanding is here. The search field only filters the "name" values, not the "device" value. This seems logical since this behavior is similar e.g. in the device view. Maybe it irritated me that "name" wasn't the first column. It seems that I'm not the only one. :-)

I expected the "devices" column to be filtered, because I needed a list of all switches with all connections, cable peers and VLANs in order to export it as CSV. Since I haven't found any other view that covers this task I used the interfaces view, but there's no option to filter by e.g. device role or location. Since our devices follow a naming convention it would have been easy to filter the needed switches by using the search field.

**Comment by jeremystretch** [comment] 2021-06-16 19:52
Ok, I'm going to close this out as it's not actually. I would suggest an export template but it sounds like you're trying export a ton of information at once: a plugin or custom script might be better suited.

**Closed by jeremystretch** 2021-06-16 19:52 UTC
Labels: status: revisions needed, type: bug
