### ISSUE TITLE
cannot create new Virtual Machine within a Cluster

### ISSUE THREAD

**Issue by fabricat** [netbox-community/netbox#10517] opened 2022-09-30 08:16 UTC
### NetBox version

v3.3.3

### Python version

3.9

### Steps to Reproduce

1. select Organization > **Sites** > ➕ Add
2. set field **Name** = "site1"
3. click **Create**
4. select Virtualization > **Cluster Types** > ➕ Add
5. set field **Name** = "type1"
6. click **Create**
7. select Virtualization > **Clusters** > ➕ Add
8. set field **Name** = "cluster1"
9. set field **Type** = "type1"
10. set field **Site** = "site1"
11. click **Create**
12. select Virtualization > **Virtual Machines** > ➕ Add
13. set field **Name** = "vm1"
14. set field **Cluster** = "cluster1"
15. leave the **Site** field empty
16. click **Create**

### Expected Behavior

A new VM "vm1" should be created and associated with the selected Cluster "cluster1".

### Observed Behavior

The VM is not created and the following error appears:
> The selected cluster (cluster1 is not assigned to this site (None).

(Note: there is also a missing closed parenthesis in the error message)

If I create the VM selecting a Cluster and also a **Site**, the operation is successful.
This is probably related with #5303

**Comment by kkthxbye-code** [comment] 2022-09-30 11:52
Please change the topic title to something more descriptive. Also please revise your reproduction steps to include all replication steps, including the creation of the cluster. With the current steps it is not reproducible.

**Comment by fabricat** [comment] 2022-09-30 13:13
Hi @kkthxbye-code 
Sorry for the wrong title: I have now amended it, together with the reproduction steps.
I hope it is all clear now.

**Comment by jeremystretch** [comment] 2022-10-03 14:18
I'm not able to reproduce the reported behavior on either v3.3.3 or v3.3.4; the virtual machine is created successfully as expected.

**Comment by jeremystretch** [comment] 2022-10-03 19:30
This is happening because you're attempting to create a VM assigned to a cluster within a site without also assigning the VM to that site, which would be invalid. We can relax the form a bit to automatically assign the site when none is selected, but I want to be clear that the validation is working as expected.

**Closed** 2022-10-03 19:36 UTC
Labels: type: bug, status: accepted

**Comment by fabricat** [comment] 2022-10-04 15:40
Thank you.
Actually, I imagined that was probably the expected behaviour, but looking at docs and error messages I did only see that you must specify a site or a cluster. 
I totally agree that when you only specify a cluster, then the site should be inherited.
For my integration/automation tool, retrieving the cluster site is an additional overhead.
