### ISSUE TITLE
Creating a new cable between two devices throws exception

### ISSUE THREAD

**Issue by Serverlag** [netbox-community/netbox#13340] opened 2023-08-02 02:29 UTC
### NetBox version

3.5.1

### Python version

3.10

### Steps to Reproduce

Create two devices with interfaces
From one of the devices click on the create cable button
Select interface as the type
Choose B side device and interface from dropdown menus
Choose status as "planned"
Choose type as "singlemode fiber"
Choose tenant from tenant dropdown menu
Click "create and add another" button

### Expected Behavior

Cable creation should complete successfully and you should be redirected to the same screen to create another cable with no errors.

### Observed Behavior

Cable is created, however you are never directed back to the screen to add another cable. Instead, an AttributeError exception was raised like below:

```
<class 'AttributeError'>

'str' object has no attribute 'label'

Python version: 3.10.6
NetBox version: 3.5.1
```

**Comment by Serverlag** [comment] 2023-08-02 04:32
A note: this only occurs when you click "Create and add another". Not when you click "create".

**Comment by abhi1693** [comment] 2023-08-02 05:03
Duplicate of #12579

**Closed** 2023-08-02 05:04 UTC
Labels: status: duplicate
