### ISSUE TITLE
Cable Trace PathSplit in one Direction

### ISSUE THREAD

**Issue by gafzgarrr** [netbox-community/netbox#15818] opened 2024-04-23 08:55 UTC
### Deployment Type

Self-hosted

### NetBox Version

v.3.7.6

### Python Version

3.8

### Steps to Reproduce

1. Create two device with interface
2. Create two patchpannel for MPO or CWDM/DWDM Connections
3. Patchpannel has 24 Front Ports, Connected to one rear port
4. Connect both rear ports
5. Connect Front Port 1+2 on both ends with the interfaces

### Expected Behavior

We expect to trace between the two interface, or get a split-path on both ends

### Observed Behavior

From one side the other end is deteced and cable trace is working between both interface, from the other side there is a split-path error after the second Patchpannel

**Comment by jeremystretch** [comment] 2024-04-23 13:02
I'm not able to reproduce this on NetBox v3.7.6. Both paths render as expected. Please see if the topology below matches what you expect.

### A to B

![path1](https://github.com/netbox-community/netbox/assets/13487278/71380cc8-846a-4012-ab54-113e4a055d72)

### B to A

![path2](https://github.com/netbox-community/netbox/assets/13487278/0fb319e0-e816-42bf-bdf1-6adf3121bb02)

**Comment by jeremystretch** [comment] 2024-05-01 19:13
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.

**Closed by jeremystretch** 2024-05-01 19:13 UTC
Labels: type: bug, status: revisions needed
