### ISSUE TITLE
API returns duplicate entries for IPs with VIP role

### ISSUE THREAD

**Issue by reshippie** [netbox-community/netbox#12938] opened 2023-06-19 20:10 UTC
### NetBox version

v3.5.3 - netbox-docker

### Python version

3.10

### Steps to Reproduce

1. Create at least 14 IPs with the VIP role, with the same address and different dns_names
2. Using the REST API, `api/ipam/ip-addresses/`  fetch all of the IPs in Netbox
3. Print out the ID and dns_name fields for all of the entries returned with that IP address.

### Expected Behavior

Fetching all IP addresses from Netbox should return all of the entries stored, with no duplicate entries.

### Observed Behavior

1. There will be at least entry, out of the 14, that is missing and 1 entry that is repeated.  
2. There will be the correct number of entries returned, just not the correct number of unique entries.

**Comment by kkthxbye-code** [comment] 2023-06-19 20:30
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.5.3. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by reshippie** [comment] 2023-06-19 23:05
We're definitely on the newest release.  
This is our production installation, it has 21K entries in IPAM.  
We've upgraded from some iteration of version 2 up through the most recent release.
We've tried dumping the Postgresql database and restoring it to another instance but we're still seeing the same behavior.

**Comment by kkthxbye-code** [comment] 2023-07-04 07:15
I'll close this out as there are no proper replication steps. If you do manage to replicate it on a clean netbox install, please make a post and I'll re-open it.

**Closed by kkthxbye-code** 2023-07-04 07:15 UTC
Labels: type: bug, status: revisions needed
