### ISSUE TITLE
KeyError on cable trace

### ISSUE THREAD

**Issue by JonathonReinhart** [netbox-community/netbox#7207] opened 2021-09-08 03:59 UTC
### NetBox version

v3.0.1

### Python version

3.8

### Steps to Reproduce

I discovered this while exploring the NetBox demo instance.

Either
- from the [interfaces page of `dmi01-scranton-rtr01`](https://demo.netbox.dev/dcim/devices/9/interfaces/), click the Trace button on either:
  - [`GigabitEthernet0/1/0`](https://demo.netbox.dev/dcim/interfaces/107/trace/)
  - [`GigabitEthernet0/1/0`](https://demo.netbox.dev/dcim/interfaces/108/trace/)
- from the [interfaces page of  `dmi01-scranton-sw01`](https://demo.netbox.dev/dcim/devices/22/interfaces/), click the Trace button on either:
  - [`GigabitEthernet1/0/1`](https://demo.netbox.dev/dcim/interfaces/578/trace/)
  - [`GigabitEthernet1/0/2`](https://demo.netbox.dev/dcim/interfaces/579/trace/)

### Expected Behavior

I would expect to see a cable trace of the cable connected between either pair of interfaces.

### Observed Behavior

> #### Server Error
> There was a problem with your request. Please contact an administrator.
>
>-----
> The complete exception is provided below:
> ```
> <class 'KeyError'>
> 
> 51
> 
> Python version: 3.8.10
> NetBox version: 3.0.1
> ```

Note: The `KeyError` key 51 (or 52) is the ID of the cable ([#51](https://demo.netbox.dev/dcim/cables/51/) or [#52](https://demo.netbox.dev/dcim/cables/52/)) which connects the interfaces

**Comment by TorstenDrees** [comment] 2021-09-08 10:33
Hi,

similar error here:
<class 'AttributeError'>

'NoneType' object has no attribute 'origin'

Python version: 3.8.5
NetBox version: 3.0.1

Regards,
Torsten

**Comment by jeremystretch** [comment] 2021-09-08 12:37
Per the bug report template:

> Additionally, **do not rely on the demo instance** for reproducing suspected bugs, as its data is prone to modification or deletion at any time.

Closing this because reproduction steps were not provided for a clean installation.

**Closed by jeremystretch** 2021-09-08 12:37 UTC
Labels: type: bug
