### ISSUE TITLE
IPv6 address assignment to interface is enforcing Network Address limitations.

### ISSUE THREAD

**Issue by nzurku** [netbox-community/netbox#13052] opened 2023-06-29 19:10 UTC
### NetBox version

v3.5.1

### Python version

3.10

### Steps to Reproduce

Create and IPv6 address that lands on the "network address". Assign this to an interface. Example, 2600::/64

### Expected Behavior

There are no "network addresses" in IPv6 that are impossible to use on network devices. Or possibly, whatever validation this is triggering was meant to be IPv4 only.

I would expect this address and ones like it to be assignable to an interface as it was before in ~v3.5.1 and earlier.

### Observed Behavior

A validation error appears "2600::/64 is a network ID, which may not be assigned to an interface."

**Comment by johannwagner** [comment] 2023-07-02 20:22
This was fixed in v3.5.4, ran into the same issue.

**Comment by jeremystretch** [comment] 2023-07-03 12:05
I believe this is a duplicate of #12687 and, as mentioned, was fixed in v3.5.4.

**Closed by jeremystretch** 2023-07-03 12:05 UTC
Labels: type: bug

**Comment by nzurku** [comment] 2023-07-03 14:21
I hate reopening things, but I think there is some confusion or another issue here. I am already running 3.5.4.

This bug is also reproducible on the public demo of Netbox.

Try to add 2600://64 to this interface: https://demo.netbox.dev/ipam/ip-addresses/add/?device=95&interface=973&return_url=/dcim/interfaces/973/
