### ISSUE TITLE
`contains` for an IPv6 prefix should not also return itself

### ISSUE THREAD

**Issue by ChrisHills463** [netbox-community/netbox#16364] opened 2024-05-31 10:38 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3-2.9.1 (docker.io/netboxcommunity/netbox)

### Python Version

3.11

### Steps to Reproduce

1. Create a prefix `2001:16d8::/48`
2. Create a prefix `2001:16d8:0:ffff::/64`
3. Fetch `GET /api/ipam/prefixes/?contains=2001:16d8:0:ffff::/64`

### Expected Behavior

There should be one result, `2001:16d8::/48`

### Observed Behavior

There are two results, `2001:16d8::/48` and `2001:16d8:0:ffff::/64`.

I believe the behaviour is caused by the (searched-for) prefix being interpreted as an address rather than a prefix, but for IPv6 this does not make sense. Ideally it should be possible to directly reference the parent prefix of an IPv6 prefix, but without a suitable member (e.g. `parent_prefix`) it seems the only alternative is to rely on `contains()`.

**Comment by ChrisHills463** [comment] 2024-05-31 10:43
One more thing to add, if you want to find the parent prefix for an IPv6 address, I would suggest either omitting the prefix value (e.g `2001:16d8:ffff::`), or using `/128` as the prefix value (e.g. `2001:16d8:ffff::/128`).

**Comment by jeffgdotorg** [comment] 2024-06-03 20:59
To make the second prefix nest beneath the first, the second needs specifying as `2001:16d8:0:ffff::/48`. Would you please update the issue body accordingly? Once I make that change, I do see the described problem behavior.

**Comment by ChrisHills463** [comment] 2024-06-04 07:47
> To make the second prefix nest beneath the first, the second needs specifying as `2001:16d8:0:ffff::/48`. Would you please update the issue body accordingly? Once I make that change, I do see the described problem behavior.

Fixed! Sorry about that.

**Comment by jeremystretch** [comment] 2024-06-04 11:55
> There are two results, 2001:16d8::/48 and 2001:16d8:0:ffff::/64.

This is the intended behavior: The `contains` filter invokes the `prefix__net_contains_or_equals` lookup, which returns any exact matching prefix or longer. This functionality has been in place for years and is well-established.

**Comment by jeffgdotorg** [comment] 2024-06-04 14:13
Thanks for weighing in, @jeremystretch. Thanks for reporting, @ChrisHills463 – I initially found the behavior confusing as well.

**Comment by jeffgdotorg** [comment] 2024-06-04 14:15
Behavior is as designed. Resolving as not planned.

**Closed by jeffgdotorg** 2024-06-04 14:15 UTC
Labels: type: bug
