### ISSUE TITLE
validators on deletion

### ISSUE THREAD

**Issue by Maxime-Parolini** [netbox-community/netbox#10738] opened 2022-10-25 11:50 UTC
### NetBox version

v3.2.9-dev

### Feature type

Change to existing functionality

### Proposed functionality

Validators currently run when an object is created or modified, but not deleted. We propose that validators also run on object deletion

### Use case

My use case is the notification of external services upon deletion (as well as creation/modification). The use of validators as opposed to webhooks allows us to refuse the action if the notification did not work properly.

### External dependencies

no new dependencies, this is possible to achieve already within the jango framework

**Comment by atownson** [comment] 2022-10-25 23:42
Related to #10244

**Comment by kkthxbye-code** [comment] 2022-11-01 06:41
I think this is actually just a duplicate of #10244

**Closed by kkthxbye-code** 2022-11-01 06:41 UTC
Labels: type: feature
