### ISSUE TITLE
Sporadically broken HTML formatting since at least 3.5.0

### ISSUE THREAD

**Issue by stavr666** [netbox-community/netbox#12760] opened 2023-05-30 18:26 UTC
### NetBox version

v3.5.1

### Python version

3.10

### Steps to Reproduce

Spontaneously observed behavior:
1. Open any list
2. Click to any object
3. Press "Go back" (or ALT+←) in browser

### Expected Behavior

List will be rendered as usual.

### Observed Behavior

Loaded only part of page, without sidebar, with empty head tag:

![image](https://github.com/netbox-community/netbox/assets/84839985/b18e3bd7-46f4-41b1-bc1d-8c3b72ee72c2)

**Comment by DanSheps** [comment] 2023-05-30 18:30
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.5.2 (Also not able to reproduce on 3.5.1). Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by abhi1693** [comment] 2023-05-30 19:06
I don't think it's a bug with netbox. Just how browsers load the css and js. When you click back, if the styling is not loaded this happens and I have seen it on other sites too.

**Comment by DanSheps** [comment] 2023-05-30 19:09
Yeah, I tried it with Chrome on both my prod and the demo and no joy.  It could also be browser specific.

**Comment by stavr666** [comment] 2023-05-30 21:56
> Please re-confirm the reported behavior on the current stable release

It's totally reproduceable in 3.5.0, 3.5.1, 3.5.2. I encountered it dozen time my own production installation (3.5.0, 3.5.1) and at least once in every 3 versions on your Demo-site, during my check of some conceptions before generating other reports there.

But I agree with @abhi1693 that it's look like browser-related (3 different Chromium-based), because it never reproduceable on repeat (forward-back buttons).

**Comment by DanSheps** [comment] 2023-05-31 13:21
Honestly, the lack of HTML in the screenshot makes me think it is the browser replaying a HTMX request, which resuslts in only a partial HTML being sent and it glitching.  (You only get the table, not anything else like the nav menu)

**Comment by kkthxbye-code** [comment] 2023-06-04 10:54
Probably similar to this:

https://github.com/bigskysoftware/htmx/issues/1201

I can reliably recreate it by going to the device list, order the table by a column, closing the tab and then hitting ctrl+shift+t in chrome (re-open closed tab). This only renders the table, without css.

Anyway, there's some context if anyone wants to look into it. There's some suggestions in the linked issue.

**Comment by DanSheps** [comment] 2023-06-05 13:08
Looks like we might just need to use the cache-busting params.

**Comment by jeremystretch** [comment] 2023-06-23 13:20
This seems like it can be addressed by setting the `Vary: HX-Request` response header as described [here](https://htmx.org/docs/#caching).

**Closed** 2023-06-29 19:53 UTC
Labels: type: bug, status: accepted, severity: low
