### ISSUE TITLE
Add Ukrainian

### ISSUE THREAD

**Issue by SmalLPUUP** [netbox-community/netbox#15682] opened 2024-04-10 13:42 UTC
### Language

Ukrainian

### ISO 639-1 code

UA

### Volunteer

Yes

### Comments

Good afternoon.
I am sure that your project will be popular among Ukrainian-speaking specialists.

Thank you for a good product.

**Comment by jeffgdotorg** [comment] 2024-04-25 20:43
Thanks for your interest in helping translate NetBox. This issue is a duplicate of #14639 so I'm resolving it as such.

**Closed by jeffgdotorg** 2024-04-25 20:43 UTC
Labels: type: translation
