### ISSUE TITLE
Cables not editable if one end of the cable is connected to device that was deleted

### ISSUE THREAD

**Issue by pv2b** [netbox-community/netbox#13229] opened 2023-07-21 12:49 UTC
### NetBox version

v3.5.6

### Python version

3.10

### Steps to Reproduce

1. Create two devices called TEST1 and TEST2. Type is not impotant, but make sure they have one interface each.
2. Connect a cable between TEST1 and TEST2, doesn't matter which interfaces, as long as it's a cable between the two devices.
3. Delete device TEST2.
4. Find the cable that was connecting TEST1 and TEST2 (e.g. through the interface list on TEST1) and click on it.
5. Verify that there is a termination on Termination A to device TEST1, but Termination B is shown as "No termination."
6. Click on "Edit".

### Expected Behavior

The edit screen for the cable should appear, allowing me to edit the cable, including changing the termination to something new.

### Observed Behavior

The following error message is shown on screen:

> Server Error
> 
> There was a problem with your request. Please contact an administrator.
> 
> The complete exception is provided below:
> 
> <class 'AttributeError'>
> 
> 'str' object has no attribute 'label'
> 
> Python version: 3.10.6
> NetBox version: 3.5.6
> 
> If further assistance is required, please post to the [NetBox discussion forum](https://github.com/netbox-community/netbox/discussions) on GitHub.

NOTE: As far as I can tell, it's not possible to have a cable that is unterminated on one end under normal circumstances, at least not through the GUI. This might explain why perhaps the edit page isn't set up to expect one end of the cable to be unterminated.

**Comment by pv2b** [comment] 2023-07-21 13:38
I gave fixing this a try, since I thought it might be a quick and easy fix of a type error somewhere. However, unfortunately it would seem that there's a fundamental lack of functionality in the cable edit form as is right now, that's beyond my ability to fix.

The issue is that there's no way to select the termination type in the cable form. In other words, once you have decided that a cable connects from an Interface to and Interface, there's no way to in the GUI edit the cable so it's instead going from an Interface to a Front Port, for example. Because there's no currently written functionality for setting a termination type, the GUI just lets you change the termination itself, not the termination type. There'd need to be a picker in the edit form to change the termination type for the use case of editing a cable that's missing one termination to make sense.

As far as I see it there's two possible paths to take here:

1. Add full support for "dangling cables", i.e. cables that by design are only connected on one end, or even on both ends. This could be useful to keep an inventory of unused cables, or to document a cable that's "dangling" in a rack ready to plug a laptop into, for example.

2. Extend the logic for deleting a device so that all cables terminated in that device get deleted on deleting the device, alternatively, do not allow a device with cables present to be deleted.

Either way, unfortunately, this involves adding some kind of new functionality, not simply squashing a bug.

**Comment by pv2b** [comment] 2023-07-21 13:42
Just one final comment, there's nothing in the underlying data model that makes it impossible to change the termination model of a cable after the fact, so if you ever run into this, a possible workaround is to use the "bulk import" mode to update the termination of the cable, bypassing this GUI bug, for example using this CSV "bulk import":

```
id,side_b_type,side_b_device,side_b_name
111,dcim.interface,Test1,2
```

**Comment by cpmills1975** [comment] 2023-07-21 18:58
I'm not currently running the most recent version of NetBox, but I'm sure that in the version I am running, deleting a device would delete any cables attached to it. You can't actually edit the terminations of a cable anyway (or you can't in the version I'm running - perhaps that has changed).

Perhaps the functionality to delete a cable has been removed now cables can be connected to multiple devices?

Perhaps a cable should automatically be deleted when all the devices on one end of it no longer exist?

**Comment by kkthxbye-code** [comment] 2023-07-23 09:07
Duplicate of https://github.com/netbox-community/netbox/issues/11460

**Closed by kkthxbye-code** 2023-07-23 09:07 UTC
Labels: type: bug
