### ISSUE TITLE
GCP IAP JWT authentication

### ISSUE THREAD

**Issue by cova-fe** [netbox-community/netbox#7728] opened 2021-11-03 12:08 UTC
### NetBox version

v3.0.8

### Feature type

New functionality

### Proposed functionality

Netbox should be able to use GCP IAP JWT token to create or authenticate users. IAP passes a signed token with email and ID of the user, so we can get those information and use them for the auth phase. I implemented a quick PoC and it is a few lines change.

### Use case

Installation of netbox in GCP could make use of IAP authentication offered by GCP.

**Comment by DanSheps** [comment] 2021-11-03 14:01
Duplicate of #7649

**Comment by cova-fe** [comment] 2021-11-03 14:23
I'm not sure it is duplicate. What I propose is to use the header provided in IAP authentication that contains username and ID. No oidc, no external backends. It is just a different form of basic auth provided by a web browser. The #7649 refers to something else, more involved, afaics.

**Comment by cova-fe** [comment] 2021-11-03 14:24
Basically:
https://github.com/cova-fe/netbox/commit/52f7fecd899c519a15966aef2d1abb387af59a82

**Comment by cova-fe** [comment] 2021-11-03 16:04
I guess that it provides less, actually. But it is a different situation. I'm using it to have a "basic auth" approach (requests will get an header that you can use and that's it). No need to set up callbacks and so forth. social auth is a bit more complex to setup.

**Comment by l1bra2013** [comment] 2021-11-05 13:17
Per https://github.com/netbox-community/netbox/issues/7649#issuecomment-958048055 - this could probably be implemented using a user provided class implementing the Django auth + REST auth interfaces. Netbox would just need to provide sufficient configuration options to allow users to override commonly used authentication related options so that everyone doesn't have to modify the netbox code to incorporate the desired auth solution.

**Comment by cova-fe** [comment] 2021-11-05 14:37
Avoiding to make changes in core code would be indeed great. However, the discussion seems to be more related to OIDC. To implement JWT auth I guess that the class will need to access http headers. Implementing REST and stuff like that wouldn't be a bit overkill for something that just checks an header and gets back username (that is already authenticated). However, if you have an example of the direction you would like to follow, I'll be happy to have a look

**Comment by cova-fe** [comment] 2022-01-12 09:36
Before this issue gets closed, is there any change that it could be looked at? We are using this approach right now and moving to OIDC will cause some (unneeded) headaches :)

**Comment by thatmattlove** [comment] 2022-02-22 16:03
I understand the intent here, and I think it's a good idea. That said, I don't like that this is GCP-specific. [JWT is an open standard](https://jwt.io/) and we could easily work with them without relying on a GCP-specific dependency. I've used [PyJWT](https://github.com/jpadilla/pyjwt/) in the past with great success. It seems to me the only thing we'd need to do differently is specific which header to read and use [GCP's](https://cloud.google.com/iap/docs/signed-headers-howto#verifying_the_jwt_header) (or any provider's) JWKS endpoint for key validation. These could both be provided via configuration settings, and therefore be used with any authentication provider.

In practice, I think the way to implement this would be as another [NetBox remote authentication backend](https://netbox.readthedocs.io/en/stable/administration/authentication/). Something like `netbox.authentication.JWTBackend`, with some configuration settings like:

* `JWT_HEADER` (string, required, specifies which HTTP header from which to read the JWT value)
* `JWT_JWKS_URL` (string, optional, specifies the [JWKS URL](https://pyjwt.readthedocs.io/en/stable/usage.html#retrieve-rsa-signing-keys-from-a-jwks-endpoint) for public key validation, doesn't validate signing key by default)
* `JWT_AUDIENCE` (string, optional, doesn't validate `audience` by default)
* `JWT_USERNAME_CLAIM` (string, optional, uses `email` by default)

That's just off the top of my head, I'm sure there's room for improvement, should we decide to move forward with this. 

Once implemented, it would work very much like `netbox.authentication.RemoteUserBackend`, the primary difference being that instead of only reading a specific HTTP header for the username attribute, additional validation is done, and additional attributes could be extracted. For example, `netbox.authentication.RemoteUserBackend` is likely susceptible  to replay attacks, whereas proper JWT validation would mitigate that by ensuring the value passed from the server side is both signed by the expected party and valid at the time of use. Additional claims could also be extracted from the JWT, such as the user's full name, role, username (which wouldn't _have_ to be their email), etc.

At any rate, I'd be happy to contribute to this if we decide to move forward with it.

**Closed** 2022-05-24 04:10 UTC
Labels: type: feature, status: under review, pending closure
