### ISSUE TITLE
Ability to add more columns to reports

### ISSUE THREAD

**Issue by Zedespook** [netbox-community/netbox#8786] opened 2022-03-03 11:08 UTC
### NetBox version

v3.1.8

### Feature type

New functionality

### Proposed functionality

Currently, when creating reports. The user may add the time, level, object, and a message to each entry. My suggestion is to add multiple columns besides and object and a message to the report.

### Use case

There might be different data that has to be reported to the user. It would add to the convenience if the user would be presented with all the data relevant on a single page in different columns.

**Comment by jeremystretch** [comment] 2022-03-03 13:28
The format of reports is fixed by design. If you want to export arbitrary data, you should instead use an [export template](https://netbox.readthedocs.io/en/stable/customization/export-templates/), [custom script](https://netbox.readthedocs.io/en/stable/customization/custom-scripts/), or a [custom plugin](https://netbox.readthedocs.io/en/stable/plugins/development/) to generate exactly what you need.

**Closed by jeremystretch** 2022-03-03 13:28 UTC
Labels: type: feature
