### ISSUE TITLE
Strange behaviour with generated >3 VLANs table for interfaces

### ISSUE THREAD

**Issue by Azmodeszer** [netbox-community/netbox#17771] opened 2024-10-16 09:49 UTC
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.4

### Python Version

3.11

### Steps to Reproduce

I'm seeing some weird behaviour with the new feature as implemented per #17655. I can't give exact guaranteed reproduction steps, because it might be something specific to my database that I haven't figured out yet, but basically:

1. Find an interface with more than 3 tagged VLANs and 1 untagged VLAN. (created before the update(?), see Observed Behavior)
2. Click on the created link for the tagged VLANs (of the form `/ipam/vlans/?interface_id=<ID>`).

### Expected Behavior

Tagged VLANs for that interface are shown correctly.

### Observed Behavior

What I am seeing is some of the tagged VLANs being listed multiple times (and the _untagged_ VLAN showing up as well, which I guess is to be expected). I've tried to reproduce it with new VLANs created _after_ the update to 4.1.4 and it seems to work as expected with those (some "older" VLANs are also only showing up once, however, so it might not be related to that at all), but when I attach a certain existing VLAN as tagged to the interface it results in multiple redundant rows again.

![image](https://github.com/user-attachments/assets/efb8a950-0a56-46b3-92e5-5b7bbe0f18ae)

**Comment by cs-1** [comment] 2024-10-17 07:48
I can confirm that we see the same behaviour.

**Comment by thordreier** [comment] 2024-10-30 14:58
If only `Q(interfaces_as_tagged=value)` or `Q(interfaces_as_untagged=value)` is used, it looks fine. But both combined messes up the joins. The query ends being:
```
SELECT
"ipam_vlan"."id", "ipam_vlan"."created", "ipam_vlan"."last_updated", "ipam_vlan"."custom_field_data",
"ipam_vlan"."description", "ipam_vlan"."comments", "ipam_vlan"."site_id", "ipam_vlan"."group_id",
"ipam_vlan"."vid", "ipam_vlan"."name", "ipam_vlan"."tenant_id", "ipam_vlan"."status", "ipam_vlan"."role_id"
FROM "ipam_vlan"
LEFT OUTER JOIN "dcim_interface_tagged_vlans" ON ("ipam_vlan"."id" = "dcim_interface_tagged_vlans"."vlan_id")
LEFT OUTER JOIN "dcim_interface" T4 ON ("ipam_vlan"."id" = T4."untagged_vlan_id")
WHERE ("dcim_interface_tagged_vlans"."interface_id" = 385 OR T4."id" = 385)
ORDER BY "ipam_vlan"."vid" ASC;
```
If ` and "dcim_interface_tagged_vlans"."interface_id" = 385` is added to the first `JOIN` the result looks fine - but I don't know how to do that in Django.

But a solution seems is to add `distinct` (in `netbox/ipam/filtersets.py`):
```
        return queryset.filter(
            Q(interfaces_as_tagged=value) |
            Q(interfaces_as_untagged=value)
        ).distinct()
```

See this commit: https://github.com/thordreier/netbox/commit/ee1de426074a28672fbc082f99348891a5df302d

**Comment by salfers** [comment] 2024-11-04 13:18
Couldn't the link just go to the interface page and focus the VLAN table? I don't see why it has to go to the VLAN list + filter there.

**Comment by thordreier** [comment] 2024-11-05 08:14
> Couldn't the link just go to the interface page and focus the VLAN table? I don't see why it has to go to the VLAN list + filter there.

That was also the first implentation in https://github.com/netbox-community/netbox/pull/17662 - but it was decided to change it.

**Comment by jsenecal** [comment] 2024-11-13 14:18
> See this commit: [thordreier@ee1de42](https://github.com/thordreier/netbox/commit/ee1de426074a28672fbc082f99348891a5df302d)

@thordreier would you be open to have this issue assigned to you and open a PR since you seem to already have the fix?

**Comment by thordreier** [comment] 2024-11-13 17:14
@jsenecal yeah, that's fine

**Comment by jeremystretch** [comment] 2024-12-26 15:23
@thordreier do you still intend to work on this issue?

**Comment by thordreier** [comment] 2024-12-27 19:57
Sorry. I forgot about this issue. I've created the pull request now.

**Closed** 2024-12-27 20:11 UTC
Labels: type: bug, status: accepted, severity: low, netbox
