### ISSUE TITLE
API error when updating custom field of type "multiple objects" with the object type being a virtualization interface

### ISSUE THREAD

**Issue by Molaron** [netbox-community/netbox#16344] opened 2024-05-29 10:14 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.10

### Steps to Reproduce

1. Create a new custom field `testfield` of type `Multiple Objects` and related object type `Virtualization > Interface`
2. Update the custom field using the api with the following body: `{ custom_fields: { test_field: [ { id: 40 } ] } }` (40 should be replaced with a valid id for a virtualization interface)

### Expected Behavior

The custom field should be updated to contain the virtualization interface with id 40

### Observed Behavior

The API returns status code 500 and the following error body:
```
{
    error: "'VMInterface' object has no attribute 'get'",
    exception: 'AttributeError',
    netbox_version: '4.0.3',
    python_version: '3.10.12'
}
```

The custom field is not updated

**Comment by jeffgdotorg** [comment] 2024-05-29 14:36
Thank you for reporting a problem you've encountered in NetBox.

Unfortunately, the provided **Steps to Reproduce** lack sufficient detail for me, the person auto-assigned to triage your issue, to get from a pristine, unpopulated NetBox instance to a state where the problem is reproducible. 

Please update the issue body in the following ways:
- Specify the set of objects that need to be created along the way beyond the obvious basics such as a site and a device type
- Provide full, self-contained instrucitons for making the API call, such as a `curl` command line invocation

**Closed** 2024-06-13 04:22 UTC
Labels: type: bug, status: revisions needed, pending closure
