### ISSUE TITLE
Cannot import or clone a Cable

### ISSUE THREAD

**Issue by Qwiko** [netbox-community/netbox#11210] opened 2022-12-16 09:12 UTC
### NetBox version

v3.4.0

### Python version

3.9

### Steps to Reproduce

1. Import Cables
2. Add data to import a cable
3. Click Import

### Expected Behavior

A cable should be created.

### Observed Behavior

A ValueError was raised.
Creating a cable through the UI is done successfully.
Using the API creates the same error as importing.

```
<class 'ValueError'>

'Cable' instance needs to have a primary key value before this relationship can be used.

Python version: 3.9.2
NetBox version: 3.4.0
```

There seems to also be an issue with Cloning a Cable:
When you click Clone on a Cable you recieve this error:

```
<class 'AttributeError'>

'str' object has no attribute 'label'

Python version: 3.9.2
NetBox version: 3.4.0
```

**Comment by Qwiko** [comment] 2022-12-16 09:15
If you provide the id for a cable it is updated correctly. This error is only when trying to import new cable objects.

**Comment by kkthxbye-code** [comment] 2022-12-16 09:49
> Add data to import a cable

Please provide all the steps required to replicate the issue, including example CSV data.

> Using the API creates the same error as importing.

Please provide replication steps for the API error also.

> There seems to also be an issue with Cloning a Cable:

This should probably be split out in a seperate bug report as they are unlikely to be related. I'm not even sure why it is possible to clone a cable as no fields are cloned and we don't provide a default "Add cable" option like most other models.

**Comment by kkthxbye-code** [comment] 2022-12-16 09:53
For reference I just tried importing the following cable and it worked without issue on 3.4.0:

```
side_a_device,side_a_type,side_a_name,side_b_device,side_b_type,side_b_name
dmi01-yonkers-sw01,dcim.interface,GigabitEthernet1/0/6,dmi01-yonkers-sw01,dcim.interface,GigabitEthernet1/0/7
```

**Comment by Qwiko** [comment] 2022-12-16 10:20
Then it must be in my environment.
Sorry for the inconvenience.
Closing this issue.

**Comment by jordanrvillarreal** [comment] 2022-12-16 20:04
I'm seeing similar behavior.  It feels like there are certain errors that aren't being caught.  While trying to bulk create if I had a bad interface type or name it would create the same primary key error but when I had included additional data in the cable color I received a specific error saying I provided 7 characters but it was only expecting 6.

**Comment by MasterWigu** [comment] 2022-12-19 16:34
I'm also seeing similar behavior. When creating new cables using the import feature (using a json snippet), it shows the same `'Cable' instance needs to have a primary key value before this relationship can be used.`. I can also confirm that the cables I'm adding have only the required fields set.

**Comment by sc68cal** [comment] 2022-12-30 13:11
I can reproduce this via trivial examples with our Ansible modules as well, with the latest from NetBox docker images 

```yaml
cables: 
  - a_device: clab-ipamexample-spine1
    a_name: e1-1
    b_device: clab-ipamexample-spine2
    b_name: e1-1
```

```yaml
- hosts: localhost
  gather_facts: False
  tags:
    - cables
  collections:
    - netbox.netbox
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "http://localhost:8000"
      netbox_token: "0123456789abcdef0123456789abcdef01234567"
      validate_certs: False
  tasks:
    - name: Create cables for spine links
      netbox_cable:
        data:
          termination_a_type: dcim.interface
          termination_a:
            device: "{{ item.a_device }}"
            name: "{{ item.a_name }}"
          termination_b_type: dcim.interface
          termination_b:
            device: "{{ item.b_device }}"
            name: "{{ item.b_name }}"
        state: present
      loop: "{{ cables }}"
```

This is supposed to be the minimal required amount of information, via our docs - https://netbox-ansible-collection.readthedocs.io/en/latest/plugins/netbox_cable_module.html#ansible-collections-netbox-netbox-netbox-cable-module

**Comment by sc68cal** [comment] 2022-12-30 13:38
I downgraded to the `2.0.0` tag of `netbox-docker` and re-ran the whole playbook and it succeeds, I think there is a significant regression that 0b86326435fe6ea07ef376a81ff6fb592906fafc introduced.

```

PLAY [all] ***********************************************************************************************************************

TASK [Create fake manufacturer] **************************************************************************************************changed: [clab-ipamexample-spine1 -> localhost]

TASK [Create router role] ********************************************************************************************************changed: [clab-ipamexample-spine1 -> localhost]

TASK [Create our site] ***********************************************************************************************************changed: [clab-ipamexample-spine1 -> localhost]

TASK [Create a device_type for our spines] ***************************************************************************************changed: [clab-ipamexample-spine1 -> localhost]

TASK [Create spine devices in netbox] ********************************************************************************************changed: [clab-ipamexample-spine1 -> localhost]
changed: [clab-ipamexample-spine2 -> localhost]
changed: [clab-ipamexample-spine4 -> localhost]
changed: [clab-ipamexample-spine3 -> localhost]

TASK [Create spine interfaces for each device in netbox] *************************************************************************changed: [clab-ipamexample-spine4 -> localhost] => (item=e1-1)
changed: [clab-ipamexample-spine2 -> localhost] => (item=e1-1)
changed: [clab-ipamexample-spine3 -> localhost] => (item=e1-1)
changed: [clab-ipamexample-spine4 -> localhost] => (item=e1-2)
changed: [clab-ipamexample-spine2 -> localhost] => (item=e1-2)
changed: [clab-ipamexample-spine3 -> localhost] => (item=e1-2)
changed: [clab-ipamexample-spine1 -> localhost] => (item=e1-1)
changed: [clab-ipamexample-spine2 -> localhost] => (item=e1-3)
changed: [clab-ipamexample-spine3 -> localhost] => (item=e1-3)
changed: [clab-ipamexample-spine1 -> localhost] => (item=e1-2)
changed: [clab-ipamexample-spine2 -> localhost] => (item=e1-4)
changed: [clab-ipamexample-spine3 -> localhost] => (item=e1-4)
changed: [clab-ipamexample-spine4 -> localhost] => (item=e1-3)
changed: [clab-ipamexample-spine1 -> localhost] => (item=e1-3)
changed: [clab-ipamexample-spine4 -> localhost] => (item=e1-4)
changed: [clab-ipamexample-spine1 -> localhost] => (item=e1-4)

PLAY [localhost] *****************************************************************************************************************

TASK [Create cables for spine links] *********************************************************************************************changed: [localhost] => (item={'a_device': 'clab-ipamexample-spine1', 'a_name': 'e1-1', 'b_device': 'clab-ipamexample-spine2', 'b_

name': 'e1-1'})

PLAY RECAP ***********************************************************************************************************************clab-ipamexample-spine1    : ok=6    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
clab-ipamexample-spine2    : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
clab-ipamexample-spine3    : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
clab-ipamexample-spine4    : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by sc68cal** [comment] 2022-12-30 13:41
One thing to note, creating the cable between `clab-ipamexample-spine1` and `clab-ipamexample-spine2` via the web UI did succeed while the API calls via the Ansible modules failed

**Comment by sc68cal** [comment] 2022-12-30 13:52
My full example is at https://github.com/sc68cal/netbox-p2p-ipam

**Comment by kkthxbye-code** [comment] 2022-12-30 14:11
@sc68cal - You got the wrong issue, this one is about csv import.

Also note that we don't accept API issues where the requests are generated via. another library, so if you create a bug report remember to replicate it with raw API requests.

**Comment by sc68cal** [comment] 2022-12-30 14:20
@kkthxbye-code 
> Also note that we don't accept API issues where the requests are generated via. another library, so if you create a bug report remember to replicate it with raw API requests.

You cannot just brush off this issue by saying oh it's another library so this isn't our problem. I am part of this same org, and responsible for the Ansible modules. In fact, we are in the same GitHub namespace, so I don't appreciate the brushoff.

> You got the wrong issue, this one is about csv import.

You closed a similar issue to this one as a duplicate, so instead of creating yet another issue, I decided to participate here.

**Comment by kkthxbye-code** [comment] 2022-12-30 14:24
> You cannot just brush off this issue by saying oh it's another library so this isn't our problem.

Just provide the raw requests that Ansible makes, not sure why you are being so aggressive. I didn't even make the rules.

The other issue was also about CSV import.

> You closed a similar issue to this one as a duplicate, so instead of creating yet another issue, I decided to participate here.

The other one was also about CSV import. Please create another issue, it's entirely unrelated to this one.

**Comment by sc68cal** [comment] 2022-12-30 14:30
> The other one was also about CSV import. Please create another issue, it's entirely unrelated to this one.

No. I am not going to create a different issue after spending my morning hunting down this regression, and putting time into putting detailed information in this bug report. I only arrived at this bug report by searching for any issue that contained the same error string that I encountered, which was the `'Cable' instance needs to have a primary key value before this relationship can be used.` error from the server.

This issue seems to be triggered from multiple code paths, both by importing, cloning, or creating a new cable. So, let's set aside category theory and get to work on hunting down the regression and fixing.

**Comment by kkthxbye-code** [comment] 2022-12-30 14:36
> So, let's set aside category theory and get to work on hunting down the regression and fixing.

There's an open PR for this issue (not your issue), you can check if that works.

Otherwise if you do not want to follow the contributor guidelines I cannot help you. Please refrain from responding again, you can contact me on slack if you have any questions. My slack name is "Simon Toft".

**Comment by DanSheps** [comment] 2022-12-30 14:45
If there is an issue with API requests, please open an issue specific to the API, and make sure to include the raw request.

We don't handle docker or ansible here which is why we need a issue with the raw request against a vanilla (non-docker) version of NetBox.

I looked at this a bit, I don't know what version of NetBox docker 2.0.0 equates to, nor do I follow the netbox-docker development to know what version of NetBox it is currently building against, however there were some API changes introduced in 3.4 that might impact building cables.

At first blush however, it doesn't looked like anything should be wrong, except for maybe the fact that interfaces need to be passed as arrays of now in the API (can't remember if this was 3.3 or 3.4 change)

**Comment by sc68cal** [comment] 2022-12-30 14:49
> Please refrain from responding again

I do not appreciate you telling me what I can or cannot do. I will honor your request by not interacting with you again. I will interact with @DanSheps going forward

**Comment by sc68cal** [comment] 2022-12-30 14:52
> I looked at this a bit, I don't know what version of NetBox docker 2.0.0 equates to, nor do I follow the netbox-docker development to know what version of NetBox it is currently building against, however there were some API changes introduced in 3.4 that might impact building cables.

> At first blush however, it doesn't looked like anything should be wrong, except for maybe the fact that interfaces need to be passed as arrays of now in the API (can't remember if this was 3.3 or 3.4 change)

Yes, this is my suspicion as well. I will retrieve what version of the NetBox API is deployed via `netbox-docker` tag `2.0.0` after I finish building #11231 and manually testing to see if that resolves the issue

**Comment by sc68cal** [comment] 2022-12-30 15:20
The proposed fix in 11231 did not fix my issue, but since I have been asked to not interact with the author, I will only put my notes here instead of commenting on that PR. The PR allows the code to go a little father, but returns a different error that appears to be a logic bug - https://gist.github.com/sc68cal/1b30c8ca7aa6a7e4af679015eb443a10 - it asks for me to define both endpoints, but I am via the Ansible module.

**Comment by sc68cal** [comment] 2022-12-30 15:21
> I looked at this a bit, I don't know what version of NetBox docker 2.0.0 equates to, nor do I follow the netbox-docker development to know what version of NetBox it is currently building against

`netbox-docker` tagged `2.0.0` corresponds to 41bf48171a61 (v3.2.7)

**Comment by kkthxbye-code** [comment] 2022-12-30 15:31
> The proposed fix in 11231 did not fix my issue, but since I have been asked to not interact with the author, I will only put my notes here instead of commenting on that PR.

That would also not be the correct place to comment, as your actual issue is that you haven't updated to the new API in v3.3. You are sending termination_a, termination_a_type, whereas it is now called a_terminations and b_terminations and take a list:

https://github.com/netbox-community/netbox/releases/tag/v3.3.0

* Several fields on the cable API serializers have been altered or removed to support multiple-object cable terminations:

| Old Name             | Old Type | New Name              | New Type |
|----------------------|----------|-----------------------|----------|
| `termination_a_type` | string   | _Removed_             | -        |
| `termination_b_type` | string   | _Removed_             | -        |
| `termination_a_id`   | integer  | _Removed_             | -        |
| `termination_b_id`   | integer  | _Removed_             | -        |
| `termination_a`      | object   | `a_terminations`      | list     |
| `termination_b`      | object   | `b_terminations`      | list     |

This isssue is about certain validations not being displayed, which is fixed in the PR. With the fix you were able to see the actual issue, which is as mentioned above, that you are sending the wrong parameters to the API.

**Comment by DanSheps** [comment] 2022-12-30 15:31
Please follow the instructions and the contributing guide.

Your issue is not related to CSV import.

**Comment by sc68cal** [comment] 2022-12-30 15:50
Ok. I did my due diligence and attempted to report my findings. It may have not been in the correct location but I spent the morning trying to hunt this down. I am moving on at this point since I'm tired to being told different things by different people when it comes to if I should post here or there, talk to people or not talk to people.

**Closed** 2023-01-06 19:57 UTC
Labels: type: bug, status: accepted, cabling
