### ISSUE TITLE
Swagger - Unable to use Prefix object in available-ips

### ISSUE THREAD

**Issue by stefanmcshane** [netbox-community/netbox#4469] opened 2020-04-09 04:13 UTC
### Environment
* Python version:   N/A
* NetBox version:   2.7.11

### Steps to Reproduce
1. Create Prefix object with available IPs
2. Get Available IPs for the prefix object (/api/ipam/prefixes/{id}/available-ips) using a swagger-generated client

### Expected Behavior
Should return a Prefix object, which has "prefix" as a required field, and family with the new static values

### Observed Behavior
Returns an object with the following issues (in order to be a valid prefix object):
- Prefix key is called "address", should be "prefix"
- Family is returned as an integer, should be a dict of {"value": 4, "type": "IPv4"} for example

**Comment by jeremystretch** [comment] 2020-04-09 13:09
Duplicate of #3356

**Closed by jeremystretch** 2020-04-09 13:09 UTC
