### ISSUE TITLE
Bulk edit of interface only shows vlans in site

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#6665] opened 2021-06-24 20:17 UTC
### NetBox version

v2.11.7

### Python version

3.7

### Steps to Reproduce

1. Create a site ("Site")
2. Create 2 vlans: 106 (Global), 129 (Site)
3. Create a device in "Site"
4. Create 2 interfaces on device
5. Select both interfaces and edit
6. Change interface mode to "Access"
7. Select VLAN and search for 106 and 129

### Expected Behavior

Vlan 106 and 129 should both show up

### Observed Behavior

Only vlan 129 shows up

**Comment by jeremystretch** [comment] 2021-08-12 13:56
I'm not able to reproduce this on `develop` currently. It's likely been resolved in a recent release. @DanSheps can you confirm please?

**Comment by jeremystretch** [comment] 2021-08-23 15:15
Closing this out as it's believed to have been resolved. Happy to re-open if someone can provide new steps to reproduce on a current stable release.

**Closed by jeremystretch** 2021-08-23 15:15 UTC
Labels: type: bug, status: under review
