### ISSUE TITLE
Assignment of already existing virtual IP addresses to FHRP group not possible

### ISSUE THREAD

**Issue by hoalex** [netbox-community/netbox#7769] opened 2021-11-07 10:20 UTC
### NetBox version

v3.1-beta1

### Python version

3.8

### Steps to Reproduce

1. Create a new IP address of type "CARP"
2. Open the edit view of the IP address object.
2. Try to assign it to an FHRP group.

### Expected Behavior

I would expect to see a third tab called "FHRP Group" under "Interface Assignment", next to Device and Virtual Machine.

### Observed Behavior

There is no form field that allows me to assign a virtual IP address to an FHRP group.

**Comment by bluikko** [comment] 2021-11-08 03:37
I was about to open a new issue but I believe it could be addressed with this issue as well.

The problem I found out was that if the IP address that was assigned to a FHRP Group is moved to another place, say some device interface, then there is no way to reset the IP address back to the FHRP Group.

The only way is to delete the FHRP Group and recreate with assigning the IP address to the FHRP Group.

The problem root cause is the same as in this issue - there is no way to assign an IP address to FHRP Group. Alternatively, re-assignment of IP addresses that are assigned to FHRP Groups could be disabled but I am not sure this is a better way.

**Comment by jeremystretch** [comment] 2021-11-08 13:11
> I would expect to see a third tab called "FHRP Group" under "Interface Assignment"

And what fields would you find under that tab? How would you expect to find and select a specific FHRP group? The reason there's no tab for FHRP group is that there's no context available to aid in the selection of a group. Suppose you have a hundred FHRP groups with the same ID. How do find the right one?

**Closed** 2021-11-11 19:45 UTC
Labels: status: accepted, type: feature, beta
