### ISSUE TITLE
Swagger API doc has incorrect documentation for `VRFRequest`

### ISSUE THREAD

**Issue by aaroneg** [netbox-community/netbox#16768] opened 2024-06-30 02:41 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.0.6

### Python Version

3.10

### Steps to Reproduce

Review the "New VRF" screen in netbox, and compare to https://$hostname/api/schema/swagger-ui/#/ipam/ipam_vrfs_create .
Very few fields are listed in the schema for  `VRFRequest`, and more fields are accepted by the API. The `PatchedVRFRequest` schema item looks more accurate.

### Expected Behavior

The documentation lists all available fields for the type of object

### Observed Behavior

The documentation is missing many fields.

**Comment by jeffgdotorg** [comment] 2024-07-01 20:52
Thank you for reporting this problem in NetBox. I was able to reproduce it in a fresh installation of v4.0.6. I'm moving your issue along to `needs owner` status.

We're generally aware that there are gaps in our OpenAPI coverage, but currently lack the team capacity to prioritize an effort to address these kinds of problems. If you or another developer with the requisite skills and capacity would like to work it through to a PR, please say so and a maintainer will assign the issue to you.

(Apologies for the copypasta of my reply on #16765)

**Comment by aaroneg** [comment] 2024-07-10 21:32
No need for apologies, opening the second issue it started to feel like i might be accidentally spamming.

**Comment by arthanson** [comment] 2024-07-12 06:07
Closing this as duplicate of #16765

**Closed by arthanson** 2024-07-12 06:07 UTC
Labels: type: bug, status: needs owner, topic: OpenAPI, severity: low
