### ISSUE TITLE
module number in installed module list

### ISSUE THREAD

**Issue by uRhaineWork** [netbox-community/netbox#9111] opened 2022-04-11 17:28 UTC
### NetBox version

v3.2.0

### Python version

3.9

### Steps to Reproduce

Follow steps in official tutorial on youtube from Jeremy:
https://www.youtube.com/watch?v=pIIqc31Mbwc
on creating module bay for device.

\\\edit///
Added steps for reproducing this behavior:

1. Add device 'fortigate-test'. Device role firewall, device type fortigate (without assigned template modules), site Test.
2. From added device -> add component -> module bays -> vdom1
3.  Add module type -> vd0-root . Manufacturer Fortigate same as device.
4. Go to Device -> module bays -> add module 'vd0-root' via green+button.

### Expected Behavior

In Device -> Module bays / installed module columne i dont want to see a number in bracket. eg.:
VDom 1: vd0-root (10)

### Observed Behavior

In Device -> Module bays / installed module columne, in its name field I get number in bracket that is not part of given name, it is a number of created module by 'system'. If I create 5 modules, delete them, add another 5 modules that number will count from last known created module number.

**Comment by jeremystretch** [comment] 2022-04-11 17:47
> Follow steps in official tutorial on youtube from Jeremy:

The video you linked is not an official tutorial, nor does it demonstrate a stable software release. Please provide detailed written reproduction steps per the bug report template.

**Comment by cyr0nk0r** [comment] 2022-04-11 18:14
I wouldn't call this a bug. It sounds like you don't want the ID included in the module name when looking at devices. Reasonable 'feature request', but I wouldn't call this a bug.

**Comment by uRhaineWork** [comment] 2022-04-11 19:09
1. Add device 'fortigate-test'. Device role firewall, device type fortigate (without assigned template modules), site Test.
2. From added device -> add component -> module bays -> vdom1
3. Add module type -> vd0-root . Manufacturer Fortigate same as device.
4. Go to Device -> module bays -> add module 'vd0-root' via green+button.

> It sounds like you don't want the ID included in the module name when looking at devices. Reasonable 'feature request', maybe not a bug though.

Looking at youtube link, there is no ID, so I thought this is only my problem. Migrated last from v.3.1.9.

**Comment by ekrichbaum** [comment] 2022-04-11 19:38
This may just be me, but I'm not sure that a module bay makes sense here.  Virtual Domains are not a physical thing (even though FTNT charges you for them like they are) and they don't have physical modules that are assigned with them. They are more like routing-instances or vrfs and could be tracked like a vrf in the ipam portion. 

I don't have any 5000s left on the network but that would be more appropriate to a module bay and module usage.

**Comment by uRhaineWork** [comment] 2022-04-12 05:44
> This may just be me, but I'm not sure that a module bay makes sense here. 

In my setup its important to see where given IP/network is. Eg my prefix / prefix list has columne with custom field on which Device is pulled with this new method from 3.2.0 via Objects, showing where gateway is terminated. Going down the line my IP address / address list has additional columne with 'fortigate vdom' custom field as I need to know at glance where given IP is. This one will pull Modules.
So u pull a main Device "fortigate" into Gateway columne, and if needed FortiGate VDOM into second columne to know if its root or somewhere else. Making VDOM as phisical object wont work, as this is not true and will cause problems in racks, connections etc. I think.

**Comment by jeremystretch** [comment] 2022-04-12 12:27
As @ekrichbaum points out, this is misusing the modules feature, which is intended to model physical hardware only. The number you see in parentheses is the module's unique primary key, which is sometimes needed to uniquely identify modules within a device (as modules by nature are unnamed).

I'm going to close this out as this is all expected behavior. If you'd like assistance modeling virtual domains, please consider starting a [discussion](https://github.com/netbox-community/netbox/discussions/new) to see what approaches others have taken.

**Closed by jeremystretch** 2022-04-12 12:27 UTC
Labels: type: bug, status: revisions needed
