### ISSUE TITLE
Deleting a connected port, interface or other connection on a device should not be possible if there's a connected cable

### ISSUE THREAD

**Issue by pobk** [netbox-community/netbox#5418] opened 2020-12-04 17:01 UTC
### Environment
* Python version: 3.7
* NetBox version: 2.9.9

### Proposed Functionality
Amend the deletion process for interfaces, and ports that prevents deletion of the interface/port if the port is bound.

The current "Disconnect" button and "Delete" button currently display the same UI with little variance, however, the delete button can be infinitely more destructive.

It should not be possible to delete a rear-port which is bound to front-ports that are bound to cables.

### Use Case
The current UI allows for the following scenario:

1. Create a patch panel device, e.g. 4U Panel Panel with 432 LC ports (modelling for example an extremely high density 4U modular patch bay with 12x 36 port LC cassettes)
1. Create a Rear-port with 432 positions (to model a 432F cable termination into a patch panel)
1. Create a Front port with the rear-port set to one of the 432F Rear-Port positions
1. Connect multiple front-ports of the 432 patch panel to devices in the rack
1. "Accidentally" click the "Delete" function, in place of the "Disconnect" button on the rear-port. Confirm the action, assuming you're disconnecting the cable from the rear-port given the difference between the two is "Delete cable" or "Delete port"... 
1. Watch in horror as 432F front-ports are also deleted as well as any connections made to each of the front-ports.
1. Make appointment with family practitioner/GP for anxiety and work related stress

This behaviour is not intuitive at present. The deletion button and disconnect button are pictographs and fairly close proximity to each other.

Furthermore the difference between the confirmation dialogue for deleting a cable and deleting a port is virtually identical aside from "Cable" or "Port". This can be missed during the mass-update/deletion process.

The use case should be as follows:

1. Create a patch panel device, e.g. 4U Panel Panel with 432 LC ports (modelling for example an extremely high density 4U modular patch bay with 12x 36 port LC cassettes)
1. Create a Rear-port with 432 positions (to model a 432F cable termination into a patch panel)
1. Create a Front port with the rear-port set to one of the 432F Rear-Port positions
1. Connect multiple front-ports of the 432 patch panel to devices in the rack
1. Clicking "Delete" function associated with a rear-port should display:
   1. an alternative deletion warning page which highlights which front-ports are also bound and that different confirmation mechanism be used to indicate that deletion of the rear-port will cascade the deletion of front-ports and cables in addition to the rear-port.
   1. an error noting that several of the front-ports are bound to cables and need to be disconnected first.

This should be expanded to include any interface, console port, power port or connection on a device. If it's connected to "something" then NetBox should either make it very obvious what other things will be affected or refuse to delete the object?

### Database Changes
No database changes required.

### External Dependencies
No external dependencies

**Comment by jeremystretch** [comment] 2020-12-04 18:21
> A delete confirmation is displayed and then actioned, which then deletes the cables.

This is the intended behavior. If you'd like to propose changing this behavior, please rewrite or resbumit your issue as a [feature request](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md) citing your specific use case.

**Comment by pobk** [comment] 2020-12-05 02:16
Revised to feature request.

**Comment by Infiniverse** [comment] 2020-12-05 09:23
Should this be expanded to, deleting any port or interface should not be possible if there is a cable connected to it?

**Comment by pobk** [comment] 2020-12-05 13:21
> Should this be expanded to, deleting any port or interface should not be possible if there is a cable connected to it?

Agreed. Have updated FR to include this on any connection made to a device, interface, ports, console, power etc...

**Comment by jeremystretch** [comment] 2020-12-08 21:16
This will need to be addressed by the community, as I suspect there's a good number of people who rely on the current behavior.

**Comment by pobk** [comment] 2020-12-15 16:10
I think the sticking point of this issue is that the confirmation page for deleting cables and a connections, look virtually identical.

Delete cable confirmation: [https://pasteboard.co/JF3FFNT.png](https://pasteboard.co/JF3FFNT.png)
Delete port confirmation: [https://pasteboard.co/JF3G0OW.png](https://pasteboard.co/JF3G0OW.png)

There's nothing immediately obvious in the UI to indicate that deletion of the port will also delete, ports, cables and interfaces and more possibly, in future. It's a lot more destructive.

I suspect the better option would be an alternative delete confirmation page, that way you're not breaking the work-flow, just reformatting it a little bit?

**Comment by TheTrafficNetwork** [comment] 2020-12-15 18:18
From my perspective, removing the cable before removing a port/interface/etc seems logical. If I were wanting to remove a module from a switch, I would in the majority of cases remove all of the cables first. I do not have anything that would break from this change so my views may be different than much more developed power users.

**Comment by pobk** [comment] 2021-02-08 23:45
So how does one get more input from the community on this to establish more of a consensus?

**Comment by pobk** [comment] 2021-03-17 11:19
Is there no more appetite for discussion here?

Is it worth putting together a PR for this?

**Comment by xkilian** [comment] 2021-03-17 12:44
I agree with the proposed changes. 

As for NOT permitting the deletion of a port, I am more in agreement than disagreement. I think other power users should provide feedback to see if after a warning it should be allowed anyway.
Our current cabling management system REQUIRES that a cable be disconnected before removing a port.. Especially because a "connexion" is not just a single cable but may be formed of a number of cables spanning multiple rooms or sites and care must be taking to decomission paths and/or single connexions depending on the use-case. (Removal, move, reconfiguration, etc.)

**Comment by xkilian** [comment] 2021-03-17 12:55
I think a PR should be prepared for this, are you proposing to do the work? I any case, the current way of doing things is dangerous.
As Netbox matures, it is issues like these that are valuable to improve workflow quality. Small things, but important things. 
Same as looking at it from a task based perspective: 
Take the TOP THREE tasks someone does in a day in Netbox and evaluate what can be improved:

- how is input done
- validation of input
- number of clicks to do the task
- number of panel changes to do a task
- complexity of data presented and interpreted to do the task
- sources of error
- sources of user frustration
- intuitiveness of UI
- consistancy of UI
- performance
- overall time mesure to do the task, etc.

Based on the evaluation, improving important use-cases will provide high value for the most users. :-)

**Comment by DanSheps** [comment] 2021-03-17 14:06
Here is my take on this:

It might be better to instead of making any sweeping changes to the current functionality, change the delete pages for every device to provide a list of "impacted" additional models.  For example, if you are deleting a rear port, it should simply state:

"You are deleting this port.  By deleting this port, the following will be deleted as well: <insert list>"

**Comment by jeremystretch** [comment] 2021-03-17 14:26
> I think a PR should be prepared for this

Per the contributing guide, please don't open a PR for an issue before it has been accepted.

**Comment by xkilian** [comment] 2021-03-17 15:47
Oups, yes of course, this should be an accepted issue before submitting an PR.

**Comment by pobk** [comment] 2021-04-21 17:57
> It might be better to instead of making any sweeping changes to the current functionality, change the delete pages for every device to provide a list of "impacted" additional models. For example, if you are deleting a rear port, it should simply state:
> 
> "You are deleting this port. By deleting this port, the following will be deleted as well: <insert list>"

This is the approach I was thinking of taking... Rather than simply looking like every other delete page in NetBox, adjust the delete template to communicate the complexity of the deletion... What else is going to be nuked. The sentiment being: if we communicate the changes to be made is a different way, someone might stop and identify the change as something they don't want to do.

The danger of the current generic approach, is that it looks like every other delete page, and users should strongly be urged to look at what they're deleting when it comes to read-ports, since it deletes more than is immediately obvious.

**Comment by pobk** [comment] 2021-04-21 18:01
@jeremystretch should I adjust the FR in line with current discussion... Re-define it as a change to templates rather than change to process?

Would that be more palatable?

**Closed** 2021-07-21 04:01 UTC
Labels: pending closure, status: under review, type: feature
