### ISSUE TITLE
Cannot edit values in decimal fields when the difference is not divisible by 0.0001

### ISSUE THREAD

**Issue by alryaz** [netbox-community/netbox#13183] opened 2023-07-14 12:12 UTC
### NetBox version

v3.5.6

### Python version

3.10

### Steps to Reproduce

1. Create a custom decimal field
2. Populate this field externally (using, for example, _pynetbox_ API) using a value that is not divisible by 0.0001 without remainder (ex. 199.99999)
3. Open editing page of the object for which field population occurred
4. Enter a new value that differs from existing one, but is divisible by 0.0001 (ex. 200)
5. Submit editing form
6. An error message surrounding the field arises stating that the new value is invalid, and that the closest valid candidates are within ±0.0001 of the previous field (ex. 199.99989 & 200.00009)

### Expected Behavior

Value saved to database on submission, no error arises

### Observed Behavior

Frontend prevents from submitting custom decimal field values whose `abs(NewValue - CurrentValue) mod 0.0001 > 0`

Example of such value: 199.447543808 changed to 200:
- New value remainder: `199.447543808 mod 0.0001 = 0.00004380799`
- Changes remainder: `abs(200-199.447543808) mod 0.0001 = 0.00005619199`

_Note:_ This is a frontend issue, not a backend one. The _step_ attribute (in `<input ... step="0.0001" ...>` is what causes it)

### (Possible) Feature request
Add ability to set custom resolution to decimal point fields

**Comment by jsenecal** [comment] 2023-07-14 19:40
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports. 

Could you please provide the steps to replicate your issue with an empty installation ?

**Comment by jeremystretch** [comment] 2023-07-25 20:50
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.

**Comment by kkthxbye-code** [comment] 2023-07-25 21:01
I mean he did edit the post afterwards, he just didn't make a new post saying he did.

**Comment by jsenecal** [comment] 2023-07-28 18:52
We were able to reproduce this bug - I reopened the issue

**Comment by jsenecal** [comment] 2023-07-28 18:54
@alryaz would you happen to know an easy way to fix this and would you like this issue assigned to you ?

**Comment by jsenecal** [comment] 2023-07-28 19:01
A potential solution would be to round the value to 4 decimals with javascript
```javascript
element.addEventListener('change', function() {
    var value = this.value;
    if (value === value) this.value = value.toFixed(4);
}, false)
```

`Number.prototype.toFixed()` Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed

**Comment by Kage1** [comment] 2023-09-01 15:36
As a follow up, it would be helpful if decimals were allowed at least 5 digits. This would allow storage of high precision numbers like custom latitude/latitude.

**Comment by pv2b** [comment] 2023-09-18 05:45
I have to ask, why does NetBox even care about how precise numbers stored in the database are? What's the problem it's trying to solve?

Unless there's any specific reason NetBox does it this way, It seems the correct approach is to allow storing numbers of arbitrary precision (well, up to the precision of the underlying datatype) and then just doing any rounding on the output side.

**Comment by jeremystretch** [comment] 2023-12-26 15:13
> Populate this field externally (using, for example, pynetbox API) using a value that is not divisible by 0.0001 without remainder (ex. 199.99999)

This is not supported: The declared precision of a custom decimal field is four decimal places. The bug in effect is that the specified value is not being rounded to the supported level of precision.

> Note: This is a frontend issue, not a backend one. The step attribute (in `<input ... step="0.0001" ...>` is what causes it)

This is because Django reasonably renders DecimalField with the `step` attribute set to the declared precision.

**Closed** 2024-04-19 14:06 UTC
Labels: type: bug, status: needs owner, pending closure, severity: low
