### ISSUE TITLE
Assigning IP to devices and interfaces

### ISSUE THREAD

**Issue by carlo-4ip** [netbox-community/netbox#13161] opened 2023-07-12 07:13 UTC
### NetBox version

v3.5.4

### Feature type

Change to existing functionality

### Proposed functionality

In the past, the assignment of an IP address to an interface was easier, because there were multiple fields (tenant, site, device, interface) to quickly search the device and select an interface.

Now there is the search button next to the interface field, which has more options and is a nice addition, but it is also not as easy as the old way. Most IP addresses are assigned to devices, so can we bring back these old "quick search" fields, next to the advanced search?

### Use case

As described in this discussion:
https://github.com/netbox-community/netbox/discussions/12577#discussioncomment-6250794

It makes it more easy and faster to link IP addresses to a device interface.

**Comment by kkthxbye-code** [comment] 2023-07-12 07:55
Duplicate of https://github.com/netbox-community/netbox/issues/12751

**Closed by kkthxbye-code** 2023-07-12 07:55 UTC
Labels: type: feature
