### ISSUE TITLE
Ability to hide core functionality menu items

### ISSUE THREAD

**Issue by kamfaima** [netbox-community/netbox#4575] opened 2020-05-05 06:58 UTC
### Environment
* Python version:  NA
* NetBox version:  NA

### Proposed Functionality
Ability to hide or display certain core functionality menu items. This could possibly be extended to hiding sub-menus in each of those core areas.

### Use Case
There will undoubtedly be times where certain tools contain functionality that overlap with others. For instance, we don't plan on storing secrets in Netbox as we already have a 3rd-party tool to do this. To enforce this, I propose simply hiding the Secrets menu from the core functionality menu so users won't be physically able to use Secrets. This will eliminate duplicate information being stored in two different tools.

It has been proposed in the Netbox user group that we can simply not grant the permissions to those menus. While this works, the menu item still appears but none of its elements are selectable. This can raise more questions like why is it there but not selectable. I would think it's better to simply not display the menu item altogether to remove this confusion.

### Database Changes
None that I know of.

### External Dependencies
None that I know of.

**Comment by jeremystretch** [comment] 2020-05-05 12:54
Duplicate of #4264

**Closed by jeremystretch** 2020-05-05 12:54 UTC

**Comment by createchange** [comment] 2020-08-21 07:10
I want to propose a solution to the problem that involves no code changes by the developer. I think you could take this to great lengths with advanced filtering and validation.

You can use uBlock (and other similar extensions) to filter out elements. 

As an example implementation, you would construct a query that finds an element with "Secrets", traverse back up X elements until you got to the navbar button, and wipe the things from existence. This would also be supremely easy to do on the dashboard.

The CSS is responsive, so hideous gaps are not left in wake.

Once you have figured it out on your machine, you would share the config with your users. It's as simple as copying and pasting - screenshots are wonderful.
