### ISSUE TITLE
From global search allow the finding of the containing subnet by searching for a single IP address

### ISSUE THREAD

**Issue by baldgeek** [netbox-community/netbox#11688] opened 2023-02-07 14:49 UTC
### NetBox version

v.3.4.2

### Feature type

Change to existing functionality

### Proposed functionality

From the global search, be able to find the subnet that an IP is in. 

Assuming the following prefixes are defined:

10.0.0.0/25

fd0b:0000:0000:8501::/64

Searching for 10.0.0.100 would return results containing 10.0.0.0/25

Searching for fd0b:0000:0000:8501:9d43:13da:e80d:879c would return results containing fd0b:0000:0000:8501::/64

Not being a programmer I can't propose a path to implementation. I'm still waiting to see if chatgpt can give me something ;)

### Use case

Returns functionality lost with the move to the new global search. 

### Database changes

I don't expect this is require any DB changes

### External dependencies

As there is similar functionality from searching prefixes directly, I don't believe there is a need for any new external dependencies.

**Comment by kkthxbye-code** [comment] 2023-02-07 19:06
As far as I can tell, duplicate of https://github.com/netbox-community/netbox/issues/11685

Please remember checking open issues before creating a new one.

**Closed by kkthxbye-code** 2023-02-07 19:06 UTC
Labels: type: feature

**Comment by baldgeek** [comment] 2023-02-08 13:29
My apologizes. I checked the day before but didn't check right before I submitted this.
