### ISSUE TITLE
The user language set in settings is not applied after logging in via Keycloak

### ISSUE THREAD

**Issue by dbmkin** [netbox-community/netbox#17103] opened 2024-08-08 08:16 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.0.6

### Python Version

3.10

### Steps to Reproduce

1. Click login via `Keycloack`
2. UI language is set to `Russian`

### Expected Behavior

UI translation should be as in user settings: `English`

### Observed Behavior

UI translation is set to `Russian`, as in `Accept-Language ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7`
Header `Content-Language:` is `ru` must be `en`

**Comment by alehaa** [comment] 2024-08-08 13:52
Might be a duplicate of #16995.

**Comment by arthanson** [comment] 2024-08-09 08:00
Closing as dupe of #16995

**Closed by arthanson** 2024-08-09 08:00 UTC
Labels: type: bug, status: needs triage
