### ISSUE TITLE
Unable to delete cable connected to circuit termination

### ISSUE THREAD

**Issue by nekonekun** [netbox-community/netbox#6459] opened 2021-05-21 09:43 UTC
### NetBox version

v2.11.3

### Python version

3.6

### Steps to Reproduce

1. Create new Circuit
![00](https://user-images.githubusercontent.com/7336287/119318821-6c14b980-bc82-11eb-86b6-1e82b97c9b9e.png)
2. Add Termination Sides
![02](https://user-images.githubusercontent.com/7336287/119318908-82bb1080-bc82-11eb-8398-5d00900b65ed.png)
3. Connect Termination Side to Device Interface
![03](https://user-images.githubusercontent.com/7336287/119318968-936b8680-bc82-11eb-85b7-0ca4b75e95b9.png)
4. Click on Disconnect button
![04](https://user-images.githubusercontent.com/7336287/119319109-b72ecc80-bc82-11eb-8f67-c8f177eaecbf.png)

### Expected Behavior

Cable deleted

### Observed Behavior

Get exception:
![05](https://user-images.githubusercontent.com/7336287/119319133-bc8c1700-bc82-11eb-896a-77b309fd3792.png)

**Comment by jeremystretch** [comment] 2021-05-21 20:00
I'm not able to reproduce the reported behavior following the instructions provided. Could you please revise your post above to cite the specific actions, citing the actual attribute values for each object and the means by which each action is taken?

**Comment by nekonekun** [comment] 2021-05-24 08:29
I don't catch exception if only one Termination Side is defined.
I don't catch exception when i delete cable using nbshell command `Cable.objects.get(id='12110').delete()`

**Comment by jeremystretch** [comment] 2021-05-25 14:43
Looks like a duplicate of #6398. Will be fixed in the upcoming v2.11.4 release.

**Closed by jeremystretch** 2021-05-25 14:43 UTC
Labels: status: revisions needed, type: bug
