### ISSUE TITLE
Swagger API has incorrect documentation for /api/circuits/provider-accounts/ and api/circuits/provider-networks

### ISSUE THREAD

**Issue by aaroneg** [netbox-community/netbox#16765] opened 2024-06-29 20:12 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.0.6

### Python Version

3.10

### Steps to Reproduce

View the swagger API docs located at https://$hostname/api/schema/swagger-ui/#/circuits/circuits_provider_accounts_create and you will see that the schema for `ProviderAccountRequest` does not mention any need to specify which provider the account is mapped to, but this field is in fact required.

### Expected Behavior

The documentation should show all fields, especially required fields.

### Observed Behavior

The required field 'provider' is missing from the documentation.

**Comment by aaroneg** [comment] 2024-06-29 21:05
Looks like it also affects `/api/circuits/provider-networks/`

**Comment by aaroneg** [comment] 2024-07-01 20:43
I'm not much of a python programmer but if you can whip up a short
explainer and it's simple enough i'm willing to give it a shot.

**Comment by jeffgdotorg** [comment] 2024-07-01 20:51
> I'm not much of a python programmer but if you can whip up a short explainer and it's simple enough i'm willing to give it a shot.

I want your expectations to be realistic – I can't guarantee approval of a PR, but if you're up for a learning exercise, go for it. Addressing these gaps really needs to be done as part of a holistic effort, using a consistent approach that has yet to be fleshed out.

**Comment by arthanson** [comment] 2024-07-10 08:03
This looks potentially like a display issue with spectacular, the field is required in the yaml:
```
    ProviderAccount:
      type: object
      description: Adds support for custom fields and tags.
      properties:
        id:
          type: integer
          readOnly: true
        url:
          type: string
          format: uri
          readOnly: true
        display:
          type: string
          readOnly: true
        provider:
          $ref: '#/components/schemas/Provider'
        name:
          type: string
          default: ''
          maxLength: 100
        account:
          type: string
          title: Account ID
          maxLength: 100
        description:
          type: string
          maxLength: 200
        comments:
          type: string
        tags:
          type: array
          items:
            $ref: '#/components/schemas/NestedTag'
        custom_fields:
          type: object
          additionalProperties: {}
        created:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        last_updated:
          type: string
          format: date-time
          readOnly: true
          nullable: true
      required:
      - account
      - created
      - display
      - id
      - last_updated
      - provider
      - url
```

**Comment by arthanson** [comment] 2024-07-10 09:23
What's happening is the nested=True serializer is getting instantiated first in CircuitSerializer, it looks like Spectacular is caching the fields from this call and using that.

**Comment by arthanson** [comment] 2024-07-12 06:10
closing as duplicate of #16670

**Closed by arthanson** 2024-07-12 06:10 UTC
Labels: type: bug, status: accepted, topic: OpenAPI, severity: low
