### ISSUE TITLE
wrong type for TreeNodeMultipleChoiceFilter in swagger

### ISSUE THREAD

**Issue by johanalmquist** [netbox-community/netbox#13459] opened 2023-08-13 12:05 UTC
### NetBox version

3.5.7

### Python version

3.10

### Steps to Reproduce

1. Go to /api/schema/swagger-ui/#/tenancy/tenancy_tenants_list
2. Enter tenant group slug

### Expected Behavior

I should get all my tenatns that belongs to the group with the provide name

### Observed Behavior

Got type i error in swagger:
Please correct the following validation errors and try again.
index0errorValue must be an integer

**Comment by johanalmquist** [comment] 2023-08-15 16:48
Hi,
My first bug report ever :) but i added some more infomation now

**Steps to Reproduce**
- create a new Tenant Group eg Name: My group Slug: my-group
- Create a new Tenant and add it to tenant  My group
- Navigate to the swagger rest api documentation (http://<netbox-host>/api/schema/swagger-ui/)
- Go down to the tenancy tab (http://<netbox-host>/api/schema/swagger-ui/#/tenancy)
- Select the route for tenancy_tenants (http://<netbox-host>/api/schema/swagger-ui/#/tenancy/tenancy_tenants_list)
- Press the "Try it out" button
- For the group query params enter the slug for the tenant group (my-group)

**Expected Behavior**
I should get all tenants that belongs to the tenant group My group. This works fine when you using api without the go via the swagger. 
The url i then: http://<netbox-host>/api/tenancy/tenants/?group=my-group

**Observed Behavior**
Got type i error in swagger:
Please correct the following validation errors and try again.
index0errorValue must be an integer

Se image
<img width="1104" alt="Skärmavbild 2023-08-15 kl  18 46 07" src="https://github.com/netbox-community/netbox/assets/16856344/b2e7f9bd-9e0c-4f40-88f2-c7b53cf4af14">
<img width="1104" alt="Skärmavbild 2023-08-15 kl  18 46 30" src="https://github.com/netbox-community/netbox/assets/16856344/21a6a6fb-df96-422e-a627-85a58a2925e6">

**Comment by kkthxbye-code** [comment] 2023-08-17 09:20
Replicates fine. Seems to be an issue with TreeNodeMultipleChoiceFilter not mapping to the correct type in the schema. Not sure how issues like these are fixed when the type depends on the `to_field_name` parameter. Doesn't seem to be an issue for `django_filters.ModelMultipleChoiceFilter`.

**Comment by aopdal** [comment] 2023-08-28 09:51
Does this bug track all string - integer errors in swagger?

**Comment by kkthxbye-code** [comment] 2023-08-28 10:05
> Does this bug track all string - integer errors in swagger?

All that are caused by `TreeNodeMultipleChoiceFilter` resolving to the wrong type.

**Comment by TorstenEhrhardt** [comment] 2024-07-12 07:50
I have a solution for this to get the type inside the TreeNodeMultipleChoiceFilter class
I already did a commit in my fork

**Closed** 2024-08-10 14:24 UTC
Labels: type: bug, status: accepted, topic: OpenAPI, severity: low
