### ISSUE TITLE
Not existing tag request returns HTTP 400

### ISSUE THREAD

**Issue by louis-oui** [netbox-community/netbox#5129] opened 2020-09-11 10:29 UTC
### Environment
* Python version: 3.6.8
* NetBox version: 2.9.3

### Steps to Reproduce
1. https://<hostname>/api/dcim/devices/?tag=doesnotexist
2. https://<hostname>/api/dcim/devices/?q=&site=doesnotexist
3. etc

### Expected Behavior

returns a json with count 0

### Observed Behavior

HTTP code 400
{
    "site": [
        "Select a valid choice. doesnotexist is not one of the available choices."
    ]
}

**Comment by jeremystretch** [comment] 2020-09-14 13:33
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Closed by jeremystretch** 2020-09-14 13:33 UTC
