### ISSUE TITLE
ip-address filter modifiers (__ic, __nic) for "interface" not functioning

### ISSUE THREAD

**Issue by DCAuto** [netbox-community/netbox#13466] opened 2023-08-14 18:06 UTC
### NetBox version

v3.4.5

### Python version

3.9

### Steps to Reproduce

using pynetbox module searching for all lo0 interfaces with a "." in them returns the "base" interface as well.

nb.ipam.ip_addresses.filter(device='TEST-DEVICE', interface__ic='lo0.')

The __ic and __nic modifiers do not function when filtering for assigned-interface-name

### Expected Behavior

Returns a list of addresses associated with "lo0.0", "lo0.1", "lo0.2" but omits the base interface "lo0"

### Observed Behavior

All 4 addresses are returned.

**Comment by kkthxbye-code** [comment] 2023-08-14 19:26
This is expected as it is documented:

https://docs.netbox.dev/en/stable/reference/filtering/#foreign-keys-other-fields

> Certain other fields, namely foreign key relationships support just the negation expression

Closing as this is not a bug. A feature request would be needed to evaluate changing it.

**Closed by kkthxbye-code** 2023-08-14 19:26 UTC
Labels: type: bug
