### ISSUE TITLE
hit "Device matching query does not exist" when delete a device

### ISSUE THREAD

**Issue by bybai** [netbox-community/netbox#3934] opened 2020-01-16 11:21 UTC
### Environment
* Python version:  3.6.6
* NetBox version:  2.6.9

### Steps to Reproduce
1. I select a device, this device has interface
2. I delete it, I got this error:
![image](https://user-images.githubusercontent.com/6743951/72520750-10b80780-3895-11ea-90e0-00530eed0953.png)

3. there is no error in backgroud:
[13/Jan/2020 07:04:30] "POST /dcim/devices/46/delete/ HTTP/1.1" 500 1766
[13/Jan/2020 07:04:30] "GET /static/bootstrap-3.4.1-dist/css/bootstrap.min.css HTTP/1.1" 304 0
[13/Jan/2020 07:04:30] "GET /static/font-awesome-4.7.0/css/font-awesome.min.css HTTP/1.1" 304 0
4. then I refresh this page, I got "Deleted device nodesw2" sucessful.

### Expected Behavior
There is no error page.

### Observed Behavior
There is a error page like above

**Comment by hSaria** [comment] 2020-01-16 12:18
I couldn't recreate this on v2.6.9, but it might be worth trying this on the latest stable release (v2.6.12).

**Comment by jeremystretch** [comment] 2020-01-16 13:59
Looks like a duplicate of #3927, which will be fixed in the next release.

**Closed by jeremystretch** 2020-01-16 13:59 UTC

**Comment by bybai** [comment] 2020-01-17 05:30
@jeremystretch, it is the same with #3927
after I added the patch in secrets/models.py, I still hit the problem
