### ISSUE TITLE
API creating of virtual-machine fails on IP

### ISSUE THREAD

**Issue by sngx13** [netbox-community/netbox#4125] opened 2020-02-10 14:19 UTC
Hi,

I'm having an issue referencing IP address i'm trying to assign to a VM. IP object is already created.

{
  "primary_ip4": [
    "The specified IP address (99.0.0.1/32) is not assigned to this VM."
  ]
}

request consists of: "primary_ip4": 3752 

{
  "id": 3752,
  "family": {
    "value": 4,
    "label": "IPv4"
  },
  "address": "99.0.0.1/32",
  "vrf": null,
  "tenant": {
    "id": 67,
    "url": "https://ipam.abc.net/api/tenancy/tenants/67/",
    "name": "INFRASTRUCTURE",
    "slug": "infrastructure"
  },
  "status": {
    "value": "active",
    "label": "Active",
    "id": 1
  },
  "role": null,
  "interface": null,
  "nat_inside": null,
  "nat_outside": null,
  "dns_name": "",
  "description": "",
  "tags": [],
  "custom_fields": {},
  "created": "2020-02-10",
  "last_updated": "2020-02-10T14:10:52.351730Z"
}

Any ideas?

Thank you.

**Comment by DanSheps** [comment] 2020-02-10 14:55
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Closed by DanSheps** 2020-02-10 14:55 UTC
