### ISSUE TITLE
NetBox 2.9 custom field selection changelog change between WebUI and API

### ISSUE THREAD

**Issue by cloos** [netbox-community/netbox#5123] opened 2020-09-10 08:08 UTC
### Environment
* Python version: 3.6.9
* NetBox version: 2.9.3

### Steps to Reproduce
1. create a custom field type selection with some values
2. create a device
3. set the custom field on the device in the WebUI: the changelog shows the custom field **value**
4. change the device status with a API patch request: the changelog shows a custom field value change from **value** to **label**

### Expected Behavior
The changelog for custom fields of type selection shows always the label, as in NetBox before 2.9

### Observed Behavior
The changelog for custom fields of type selection show on WebUI changes the value and on API changes the label (even if the custom field value wasn't changed by the API request).

Changelog of custom field value set via WebUI, custom field value (1) is shown:
![netbox_webui_custom_field_value_change](https://user-images.githubusercontent.com/165430/92698439-adf80c80-f34c-11ea-9e05-8cc42a768ecf.png)

Changelog of status change via API patch request, custom field changes from value (1) to label (D):
![netbox_api_status_change](https://user-images.githubusercontent.com/165430/92698783-1646ee00-f34d-11ea-9949-1ca85805aa3c.png)

**Comment by jeremystretch** [comment] 2020-09-14 15:30
Thank you for opening a bug report. I was unable to reproduce the reported behavior on the current `develop` branch: Updating the field via both the web UI and the REST API result in the changelog representation showing the integer value. This was likely changed during work on #5109.

I'm going to close this out as I'm fairly confident it's already been fixed, but please ask that it be re-opened if you continue to experience the issue on v2.9.4.

**Comment by cloos** [comment] 2020-09-14 16:22
@jeremystretch any chances to restore the old behavior from NetBox 2.8 to show the custom field choice label in the changelog?
Because it is hard to review a change in the changelog if you only see the integer IDs of the custom field choices.

**Comment by jeremystretch** [comment] 2020-09-14 17:40
Custom fields are being overhauled under #4878, so the entire data model will change in v2.10.

**Comment by cloos** [comment] 2020-09-25 11:50
@jeremystretch  I still can replicate this in 2.9.4

```shell
curl -sX PATCH -H "Authorization: Token $NETBOX_API_TOKEN" -H "Content-Type: application/json" -H "Accept: application/json; indent=2" "$NETBOX_URL/api/dcim/devices/109/" --data '{"status": "active"}'
```

![netbox_api_status_change](https://user-images.githubusercontent.com/165430/94263750-d62f6000-ff35-11ea-95dc-dde3382f2835.png)

**Comment by cloos** [comment] 2020-10-19 07:44
@jeremystretch can you please re-open this issue as I still can replicate the problem in 2.9.4.

**Comment by jeremystretch** [comment] 2020-10-19 13:18
FYI custom fields have been overhauled entirely for v2.10, so it's likely this won't be addressed in v2.9.

**Comment by cloos** [comment] 2020-10-20 12:08
@jeremystretch I can confirm that I don't see this problem in v2.10

I have also found with `git bisect` the commit that introduced this problem: dd707c97af7df048db7bb659fa11bc8002115804.
Would be great if you would find time to fix this for v2.9.

**Comment by jeremystretch** [comment] 2020-10-20 13:07
@cloos would you like to volunteer to take ownership of this issue?

**Comment by cloos** [comment] 2020-10-21 15:54
@jeremystretch I think I found the problem and can create a PR for this.

**Comment by cloos** [comment] 2020-10-23 09:20
@jeremystretch I have so far added tests and fixed it for WebUI create and update and API update, but I can't find the place where the cf values are cached for the API create request. Maybe you can give me a hint.

**Comment by cloos** [comment] 2020-12-15 16:16
@jeremystretch as NetBox 2.10 is released, this issue is no longer present and can be closed.

But I would like to provide the tests I have created, so this issue will never happen again.
Can we change the purpose if this issue or should I create a new one for the tests?

**Closed** 2020-12-16 19:29 UTC
Labels: status: accepted, type: bug
