### ISSUE TITLE
 A component template cannot be associated with both a device type and a module type.

### ISSUE THREAD

**Issue by xlimzlanex** [netbox-community/netbox#15307] opened 2024-02-28 23:50 UTC
### Deployment Type

Self-hosted

### NetBox Version

v3.7.3

### Python Version

3.8

### Steps to Reproduce

![Screenshot 2024-02-28 at 5 45 29 PM](https://github.com/netbox-community/netbox/assets/146968821/91750728-b29c-461b-baa3-d8473f68851c)

Trying to add a module to a device. Tried to add as a interface and did not work. Gave error in title. Also was able to reproduce in https://demo.netbox.dev/
![Screenshot 2024-02-28 at 5 47 42 PM](https://github.com/netbox-community/netbox/assets/146968821/a46b05fb-60cd-429e-b5ba-25692f1ae7b0)
.

### Expected Behavior

I would think that this would just work. After reading through the other issues it appeared to have been fixed but is now broken again. Please help

### Observed Behavior

Got greeted with this cool box.

**Comment by jeremystretch** [comment] 2024-02-29 12:53
This is working as intended. A component template can only exist on a device type _or_ a module type. It would not make sense to assign it to both.

**Closed by jeremystretch** 2024-02-29 12:53 UTC
Labels: type: bug
