### ISSUE TITLE
If the global search only finds one result, automatically redirect the user to its detail page

### ISSUE THREAD

**Issue by hoalex** [netbox-community/netbox#4759] opened 2020-06-15 12:41 UTC
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.4

### Proposed Functionality
When the search results of a global search contains exactly one entry, automatically redirect the user to this result's entry page. For example, if only a single device/VM/rack is found, redirect to the details page of this device/VM/rack.

### Use Case
This would save the user one mouse click to select the only entry in the search results page.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment] 2020-06-15 13:10
Duplicate of #2668

**Closed by jeremystretch** 2020-06-15 13:10 UTC
