### ISSUE TITLE
Assign FHRP Group "Group" dropdown limited to ~50 entries

### ISSUE THREAD

**Issue by moobys** [netbox-community/netbox#12281] opened 2023-04-18 13:53 UTC
### NetBox version

v3.4.8

### Python version

3.8

### Steps to Reproduce

1. Create 52+ FHRP groups
2. Try to assign FHRP group to interface

### Expected Behavior

All FHRP groups should be listed in the drop down

### Observed Behavior

FHRP group drop down will cut off at about 50 in the list and not display all FHRP groups

**Comment by jeremystretch** [comment] 2023-04-19 21:30
I'm not able to reproduce this on v3.4.8. After creating 100 FHRP groups, they all appear in the list of available groups when attempting to assign one to an interface.

It's likely that something is preventing the second API call from succeeding when you reach the end of the list. See if you can employ your browser's developer tools to determine whether the second API call is being made, and if so what the response is.

**Comment by moobys** [comment] 2023-04-25 17:37
I was able to recreate this today. I have 50+ FHRP groups and a switch with
50+ SVI virtual vlan interfaces but I don't think it is the FHRP group
quantity as much as group IDs above 200.
If I have an IP address assigned to the vlan interface first, then select
'assign FHRP group', only the FHRP group with an IP in the same subnet
appears.
If I do not have an IP address assigned to the vlan interface first, and
select  'assign FHRP group', all FHRP groups with group ID <200 appear, but
not the higher group IDs. This was my issue as I was trying to assign FHRP
groups with group IDs in the 200-255 range.

I was able to assign IPs to the interfaces first and then the FHRP group
(greater than 200) to the interface, so I'm not sure it's an issue now,

Thanks,
Jeff Blackmon
***@***.***

**Comment by jeremystretch** [comment] 2023-05-02 13:30
I'm going to close this out it doesn't appear any action is needed at this time. If you continue to encounter issues, we're happy to revisit this.

**Closed by jeremystretch** 2023-05-02 13:30 UTC
Labels: type: bug, status: revisions needed
