### ISSUE TITLE
No image preview on mouse hover

### ISSUE THREAD

**Issue by tux-mania** [netbox-community/netbox#12701] opened 2023-05-24 13:37 UTC
### NetBox version

v3.5.2

### Python version

3.9

### Steps to Reproduce

1. Go to a Site containing images in attachment
2. Put the mouse on the image link name

### Expected Behavior

Usually, when placing the mouse on the image link (without clicking), an image preview used to appear.

### Observed Behavior

Nothing happens now (we have to click to show the image).

**Comment by kkthxbye-code** [comment] 2023-05-24 13:41
Duplicate of https://github.com/netbox-community/netbox/issues/12627

**Closed by kkthxbye-code** 2023-05-24 13:41 UTC
Labels: type: bug
