### ISSUE TITLE
N+1 issue on the /api/ipam/ip-addresses/ endpoint

### ISSUE THREAD

**Issue by mulmat** [netbox-community/netbox#15845] opened 2024-04-25 09:00 UTC
### Deployment Type

Self-hosted

### NetBox Version

v3.7.6

### Python Version

3.10

### Steps to Reproduce

Call the  `/api/ipam/ip-addresses/` endpoint with more than 1 assigned ip address in the database (important that the ip addresses are assigned and you are listing assigned ip addresses, for example by using `assigned_to_interface=true` filter)

### Expected Behavior

No N+1 issue.

I can submit I PR if wanted (I think the issue is that `IPAddressViewSet` are missing `assigned_object_type` in the `prefetch_related`)

### Observed Behavior

N+1 issue with the following query:

`SELECT ••• FROM "django_content_type" WHERE "django_content_type"."id" = X LIMIT 21`

**Comment by jeremystretch** [comment] 2024-04-25 12:08
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.7.6. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by jeremystretch** [comment] 2024-04-29 14:15
@mulmat thanks, I've assigned this to you. A word of caution: be aware that the tables wipe out any prefetches set on the view's queryset, so addressing this will likely need work on the column itself.

**Comment by jeremystretch** [comment] 2024-04-29 14:43
Sorry; I had it in my head that this was for the UI. Disregard my note above!

**Closed** 2024-04-29 14:50 UTC
Labels: type: bug, status: needs owner, severity: low
