### ISSUE TITLE
Time in Change Log without timezone

### ISSUE THREAD

**Issue by fixed77** [netbox-community/netbox#16143] opened 2024-05-15 11:49 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.0.2

### Python Version

3.10

### Steps to Reproduce

1. Set TIME_ZONE in configuration.py
2. Make changes
3. Go to Changelog

### Expected Behavior

Time in Changlelog table and events in localtime

### Observed Behavior

Time in Changlelog table and events in UTC

**Comment by samk-acw** [comment] 2024-05-27 05:43
This seems to be a regression due to https://github.com/netbox-community/netbox/pull/15737, or a djanjo 5 side effect.

A potential fix is loading the TIME_ZONE preference and doing .astimezone() before any .isoformat() call. This appeared to work when testing for myself but not sure about any other implications

**Comment by Julio-Oliveira-Encora** [comment] 2024-05-27 20:00
Could you please assign it to me?

**Closed** 2024-06-12 13:23 UTC
Labels: type: bug, status: accepted, severity: low
