### ISSUE TITLE
LdapBackendAuthentication with API tokens

### ISSUE THREAD

**Issue by jessux** [netbox-community/netbox#11115] opened 2022-12-05 22:17 UTC
### NetBox version

V3.3.9

### Python version

3.9

### Steps to Reproduce

Setup LDAP authentication with 

# Remote authentication support
REMOTE_AUTH_ENABLED = True
REMOTE_AUTH_BACKEND = 'netbox.authentication.LDAPBackend'
REMOTE_AUTH_HEADER = 'HTTP_REMOTE_USER'
REMOTE_AUTH_AUTO_CREATE_USER = True
REMOTE_AUTH_DEFAULT_GROUPS = []
REMOTE_AUTH_DEFAULT_PERMISSIONS = {}

Log to netbox
Create a local account + a token or a create a token for your account

Setup logging debug for LDAP

Call API with the token

### Expected Behavior

The API call don't need to call the LDAP authentication

### Observed Behavior

Every API call, it calls the LDAP

**Comment by jessux** [comment] 2022-12-05 22:33
Update :

in the file authentication.py:
       user = token.user
      # When LDAP authentication is active try to load user data from LDAP directory
      if settings.REMOTE_AUTH_BACKEND == 'netbox.authentication.LDAPBackend':
          from netbox.authentication import LDAPBackend
          ldap_backend = LDAPBackend()

          # Load from LDAP if FIND_GROUP_PERMS is active
          # Always query LDAP when user is not active, otherwise it is never activated again
          if ldap_backend.settings.FIND_GROUP_PERMS or not token.user.is_active:
              ldap_user = ldap_backend.populate_user(token.user.username)
              # If the user is found in the LDAP directory use it, if not fallback to the local user
              if ldap_user:
                  user = ldap_user

This part of code calls every requests the user in the LDAP.
Our LDAP locks connections for 2 minutes when spamming binding requests.
Is this part of code is normal or should be changed ?
We commented this part on our netbox and works fine !

**Comment by kkthxbye-code** [comment] 2022-12-06 06:41
Disable AUTH_LDAP_FIND_GROUP_PERMS and use AUTH_LDAP_MIRROR_GROUPS or manage groups manually instead.

Related issues and discussions:

https://github.com/netbox-community/netbox/pull/7928
https://github.com/netbox-community/netbox/issues/7751
https://github.com/netbox-community/netbox/pull/7676
https://github.com/netbox-community/netbox/issues/6926
https://github.com/netbox-community/netbox/discussions/7708

Short summary: The remaining issue is caused by the cache in django-auth-ldap not functioning with the way we are calling it for API access. No one has even shown any interest in fixing the underlying issue though.

I'll close this out, if you are interested in fixing the django-auth-ldap integration (not just removing the authentication code), I'll reopen it, assign you and you can rewrite the bug report to conform to the template.

**Closed by kkthxbye-code** 2022-12-06 06:41 UTC
Labels: type: bug

**Comment by jessux** [comment] 2022-12-07 13:38
Hello,
Thanks for your reply.
I'm not having time for this right now but if i find a correction i'll post it for sure !
