### ISSUE TITLE
Deleting vlan deployed on interface causes Server Error

### ISSUE THREAD

**Issue by netixx** [netbox-community/netbox#5906] opened 2021-03-02 14:18 UTC
### Environment
* Python version: 3.8.7
* NetBox version: 2.10.4

### Steps to Reproduce
1. Create a VLAN (specify VID and VLAN name, no specific configuration needed)
2. Use this vlan as access on a interface: select an interface in a device, configure 802.1q mode (say access), select previously created vlan in "Untagged VLAN". Please note it also works when using the tagged option.
3. Delete the previously created VLAN (select VLAN, delete, confirm).
4. Go back to the page of the interface => the Server Error occurs.

### Expected Behavior
Option A: prevent VLAN from being delete as configuration of interface depends on it.
Option B: delete the vlan from the configuration of the interface when the vlan is deleted from NetBox.

### Observed Behavior
Following error occurs when browsing the interface:
```
<class 'ipam.models.VLAN.DoesNotExist'>

VLAN matching query does not exist.

Python version: 3.8.7
NetBox version: 2.10.4
```

I would favor option B, as from a user standpoint, deleting a vlan should remove this vlan on all interfaces.
However, dealing with access interfaces could be more tricky...

**Comment by xkilian** [comment] 2021-03-02 14:37
I would kindly disagree, that deleting a vlan that is used should not be allowed. 
In a switch or router you cannot delete a vlan if it is assigned. Least surprise. Deleting a vlan that is used could have all kinds of funky side effects, and implies that changes are also done beyond the original intention. Trunk port that only has vlan X on it, access ports, prefixes assigned to vlans, etc.
Of course you have to find all the places the vlan is assigned and unassign them, which is a hassle, but it *is* a change which should be tracked.

**Comment by netixx** [comment] 2021-03-02 15:38
Our use case is mostly switching, this is why I favored option B, but as I stated, option A is the more rational choice (and more consistent with the rest of the objets).

**Comment by jeremystretch** [comment] 2021-03-02 15:57
Please expand your steps above to detail exactly how the VLAN is being created, assigned, and deleted so that someone else can attempt to reproduce the issue.

**Comment by netixx** [comment] 2021-03-02 17:14
I updated my original post above.
I really didn't do anything specific to trigger this behaviour.
Please let me know if I need to provide any additionnal information or steps.

**Comment by sdktr** [comment] 2021-03-02 22:06
I'd prefer option C in this- as well as other 'locked-when-in-use' cases: warn for dependencies but allow to delete anyway instead of going back to all the referenced dependent resources and delete the association 1-by-1

**Comment by netixx** [comment] 2021-03-11 09:19
in the case of option C, would the vlan be removed from the interface ? or would the interface display an explicit error on the vlan field (as opposed to the server error as it is currently the case) ?

**Comment by jeremystretch** [comment] 2021-03-11 18:55
Seems to be yet another caching issue. I've been able to confirm that this only occurs when caching is enabled. I'm not sure why deleting the VLAN is not invalidating the cached query.

**Comment by jeremystretch** [comment] 2021-07-26 12:05
Closing this out as caching is being removed in v3.0. The workaround for now is to disable caching by setting `CACHE_TIMEOUT = 0` in configuration.py.

**Closed by jeremystretch** 2021-07-26 12:05 UTC
Labels: pending closure, status: needs owner, type: bug
