### ISSUE TITLE
Webhooks should optionally send the previous object or a diff

### ISSUE THREAD

**Issue by twexler** [netbox-community/netbox#4530] opened 2020-04-23 15:48 UTC
### Environment
* Python version:  3.x.x
* NetBox version:  2.7.10

### Proposed Functionality
Webhook payloads would either contain the previous state of the object, or a diff of what is changing

### Use Case
We're using Netbox as a source of truth to drive declarative deployments with ansible, wherein the inventory file is automatically updated by an external system via Git. Knowing both the original and the end state of the object is important in this workflow, as the inventory files may be stored in disparate git repos.

### Database Changes
None

### External Dependencies
None

**Comment by dstarner** [comment] 2020-04-23 15:49
I wouldn't say optionally. The changelog should provide a diff in case the last change was outside of the retention log period. This functionality already exists and is used elsewhere, so using this to save to the model shouldn't be a big deal, other than some slight gained performance overhead.

**Comment by twexler** [comment] 2020-04-23 15:50
I'm only proposing it be optional as it's a potential breaking change in the webhook's payload shape, and it could potentially make the webhook payload much larger.

**Comment by dstarner** [comment] 2020-04-23 16:14
I would think that adding a `prev_object_data` to the `ObjectChange` model wouldn't be too bad. Then scripts, webhooks, and the API could use this functionality.

**Comment by jeremystretch** [comment] 2020-04-24 13:11
Duplicate of #3451

**Closed by jeremystretch** 2020-04-24 13:11 UTC

**Comment by twexler** [comment] 2020-04-24 13:49
@jeremystretch that issue was closed as stale, and the comments don't address the concerns I'm looking to address. Can we re-open this for more discussion?
