### ISSUE TITLE
Ability to Wireless Point to Point Links

### ISSUE THREAD

**Issue by lazylionca** [netbox-community/netbox#5354] opened 2020-11-17 21:19 UTC
### Environment
* Python version: 
* NetBox version: 

### Proposed Functionality

We are a Wireless ISP. We would like to be able to add Point-to-Point Wireless Links as an entity similar to cables.
The entity would then reference multiple devices, cables, interfaces, and sites.
Not just two devices though as there are bonded or aggregated devices that work together in a LAG to form
a singular network path.  

### Use Case

Wisps mostly but also companies who tie two sites together via a PTP radio shot.
While this may seem similar to Circuits, we have multiple customer circuits that traverse our radios links same as a cable.

### Database Changes

Add a new element type similar to Cables or Circuits with relevant properties such as Max Speeds, Distance, 

### External Dependencies

None Expected

**Comment by jeremystretch** [comment] 2020-11-17 21:20
Duplicate of #3979

**Closed by jeremystretch** 2020-11-17 21:20 UTC
