### ISSUE TITLE
Add Components to Module Types not working as expected?

### ISSUE THREAD

**Issue by bdangus** [netbox-community/netbox#10389] opened 2022-09-16 15:47 UTC
### NetBox version

V3.3.3

### Python version

3.10

### Steps to Reproduce

I'm reluctant to label this as a bug, because I may be doing something wrong, but I'm not sure what?  In any event, here are the details...

I'm doing this all from the demo application: (https://demo.netbox.dev/)
I'm trying to add an interface component to a module type.

Create a Module Type
Choose Add Components... Interfaces
The "Add a new interface template" form appears:
- Device type* is "-----" (I'm not sure what to put here since I don't think it's relevant in this context)
- Module type is pre-selected based on the module type I am adding an interface to
- I choose an interface Type (e.g. 100BASE-TX)
If I leave Device Type* blank, I get "Device Type field is required" message underneath the Device Type field
If I select a Device Type (just to try it), I get "A Component template cannot be associated with both a device type and a module type" message in red in the bottom right.

I also tried adding a Power Port component and ran into the same thing.

### Expected Behavior

I'm expecting that I won't need to select a Device Type when adding a Component to Module Type.

### Observed Behavior

I'm being forced to select a Device Type when adding a Component to Module Type.  If I do, I get "A Component template cannot be associated with both a device type and a module type" message in red in the bottom right.

**Comment by kkthxbye-code** [comment] 2022-09-16 15:50
Duplicate of https://github.com/netbox-community/netbox/issues/10383

It is fixed and will be in the next release.

**Closed by kkthxbye-code** 2022-09-16 15:50 UTC
Labels: type: bug
