### ISSUE TITLE
Rack SVG splits into two at certain screen widths

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#4110] opened 2020-02-06 17:15 UTC
### Environment
* Python version:  3.5.2
* NetBox version:  2.7.4

### Steps to Reproduce
1. Create a rack with height 47U
2. Go to `/dcim/racks/NNN/`
3. Adjust the width of the window

### Expected Behavior
SVGs to display normally, regardless of screen width.

### Observed Behavior
At a screen width between 992px and 1183px, the rack splits into two, with U labels 1-47 at the top and the actual U slots below. 

![image](https://user-images.githubusercontent.com/44789/73960849-7d0db000-4903-11ea-9c59-bedaa2221905.png)

This is with Chrome 79 under macOS 10.14.6

**Comment by DanSheps** [comment] 2020-02-12 05:37
Duplicate of #3986

**Closed by DanSheps** 2020-02-12 05:37 UTC
Labels: status: accepted, type: bug
