### ISSUE TITLE
Regex validator in field `dns_name` in model `IPAddress` conflict with empty string value

### ISSUE THREAD

**Issue by haminhcong** [netbox-community/netbox#4074] opened 2020-02-01 09:03 UTC
### Environment
* Python version:   3.6.8
* NetBox version:   2.6.6, develop

### Steps to Reproduce
1. Run netbox with default configuration, create an IP Address, example `192.168.10.15/24`, with `dns name`  field is empty
2. Get netbox swagger schema document from url `/api/swagger.yaml`.Create python netbox client by `swagger-codegen` from swagger document
3. Use client to get ipaddress list from netbox api, example:

```python
import netbox_client

netbox_client_config = netbox_client.Configuration()
netbox_client_config.host = #NETBOX_API_URL
netbox_client_config.api_key["Authorization"] = "Token {}".format(
    #TOKEN
)

api_client = netbox_client.ApiClient(netbox_client_config)
ipam_app_api = netbox_client.IpamApi(api_client)
api_resp = ipam_app_api.ipam_ip_addresses_list()
print('done')

```

### Expected Behavior

python client return IP Address object list. No Exceptions raised.

### Observed Behavior

python netbox client raise Exception:

```log
ValueError: Invalid value for `dns_name`, must be a follow pattern or equal to `/^[0-9A-Za-z._-]+$/`
```

when at least one IP Address has empty `dns_name`

### Reason

With current iplementation:

```python

DNSValidator = RegexValidator(
    regex='^[0-9A-Za-z._-]+$',
    message='Only alphanumeric characters, hyphens, periods, and underscores are allowed in DNS names',
    code='invalid'
)

class IPAddress(ChangeLoggedModel, CustomFieldModel):
    #...
    dns_name = models.CharField(
        max_length=255,
        blank=True,
        validators=[DNSValidator],
        verbose_name='DNS Name',
        help_text='Hostname or FQDN (not case-sensitive)'
    )

```

`dns_name` field will generated in swagger document like this:

```yaml
  IPAddress:
    required:
      - address
      dns_name:
        title: DNS Name
        description: Hostname or FQDN (not case-sensitive)
        type: string
        pattern: ^[0-9A-Za-z._-]+$
        maxLength: 255
```

this definition when converted to python client:

```python
    @dns_name.setter
    def dns_name(self, dns_name):
        """Sets the dns_name of this IPAddress.

        Hostname or FQDN (not case-sensitive)  # noqa: E501

        :param dns_name: The dns_name of this IPAddress.  # noqa: E501
        :type: str
        """
        if dns_name is not None and len(dns_name) > 255:
            raise ValueError("Invalid value for `dns_name`, length must be less than or equal to `255`")  # noqa: E501
        if dns_name is not None and not re.search(r'^[0-9A-Za-z._-]+$', dns_name):  # noqa: E501
            raise ValueError(r"Invalid value for `dns_name`, must be a follow pattern or equal to `/^[0-9A-Za-z._-]+$/`")  # noqa: E501

        self._dns_name = dns_name
```

when dns_name is empty or missing, Django automatically set its value in database to empty string `''`. In this scenario, when python client get ipaddress info from netbox api, dns_name will be validated in `dns_name.setter` method and not pass regex validator, and ValueError will be raised.

## Proposal Change

Because we allow dns_name is empty, could we change validator restriction from `1 or many`: `'^[0-9A-Za-z._-]+$'` to `0 or many`: `'^[0-9A-Za-z._-]*$'` ?

**Comment by kobayashi** [comment] 2020-02-06 05:40
This does not cause any current Regular expression. 

```python
>>> bool(re.search(r'^[0-9A-Za-z._-]+$', "")) # 1 or many
False
# 0 or many
>>> bool(re.search(r'^[0-9A-Za-z._-]*$', ""))
True
>>> bool(re.search(r'^[0-9A-Za-z._-]*$', "test"))
True
>>> bool(re.search(r'^[0-9A-Za-z._-]*$', "!@#"))
False
>>> bool(re.search(r'^[0-9A-Za-z._-]*$', "!"))
False
>>>
```

**Comment by kobayashi** [comment] 2020-02-06 07:51
Opened PR #4101 . If this issue is accepted, we can merged it.

**Comment by jeremystretch** [comment] 2020-02-06 14:49
I'm afraid I don't follow. Here is the current API definition generated on v2.7.4:

```yaml
  IPAddress:
    required:
      - address
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      <snip>
      dns_name:
        title: DNS Name
        description: Hostname or FQDN (not case-sensitive)
        type: string
        pattern: ^[0-9A-Za-z._-]+$
        maxLength: 255
      description:
        title: Description
        type: string
        maxLength: 100
      <snip>
```

As I understand it, this asserts that the only _required_ field is `address`; the `dns_name` field and others are optional. Are we in agreement that this is correct?

If so, I see no reason to modify the regex, as it should be enforced only if a value is present. If the client being created is demanding a value for the field despite it not being a required field, that sounds to me like a bug in the client.

**Comment by DanSheps** [comment] 2020-02-06 15:24
It looks like this might be an issue with netbox_client and not Netbox.

It looks like @haminhcong is trying to poll the /ipam/ip-addresses endpoint with the netbox_client.

I haven't tested Netbox client but https://master.netbox.dansheps.com/ipam/ip-addresses/ returns s clean page.

I think the issue is @haminhcong is looking at the form or filter but the form doesn't do anything with a list query and the filter isn't interacted with unless there is a query string to perform filtering.

**Comment by DanSheps** [comment] 2020-02-06 23:41
Here is the relevant section from the swagger.yaml on 2.7.4:


```
  IPAddress:
    required:
      - address
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      family:
        title: Family
        required:
          - label
          - value
        type: object
        properties:
          label:
            type: string
          value:
            type: string
        readOnly: true
      address:
        title: Address
        description: IPv4 or IPv6 address (with mask)
        type: string
      vrf:
        $ref: '#/definitions/NestedVRF'
      tenant:
        $ref: '#/definitions/NestedTenant'
      status:
        title: Status
        required:
          - label
          - value
        type: object
        properties:
          label:
            type: string
          value:
            type: string
      role:
        title: Role
        required:
          - label
          - value
        type: object
        properties:
          label:
            type: string
          value:
            type: string
      interface:
        $ref: '#/definitions/IPAddressInterface'
      nat_inside:
        $ref: '#/definitions/NestedIPAddress'
      nat_outside:
        $ref: '#/definitions/NestedIPAddress'
      dns_name:
        title: DNS Name
        description: Hostname or FQDN (not case-sensitive)
        type: string
        pattern: ^[0-9A-Za-z._-]+$
        maxLength: 255
      description:
        title: Description
        type: string
        maxLength: 100
      tags:
        type: array
        items:
          type: string
          minLength: 1
      custom_fields:
        title: Custom fields
        type: object
      created:
        title: Created
        type: string
        format: date
        readOnly: true
      last_updated:
        title: Last updated
        type: string
        format: date-time
        readOnly: true
```

**Comment by DanSheps** [comment] 2020-02-06 23:42
I just double checked and can confirm that @jeremystretch is correct, the swagger.yaml is correct for this and it looks like if anything this is a swagger-codegen issue and not a Netbox issue,

**Comment by haminhcong** [comment] 2020-02-07 02:12
> I'm afraid I don't follow. Here is the current API definition generated on v2.7.4:
> 
> ```yaml
>   IPAddress:
>     required:
>       - address
>     type: object
>     properties:
>       id:
>         title: ID
>         type: integer
>         readOnly: true
>       <snip>
>       dns_name:
>         title: DNS Name
>         description: Hostname or FQDN (not case-sensitive)
>         type: string
>         pattern: ^[0-9A-Za-z._-]+$
>         maxLength: 255
>       description:
>         title: Description
>         type: string
>         maxLength: 100
>       <snip>
> ```
> 
> As I understand it, this asserts that the only _required_ field is `address`; the `dns_name` field and others are optional. Are we in agreement that this is correct?
> 
> If so, I see no reason to modify the regex, as it should be enforced only if a value is present. If the client being created is demanding a value for the field despite it not being a required field, that sounds to me like a bug in the client.


According swagger schema document for `dns_name` field you posted above:  `dns_name` field is not required => `dns_field` can have null value, and any string satisfy with Regex `'^[0-9A-Za-z._-]+$'` 
=> Empty string is not valid with this swagger schema definition.

But in Django model definition for `dns_name` field, we have two condition `blank=True` and `validators=[DNSValidator]`, it means that `dns_name` value range store in DB is empty string `''` and every value match with regex `'^[0-9A-Za-z._-]+$'` => Empty string is valid with Django Model definition

=> have a conflict between `dns_name` Django Model Definition and  `dns_name`  document schema definition.

You don't catch any error when query API with plain HTTP clients like curl or wget, because these clients don't validate API response, but with other clients use swagger document to validate API response like python client, exception will be raised.

=> I don't think it is a client problem, because this is the conflict between generated swagger schema definition and Django model definition.

**Comment by jeremystretch** [comment] 2020-02-07 02:50
`blank=True` explicitly states that the field may be blank. The validators apply _only if_ a value is provided. It would be redundant to mandate that all regexes for optional fields match an empty value. This is how Django works, so this this is the logic we abide by. Sorry, but you'll have to raise this as a bug against swagger-codegen, or whatever is being used to generate the API client.

**Closed by jeremystretch** 2020-02-07 02:50 UTC
Labels: status: gathering feedback
