### ISSUE TITLE
In device view: Interface list ordering is inconsistent

### ISSUE THREAD

**Issue by aleheux-tc** [netbox-community/netbox#4679] opened 2020-05-22 20:04 UTC
### Environment
* Python version: 2.7.16
* NetBox version: 2.7.10

### Steps to Reproduce
1. Add interfaces to a device (`et-0/0/[0-2]`)
2. Add interface et-0/0/2.0

It will show et-0/0/2.0 above et-0/0/2 in the list (This is undesirable)
Order:
et-0/0/0
et-0/0/1
et-0/0/2.0
et-0/0/2
[...]

3. Add interface et-0/0/2.1

It will now show the interfaces in the correct order:

et-0/0/0
et-0/0/1
et-0/0/2
et-0/0/2.0
et-0/0/2.1
[...]

### Expected Behavior

Show interfaces in the correct order:
et-0/0/0
et-0/0/1
et-0/0/2
et-0/0/2.0
[...]
And et-0/0/2.1 after et-0/0/2.0 when added.

### Observed Behavior

Incorrect order:

et-0/0/0
et-0/0/1
et-0/0/2.0
et-0/0/2
![Uploading IMG_7911.jpg…]()

[...]
![IMG_7910](https://user-images.githubusercontent.com/44006214/82705458-f85b5d80-9c77-11ea-8ee9-bbac4226e038.jpg)

**Comment by jeremystretch** [comment] 2020-05-22 20:27
Duplicate of #4336. Please upgrade to a more recent release.

**Closed by jeremystretch** 2020-05-22 20:27 UTC
