### ISSUE TITLE
Cable not tracing when creating frontports after connecting rearport

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#10237] opened 2022-09-01 14:38 UTC
### NetBox version

v3.3.1

### Python version

3.10

### Steps to Reproduce

1. Create a device and add a rearport
3. Connect the rearport to e.g. another rearport
4. add frontports to the rearports
5. create everything needed to trace through the rearport of 1. (if -> fp -> rp (from 1.) -> rp -> fp -> if)
6. trace the route
7. click on a rearport in the trace view

### Expected Behavior

Complete cable paths should be shown.

### Observed Behavior

One Incomplete Path in Related Paths that won't trace the whole route.

**Comment by jeremystretch** [comment] 2022-09-01 14:53
I'm afraid this isn't enough detail to reproduce. Please specify exactly what you're doing at each step along the way, so that someone else can attempt to reproduce the reported issue.

**Comment by PaulR282** [comment] 2022-09-02 06:17
So the key is to create the frontports after the rearport is connected. If you then go in the rearport and click on the trace button next to the cable at the "Connection" field, one trace is incomplete.

**Comment by DeemGit** [comment] 2022-09-02 08:55
@jeremystretch 

I recorded a video demonstrating @PaulR282 explanation.
[https://youtu.be/4DUA-YFW_Ow](https://youtu.be/4DUA-YFW_Ow)
 
 So, in short: Create 2 patch panels, connect 2 rear ports. Create 2 devices (ex routers). connect 1 interface to 2 front ports in patch panel for both of them. click "trace" and get an exception.

**Comment by PaulR282** [comment] 2022-09-02 09:12
@DeemGit 

Thanks for the video, but this is not what I meant. As I said, the problem occurs when creating a rearport, connecting that rearport, and then creating the frontports and connecting them.

**Comment by DeemGit** [comment] 2022-09-02 11:46
@PaulR282  
That was shown in the first part of video. Anyway some kind of a bug exists.

**Comment by jeremystretch** [comment] 2022-09-02 16:01
@DeemGit thanks for taking the time to record the video. The bug you encountered has been captured under #10217 and is resolved in the upcoming release.

@PaulR282 I'm afraid I'm still not able to reproduce the reported behavior under the current `develop` branch. It's possible that it may have already been resolved under another bug.

**Comment by PaulR282** [comment] 2022-09-05 06:27
@jeremystretch I tried to reproduce the problem in the latest version, but it looks like it has been resolved. However, there is now another problem but I'm going to make a new BR for this one.

**Comment by PaulR282** [comment] 2022-09-06 09:41
I need to correct myself, the issue has not been resolved. I reproduced it in the latest v3.3.2-dev version. Here are detailed steps to reproduce:

1. Create 2 Switche (or some sort of device with interfaces)
2. Create 2 devices that will function as patchpanel (these need to be empty, so no rear or frontports from the device type)
3. Create a rearport in both patchpanel
4. Connect the rearports
5. Create at least 1 frontport in both patchpanel
6. Connect each frontport to a switch so you get the following path:
Interface Switch 1 -> Frontport Patchpanel 1 -> RP Patchpanel 1 -> RP Patchpanel 2 -> FP Patchpanel 2 -> Interface Switch 2
7. Go to one of the rearports of the patchpanel
8. Click on "Trace" next to the cable ID
2 complete traces should be shown (from one interface to another and vise versa) but 1 trace is incomplete. You can also see it in one of the connected interfaces, where the Connection Path Status shows "Not Reachable"

**Comment by jeremystretch** [comment] 2022-09-06 12:27
> I reproduced it in the latest v3.3.2-dev version.

This could indicate any point along the development of v3.3.2. Please try the final v3.3.2 release now that it's available.

**Comment by PaulR282** [comment] 2022-09-06 13:54
> > I reproduced it in the latest v3.3.2-dev version.
> 
> This could indicate any point along the development of v3.3.2. Please try the final v3.3.2 release now that it's available.

It's the same in v3.3.2

**Comment by jdp-minpcdk** [comment] 2022-09-15 09:33
I in v3.3.2 Cable not tracing,  I create a circuits termination connected to front port(patch panel), but working when I connect to a Interface port.

**Comment by DanSheps** [comment] 2022-09-15 17:20
You need a cable "endpoint" (interface, circuit, etc) to do a trace.

**Comment by Wexter** [comment] 2022-10-05 17:28
Probably I have same issue with circuits and provider networks, in 3.3.4 it's not working as in 3.2.9
Working in 3.2.9 https://youtu.be/LhyJyduvS8w
Not working in 3.3.4  
Both instances running in separate docker-compose containers. Have same problem on production instance, which was upgraded from 3.2.9 to 3.3.4.
Existing cables tracing works fine, but it's becoming broken if I change anything in circuit/cable/network

**Comment by jeremystretch** [comment] 2022-11-17 20:48
I'm not able to reproduce this on v3.3.8 using the steps [provided above](https://github.com/netbox-community/netbox/issues/10237#issuecomment-1237915215): Both end-to-end paths are created successfully as expected.

![Screenshot 2022-11-17 at 15-46-45 Cable Trace for Rear Port RP1 NetBox](https://user-images.githubusercontent.com/13487278/202556351-524eeee0-c777-41dd-b4c7-ed7cd496b88f.png)

I'm going to close this issue as it has likely been resolved by some other change. If anyone is able to reproduce the error on the current release, please open a **new** issue with complete reproduction steps.

**Closed by jeremystretch** 2022-11-17 20:48 UTC
Labels: type: bug, status: revisions needed
