### ISSUE TITLE
Unable to tag vlan to multisite cluster

### ISSUE THREAD

**Issue by nomad-cyanide** [netbox-community/netbox#8883] opened 2022-03-16 11:24 UTC
### NetBox version

v.3.1.9

### Python version

3.8

### Steps to Reproduce

1. Create 2 sites (test-site1 and test-site2)
2. Create 1 Site-group (test-site-group) containing test-site1 and test-site2
3. Create 1 vlan-group (test-vlan-group1) with scope site-group = test-site-group.
4. Create 1 vlan (test-vlan1) in test-vlan-group1.
5. Create 2 devices (test-device1 and test-device2) One device for each site (e.g. test-device belongs to test-site1)
6. Create 1 Cluster (test-cluster1) and add the 2 test-devices to it. Since each device belongs to different sites, you cannot set a site for the cluster, so leave that as "none"
7. create a Virtual Machine (test-vm-1) in test-cluster1 and add an interface to that vm (mgmt)
8. Edit the mgmt interface on test-vm-1, set  802.1Q Mode to "Access" and select the vlan-group "test-vlan-group1". 
9. This is where I would expect to be able to select test-vlan-1 from vlan-group test-vlan-group1.
Only if I remove one of the devices from the cluster and set a site (e.g. test-site1) on the cluster, am I able to select a vlan from the vlan-group test-vlan-group1

The reason that I need to be able to do this, is because clusters are multisite, connected with L2 vlans. 
We could define a site-group covering both sites, but then we would have to set all devices to that (multi)site, which in turn does show the correct information about where the devices are physically placed.

### Expected Behavior

I would expect to be able to select the vlan from the vlan-group I select from the interface GUI.

It looks like this might only be a GUI problem, as I can still tag vlans using the API.

### Observed Behavior

I am not able to select a vlan in GUI.

**Comment by DanSheps** [comment] 2022-03-18 14:25
This would be more appropriate as a feature request, and there is already a FR for this specific issue:  #6429

**Comment by DanSheps** [comment] 2022-03-18 14:25
Duplicate of #6429

**Closed** 2022-03-18 14:25 UTC
Labels: type: bug

**Comment by nomad-cyanide** [comment] 2022-03-21 08:18
then how come it seems to work, when tagging interfaces via the API?
