### ISSUE TITLE
Configure Table on Device Interface does not work

### ISSUE THREAD

**Issue by BirknerAlex** [netbox-community/netbox#7242] opened 2021-09-10 11:12 UTC
### NetBox version

v3.0.2

### Python version

3.9

### Steps to Reproduce

1. Go to a device detail page
2. Click on interfaces
3. Click on "Configure Table"
4. Try to add Columns from the left to the right side

Example URL:/dcim/devices/DEVICEID/interfaces/

Nothing happens.

### Expected Behavior

Able to add or remove colums from the table on device interfaces.

### Observed Behavior

I'm not able to change columns on the device interfaces table.

**Comment by jeremystretch** [comment] 2021-09-10 12:49
I'm not able to reproduce this on v3.0.2. The table is updated as expected. Maybe you need to force a refresh in your browser?

**Comment by BirknerAlex** [comment] 2021-09-10 12:55
I cleared the browser cache, cleared Cloudflare and Nginx cache, definitely broken on our side. No javascript errors in the browser console. My colleagues confirmed me it's not working on their side to, only this table is affected, all others working fine.

Tried to add the VLAN columns to the table:
![Bildschirmfoto 2021-09-10 um 14 52 42](https://user-images.githubusercontent.com/779751/132856306-5f74325e-cc73-4bbf-b1e5-8f2b10289ea4.png)

**Comment by jeremystretch** [comment] 2021-09-10 13:00
Does it work for you on the [demo instance](https://demo.netbox.dev/dcim/devices/14/interfaces/)?

**Comment by BirknerAlex** [comment] 2021-09-10 13:15
Yap on the demo page does it work for me, very strange, I will try to debug this on our side and maybe track down the issue.

**Comment by jeremystretch** [comment] 2021-09-10 13:21
Try running `manage.py collectstatic` on the server. Maybe static files weren't successfully copied during the upgrade.

**Comment by ziggekatten** [comment] 2021-09-10 16:28
> Try running `manage.py collectstatic` on the server. Maybe static files weren't successfully copied during the upgrade.

This! Lot of strange things if including above is not done. This was the root cause of my issues with adding columns. 

Another fun thing, if you clone a setup using same sectet key and stuff, trying to browse the two cloned instances at different versions with the same browser is an interesting user experience when going into cookie and caching hell....,

**Comment by jeremystretch** [comment] 2021-09-13 13:48
Closing this for now as it doesn't seem to be an actionable bug, but please feel free to ask for it to be re-opened if you discover something.

**Closed by jeremystretch** 2021-09-13 13:48 UTC
Labels: type: bug, status: revisions needed
