### ISSUE TITLE
Support secrets fields in virtual machines

### ISSUE THREAD

**Issue by takmiz** [netbox-community/netbox#5349] opened 2020-11-16 14:54 UTC
### Environment
* Python version: 3.6
* NetBox version: 2.9.9

### Proposed Functionality
Support secrets fields in virtual machines.

### Use Case
A secrete fields in virtual machines can be stored virtual machin's credentials.
Now virtual machin's credentials may be stored in custom fields. But virtual machin's credentials is revealed by anyone..

### Database Changes
I don't believe there would be a requirement for any database changes.

### External Dependencies
None.

**Comment by jeremystretch** [comment] 2020-11-16 15:18
Duplicate of #1503

**Closed by jeremystretch** 2020-11-16 15:18 UTC
