### ISSUE TITLE
Adding components to device type appears broken in 2.11.8

### ISSUE THREAD

**Issue by mabroze** [netbox-community/netbox#6724] opened 2021-07-08 13:38 UTC
### NetBox version

v2.11.8

### Python version

3.7

### Steps to Reproduce

1. Open a Device Type.
2. Click Add Components, then click any of the component types.
3. The issue occurs on the page that opens next.

### Expected Behavior

A form for entering the relevant attributes for the chosen component type is shown.

### Observed Behavior

A mostly empty form is shown. No fields and dropdowns for entering attribute values. The only controls are buttons for Create, Create and Add More, and Cancel.

Additional information:
- The issue appears to affect all combinations of device type and component type. Basically any page matching `/dcim/*-templates/add/`.
- The issue does not affect adding components to devices, only to device _types_.
- The issue appeared after upgrading from 2.10.3 to 2.11.8. Verified on two independent NetBox installations. Detailed version information: Python 3.7.3, PostgreSQL 11.12, Debian 11.12-0, Redis server 5.0.3, NetBox 2.11.8.
- Disabling caching did not resolve the issue.

Apologies if this has been reported elsewhere; I was unable to find any posts regarding this issue.

**Comment by mabroze** [comment] 2021-07-08 14:00
[Posted](https://groups.google.com/g/netbox-discuss/c/g6LTJplCB-I) to the NetBox group re this issue.

**Comment by candlerb** [comment] 2021-07-08 14:00
Duplicate of #6714 and fixed in Netbox 2.11.9

**Closed** 2021-07-08 14:19 UTC
Labels: type: bug
