### ISSUE TITLE
VLAN Group and VLAN cannot be assigned to an IPAM PREFIXE when Site is selected.

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#9284] opened 2022-05-03 10:33 UTC
### NetBox version

v3.2.1

### Python version

3.10

### Steps to Reproduce

- Create or change an IPAM prefix
- Choose a region
- Choose a site

### Expected Behavior

Selection of VLAN Group and VLAN

### Observed Behavior

Unable to select VLAN Group and VLAN. Except region and site will be removed.

Apparently no VLAN Group or VLAN can be selected because they have no site attribute?

If I remove the Site/VLAN Assignment Attribute Region and Site, the VLAN group and VLAN Attribute can be filled.

**Comment by jeremystretch** [comment] 2022-05-03 12:08
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by DanSheps** [comment] 2022-05-03 13:47
Duplicate of #9279

**Closed by DanSheps** 2022-05-03 13:47 UTC
Labels: type: bug, status: duplicate

**Comment by LHBL2003** [comment] 2022-05-03 13:53
I hope the minimalistic steps help to recreate the problem:

**Add Sites**
`
name,slug,status
TestSites,testsites,active
`

**Add VLAN Group:**

`
name,slug
VG1, vg1
`

**Add VLAN**
`
vid,name,status
4000,Test4000,active
`

**Add Prefixes**
`
prefix,status
192.168.0.0/24,active
`

**Edit Prefix**
Site/VLAN Assignment --> Site --> Select "TestSites"

**Failure:**
I can NOT select a VLAN group or VLAN

Site/VLAN Assignment --> Site --> remove selection
I can select a VLAN group or VLAN

Can it be that one may only document site or VLAN? 

"Site/VLAN  Assignment" ALIAS 
"Site **or** VLAN Assignment"

If so, then I misunderstood.
I wasn't aware that only one or the other could be used.
Because if I configure the VLAN first and then the site. Then I can save it too.
