### ISSUE TITLE
Export Cables issue

### ISSUE THREAD

**Issue by LarsSche** [netbox-community/netbox#5112] opened 2020-09-09 10:25 UTC
### Environment
* Python version: 3.8
* NetBox version: 2.9.3

### Steps to Reproduce
1. Go to Devices --> cables
2.  Click on export
3. Look in the csv file

### Expected Behavior
I expected to see in the columns "termination_a_type", "termination_a_id", "termination_b_type", "termination_b_id"
the device name and assigned ports.

### Observed Behavior
I just see:
dcim.rearport,266,dcim.rearport,217
No device or port assignments.

For example:
termination_a_type,termination_a_id,termination_b_type,termination_b_id,type,status,label,color,length,length_unit
dcim.rearport,266,dcim.rearport,217,Multimode   Fiber (OM2),Connected,,ff9800,,
dcim.rearport,268,dcim.rearport,269,Multimode   Fiber (OM2),Connected,,ff9800,,

**Comment by jeremystretch** [comment] 2020-09-09 13:40
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Closed by jeremystretch** 2020-09-09 13:40 UTC
