### ISSUE TITLE
Drag & Drop Devices from Rack to different U and Rack

### ISSUE THREAD

**Issue by rafac92** [netbox-community/netbox#4251] opened 2020-02-24 14:51 UTC
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.7

### Proposed Functionality
In the view "Rack Elevations" it would be nice to have the possibility to move Devices to other positions in the same Rack or to a different Rack via DRAG & DROP. 

### Use Case
We have Racks which were only used for preparating the Devices so we will mount the HW in these Racks and after having deployed/modified the Devices we unmount from the Rack and put it into other Racks. 

### Database Changes
-

### External Dependencies
-

**Comment by jeremystretch** [comment] 2020-02-24 15:03
Duplicate of #124. Not something we can implement given the current UI and our limited development resources.

**Closed by jeremystretch** 2020-02-24 15:03 UTC

**Comment by rafac92** [comment] 2020-02-24 15:38
hi @jeremystretch thanks for the reply. I understand the lack of limited development resources.
