### ISSUE TITLE
Clicking to the left of a field acts as if the field was clicked

### ISSUE THREAD

**Issue by Chiniquy** [netbox-community/netbox#16302] opened 2024-05-27 08:08 UTC
### NetBox Version

v4.0.3

### Python Version

3.10

### Steps to Reproduce

This seems to be the case for all objects in Netbox, both in the Create New screen and in the Edit screen. I will use an IP address for this example. 

1. Click on "Add new IP address"
2. Left click to the left of the name of any field (see the red X in the image)
![image](https://github.com/netbox-community/netbox/assets/10709382/c18f366a-457a-4eff-989f-d634a6c78d9a)
3. The field will now act as if it was clicked, even though it was not clicked

There seems to be a limit to how far left you can go before this stops occuring. 

### Expected Behavior

When clicking outside of the field, the field should not act as if it was clicked. 
Clicking on the red X in the image should do nothing (and close any open drop-downs). 

### Observed Behavior

The field acts as if it was clicked, and the drop down opens up.

**Comment by DanSheps** [comment] 2024-05-27 19:05
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Closed by DanSheps** 2024-05-27 19:05 UTC

**Comment by Chiniquy** [comment] 2024-05-28 08:48
Maybe I am missing something, but I cannot see how this could possibly be the intended behavior?

**Comment by Chiniquy** [comment] 2024-06-03 07:18
I believe this issue was closed in error. Any chance to get a second set of eyes on it?
