### ISSUE TITLE
Context data merges instead of overwritting with dicts

### ISSUE THREAD

**Issue by tehungtseng1** [netbox-community/netbox#15880] opened 2024-04-29 09:36 UTC
### Deployment Type

Self-hosted

### NetBox Version

v3.7.2

### Python Version

3.11

### Steps to Reproduce

Create two config contexts with one lower weight and one heigher weight.
Use dict as your data

**lower_weight:**
```
{
    "the_dict_to_check": {
        "low_weight_key": "low_weight_data"
    },
    "the_list_to_check": [
        "lower_weight_data"
    ],
    "the_variable_to_check": "lower_weight_data"
}
```
**higher_weight:**
```
{
    "the_dict_to_check": {
        "higher_weight_key": "higher_weight_data"
    },
    "the_list_to_check": [
        "higher_weight_data"
    ],
    "the_variable_to_check": "higher_weight_data"
}
```

### Expected Behavior

https://docs.netbox.dev/en/stable/features/context-data/

https://github.com/netbox-community/netbox/issues/5698#issuecomment-773519600

Should overwrite the variable instead of merge. This works as intended in a list

```
{
    "the_dict_to_check": {
        "higher_weight_key": "higher_weight_data",
    },
    "the_list_to_check": [
        "higher_weight_data"
    ],
    "the_variable_to_check": "higher_weight_data"
}
```

### Observed Behavior

Seems to be this line; 
https://github.com/netbox-community/netbox/blob/v3.7.2/netbox/utilities/utils.py#L275
https://github.com/netbox-community/netbox/blob/master/netbox/utilities/utils.py#L276

```
{
    "the_dict_to_check": {
        "higher_weight_key": "higher_weight_data",
        "low_weight_key": "low_weight_data"
    },
    "the_list_to_check": [
        "higher_weight_data"
    ],
    "the_variable_to_check": "higher_weight_data"
}

```

**Comment by jeremystretch** [comment] 2024-04-29 13:37
This is working as intended. There's even an example in the previous issue to which you linked confirming that this is expected behavior.

Individual keys mapping to discrete values (strings, numbers, lists) are overwritten whereas dictionaries are merged. This is true at all levels of the data hierarchy. If you want to overwrite a lower-weight item, you need to reuse the same key when defining a higher-weight item.

**Closed by jeremystretch** 2024-04-29 13:37 UTC
Labels: type: bug, status: needs triage
