### ISSUE TITLE
Cannot add/change position on device settings

### ISSUE THREAD

**Issue by craftdax** [netbox-community/netbox#3539] opened 2019-09-25 12:24 UTC
### Environment
* Python version:  v3.6.8
* NetBox version:  v2.6.4

### Steps to Reproduce
1. Add device to rack, leave it unracked
2. Open device
3. Press on position for it to search the available positions

When I try to add a device without pre-selection the rack position, change a device position or rack an unracked device, I cannot find any available positions in the device. This is with all of the positions being available and all the other information filled out in the form.

**Comment by jeremystretch** [comment] 2019-09-25 13:12
Duplicate of #3521

**Closed by jeremystretch** 2019-09-25 13:12 UTC
