### ISSUE TITLE
User has no config

### ISSUE THREAD

**Issue by exiz01** [netbox-community/netbox#5077] opened 2020-08-31 18:23 UTC
## Environment
* Python version: 3.6.9
* NetBox version: 2.9.2

### Steps to Reproduce
1. Set LDAP authentication
2. when login with a new LDAP user this error is [displayed](https://i.imgur.com/F35zomR.png)
I was able to trace the error to this function inside netbox/users/models.py
`def create_userconfig(instance, created, **kwargs):`
`    if created:`
`        UserConfig(user=instance).save()`

### Expected Behavior
User config inside users_userconfig table should be created.

### Observed Behavior
[Error MSG](https://i.imgur.com/F35zomR.png)

**Comment by jeremystretch** [comment] 2020-08-31 18:43
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v2.9.2. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by gaussk32** [comment] 2020-09-02 16:47
same problem here 

    Python version: 3.6.9
    NetBox version: 2.9.2

**Comment by jeremystretch** [comment] 2020-09-09 14:14
Closing as no further detail has been provided as requested.

**Closed by jeremystretch** 2020-09-09 14:14 UTC
Labels: status: revisions needed
