### ISSUE TITLE
Cable color no longer displaying on device page

### ISSUE THREAD

**Issue by AllenRDCo** [netbox-community/netbox#5840] opened 2021-02-19 00:05 UTC
The cable colors used to show on the device pages until recently. We just upgraded from 2.9.7 to 2.10.4 and I noticed the cable color is no longer shown when looking at the interface tab for a device. I found this previous feature request that I assume is what added it originally: https://github.com/netbox-community/netbox/issues/3457

I see another feature request that is similar but apparently more involved: https://github.com/netbox-community/netbox/issues/3682

Can we get the cable colors added back to the interface list of the devices as it was before? I'm not sure why it was dropped when you switched to the tab layout for the device pages, but now to see what color a cable should be you have to go into each individual cable. And the Cables page doesn't show the color by default, but I was able to use the configure option to have it show them on there. I cannot find that option though when configuring the display of the interfaces tab for devices.

Eyeroll...

### Environment
* Python version: 3.7.3
* NetBox version: 2.10.4

### Steps to Reproduce
1. Log into Netbox
2. Go to a device page (ex server-1)
3. Go to the Interfaces tab

### Expected Behavior
Be able to see the color block for cables connected to the interfaces that shows what color the cable is.

### Observed Behavior
Don't see the color block for the cables connected to the interfaces so I have to click on each individual cable to view the cable color.

**Comment by DanSheps** [comment] 2021-02-22 18:36
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by jeremystretch** [comment] 2021-03-10 22:25
This would be a feature request, not a bug, since the removal of this information in the prior release was intentional.

I've marked this as `needs owner` if someone would like to work on it. Implementing this would entail the introduction of a new configurable table column to show the cable color for _all_ cable termination components (not just interfaces).

**Closed** 2021-03-31 19:56 UTC
Labels: status: accepted, type: feature
