### ISSUE TITLE
Error when creating bulk ip addresses (/ipam/ip-addresses/bulk-add/ 'str' object has no attribute '_meta')

### ISSUE THREAD

**Issue by Soeren-FT** [netbox-community/netbox#4414] opened 2020-03-27 09:08 UTC
# Environment
* Python version:  3.6.9
* Django Version: 2.2.10
* NetBox version:   2.7.10

### Steps to Reproduce
1. Moving to "IPAM\IP Addresses"
2. Click Button "Add"
3. Click Tab "Bulk Create"

### Expected Behavior
- Show formular for create bulk ip addresses

### Observed Behavior
Server Error
There was a problem with your request. Please contact an administrator.
The complete exception is provided below:

Internal Server Error: /ipam/ip-addresses/bulk-add/
AttributeError at /ipam/ip-addresses/bulk-add/ 'str' object has no attribute '_meta'

**Comment by tysonvabaza** [comment] 2020-03-27 11:02
Excact Same Issue with NetBox v2.7.10 / Python 3.6.9

**Comment by DanSheps** [comment] 2020-03-27 15:21
This looks like it might be fixed in develop already.

**Comment by DanSheps** [comment] 2020-03-27 15:23
Duplicate of #4365

**Closed by DanSheps** 2020-03-27 15:23 UTC
Labels: status: duplicate, type: bug
