### ISSUE TITLE
Changed behavior for the /api/ request

### ISSUE THREAD

**Issue by VitMain** [netbox-community/netbox#16295] opened 2024-05-24 22:45 UTC
### Deployment Type

Self-hosted

### NetBox Version

4.0.3

### Python Version

3.10

### Steps to Reproduce

configuration.py
LOGIN_REQUIRED = True

In version 3.7.8, unauthenticated request to the API return 200 and response with endpoints:
Request:
GET /api/ HTTP/1.1

Response:
{
    "circuits": "https://somehost/api/circuits/",
    "core": "https://somehost/api/core/",
    "dcim": "https://somehost/api/dcim/",
    "extras": "https://somehost/api/extras/",
    "ipam": "https://somehost/api/ipam/",
    "plugins": "https://somehost/api/plugins/",
    "status": "https://somehost/api/status/",
    "tenancy": "https://somehost/api/tenancy/",
    "users": "https://somehost/api/users/",
    "virtualization": "https://somehost/api/virtualization/",
    "vpn": "https://somehost/api/vpn/",
    "wireless": "https://somehost/api/wireless/"
}

In version 4.0.3, unauthenticated request to the API return 403 and 
Request:
GET /api/ HTTP/1.1

Response:
{
    "detail": "Authentication credentials were not provided."
}

Changing LOGIN_REQUIRED = False returns old behavior

Not sure that a bug, may be right now it's a correct behavior.

### Expected Behavior

Expected response with the endpoints (?)

### Observed Behavior

Please check reproduce.

**Comment by arthanson** [comment] 2024-05-29 15:38
We think this was probably caused by a large change to the underlying Django REST framework.  This is actually more correct behavior, but worth calling out in the release notes.  I've opened a doc issue to track this #16352. Thanks for bringing this to our attention, closing out this issue in favor of the doc update.

**Closed by arthanson** 2024-05-29 15:38 UTC
Labels: type: bug
