### ISSUE TITLE
'str' object has no attribute 'delete'  Uploading Front or rear picture in device types

### ISSUE THREAD

**Issue by mikehak74** [netbox-community/netbox#13898] opened 2023-09-26 08:19 UTC
### NetBox version

v3.6.2

### Python version

3.10

### Steps to Reproduce

Just add a picture in front or rear in the device types and after you click on save you got the following error.

### Expected Behavior

Normal upload of picture.

### Observed Behavior

<class 'AttributeError'>

'str' object has no attribute 'delete'

Python version: 3.10.12
NetBox version: 3.6.2
Plugins: 
  netbox_attachments: 3.0.1
  netbox_data_flows: 0.7.4
  netbox_topology_views: 3.7.0

**Comment by abhi1693** [comment] 2023-09-26 08:24
Duplicate of #13845

**Closed** 2023-09-26 08:25 UTC
Labels: status: duplicate
