### ISSUE TITLE
Support for VPN Tunnels

### ISSUE THREAD

**Issue by larsuhartmann** [netbox-community/netbox#5960] opened 2021-03-11 08:26 UTC
### NetBox version

v2.10.6

### Feature type

New functionality

### Proposed functionality

Implement a solution that represents point to point and point to multipoint vpn tunnels

### Use case

as SD-WAN Deployments become more and more common (and are replacing the classical mpls WAN which we could model with Circuits) it would be nice to have a way to describe VPN Tunnels in Netbox

**Comment by jeremystretch** [comment] 2021-03-11 14:05
This looks like a duplicate of #5845, and would need _much_ more detail about the proposed implementation to be actionable.

**Closed by jeremystretch** 2021-03-11 14:05 UTC
Labels: type: feature
