### ISSUE TITLE
Custom field with trailing white space unable to import

### ISSUE THREAD

**Issue by ponchofiesta** [netbox-community/netbox#15082] opened 2024-02-08 07:56 UTC
### Deployment Type

Self-hosted

### NetBox Version

v3.6.9

### Python Version

3.8

### Steps to Reproduce

1. Create custom field for Virtual machine with multi selection
2. One value has a trailing whitespace, e.g. "bla "
3. Try to import this value via CSV:
  ```csv
  id,cf_CustField
  123,bla
  ```
  This won't work too:
  ```csv
  id,cf_CustField
  123,"bla "
  ```
  But this works:
  ```csv
  id,cf_CustField
  123,"bla ,anotherBla"
  ```

### Expected Behavior

It will get imported

Suggestion: By default remove any leading and trailing white spaces form field values.

### Observed Behavior

Error: "Record 1 cf_CustField: Select a valid choice. bla is not one of the available choices."

**Comment by jeremystretch** [comment] 2024-02-08 14:05
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.7.1. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by sleepinggenius2** [comment] 2024-02-08 16:31
I would be extremely careful about automatically stripping leading and trailing white space in imports. There is already a pretty frustrating bug when importing tab-separated data where the input gets trimmed and it breaks on the last row if it has legitimate trailing tabs for empty columns. I think the expectation should be that data entered during a bulk import has already been adequately cleaned beforehand.

**Comment by ponchofiesta** [comment] 2024-02-08 17:27
I'm not sure if the problem was understand correctly. Wgen defining the custom field, one of the possible values has a trailung blank. And it is not possbile to import this value using CSV import. It looks like Netbox already drops the blank on an import and therefore the importvalue doesn't match the custom field value.

**Comment by ponchofiesta** [comment] 2024-02-09 07:54
I analyzed the source code a little and I think I found the cause. The csv reader doesn't drop the blank values but Netbox does:
https://github.com/netbox-community/netbox/blob/develop/netbox/utilities/forms/utils.py#L237

And if I understand the code correctly, the CustomFieldChoices are not striped.

**Comment by sleepinggenius2** [comment] 2024-02-09 16:28
> Suggestion: By default remove any leading and trailing white spaces form field values.

That made it sound like you were saying that the fields should be stripped in the CSV import, not on the custom field choice value. It sounds though like the CSV fields are being stripped, while the custom field choice values are not. So, is this bug actually for the custom field choice values not being stripped? If so, that was extremely unclear from the initial bug report, but it does make sense to me.

That being said, I also find it kind of surprising and a bit unintuitive from a UX standpoint that a quoted value in the CSV import would still strip white space. I might understand that if the field was just left raw and unquoted, but maybe that nuance of unquoting is handled by the CSV library and the NetBox code is not able to make that distinction.

**Comment by ponchofiesta** [comment] 2024-02-23 08:23
@jeremystretch I verified it with current Netbox version using Docker [v3.7.3-2.8.0].

Steps:
- Created Super user, Dummy Cluster, VM, Custom field
- Custom Field Choice Set with these exact "Extra Choices" (note the " " after "Space"):
  ```
  Space 
  NoSpace
  AnotherOne
  ```
- Create the Custom Field for VMs using the Custom Field Choice Set
- Try to import this data to the VM via CSV. All of these variants will fail:
  Without extra space:
  ```
  id,cf_TestField
  1,Space
  ```
  With extra space after "Space":
  ```
  id,cf_TestField
  1,Space 
  ```
  With extra space and quotes:
  ```
  id,cf_TestField
  1,"Space "
  ```

And this happens because Netbox trims import data fields but not field choice values. I'd say trimming import data is incorrect behavior.

**Comment by Julio-Oliveira-Encora** [comment] 2024-05-17 19:10
Could you please assign it to me?

**Closed** 2024-05-21 13:59 UTC
Labels: type: bug, status: accepted, severity: low
