### ISSUE TITLE
Cable connection in batch

### ISSUE THREAD

**Issue by lmgonzalezl** [netbox-community/netbox#3678] opened 2019-11-07 13:14 UTC
### Environment
* NetBox version:  v2.6.7

### Proposed Functionality
In most cases the connection of the rear ports of a patch panel has a 1:1 relationwith a second panel. It would be interesting to be able to connect all tracer ports in batch.

### Use Case
Batch all the trace ports of two patch panels. This is useful in structured cabling.

Example image

![imagen](https://user-images.githubusercontent.com/51785108/68391825-b7cb4500-0168-11ea-8b9d-7fc10212b01b.png)

### Database Changes
It is not necessary

**Comment by jeremystretch** [comment] 2019-11-07 13:29
This is a good idea, but it needs to be fleshed out. What is the proposed workflow? Let's say I have two panels created with all the appropriate front/rear ports. How do I connect all the rear ports together? What happens if some of the rear ports are already connected, or one panel has more than the other?

**Comment by lmgonzalezl** [comment] 2019-11-07 20:59
**Proposed workflow**
Visually I see it as follows:

I would keep the current format to select the rear ports but with the option to select both side a and side b and add a pop-up window that allows you to choose cable type, length, color, etc ... this would add it in a table.

**Select rear ports on both sides**
![imagen](https://user-images.githubusercontent.com/51785108/68421585-d3514280-019e-11ea-824c-47ea701f448e.png)

**Pop-up window**
![imagen](https://user-images.githubusercontent.com/51785108/68421750-1f9c8280-019f-11ea-8ff1-298042404940.png)

**Table**
![imagen](https://user-images.githubusercontent.com/51785108/68421769-2aefae00-019f-11ea-860a-3cf2761143d4.png)

**What happens if some of the rear ports are already connected, or one panel has more than the other?**

As validation is done this will not be a problem because connected ports already are disabled from the selection.

**Comment by lmgonzalezl** [comment] 2019-11-08 14:12
I see that there is another issue (#[2855](https://github.com/netbox-community/netbox/issues/2855)) where this has been discussed. In any case I add a new option to implement it.

**Comment by jeremystretch** [comment] 2019-11-11 22:10
Marking this as a duplicate of #2855. Please feel free to copy your comment above there.

**Closed by jeremystretch** 2019-11-11 22:10 UTC
Labels: status: revisions needed
