### ISSUE TITLE
Editing Existing Virtual Machine Platform Does not Return Platform list

### ISSUE THREAD

**Issue by Stoicizmgames** [netbox-community/netbox#7268] opened 2021-09-14 16:14 UTC
### NetBox version

v3.0.2

### Python version

3.8

### Steps to Reproduce

1. Click on "Virtualization" tab
2. Click on Virtual Machines
3. Click on existing Virtual machine - Edit- Management - platform dropdown 
 

### Expected Behavior

The **Select Platform** drop down field should return a list of selectable pre-existing platforms but does not.

This was also noted by another user in Issue #7230

### Observed Behavior

The drop down shows no results and is null

**Comment by jeremystretch** [comment] 2021-09-14 20:41
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.0.2. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by Stoicizmgames** [comment] 2021-09-14 20:45
![image](https://user-images.githubusercontent.com/64975116/133331142-e920af8b-dcf9-4853-bc10-db8d900443cc.png)


While in The virtual machine to edit and add the platform
![image](https://user-images.githubusercontent.com/64975116/133331239-78d22998-e707-414b-b8f6-56ca4329ba65.png)

**Comment by jeremystretch** [comment] 2021-09-16 18:16
I'm not able to reproduce this on v3.0.2. Note that any platforms bound to a specific manufacturer will not appear in the list of available options for VM, and that this is expected behavior.

**Comment by jeremystretch** [comment] 2021-09-27 16:01
Closing as there has been no further response.

**Closed by jeremystretch** 2021-09-27 16:01 UTC
Labels: type: bug, status: revisions needed
