### ISSUE TITLE
For a prefix that is marked "utilised" child prefix creation should be blocked

### ISSUE THREAD

**Issue by imdhruva** [netbox-community/netbox#16422] opened 2024-06-06 04:22 UTC
### Deployment Type

NetBox Cloud

### NetBox Version

v3.7.3

### Python Version

3.10

### Steps to Reproduce

1. Create a prefix "10.120.36.0/22" with a specific VRF/Tenant/Site/Region/Role and mark it as "Utilised" (and not marked as pool); status is set to "Active"
2. Create another prefix "10.120.37.0/24" with the same VRF/Tenant/Site/Region/Role

### Expected Behavior

child prefix "10.120.37.0/24" should be blocked from creation.

### Observed Behavior

child prefix is created

**Comment by DanSheps** [comment] 2024-06-06 18:52
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Closed by DanSheps** 2024-06-06 18:52 UTC

**Comment by imdhruva** [comment] 2024-06-06 22:45
@DanSheps Thanks for getting back on this. I was under the assumption that the purpose of IPAM (amongst other things) is to let us allocate child prefixes and stop us from allocating an overlapping prefix and so if `10.120.36.0/22` is already allocated and marked as utilised then any of the overlaps should be invalid.

Can you please explain why is this an intended behaviour instead?

**Comment by jeremystretch** [comment] 2024-06-07 11:45
Address planning happens at many different levels and in many different contexts. An IPAM system which does not permit the user to mark a parent prefix as utilized with respect to higher-scope planning while still allowing more granular allocations within it would be practically useless for most people. Of course, if this doesn't meet your needs, you are free to fork the code and modify it as you see fit.

**Comment by DanSheps** [comment] 2024-06-07 18:50
> Of course, if this doesn't meet your needs, you are free to fork the code and modify it as you see fit.

This may also be possible with a custom validator, not even requiring a fork of the code.
