### ISSUE TITLE
Power port missing from bulk edit of power outlets

### ISSUE THREAD

**Issue by mikewright** [netbox-community/netbox#3327] opened 2019-07-05 03:14 UTC
### Environment
* Python version:  3.5.3
* NetBox version:  2.6.1

### Steps to Reproduce
1. View a device with power outlets and a power port
2. Select at least one power outlet
3. Select the bulk edit button

### Expected Behavior
There should be the ability to assign a power port to the power outlet (this is available when editing a single power outlet)
![expected](https://user-images.githubusercontent.com/44380251/60695704-0b612400-9f26-11e9-8547-a491422135f9.png)

### Observed Behavior
Cannot select power port. Only Feed Leg, description and tags are available.
![observed](https://user-images.githubusercontent.com/44380251/60695701-069c7000-9f26-11e9-9b54-034883867507.png)

**Comment by jeremystretch** [comment] 2019-09-25 14:23
Whoops, failed to flag #3524 as a duplicate of this issue. This was resolved in fe85dc1.

**Closed by jeremystretch** 2019-09-25 14:23 UTC
