### ISSUE TITLE
Data source sync is broken

### ISSUE THREAD

**Issue by rizlas** [netbox-community/netbox#17735] opened 2024-10-11 09:14 UTC
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.3

### Python Version

3.10

### Steps to Reproduce

1. Add a new git data source
2. Add this example repository https://github.com/BarbarossaTM/netbox-scripts.git
3. Try to sync

### Expected Behavior

Sync completed without errors

### Observed Behavior

`UnboundLocalError("local variable '_' referenced before assignment")`

Tested also on demo.netbox.dev and a self hosted instance.

![Screenshot from 2024-10-11 10-59-43](https://github.com/user-attachments/assets/0c13f210-fe13-43ec-8ac0-f77a658505df)

I'm also facing impossibility to schedule scripts, but I'm currently investigating.

**Comment by jeremystretch** [comment] 2024-10-11 11:45
Duplicate of #17713

**Closed by jeremystretch** 2024-10-11 11:45 UTC
Labels: type: bug, status: needs triage
