### ISSUE TITLE
Server Error when deleting no more existing Journal Entry Kind

### ISSUE THREAD

**Issue by advoenkin** [netbox-community/netbox#13849] opened 2023-09-21 14:56 UTC
### NetBox version

v.3.6.2

### Python version

3.10

### Steps to Reproduce

1. Go to random Location in Locations, add Journal Entry with random Kind.
2. Go to configuration.py
3. Setup 
```python
FIELD_CHOICES = {
    'extras.JournalEntry.kind': (
        ('something', 'Something', 'blue'),
    ),
}
```
4. Go again in Location where we was add Journal Entry. 
5. Try to delete Journal Entry with no more existing Kind.

### Expected Behavior

The entry should have been successfully deleted despite the fact that Kind no longer exists.

### Observed Behavior

Server Error 

```
<class 'KeyError'>

'success'

Python version: 3.10.12
NetBox version: 3.6.2
Plugins: None installed
```

**Comment by jeremystretch** [comment] 2023-09-21 18:16
I've updated your example configuration above to be complete.

The root cause here is the removal of the previously valid field choice. When NetBox attempts to generate a serialized copy of the journal entry (for change logging), it cannot map the raw field value to its label. This will affect any model with a configurable choice field, not just journal entries.

There's not a lot we can do in this situation, short of (somehow) preventing administrators from removing choices which have been assigned to objects. The simplest fix would be to use either the raw field value or an empty string in place of the choice label.

**Closed** 2023-09-26 16:06 UTC
Labels: type: bug, status: accepted, severity: low
