### ISSUE TITLE
Component Selector for InventoryItemTemplates does not filter to Target DeviceType

### ISSUE THREAD

**Issue by chadhpaine** [netbox-community/netbox#16236] opened 2024-05-22 03:38 UTC
### Deployment Type

Self-hosted

### NetBox Version

v3.7.8

### Python Version

3.10

### Steps to Reproduce

0. Start with a clean instance (for illustration purposes).
1. Create a Device Type.
2. Add an Interface Template to the Device Type from Step 1.
3. Create another Device Type.
4. Add an Interface Template to the Device Type from step 3.
4a. For added effect, use the same name for this template as for the template from Step 2.
5. Add an Inventory Item Template to one Device Type or the other.
5a. Attempt to associate the Inventory Item Template to the Interface from the target device-type.
5b. Observe that two Inventory Item Templates appear in the list.
5bi. If Step 4a is observed, observe that both items in the list have the same name, but no other distinguishing features.

### Expected Behavior

The Component Selector within the Inventory Item Template Create / Edit menus shows only components-templates associated with the target device.

### Observed Behavior

The Component Selector within the Inventory Item Template Create / Edit menus shows component-templates from what appears to be every device-type registered to the instance.

![image](https://github.com/netbox-community/netbox/assets/71343685/d5c83686-efc6-44c9-ab40-4eff17591140)

### Additional Information

Follows feature-availability introduced by #15759.

**Comment by chadhpaine** [comment] 2024-05-22 03:59
Does not reproduce at demo.netbox.dev (Netbox 4), but it would still be great if we could get a backport-fix for Netbox 3. NB4:
![image](https://github.com/netbox-community/netbox/assets/71343685/c57b1d6c-33ef-495f-92df-9c84ac87fb73)

**Comment by jeffgdotorg** [comment] 2024-05-22 22:01
At the moment, the NetBox developer team's size and capacity precludes maintaining multiple concurrent release trains. We hope this will change in the future, but for now, back-porting fixes to previous release trains is not something we can do.

Thank you for confirming that the problem is fixed in the 4.0 train!

**Closed by jeffgdotorg** 2024-05-22 22:01 UTC
Labels: type: bug, status: needs triage
