### ISSUE TITLE
Cannot filter sites by physical_address

### ISSUE THREAD

**Issue by apm6** [netbox-community/netbox#13790] opened 2023-09-17 04:20 UTC
### NetBox version

3.1.5

### Python version

3.10

### Steps to Reproduce

'/dcim/sites?physical_address=test'

### Expected Behavior

I would expect this filter to work since physical_address is a field in the site object.

### Observed Behavior

The physical_address filter does not work and the api returns all sites. Using 'address' as the filter does not work either.

**Comment by abhi1693** [comment] 2023-09-17 05:24
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

I do not think this is a bug because even on the latest version (3.6.1), I do not see any filter on the site for physical address. You should rather raise this as a feature request. Moreover, I'd suggest to upgrade to the latest version if possible as the FR will be added for 3.6 if accepted.

**Closed** 2023-09-18 12:16 UTC
Labels: type: bug
