### ISSUE TITLE
Wrong minimum PostgreSQL Version?

### ISSUE THREAD

**Issue by rmuehl** [netbox-community/netbox#4685] opened 2020-05-25 08:08 UTC
### Environment
* Python version: 3.6
* NetBox version: 2.8.3
* OS: RHEL7
* PostgreSQL 9.4.24

### Steps to Reproduce
Install Docs says minimum version of postgresql is 9.4.
But when I try to add Users or Groups to a secret role, I get a server error (see below).

It seams, that "ON CONFLICT" is introduced in postgres 9.5.

server error:
> <class 'django.db.utils.ProgrammingError'>
syntax error at or near "ON"
LINE 1: ...ups" ("secretrole_id", "group_id") VALUES (12, 1) ON CONFLIC...

pg_log:
>ERROR:  syntax error at or near "ON" at character 85
STATEMENT:  INSERT INTO "secrets_secretrole_users" ("secretrole_id", "user_id") VALUES (11, 18) ON CONFLICT DO NOTHING

**Comment by DanSheps** [comment] 2020-05-25 15:15
Duplicate of #4645

**Closed by DanSheps** 2020-05-25 15:15 UTC
