### ISSUE TITLE
Deleting module can break cable edit functionality

### ISSUE THREAD

**Issue by wz4** [netbox-community/netbox#13443] opened 2023-08-11 03:13 UTC
### NetBox version

3.5.7

### Python version

3.9

### Steps to Reproduce

1. Add module with ports to a device
2. Add cable and terminate at least one end to a port on the module
3. Delete the module
4. Try to edit the cable
5. Server error is produced

### Expected Behavior

A module should not be allowed to be deleted if it has ports that are terminated to one end of a cable.

### Observed Behavior

Error generated when trying to edit the cable.

<class 'AttributeError'>

'str' object has no attribute 'label'

**Comment by jeremystretch** [comment] 2023-08-11 11:17
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by DanSheps** [comment] 2023-08-11 16:03
Duplicate of #11460

Please use the search in the future

**Comment by DanSheps** [comment] 2023-08-11 16:03
Duplicate of #11460

**Closed** 2023-08-11 16:04 UTC
Labels: type: bug, status: duplicate
