### ISSUE TITLE
object name not displayed for user notification via notification group

### ISSUE THREAD

**Issue by kuhball** [netbox-community/netbox#17139] opened 2024-08-13 09:38 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.1.0-beta1

### Python Version

3.12

### Steps to Reproduce

1. Create a notification group and event rule
2. Trigger notification
3. Look at user notifications

Reproducible within the beta-demo instance.
<img width="824" alt="Screenshot 2024-08-13 at 11 37 16" src="https://github.com/user-attachments/assets/05661522-50eb-43c6-9976-307624fb0481">

### Expected Behavior

Displayed notification contains an object name with a clickable link.

### Observed Behavior

Empty `<a>` anchor is inserted into html with the correct link. 
![Bild](https://github.com/user-attachments/assets/02aaea24-eedc-41e0-acf0-b131ed68ae89)

After clicking the link everything is correctly displayed.

**Comment by arthanson** [comment] 2024-08-13 10:41
Dupe of #17097

**Closed by arthanson** 2024-08-13 10:41 UTC
Labels: type: bug, status: needs triage
