### ISSUE TITLE
Unable to import devices, get an error "Device has no device_type".

### ISSUE THREAD

**Issue by ziggekatten** [netbox-community/netbox#3618] opened 2019-10-16 20:09 UTC
### Environment
* Python version: 3.7.4  
* NetBox version: v2.6.6 

### Steps to Reproduce
1. Create a device type with name "PP 24/12 port Single Mode" with maufacturer FOSS
2. Import the following data:
name,device_role,tenant,manufacturer,model_name,platform,serial,asset_tag,status,site,rack_group,rack_name,position,face,comments
FM002-1,Patch Panel,DCF,FOSS,PP 24/12 port Single Mode,,,,Active,R25,R25,1.4,1,Rear,Housing

### Expected Behavior
Sucessfull import

### Observed Behavior
Following error:
<class 'dcim.models.Device.device_type.RelatedObjectDoesNotExist'>

Device has no device_type.

I have tried several device types, also expored them and done copy and paste to avoid typos, but no luck.

**Comment by ziggekatten** [comment] 2019-10-16 20:14
Allright, it seems that using slash(/) in the name is a NO NO if you would like to import.

**Comment by DanSheps** [comment] 2019-10-17 14:10
I am unable to reproduce this on master.netbox.dansheps.com

Steps:

* Create site: R25
* Create rack group: R25
* Create rack: 1.4
* Create Tenant: DCF
* Create Manufacturer: FOSS
* Create Device Type: PP 24/12 port Single Mode
  * Create 6 rear ports
  * Create 6 front ports
* Create Device Role: Patch Panel
* Perform import

Please provide reproducible steps for us to determine if this is a bug.  In the future, make sure you provide all steps needed to get to the end result (in this case, creation of everything else)

**Comment by ziggekatten** [comment] 2019-10-17 15:08
The steps above is excactly how I have done it. Next time I'll ensure I'll be more specific end to end.

Imports works as they should, as long as the device type name name does NOT contain a "/".

As soon as I rename my device type to "PP 24-12 port Single Mode" and change my device import to use that name instead, it works as it should.  Changing it back, and it fails again. 

I can live with it as such, but a little bit annoying.

**Comment by DanSheps** [comment] 2019-10-17 17:34
The problem is though, even including the "/", I am unable to replicate your results.

**Comment by jeremystretch** [comment] 2019-10-23 21:19
Also unable to replicate this on v2.6.6. I can confirm that "PP 24/12 port Single Mode" is a valid device type name (though I would strongly discourage the use of slashes for other reasons). I can't get it to generate a `RelatedObjectDoesNotExist` exception with the data provided.

Going to close this out, but please ask that it be reopened if you're able to recreate it again (be sure to capture the full stack trace).

**Closed by jeremystretch** 2019-10-23 21:19 UTC
Labels: status: revisions needed
