### ISSUE TITLE
Creating an IP (via bulk import or API) assigned to a device without specifying interface creates inconsistency

### ISSUE THREAD

**Issue by aldem** [netbox-community/netbox#13306] opened 2023-07-30 13:49 UTC
### NetBox version

v3.5.7

### Python version

3.11

### Steps to Reproduce

1. Create any device (or choose existing one) for testing
2. Do a bulk IP import or use API to create an IP assigned to a device without specifying an interface, like this (bulk import):
```csv
address,status,device
11.22.33.44/32,active,example.dev
```
3. Try to open device page afterwards and observe "Server error" page

### Expected Behavior

If specifying a device without interface is not allowed any request attempting to do this must be rejected.

It would be better though to allow to assign IP without specifying interface (for ephemeral interfaces or similar things) but probably this is a topic for another issue.

### Observed Behavior

Attempt to open a device page which has IP assigned but without interface results in "Server error":

```
<class 'AttributeError'>

'ImageDraw' object has no attribute 'textsize'

Python version: 3.11.2
NetBox version: 3.5.7
```

Further, this "phantom" device assignment is invisible on IP page (no device shown) so it might be hard to detect where is the problem.

**Comment by jeremystretch** [comment] 2023-07-30 13:53
Duplicate of #13115. Please remember to search existing issues before submitting a new one.

**Closed by jeremystretch** 2023-07-30 13:53 UTC
Labels: type: bug

**Comment by aldem** [comment] 2023-07-30 13:55
Even worse... just noticed that *all* device pages produce "Server error" after this, and even deletion of IP address does not solve the issue.
