### ISSUE TITLE
When Importing an Exported CSV File, It does not like the Capitalized Column names, and values

### ISSUE THREAD

**Issue by cschar** [netbox-community/netbox#13829] opened 2023-09-19 23:16 UTC
### NetBox version

v3.6.1

### Python version

3.8

### Steps to Reproduce

I followed the tutorial on the site,

I constructed 2 prefix entries, then

I Exported a Prefixes.csv file as such:
<img width="1162" alt="Screenshot 2023-09-19 at 7 17 58 PM" src="https://github.com/netbox-community/netbox/assets/296551/e5647733-4b1b-4d5c-adc1-99a9907f40b8">

```
Prefix,Status,Children,VRF,Utilization,Tenant,Site,VLAN,Role,Description,ID,Prefix (Flat),Tenant Group,VLAN Group,Pool,Marked Utilized,Comments,Tags,Created,Last updated,Depth
198.168.11.0/24,Active,0,Global,0.0%,,my-site,,,,1,198.168.11.0/24,,,False,False,,,2023-09-19 21:35,2023-09-19 21:38,0
198.168.12.0/24,Active,0,Global,100%,,my-site,,,a second prefix,2,198.168.12.0/24,,,False,True,,,2023-09-19 21:38,2023-09-19 21:38,0
```

I then deleted entries so I could test importing.

I then tried to import it through the UI using 'Direct import'
<img width="1164" alt="Screenshot 2023-09-19 at 7 10 24 PM" src="https://github.com/netbox-community/netbox/assets/296551/ee767c86-4b4c-4dec-9fdc-4921a56300a3">

I clicked submit, and it complained about missing entries
<img width="1193" alt="Screenshot 2023-09-19 at 7 10 34 PM" src="https://github.com/netbox-community/netbox/assets/296551/3f0a6011-4a41-4f40-8dea-7707f7694b0b">

I modified the text to not use uppercase for first field, only 1 error remained

<img width="1183" alt="Screenshot 2023-09-19 at 7 10 52 PM" src="https://github.com/netbox-community/netbox/assets/296551/ec38f3ac-5f52-4b19-a249-bd41dbab0724">

modified text to have no uppercase rquired fields.. New error, now the values needed to be lowercased
<img width="1174" alt="Screenshot 2023-09-19 at 7 11 02 PM" src="https://github.com/netbox-community/netbox/assets/296551/69e1a0c5-99ba-4752-95e6-83e78e18cd16">

lowercased the 'Active' to 'active' and clicked submit.
<img width="1170" alt="Screenshot 2023-09-19 at 7 11 16 PM" src="https://github.com/netbox-community/netbox/assets/296551/a71560aa-594b-4507-829a-a7513a677b16">

worked.

Seems the exported file should either export as lowercase if it expects lowercase input, or on input, it does the conversion for us.

### Expected Behavior

be able to import/export without having to lowercase strings manually.

### Observed Behavior

errors appeared not allowing me to import

**Comment by abhi1693** [comment] 2023-09-20 04:17
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

Moreover see https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#why-cant-i-pass-exported-data-directly-into-the-import-form

**Closed** 2023-09-20 04:18 UTC
