### ISSUE TITLE
Cable import throws 'Server Error' if one end doesn't exist 

### ISSUE THREAD

**Issue by mmfreitas** [netbox-community/netbox#11276] opened 2022-12-21 12:28 UTC
### NetBox version

v3.4.1

### Python version

3.9

### Steps to Reproduce

1. Create device-1
2. Create interface-1 type 100BASE-TX on device-1
3. Attempt to import  the following data through cable import as csv

```
side_a_device,side_a_name,label,side_b_name,side_b_device,side_a_type,side_b_type,type,status,tenant,length,length_unit,color
device-1,interface-1,1908,interface-2,device-2,dcim.interface,dcim.interface,cat5e,connected,,,m,9e9e9e
```

Notice that I havent created device-2 nor the interface-2, this is intended.

### Expected Behavior

If one of the required endpoints of the cable are missing, netbox should throw a notification error stating which one is missing so the user can create or correct the information.

### Observed Behavior

![image](https://user-images.githubusercontent.com/91552302/208905012-83889298-cc53-464c-8cf2-f03f9c00c376.png)

**Comment by kkthxbye-code** [comment] 2022-12-21 12:30
Duplicate of https://github.com/netbox-community/netbox/issues/11210

**Closed by kkthxbye-code** 2022-12-21 12:30 UTC
Labels: type: bug, status: duplicate
