### ISSUE TITLE
Interface Templates should include custom fields attached to DCIM>Interface

### ISSUE THREAD

**Issue by dpotter-intoto** [netbox-community/netbox#10754] opened 2022-10-26 13:27 UTC
### NetBox version

v3.3.5

### Feature type

Change to existing functionality

### Proposed functionality

**Interface templates** (which are created with **Device Types**) should allow the specification of values for custom fields that have been added to `DCIM>Interface`.

This will allow the device type to contain values for custom fields on interfaces as well as stock fields on interfaces.

### Use case

Any user who has the need for a custom field on DCIM>Interface is also likely to desire a default value that may vary from interface to interface.

For example, a user creates a custom field `requires_ptp` for DCIM>Interface.  This field specifies whether this interface requires PTP timing information from the network.

When I create a device, the values "true" or "false" should be automatically populated in this field for each interface, based on the default value kept inside the device type's interface template.  

Currently, this is not possible, because interface templates only allow users to specify values for stock fields, not custom fields.

### Database changes

unknown.  Possibly a change to how interface templates are stored.

### External dependencies

none

**Comment by sleepinggenius2** [comment] 2022-10-26 14:34
I had proposed this for all of the device component templates in #9243 as well, but it unfortunately did not gain a lot of traction then. I would still love to see this implemented, as my organization is facing similar issues to yours.

It would also be nice to have some more of the core fields implemented in templates as well, so you can do things like disable interfaces by default or set a default MTU, speed, duplex, or 802.1Q Mode.

**Comment by cyr0nk0r** [comment] 2022-10-27 17:08
I have also asked for this feature in https://github.com/netbox-community/netbox/issues/10324

**Comment by kkthxbye-code** [comment] 2022-10-27 17:37
I'll close this as duplicate of #9243 as I think that is the best description of the feature. I have re-opened the issue to give it another chance as I think it's a neat idea if we can figure out a good implementation.

**Closed by kkthxbye-code** 2022-10-27 17:37 UTC
Labels: type: feature

**Comment by sleepinggenius2** [comment] 2022-10-28 17:26
@kkthxbye-code Can you please unlock #9243 for comments?

**Comment by kkthxbye-code** [comment] 2022-10-28 17:55
@sleepinggenius2 - Sorry my bad, missed that🤦
