### ISSUE TITLE
It's now possible to create uneditable cables, that 1-side connected

### ISSUE THREAD

**Issue by stavr666** [netbox-community/netbox#12439] opened 2023-05-02 20:50 UTC
### NetBox version

v3.5.0

### Python version

3.10

### Steps to Reproduce

Found it in today's [Demo](https://demo.netbox.dev/).

Cables with id 1-33, 87-92 have no A-side device or termination:

![image](https://user-images.githubusercontent.com/84839985/235781701-0d0d09c1-8b46-4c46-a25e-781886051e5e.png)

It causes server error with Edit attempt.

### Expected Behavior

Pressing Edit must open Cable Edit form, validating connection on save.

### Observed Behavior

Error "'str' object has no attribute 'label'":

![image](https://user-images.githubusercontent.com/84839985/235782599-4bdf3799-4aa3-4375-b717-c3e0755512e8.png)

**Comment by jeremystretch** [comment] 2023-05-02 20:51
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by stuntguy3000** [comment] 2023-05-03 01:36
I reckon it's a demo data problem - Null devices are specified for these cable terminations.

![image](https://user-images.githubusercontent.com/1522389/235818203-f6176a97-0776-4501-a76c-0daa92e720e9.png)

**Comment by ThomasADavis** [comment] 2023-05-03 18:11
Create the cable, then on one end disconnect it - this is not the same as editing or deleting the cable.  Presto, one end connected, the other null.  To get a null/null cable, you need to use the API.. and yes, it's possible to get some of those..

**Comment by DanSheps** [comment] 2023-06-26 19:25
Duplicate of #11460

**Closed by DanSheps** 2023-06-26 19:25 UTC
Labels: type: bug, status: accepted, topic: cabling, severity: medium
