### ISSUE TITLE
?dns_name__empty=False not working

### ISSUE THREAD

**Issue by AndreasMoe** [netbox-community/netbox#10112] opened 2022-08-23 14:00 UTC
### NetBox version

v3.2.8

### Python version

3.10

### Steps to Reproduce

PS! Using invoke-restmethod by powershell (Python version not applicable)

1. Filtering API call to only return ipaddress entries that have dns_name set
2. https://xxx/api/ipam/ip-addresses/?dns_name__empty=False 
3. All IP-addresses are returned ( if ?limit=0 added)

Addressed earlier in

"[jeremystretch](https://github.com/jeremystretch) commented [on 1 Jul 2021](https://github.com/netbox-community/netbox/issues/6138#issuecomment-872488043)
I've added a custom empty lookup to address this use case. You can now do e.g. ?dns_name__empty=False to return all records with non-empty values." 

### Expected Behavior

Only IP-Addresses that has dns_name should be returned

### Observed Behavior

All IPs are returned

**Comment by jeremystretch** [comment] 2022-08-23 14:07
Best I can figure, this is a duplicate of #9231. If not, please put some effort into rewriting your issue above to clearly convey the problem.

**Closed by jeremystretch** 2022-08-23 14:07 UTC
Labels: type: bug
