### ISSUE TITLE
backports.zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key Asia/Hanoi'

### ISSUE THREAD

**Issue by chesronw** [netbox-community/netbox#9985] opened 2022-08-12 07:12 UTC
### NetBox version

v3.2.8

### Python version

3.8

### Steps to Reproduce

Error after upgrading to 3.2.8. 
Services not starting anymore.  502 Bad Gateway

Upgrade from 3.2.5 to 3.2.8

### Expected Behavior

Should work as normal

### Observed Behavior

502 Bad Gateway

See errors below after upgrade:

![Screenshot 2022-08-12 091145](https://user-images.githubusercontent.com/85490348/184303381-efcf9ece-0a20-4fe8-9aa7-39f56c2bec4f.jpg)

**Comment by davidh-hostwinds** [comment] 2022-08-12 09:28
This seems to be due to [pytz upgrading from 2022.1 to 2022.2](https://pypi.org/project/pytz/#history).
Downgrading pytz to the previous release seemed to fix the issue in our virtualenv.

**Comment by jeremystretch** [comment] 2022-08-12 12:29
Marking this as a duplicate of #9986 (even though it was opened first) as #9986 has a bit more detail.

**Closed by jeremystretch** 2022-08-12 12:29 UTC
Labels: type: bug
