### ISSUE TITLE
Tenant Groups list display doesn't show count of tenants

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#4485] opened 2020-04-14 11:38 UTC
### Environment
* Python version: 3.7.7
* NetBox version: 2.8.0

### Steps to Reproduce
1. Create a bunch of tenant groups
2. Create a tenant assigned to one of the groups
3. View the Tenant Groups list at /tenancy/tenant-groups

### Expected Behavior
The tenants column should show the number of tenants in the tenant group or sub groups. The rack groups view does this correctly.

### Observed Behavior
The 'Tenants' column shows 0 for all tenant groups. Compare this to racks in a rack-group - the rack groups display shows the number of racks in the rack group or in one or it's sub-groups.

**Comment by jeremystretch** [comment] 2020-04-14 14:20
Looks like another caching issue. I'm not able to replicate this with caching disabled.

**Comment by cpmills1975** [comment] 2020-04-14 14:24
Indeed. Having disabled the cache, it does now show the count of tenants. I'll close this one too!

**Comment by lampwins** [comment] 2020-04-29 05:30
@cpmills1975 this should have been resolved in 2.8.1. Can you confirm?

**Comment by lampwins** [comment] 2020-05-05 01:32
I confirmed this is fixed in 2.8.1

**Closed by lampwins** 2020-05-05 01:32 UTC
Labels: status: gathering feedback, type: bug
