### ISSUE TITLE
VPN - Can't create tunnel termination on virtual machine

### ISSUE THREAD

**Issue by janos-lamberg-liszkay** [netbox-community/netbox#14770] opened 2024-01-11 10:47 UTC
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.11

### Steps to Reproduce

1. Create a new tunnel
2. Navigate to the create new tunnel termination form
3. In the _Type_ field, select _Virtual Machine_
4. In the _Virtual Machine_ field select a virtual machine
5. In the _Interface_ field select an interface on the virtual machine
6. Click the create button

### Expected Behavior

A new tunnel termination should be created with the selected interface on the selected virtual machine

### Observed Behavior

A new tunnel termination is created with a seemingly random interface selected on a seemingly random **device** (not virtal machine).
![2024-01-11_11-46](https://github.com/netbox-community/netbox/assets/117651078/8c41b9f2-a4a0-4907-81a1-698e1a01ab3b)
![2024-01-11_11-46_1](https://github.com/netbox-community/netbox/assets/117651078/5f090499-d6e6-4143-ac2f-a5a6b85b749a)

**Comment by jeffgdotorg** [comment] 2024-01-11 18:22
Thanks for reporting a problem in NetBox.

Your bug report is valid, but it's also a duplicate of #14663, which has already been fixed. I'm therefore closing this issue.

**Closed by jeffgdotorg** 2024-01-11 18:22 UTC
Labels: type: bug

**Comment by peterbaumert** [comment] 2024-01-11 18:47
@jeffgdotorg its not a duplicate completly. The other issue just fixed the problem in the tunnel creation form. But not the tunnel termination creation form which this issue here is about.

**Comment by peterbaumert** [comment] 2024-01-12 16:16
@jeffgdotorg @jeremystretch can this be reopened?

**Comment by DanSheps** [comment] 2024-01-17 22:42
> can this be reopened?

If you believe there is still a problem with the form, please open a bug report and provide detailed reproduction steps on the current release.

**Comment by peterbaumert** [comment] 2024-01-18 03:24
> > can this be reopened?
> 
> 
> 
> If you believe there is still a problem with the form, please open a bug report and provide detailed reproduction steps on the current release.

Honestly i give up now. Repro and everything is still the same as up. I also wrote already that the other issue was about Tunnel creation form and this is about tunnel termination creation form but yeah im out.

**Comment by stwalkerster** [comment] 2024-01-18 11:02
@DanSheps, @jeffgdotorg  I can reproduce this using the reproduction steps outlined in *this* bug report on v3.7.1.

If you would like me to copy-paste this into a new bug I'd be happy to do so, but it's probably less effort to just re-open this.

**Comment by abhi1693** [comment] 2024-01-18 11:07
The issue reported is not reproducible however I can see a different issue at the moment that a valid virtual machine is not being allowed to pass the validation on the form.

**Comment by abhi1693** [comment] 2024-01-18 11:36
I have opened a new issue #14839 please share your comments over there
