### ISSUE TITLE
class 'django.utils.datastructures.MultiValueDictKeyError

### ISSUE THREAD

**Issue by whtkam** [netbox-community/netbox#10390] opened 2022-09-16 16:48 UTC
### NetBox version

v3.3.3

### Python version

3.9

### Steps to Reproduce

I Upgraded to Version 3.3.3

When I save an interface, the server error comes up

The same works in the previous version 3.3.2

### Expected Behavior

save interface

### Observed Behavior

<class 'django.utils.datastructures.MultiValueDictKeyError'>

'device'

Python version: 3.9.11
NetBox version: 3.3.3

**Comment by kkthxbye-code** [comment] 2022-09-16 16:53
Duplicate of https://github.com/netbox-community/netbox/issues/10387

**Closed by kkthxbye-code** 2022-09-16 16:53 UTC
Labels: type: bug
