### ISSUE TITLE
Config Revisions return at the first occurrence when Netbox restarts

### ISSUE THREAD

**Issue by chrisho95** [netbox-community/netbox#15312] opened 2024-02-29 12:19 UTC
### Deployment Type

Self-hosted

### NetBox Version

v3.7.3

### Python Version

3.11

### Steps to Reproduce

1. Create two Configuration revisons in Admin -> CONFIGURATION -> Config Revisions
The second config is Active

![image](https://github.com/netbox-community/netbox/assets/82440344/0abbb73f-c382-4303-b77f-a60fa5bd62dd)

2. Restart Netbox
The first confg is Active and the second config is Inactive

![image](https://github.com/netbox-community/netbox/assets/82440344/e068cd2d-8174-40f8-a4c4-cee0b2496489)

3. I have to reactivate the latest version

![image](https://github.com/netbox-community/netbox/assets/82440344/390dcaa5-c12d-4a24-aca9-c75de039f136)

### Expected Behavior

When netbox restarts, I would like the last config to remain active.

### Observed Behavior

It happened that the first config was activated when restarting Netbox and the second was deactivated.

**Comment by jeremystretch** [comment] 2024-02-29 20:09
I'm unable to reproduce this behavior.

> 2. Restart Netbox

What exactly are you restarting? The current configuration version is stored in Redis, so if you're destroying the Redis database somehow then yes you'll lose the active configuration (along with any other cached data or queued jobs).

**Comment by chrisho95** [comment] 2024-03-01 07:06
I forgot to mention that my netbox instance was installed on docker.

So to restart Netbox I do "docker-compose down && docker-compose up -d".

On older versions of Netbox I didn't have this problem.

**Comment by abhi1693** [comment] 2024-03-01 10:53
Do you have a persistent volume attached to your redis instance? It seems to me that your redis is losing the applied revision

**Comment by chrisho95** [comment] 2024-03-01 12:50
Yes.

   **# redis
  redis-reseau:
    image: redis:7-alpine
    container_name: redis-reseau
    restart: unless-stopped
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    #- redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    - redis-server --appendonly yes --requirepass FOOBAR
    env_file: ./env/redis.env
    volumes:
    - netbox-redis-data:/data**

**Comment by jsenecal** [comment] 2024-03-04 21:42
> netbox-redis-data

Make this a bind mount or an external volume. It should then survive the destruction of the docker-compose project.

**Comment by jeremystretch** [comment] 2024-03-08 21:40
From the discussion above this appears to be related to the specific means of deployment and not something that can be addressed in NetBox itself. If means to reproduce this in NetBox natively can be identified, I'll be happy to reopen this issue.

**Closed by jeremystretch** 2024-03-08 21:40 UTC
Labels: type: bug, status: revisions needed

**Comment by ziggekatten** [comment] 2024-05-02 14:21
We also run docker, and have done so for years without issues. We have upgraded out test/integrationtest and production environments from 3.4.10 to 3.7.5 the past three weeks. All of the environments behave in the same way! And we use persistent volumes, in this case also on different disks systems. It always default back to the first config revision after an restart of Netbox.

Now, as I understand it, Redis is involved here, but in what way? How is the configuration revision stored and read by Netbox when starting up?
