### ISSUE TITLE
Error Message Box Pops up in the Wrong Position

### ISSUE THREAD

**Issue by frnksmdlkedjnfr** [netbox-community/netbox#13017] opened 2023-06-27 02:47 UTC
### NetBox version

4527ddaf08ee (v3.5.4) Docker

### Python version

3.8

### Steps to Reproduce

1. Click 'Circuit Type Bulk Import'
2. Paste a CSV text that contains errors (in my case:)
```
name,slug
ASE,ase
ASEoD,aseod
DDN,ddn
DPLC,dplc
EPL,epl
Ethernet,eth
IPLC,iplc
MPLS,mpls
MSTP,mstp
SDH,sdh
裸光纖,bare-fibre
```
3. Click 'Submit'

### Expected Behavior

The error message box placed properly at the bottom right corner

### Observed Behavior

1. In PC layout, the error message box pops up at the top left corner, completely blocking the message:
![2023-06-27_10-34-55_Circuit Type Bulk Import  NetBox - Cent Browser](https://github.com/netbox-community/netbox/assets/63704404/e37b1266-c965-4e8f-b751-646f56d9e548)

2. In tablet and mobile layouts, the message box is nowhere to be seen:
![2023-06-27_10-35-30_Circuit Type Bulk Import  NetBox - Cent Browser](https://github.com/netbox-community/netbox/assets/63704404/98e1ac8c-31fe-412c-a6b5-1b168460602c)
![2023-06-27_10-42-08_Circuit Type Bulk Import  NetBox - Cent Browser](https://github.com/netbox-community/netbox/assets/63704404/9bc0e74e-d70d-4f53-b9b3-a41bbbcb95c5)

**Comment by jeremystretch** [comment] 2023-06-27 12:32
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.5.4. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by kkthxbye-code** [comment] 2023-07-04 07:18
I cannot replicate this (either scenario) and since there's been no update, I'll close it out. If you manage to replicate it on a clean instance please share the replication steps.

**Closed by kkthxbye-code** 2023-07-04 07:18 UTC
Labels: type: bug, status: revisions needed
