### ISSUE TITLE
VM creation via GUI or Script

### ISSUE THREAD

**Issue by c4lidos** [netbox-community/netbox#10090] opened 2022-08-22 14:41 UTC
### NetBox version

v3.3.0

### Python version

3.8

### Steps to Reproduce

1. Go to Virtualization 
2. Click to Virtual Machines  https://netbox.ibi-berlin.de/virtualization/virtual-machines/ 
4. Click on ADD https://netbox.ibi-berlin.de/virtualization/virtual-machines/add/
5. fill out the template leaving Site field blank
![netbox_vm_create_cluster02](https://user-images.githubusercontent.com/61190734/185948118-f744dc77-9d5b-4f42-ad67-d0e80a7e095f.png)
![netbox_vm_create_cluster (2)](https://user-images.githubusercontent.com/61190734/185946552-98a72d4e-9a5d-4afe-a308-c1690cda09c1.png)

### Expected Behavior

Should take the Site from the Device and/or Cluster

### Observed Behavior

The Selected cluster (xxx is not assigned to this site(none).

**Comment by jeremystretch** [comment] 2022-08-22 15:07
Duplicate of #10088. Please follow the instructions provided in my comment, and do not open duplicate issues. Additionally, you have again ignored the bug report template:

> Describe in detail the exact steps that someone else can take to reproduce this bug using the current stable release of NetBox.

**Closed by jeremystretch** 2022-08-22 15:07 UTC
Labels: type: bug
