### ISSUE TITLE
Issue when I click on "Child prefixes" tab

### ISSUE THREAD

**Issue by earendilfr** [netbox-community/netbox#7104] opened 2021-08-31 19:19 UTC
### NetBox version

v3.0.0

### Python version

3.8

### Steps to Reproduce

1. Select an existing IP prefix
2. Click on the tab to see the child prefixes.

This issue could be seen for IP prefix with child prefixes and for IP prefix without child prefixes.

This current installation (and the data in database) was upgraded from version 2.11.7

### Expected Behavior

The list of child prefixes for the current prefix

### Observed Behavior

We receive the following error message:
```
 There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'str' object has no attribute 'available_columns'

Python version: 3.8.6
NetBox version: 3.0.0
```

**Comment by jeremystretch** [comment] 2021-08-31 19:24
Duplicate of #7072

**Closed by jeremystretch** 2021-08-31 19:24 UTC
Labels: type: bug
