### ISSUE TITLE
Wrong type for region on get dcim devices in swagger

### ISSUE THREAD

**Issue by aopdal** [netbox-community/netbox#13580] opened 2023-08-28 09:45 UTC
### NetBox version

v3.5.8

### Python version

3.10

### Steps to Reproduce

1. Click on REST API documentation icon in NetBox web interface
2. Go to GET /api/dcim/devices/ 
3. Click on Try it out
4. Go down to region
5. Click add integer item -> should be add string item to register region slug
6. Write a valid region slug
7. Go down to Execute and click it

### Expected Behavior

Should list devices belonging to a Region

### Observed Behavior

The following error message comes up:
Please correct the following validation errors and try again.
index0errorValue must be an integer

**Comment by abhi1693** [comment] 2023-08-28 09:48
Duplicate of #13459

**Closed by abhi1693** 2023-08-28 09:48 UTC
Labels: status: duplicate
