### ISSUE TITLE
Porblem with Cable Bulk Import/export

### ISSUE THREAD

**Issue by TheKingOfChaos** [netbox-community/netbox#5245] opened 2020-10-16 20:47 UTC
### Environment
* Python version: python 3.6
* NetBox version: v2.9.4

### Steps to Reproduce
1. use the cable Export function 
2. take the file and use the Cable Bulk Import 

### Expected Behavior
the Expected was that i can use the export and import the data back

### Observed Behavior
the fieldt names of the import and export is not compatible

**Comment by jeremystretch** [comment] 2020-10-16 20:49
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Comment by martink2** [comment] 2020-10-17 16:51
We ran into the same issue. Using Export on cables gives a CSV with 
the following headers:

`termination_a_type,termination_a_id,termination_b_type,termination_b_id,type,status,label,color,length,length_unit`

But the import for cables expects:

`side_a_device,side_a_type,side_a_name,side_b_device,side_b_type,side_b_name`

Which means when you want to import the data back you need to rename the headers and replace all device id's with the device names.

**Comment by jeremystretch** [comment] 2020-10-19 13:15
Duplicate of #4429. Please note that this is expected behavior, as the CSV import fields are customizable.

**Closed by jeremystretch** 2020-10-19 13:15 UTC
