### ISSUE TITLE
Bulk import of Journal entries ignore specified user

### ISSUE THREAD

**Issue by Kage1** [netbox-community/netbox#13717] opened 2023-09-07 20:47 UTC
### NetBox version

v3.5.8

### Python version

3.10

### Steps to Reproduce

1. Goto Operations - Journal Entries
2. Select import
3. Enter headers including "created_by"
4. Fill out data to import including ID of the user to create the entry as
4a. The user exists as an admin in organization
5. Submit the import with auto-detect format
6. The journal entry is created on the dcim.device but the user who created it is me vs the specified user.

### Expected Behavior

The journal entry should be created and show it was the other user.

### Observed Behavior

The journal entry is created by my user.

**Comment by pv2b** [comment] 2023-09-08 05:41
I'm unable to reproduce this on 3.6.1. I tried this in the demo instance:

```
assigned_object_type,assigned_object_id,kind,comments,created_by
dcim.device,108,danger,will robinson,2
```

And it created the journal entry by user number 2 (which in this case is "alice").

My guess was that maybe you accidentally entered the username (e.g. `alice`) instead of the user's ID (e.g. 2)? But this makes no sense because then you'll just get a validation error on import, you won't get a successful import like that.

Can you please clarify the exact CSV used for import? For example, make sure your headers are spelled correctly, including being all-lowercase. Unrecognized headers will be ignored. And also, if possible, try out your use case on the latest version of NetBox, optionally through the demo site at https://demo.netbox.dev/ which might be easier for you than upgrading.

**Comment by jeremystretch** [comment] 2023-09-08 14:46
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment] 2023-09-21 18:59
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.

**Closed by jeremystretch** 2023-09-21 18:59 UTC
Labels: type: bug, status: revisions needed
