### ISSUE TITLE
Missing Django ContentType (extras | reportresult) after update to 2.9.1

### ISSUE THREAD

**Issue by rebortg** [netbox-community/netbox#5066] opened 2020-08-28 08:15 UTC
### Environment
* Python version: 3.6
* NetBox version: 2.9.1

### Steps to Reproduce
1. upgrade from 2.8.9 to 2.9.1
2. test the permissions for report
I also sadly can't repoduce this with an update fom a fresh 2.8.9 to 2.9.1

### Expected Behavior
Can set the permission for the reportresult views

### Observed Behavior
Can't set the permission

I have a prod and a test system with this error.

In a fresh install of 2.9.1 all is fine.
The diff is the content of the django_content_type table:

fresh 2.9.1:
```
>>> from django.contrib.contenttypes.models import ContentType
>>> ContentType.objects.count()
85
>>> ContentType.objects.filter(app_label="extras", model="reportresult")
<QuerySet [<ContentType: reportresult>]>
```

in my upgraded 2.9.1:
```
>>> from django.contrib.contenttypes.models import ContentType
>>> ContentType.objects.count()
84
>>> ContentType.objects.filter(app_label="extras", model="reportresult")
<QuerySet []>
```

in my test system i manually add the missing ContentType, this worked and the permission will be fixed.
Does this somehow have an effect in the future?

**Comment by jeremystretch** [comment] 2020-08-31 12:44
> I also sadly can't repoduce this with an update fom a fresh 2.8.9 to 2.9.1

Then it's unlikely anyone else will be able to either. Without complete instructions for reproducing the reported bug, this isn't actionable.

> Can set the permission for the reportresult views

The ReportResult model no longer exists in v2.9.1.

**Comment by rebortg** [comment] 2020-08-31 14:17
strange, i try a upgrade path from a late 2.6 version but i don't get it to reproduce.

> The ReportResult model no longer exists in v2.9.1.

Yes, but in a fresh 2.9.1 the Django ContentType (extras | reportresult) will be there and some views class use them as permission requirement. [here](https://github.com/netbox-community/netbox/blob/2435c177f53186b1f9d4683377b3e73315a7e0d3/netbox/extras/views.py#L318)

One last question, before you close this due to non-reproducibility.
As i mention i have this issue in my prod and test environment. When i add the ContentType manually (in test it worked), does this have negative effects in the future?

**Comment by jeremystretch** [comment] 2020-08-31 14:19
> When i add the ContentType manually (in test it worked), does this have negative effects in the future?

Yes: you should never be adding content types manually.

**Comment by rebortg** [comment] 2020-09-01 19:26
I don't know why, or what i have done in the past. But i get it to reproduce in a fresh 2.9.1

Steps:
1. install a fresh 2.9.1 versin (i used [netbox-docker](https://github.com/netbox-community/netbox-docker))
2. add a permission with all objects and all action rights
3. add a non admin user with the permission from point 2
4. have a simple report
5. log in with the user

user have no permission to reports view.

6. update to 2.9.2

user have no permission to reports view

I think the root case is the wrong permission in the [ReportView](https://github.com/netbox-community/netbox/blob/2435c177f53186b1f9d4683377b3e73315a7e0d3/netbox/extras/views.py#L318)?

**Comment by rebortg** [comment] 2020-09-08 16:59
Hi, i respect the guidelines it important to get this project clean. But shouldn't the correct order to be first accept or close the attached issue before closing the PR?
I keep my branch active, so if someone of the maintainer can reproduce the bug, you can reopen the PR.

**Comment by jeremystretch** [comment] 2020-09-08 17:08
@rebortg please see the [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md):

> Any pull request which does not relate to an **accepted** issue will be closed.

**Comment by jeremystretch** [comment] 2020-09-23 14:28
I'm not 100% clear on the issue being described here. It looks like it's potentially resolved by #5137.

**Comment by rebortg** [comment] 2020-09-23 16:08
yes, it is the case, i was on a wrong path at the beginning and think the content type was missing, but i was a wrong permission string in the report view and some other places like in the template
The PR, i link here, will solve this issue

**Comment by jeremystretch** [comment] 2020-09-23 16:13
#5137 has already been resolved. Going to close this out.

**Comment by jeremystretch** [comment] 2020-09-23 17:32
#5137 addresses the mismatch in permission evaluation among the different report views. This issue deals with the transition from the old ReportResult permissions to using the Report model directly.

**Closed** 2020-09-23 17:41 UTC
