### ISSUE TITLE
Interface names listing is duplicated multiple times at connection of interfaces to another device

### ISSUE THREAD

**Issue by drikusb** [netbox-community/netbox#6809] opened 2021-07-25 23:45 UTC
### NetBox version

v3.0-beta1(demo instance)

### Python version

3.8

### Steps to Reproduce

1, Select a device in demo instance eg; dmi01-rochster-sw01
2. Connect interface GigabitEthernet1/0/3 to another device
3. Select 'Device'  dmi01-rochester-rtr01
4. 'Select Name' section brings up a listing of interfaces duplicated 13 times
![netbox-interface-dup-bug](https://user-images.githubusercontent.com/7657718/126917232-1a56b570-8fc2-4efa-8072-45129800d956.PNG)

### Expected Behavior

Interfaces should not be duplicated in the 'Select Name' listing . 

### Observed Behavior

Listed each real interface 13 times for each interface created for/on the device.

**Comment by jeremystretch** [comment] 2021-07-29 14:53
I'm not able to replicate this. What I think may be happening is that the interfaces list is being populated prematurely, before the B side device is selected. This will cause it to populate *all* interfaces, rather than just those assigned to the selected device. (After selecting a device, the interfaces list returns only the relevant interfaces.)

Still a bug, though. We should prevent fields which rely on parent selections from auto-populating until those parent fields have been selected.

**Comment by thatmattlove** [comment] 2021-07-30 08:23
The cause of this is the same as #6808. Closing this as a duplicate.

**Closed by thatmattlove** 2021-07-30 08:23 UTC
Labels: beta, status: duplicate, type: bug
