### ISSUE TITLE
can not view get_environment from naplam

### ISSUE THREAD

**Issue by lutfisan** [netbox-community/netbox#4118] opened 2020-02-07 10:43 UTC
### Environment
* Python version: 3.6  
* NetBox version: 2.7.0  

### Steps to Reproduce
1. Set up napalm as per docs
2. Click device's status tab

### Observed Behavior
can not view get_environment from naplam
![netbox](https://user-images.githubusercontent.com/29010489/74022913-148d0480-49d1-11ea-92ac-a49222c3ec60.png)

**Comment by hSaria** [comment] 2020-02-07 13:04
This is a duplicate of #3960. Release v2.7.2 includes the fix for this.

**Comment by DanSheps** [comment] 2020-02-07 13:34
Thank you for submitting this issue. Before any further work can be done, please upgrade to the most recent stable release of NetBox (currently 2.7.4) as this issue may have already been addressed. Please then update your issue to indicate whether further action is needed.

**Closed by DanSheps** 2020-02-07 13:34 UTC
