### ISSUE TITLE
Preconfigured rack filtering for B device field in cables form

### ISSUE THREAD

**Issue by coloHsq** [netbox-community/netbox#12792] opened 2023-06-01 16:11 UTC
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

It would be great to have the possibility to have back the old behavior for cables form, in which the B side device field came pre filtered to display devices in the same rack of the A side device.
I'm not requesting a rollback, as for my use case it would be enough just to have the B side device field pre filtered with the same rack as A, maybe with the option to have it enabled/disabled by default.

P.S. I've played a bit with the code, and passing the b rack pk from the url params down to device field's query_param in get_cable_form() seems to be working fine.

### Use case

In our datacenter we're using End of Row architecture, so almost 90% of the cables inserted on Netbox by common users are confined in the same rack, as almost everything runs trough patch panels.
Given this design, having the B side device field pre configured saves a lot of time and, from what I've seen, reduces the error risk.

### Database changes

None

### External dependencies

None

**Comment by martinum4** [comment] 2023-06-01 20:16
I already asked this with #12704

**Comment by Chiniquy** [comment] 2023-06-07 09:53
I've also been struggling a bit with this since the latest updates. I agree that a pre-filter for the existing rack would save a lot of time during cable creation. In my experience the vast majority of cables are within the same rack, or at the very least within the same location.

**Comment by DanSheps** [comment] 2023-06-07 19:26
Duplicate of #12704

**Comment by DanSheps** [comment] 2023-06-07 19:26
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #$ISSUE for further discussion.

**Closed by DanSheps** 2023-06-07 19:26 UTC
Labels: type: feature
