### ISSUE TITLE
SAS cables and connectors

### ISSUE THREAD

**Issue by 2code4me** [netbox-community/netbox#10265] opened 2022-09-06 14:53 UTC
### NetBox version

v3.2.7

### Feature type

New functionality

### Proposed functionality

I saw that it has been already asked (and rejected) some years ago, so I try again...

would be possible to add new Interface Type for SAS connections?
In details:

Add External Mini SAS Male (SFF-8088) cables
Add External Mini SAS Female (SFF-8088) Interface type for devices
Add External Mini SAS HD Male (SFF-8644) cables
Add External Mini SAS HD Female (SFF-8644) interface type for devices

### Use case

I'm adding a DM3000H Storage Array from Lenovo to our infrastructure (but of course we already have a lot of stuff using sas connector/cables) and I would like to create a device template with all the connector types other than LAN/USB/FC.

Thanks

**Comment by DanSheps** [comment] 2022-09-06 17:35
Duplicate of #2715

**Comment by DanSheps** [comment] 2022-09-06 17:42
As with all of the previous feature requests, this is still currently out of scope for the project and as such won't be something we will be getting to any time in the near or semi-far future (maybe once our open issues are <100 we could reinvestigate this)

Related FR's:

#659
#2175
#3617
#6396
#6549

**Closed** 2022-09-06 17:43 UTC
Labels: type: feature
