### ISSUE TITLE
clone device type does not clone components

### ISSUE THREAD

**Issue by petersonbasso** [netbox-community/netbox#8840] opened 2022-03-10 11:57 UTC
### NetBox version

v3.1.9

### Feature type

Change to existing functionality

### Proposed functionality

the clone button in device types, should clone all created components.

### Use case

The idea behind cloning an object is to take advantage of everything already created previously, currently the clone is only taking advantage of basic information, leaving this option with little use.

**Comment by jeremystretch** [comment] 2022-03-10 13:16
This was proposed in #4056 and again in #5536, but no one was interested in owning the implementation. If you would like to own this and commit to delivering a PR, I'll gladly assign it to you. Otherwise, it will be closed as a duplicate.

**Comment by jeremystretch** [comment] 2022-03-10 15:44
Issues are allowed to remain open for three months. In that time, if no one has expressed interest in owning it, the issue is closed as stale to ensure we don't amass hundreds of inactive issues. People can still find it when searching.

**Closed by jeremystretch** 2022-03-10 15:44 UTC
Labels: type: feature
