### ISSUE TITLE
Display Script Results Instead of Job Logs

### ISSUE THREAD

**Issue by bitcollector1** [netbox-community/netbox#15983] opened 2024-05-07 01:15 UTC
### NetBox version

v4.0.0

### Feature type

Restore functionality back to the way it was prior to NetBox 4.0; so you can get a link back to the results, from the list of jobs.

### Proposed functionality

From the list of completed jobs, provide link to the script "results" page instead of the jobs "logs" page.

<img width="1302" alt="Screenshot 2024-05-06 at 18 09 14" src="https://github.com/netbox-community/netbox/assets/50723251/a61a2ff4-1575-4791-b5b1-b0bb9d892a5f">

Script Results: (right after the script runs)
<img width="1191" alt="Screenshot 2024-05-06 at 18 10 51" src="https://github.com/netbox-community/netbox/assets/50723251/4daa3d92-a9b5-4ebe-aac6-2085b7e6fe36">

Job Log: (Prior to NetBox 4.0 clicking on the "Name" would bring you to the results page. Now both "ID" and "Name" bring you to log page. 
<img width="1155" alt="Screenshot 2024-05-06 at 18 12 57" src="https://github.com/netbox-community/netbox/assets/50723251/e1807509-76b0-4059-b2bf-fec3cfa96b53">

### Use case

Restore functionality back to the way it was prior to NetBox 4.0; so you can get a link back to the results. 

Change this link:
/core/jobs/41699/

to this:
/extras/scripts/results/41699/

It's much easier to read the results with all the formatting and color coding.

**Comment by bitcollector1** [comment] 2024-05-08 17:36
I believe this might be related to 
https://github.com/netbox-community/netbox/pull/16041

**Comment by bitcollector1** [comment] 2024-05-08 18:02
Looks like my use case is slightly different as I did not write my results to be in markdown.  That said, previously the logs showed the nice formatting. 

Maybe I need to redo my scripts to produce the markdown as was done in 
https://github.com/netbox-community/netbox/issues/16031

**Comment by bitcollector1** [comment] 2024-05-09 14:54
Thanks for taking this up @abhi1693

**Comment by bitcollector1** [comment] 2024-05-09 20:33
Just wanted to confirm that this adds a new column for the "results" to the main jobs page.
https://netdevbox.hwe.ebay.com/core/jobs/

I'm trying to follow along and it looks like the results are only showing up here:
https://netdevbox.hwe.ebay.com/extras/scripts/17/jobs/

I use this page the most to navigate all the various jobs and to view the results.

**Comment by jeremystretch** [comment] 2024-05-14 11:49
@bitcollector1 we can't add a "result" column to the generic jobs list as not all jobs reference a result (those are only for scripts).

**Comment by Mailstorm-ctrl** [comment] 2024-06-06 20:47
To add on to this...it doesn't appear adding an object to logs references the object anymore.
`self.log_info("example message",obj=Device.objects.get(serial=serial_no["sr_no"]))`

![image](https://github.com/netbox-community/netbox/assets/53045430/434a78f3-2ff3-4ad7-b323-7f6f7856b516)

**Comment by llamafilm** [comment] 2024-06-22 04:53
There is a very similar issue with the results of a report.  The object name and URL are shown as 2 separate columns which is hard to read.  I suggest hiding the URL column and making it a hyperlink on the name.  I think this is how it worked in v3, but I'm not positive.  The spirit of this change is the same for both, but let me know if this should be a separate issue.

<img width="1181" alt="image" src="https://github.com/netbox-community/netbox/assets/3991046/fd4c1a16-df4d-40e2-93c8-0a3f05698722">

**Comment by llamafilm** [comment] 2024-09-21 07:31
Please don’t close this. I use the results page quite often and this is a major usability regression since v3.

**Closed** 2024-10-24 04:03 UTC
Labels: type: feature, status: needs owner, pending closure, complexity: low
