### ISSUE TITLE
Error when bulk importing IP-addresses linked to device-interfaces

### ISSUE THREAD

**Issue by etoosamoe** [netbox-community/netbox#4660] opened 2020-05-19 07:24 UTC
### Environment
* Python version: 3.6.9
* NetBox version:  2.8.3

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2. Make interfaces in device ``mow-101-rt-vpn-ospf-hub``, e.g.: ipip-tunnel7
3. Create IP address bulk import file, e.g.:
```
address,status,device,interface,description
172.16.203.1/30,Active,mow-101-rt-vpn-ospf-hub,ipip-tunnel7,IPIP-VOLG-ISP1
172.16.205.1/30,Active,mow-101-rt-vpn-ospf-hub,ipip-tunnel29,CDROC-DC
172.16.199.1/24,Active,mow-101-rt-vpn-ospf-hub,ether7,Connection L2VPN-MTS
172.16.206.1/30,Active,mow-101-rt-vpn-ospf-hub,ipip-tunnel1,Khabarovsk-ISP1
172.16.207.1/30,Active,mow-101-rt-vpn-ospf-hub,ipip-tunnel3,Khabarovsk over Internet MTS 
```
3. Get error

P.S. If you delete ``interface`` from import text, the error is the same:
```
address,status,device,description
172.16.203.1/30,Active,mow-101-rt-vpn-ospf-hub,IPIP-VOLG-ISP1
```

It works when you importing ``address,status,description``.

### Expected Behavior
Get list of created IP addresses linked to device-interface

### Observed Behavior
```
 There was a problem with your request. Please contact an administrator.
The complete exception is provided below:
<class 'KeyError'>
'interface_name'
If further assistance is required, please post to the NetBox mailing list. 
```
![image](https://user-images.githubusercontent.com/38806450/82296952-a1753000-99ba-11ea-8705-15b318f3b63f.png)

What am I doing wrong?

**Comment by jeremystretch** [comment] 2020-05-19 12:50
Duplicate of #4649

**Closed by jeremystretch** 2020-05-19 12:50 UTC

**Comment by etoosamoe** [comment] 2020-05-19 13:26
Thanks for answer. I read #4649 but I importing with specifying device and interface:
```
address,status,device,interface,description
172.16.203.1/30,Active,**mow-101-rt-vpn-ospf-hub**,**ipip-tunnel7**,IPIP-VOLG-ISP1
172.16.205.1/30,Active,mow-101-rt-vpn-ospf-hub,ipip-tunnel29,CDROC-DC
172.16.199.1/24,Active,mow-101-rt-vpn-ospf-hub,ether7,Connection L2VPN-MTS
172.16.206.1/30,Active,mow-101-rt-vpn-ospf-hub,ipip-tunnel1,Khabarovsk-ISP1
172.16.207.1/30,Active,mow-101-rt-vpn-ospf-hub,ipip-tunnel3,Khabarovsk over Internet MTS 
```

**Comment by opericgithub** [comment] 2020-05-27 06:52
anyone?
