### ISSUE TITLE
Unable to provision a config-template with local data source via the REST API

### ISSUE THREAD

**Issue by desnoe** [netbox-community/netbox#13506] opened 2023-08-18 07:51 UTC
### NetBox version

v3.6.1

### Python version

3.11.4

### Steps to Reproduce

1. Start from a fresh NetBox instance, configure an API token and configure these 2 environment variables:

```
TOKEN=mynetboxtoken
NETBOX_URL=http://my.netbox.url
```

Please replace with values relevant to your NetBox instance.

2. Create `/etc/netbox/templates` directory on the NetBox instance and create a trivial Jinja2 template to the NetBox instance in it:

```
mkdir -p /etc/netbox/templates
echo 'This is a simple Jinja2 template.' > /etc/netbox/templates/basic.j2
```

4. Provision a new local data source using the REST API:

```
curl -X POST \
-H "Authorization: Token $TOKEN" \
-H "Content-Type: application/json" \
-H "Accept: application/json; indent=4" \
$NETBOX_URL/api/core/data-sources/ \
--data '{
    "name": "templates",
    "type": "local",
    "source_url": "file:///etc/netbox/templates",
    "enabled": true
}'
```

Make sure it is correctly created and note down its id:

```
DATASOURCE_ID=1
```

Please replace with the id of the created object.

5. Sync this new local data source using the REST API:

```
curl -X POST \
-H "Authorization: Token $TOKEN" \
-H "Content-Type: application/json" \
-H "Accept: application/json; indent=4" \
$NETBOX_URL/api/core/data-sources/$DATASOURCE_ID/sync/ \
```

6. Provision a new config template based on the `basic.j2` Jinja2 template in this local data source using the REST API:

```
curl -X POST \
-H "Authorization: Token $TOKEN" \
-H "Content-Type: application/json" \
-H "Accept: application/json; indent=4" \
$NETBOX_URL/api/extras/config-templates/ \
--data '{
    "name": "basic",
    "template_code": "Will be overwritten after data_file is synced",
    "data_source": {"name": "templates"},
    "data_file": {"path": "basic.j2"}
}'
```

Make sure it is correctly created and note down its id:

```
CONFIGTEMPLATE_ID=1
```

Please replace with the id of the created object.

7. Sync this new config template:

```
curl -X POST \
-H "Authorization: Token $TOKEN" \
-H "Content-Type: application/json" \
-H "Accept: application/json; indent=4" \
$NETBOX_URL/api/extras/config-templates/$CONFIGTEMPLATE_ID/sync/
```

Now, the config template can be used on a device or device-role.

### Expected Behavior

At step 6, I expect `data_file` to be correctly populated in the JSON data of the POST response. I should get:

```
{
    ...
    "data_file": {
        ...
        "path": "basic.j2"
    },
    ...
}
```

### Observed Behavior

At step 6, the JSON data I'm really receiving in the POST response is:

```
{
    ...
    "data_file": null,
    ...
}
```

**Comment by desnoe** [comment] 2023-08-18 07:52
Check this link for the discussion on Slack:
https://netdev-community.slack.com/archives/C01P0FRSXRV/p1692216027078659

**Comment by jeremystretch** [comment] 2023-08-21 13:15
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment] 2023-08-28 18:02
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.

**Comment by desnoe** [comment] 2023-09-14 15:33
I have added more details to reproduce the problem, step by step, and I hope this will be clear enough. Could you please reopen this issue ?

I also have a bugfix ready.

**Comment by jeremystretch** [comment] 2023-09-21 19:19
This occurs because the `data_source` and `data_file` fields on ConfigTemplateSerializer are read-only. I can't say at this point what the reasoning was for preventing write operations to these fields.

@desnoe I'll assign this to you as you mention having a fix prepared. Thanks!

**Comment by desnoe** [comment] 2023-09-22 16:19
Thanks Jeremy. I just opened a PR.
`data_source` is not read-only in ConfigTemplateSerializer  and is already working fine through the API.
I only modified `data_file`which was read-only.

**Comment by jeremystretch** [comment] 2023-09-25 17:32
> I only modified `data_file` which was read-only, `data_source` is not read-only in ConfigTemplateSerializer and is already working fine through the API.

My mistake, I must have misread the code.

**Closed** 2023-09-25 17:33 UTC
Labels: type: bug, status: accepted, severity: medium
