### ISSUE TITLE
URLs for devices on Front/Rear rack does not persist protocol

### ISSUE THREAD

**Issue by DSpeichert** [netbox-community/netbox#4739] opened 2020-06-10 00:48 UTC
### Environment
* Python version: Python 3.7.7
* NetBox version: 8c15eb0d4d28 (v2.8.5)

### Steps to Reproduce
1. Add any device to a rack
2. Click on the device on the rack visualization (at the RU)
3. You jump from a `https://` to `http://`

### Expected Behavior
Link should be relative or take protocol into account.

### Observed Behavior
Netbox generates an absolute link but using `http://` when the current protocol in use is `https://`.

I deployed using https://github.com/netbox-community/netbox-docker and run TLS using [hitch proxy](https://github.com/netbox-community/netbox-docker/wiki/TLS). I looked through configuration and there is no documented "Base URL" option that I could configure to make Netbox generate correct URLs.

I think it would be easiest to just use relative URL there as well.

**Comment by jeremystretch** [comment] 2020-06-10 02:28
Another duplicate of #4526. Your HTTP frontend must be configured to forward the protocol to the WSGI worker.

**Closed by jeremystretch** 2020-06-10 02:28 UTC
