### ISSUE TITLE
Color mode does not take system theme in consideration after initial load

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#12330] opened 2023-04-24 08:58 UTC
### NetBox version

v3.4.8

### Python version

3.10

### Steps to Reproduce

1. Set system theme to dark
2. Clear brower cache and local storage
3. Notice the UI shows dark
4. Change the system theme to light
5. No change is seen on the UI

### Expected Behavior

Theme should work with system theme if user prefers it

### Observed Behavior

Theme discards user preference

**Comment by abhi1693** [comment] 2023-04-24 09:00
I have solved this issue in https://github.com/netbox-community/netbox/tree/fix/color-mode by introducing a new preference called `system`, when set uses the system theme else uses whatever the user prefers from light or dark. Note that this also considerably reduces the logic as well simplififying the underlying code.

Currently, the branch is built using feature as it introduces a new variable.

**Comment by arthanson** [comment] 2023-06-27 15:49
@abhi1693 assigning to you as it looks like you have a PR

**Comment by jeremystretch** [comment] 2023-12-14 16:38
Marking this as blocked by #12128

**Comment by arthanson** [comment] 2024-01-24 20:45
I think this is a non bug, you have to actually have to clear out "cookies and other site data" for this to work with the reproduction steps above.  Doing so will cause you to be logged out and removes the cookie settings, if you refresh the page you will see that you have to log back in and then can change the light/dark mode.

**Closed** 2024-04-11 15:37 UTC
Labels: type: bug, status: blocked, topic: UI/UX, severity: low
