### ISSUE TITLE
"Create and add another" - Rack Position not accepted

### ISSUE THREAD

**Issue by joni1993** [netbox-community/netbox#5492] opened 2020-12-18 11:07 UTC
### Environment
* Python version: 3.6.9
* NetBox version: v2.10.1

### Steps to Reproduce
1. Add Device to Rack Position
2. Fill out as needed
3. Select Rack Position
4. Add Device via "Create and Add another" button
5. Object ist created, form open again
6. Select available rack position
7. Try to create Object (either "Create" or "Create and Add Another"
8. Form complains on Rack position "Select a valid choice. XX is not one of the available choices." (Where XX is chosen position number)

### Observed Behavior
"Create and Add Another" Button should not 

### Workaround
Don't use the "Create and Add Another" button - Instead use Create, use the browser back button and submit the form again with updated position

**Comment by DanSheps** [comment] 2020-12-18 14:12
Have you added the rack face?  If you set a rack position you also need to set a rack face.  If not, you get a less then helpful message relating to the position however it is the face that is the problem.

**Comment by joni1993** [comment] 2020-12-18 14:53
Ok thats odd - i didn't noticed the rack face gets unset on "add another". Either the error message should be more clear or the face should not get reset.

**Comment by jeremystretch** [comment] 2020-12-18 14:55
> Either the error message should be more clear or the face should not get reset.

I haven't checked the behavior myself, but it sounds like a bug. Let's keep this issue open.

**Comment by DanSheps** [comment] 2020-12-18 15:05
Duplicate of #5301

**Closed by DanSheps** 2020-12-18 15:05 UTC
