### ISSUE TITLE
Nested Module Bays?

### ISSUE THREAD

**Issue by dar72** [netbox-community/netbox#12884] opened 2023-06-13 14:46 UTC
### NetBox version

v3.5.3

### Feature type

New functionality

### Proposed functionality

Is it possible to add the functionality to devices to have nested module bays?

This would be allowing a module to have a module bay of its own to mount another module into, this combination would then in turn be mounted into a device which also has a module bay.

This is for chassis routers, eg Juniper MX series

### Use case

We use MPCE Type 2 3D (750-038491) cards in Juniper MX routers, these contain up to two MIC (750-049846) cards to provide the interfaces.

It seems the only way to properly represent this is to have the ability to have the MPCE card as a module to add to the MX router and that MPCE module to also have module bays, then MIC cards can be represented by a module which can be added to the MPCE module which is already part of the MX.

Routing engines also work in the same way with the SCBE cards that they go into. I'm sure other vendors have similar things in chassis devices.

**Comment by DanSheps** [comment] 2023-06-14 16:51
Duplicate of #10500

**Closed by DanSheps** 2023-06-14 16:51 UTC
Labels: type: feature
