### ISSUE TITLE
Menu collapse behavior change (in 4.0 vs 3.7)

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#16074] opened 2024-05-10 07:48 UTC
### NetBox version

v4.0.1

### Feature type

Change to existing functionality

### Proposed functionality

In v3, the menu collapsed when another main menu item was selected.
in v4 all submenu's remain open
This causes a very inefficient UI experience.

### Use case

navigating the menu has become more click/scroll heavy.
As you mentioned in #15814, this change in behavior was done intentionally.

I would propose to either
- return the v3 behavior
- add a 'quicksearch' to the top of the navigation bar, so quickly look for submenu items and auto collapse/expand the menu's

**Comment by arthanson** [comment] 2024-05-10 16:13
Closing as dupe of #15614

**Comment by PieterL75** [comment] 2024-05-10 21:15
@arthanson I think you miss interpreted my request.
This is not about the menu bar siding left/right
But about the sub menu opening and closing. 

Can you please review my FR?

Pieter

**Comment by arthanson** [comment] 2024-05-10 21:32
ah okay, that makes sense.

**Comment by rhcinos** [comment] 2024-05-28 13:06
I like the idea of a search box.
Another option might be for a user preference to switch between tab collapse modes.

**Comment by jeremystretch** [comment] 2024-06-04 13:55
I'm going to close this as redundant to #16392, which (despite being opened more recently) better captures the proposed change and work to be done.

**Closed by jeremystretch** 2024-06-04 13:55 UTC
Labels: type: feature, status: under review, complexity: medium
