### ISSUE TITLE
Azure SSO not working in maintenance mode / HA setup with Postgres in read-only mode

### ISSUE THREAD

**Issue by bsmout** [netbox-community/netbox#15746] opened 2024-04-17 10:46 UTC
### Deployment Type

Self-hosted

### NetBox Version

v3.7.5

### Python Version

3.11

### Steps to Reproduce

Netbox Docker with Azure configure as SSO provider as documented here: https://docs.netbox.dev/en/stable/administration/authentication/microsoft-azure-ad/

SSO works fine on the primary Netbox server. When streaming Postgresql to a 2nd instance with the Postgresql in read-only mode and Netbox in maintenance mode local accounts work fine but the SSO is broken. 

As soon as I put the database in R/W SSO works (with Netbox still in maintenance mode).

### Expected Behavior

Be able to login with both local and SSO accounts when the DB is in Read-Only mode and Netbox in maintenance mode.

### Observed Behavior

The following error is thrown:

<class 'social_core.exceptions.AuthMissingParameter'>

Missing needed parameter state

**Comment by jeffgdotorg** [comment] 2024-04-18 23:29
Thanks for reporting a problem you've encountered with NetBox.

Since our team has to be able to reproduce the problem before we'll be able to confirm this bug, and since streaming PostgreSQL can be set up in more than one way, we need more detail in the *Steps to Reproduce* portion of your issue body. Please edit the body and decompose that section, which is currently a summary, into detailed steps. It needs to start with a freshly installed system, and be written so that a person familiar with PostgreSQL, but *not* familiar with streaming replication, can follow them and arrive at the same unexpected behavior you're seeing.

**Comment by jeremystretch** [comment] 2024-05-17 12:47
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.

**Closed by jeremystretch** 2024-05-17 12:47 UTC
Labels: type: bug, status: revisions needed
