### ISSUE TITLE
PATCH requests to cable-terminations do not update the old endpoint

### ISSUE THREAD

**Issue by SheffSix** [netbox-community/netbox#12023] opened 2023-03-21 12:21 UTC
### NetBox version

v3.4.6

### Python version

3.8

### Steps to Reproduce

I came across bug #11901 (although I am working with front ports not interfaces), and had the idea of sending the PATCH/PUT to /dcim/cable-terminations/{id} directly instead of the cable.

The results are an imporovement, but still has to problem that the old endpoint still thinks it is connected to the cable.

Steps to reproduce:

- create three devices
- Create three rear ports and three front ports, one of each for each device
- create a cable connection between two of the devices' front ports
- request an API PATCH HTTP request to change the device and port of b termination to the third device.

### Expected Behavior

The cable is moved from port two to port three, and there are no references to the cable on port two

### Observed Behavior

Looking at the properties of the cable, it shows that it is connected to ports one and three as expected.

However, from the front port view, port two still reports as being connected to the cable as well as ports one and three.

**Comment by jozefws** [comment] 2023-03-24 17:08
Duplicate of #11901 :)

**Comment by jsenecal** [comment] 2023-07-05 19:53
> Duplicate of #11901 :)

It isnt.

**Comment by arthanson** [comment] 2023-09-06 00:16
I repro #11901 but not this one, regardless I think https://github.com/netbox-community/netbox/pull/13337 will fix this as well.

**Closed** 2023-09-26 17:16 UTC
Labels: type: bug, status: accepted, topic: cabling, severity: medium

**Comment by jeremystretch** [comment] 2023-09-26 18:26
I was not able to reproduce this on v3.6.2 (prior to the merger of PR #13337). It was likely resolved by some other change in a more recent release.
