### ISSUE TITLE
Quick search does not search all columns in the lists. (Unreliable search)

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#9541] opened 2022-06-15 14:43 UTC
### NetBox version

v3.2.4

### Python version

3.10

### Steps to Reproduce

Example 1:
- Go to Organization --> Locations
- Use the "Quick search" filter, search for something in the Tags column.
= No result found, although this is available.

Example 2:
- Create a device and associate it with an IP address.
- Open the IPAM --> IP Addresses list.
- Visable the Devices column
- Use the "Quick search" filter to search for the device.
= No result found, although this is available.

Example 3:
- Go to Devices --> Devices
- Use the "Quick search" filter, search for something in the Role column.
= No result found, although this is available.

### Expected Behavior

That everything is found that is also displayed in the table.

### Observed Behavior

In general, I have already noticed that the Quicksearch omits many columns. 

This leads to questions: Is there no entry or does Netbox ignore the entry.
The user has to search and check whether Quicksearch ignores things or works correctly.

**Comment by jeremystretch** [comment] 2022-06-17 18:59
There is no effective difference between using the "quick search" field above a table and the search box under the filters tab: They both employ the exact same logic behind the scenes, which has no knowledge about what columns are being displayed in the results table. Additionally, searching is a balancing act: Searching on too many fields or matching too liberally will result in excessive undesired results, reducing the utility of the search function overall.

As this is working as intended, I'm going to close this bug report. However, if you would like to propose specific extensions or modifications to the search logic for specific objects, you're certainly welcome to do so in a feature request.

**Closed by jeremystretch** 2022-06-17 18:59 UTC
Labels: type: bug
