### ISSUE TITLE
Poor performance in Safari with long lists of items

### ISSUE THREAD

**Issue by abrahamvegh** [netbox-community/netbox#17117] opened 2024-08-09 19:31 UTC
### Deployment Type

Self-hosted

### NetBox Version

4.0.8

### Python Version

3.11

### Steps to Reproduce

1. Access any long list of items (reproducible for me on the demo instance, [example](https://demo.netbox.dev/ipam/ip-addresses/))
2. Scroll the list

### Expected Behavior

The list should scroll as performantly as it did prior to 4.x, with no stuttering and without hanging the browser. The browser scroll bar should update with the scroll position.

### Observed Behavior

Screenshot below has part of the story, but there's just some really strange performance issues with lists that cause my browser (non-beta Safari on non-beta macOS, latest) to hang when scrolling, but also to hang when I switch from another tab back to the tab with the list in it.

<img width="2672" alt="Screenshot 2024-08-09 at 3 22 17 PM" src="https://github.com/user-attachments/assets/9c31fb1e-84e7-4a03-933a-e0adf40a717e">

I’ve been seeing this since 4.x with the UI refresh, haven't had time to write it up until now/was hoping somebody else was running into this and it would get solved, but it seems like it's ongoing. 😅

**Comment by jeremystretch** [comment] 2024-08-10 13:51
This is a known issue with the Safari browser; the issue has not been reproducible in Chrome or Firefox.

If you would like to propose a specific change in NetBox to work around the bug in Safari we're happy to try it.

**Comment by coelho** [comment] 2024-08-10 23:38
@jeremystretch I'm not sure that we can conclude that until the issue is diagnosed. 

Netbox may for example have a bug that is causing excess manipulations to the DOM that, sure, other browsers play nice with performance-wise, but is still unintentional behavior indicative of a bug in Netbox itself.

**Comment by jeremystretch** [comment] 2024-08-11 12:48
@coelho would you like to volunteer to investigate this issue?

**Comment by coelho** [comment] 2024-08-12 23:04
@jeremystretch It may be more efficient from someone who has an understanding of the frontend UI code. I might give it a stab via process of elimination if I have more time, but Safari developer tools were not useful from my initial investigation.

**Comment by abrahamvegh** [comment] 2024-08-12 23:58
@jeremystretch please assign this to me, it drives me nuts, I will investigate to the best of my abilities.

**Comment by jeremystretch** [comment] 2024-08-13 11:43
@abrahamvegh this issue cannot be assigned for work until a bug in NetBox itself has been confirmed. So far, no one has been able to point to a specific change in NetBox that would likely resolve the issue. (Again, this issue is only reproducible in Safari.)

**Comment by coelho** [comment] 2024-08-22 11:50
@jeremystretch @abrahamvegh Issue is resolved on my end by applying the following CSS:

```
.table-responsive {
    overflow-x: visible !important;
}
```

**Additional Notes**
The bug is caused by the `dropdown-toggle`s inside the `table-responsive`, and the use of transform in their CSS:

```
.table-responsive {
    overflow-x: auto;
}
.dropdown-toggle:after {
    transform: rotate(-45deg);
}
```

I did not test if there are more variables that cause this bug to occur, but I did test that if you remove either CSS, the performance issues are resolved. I settled on removing `overflow-x: auto;`, as it seems to have no functional impact besides a minor cosmetic change.

**Comment by jeremystretch** [comment] 2024-08-22 12:23
Thanks for tracking that down @coelho. I'll open this up for anyone who would like to work on it and can confirm that it fixes the issue in Safari.

> it seems to have no functional impact besides a minor cosmetic change.

What is the cosmetic change?

**Comment by coelho** [comment] 2024-08-22 12:39
@jeremystretch 

### Before (with `overflow-x: auto;`):

![cwoEnIUito=](https://github.com/user-attachments/assets/45653de8-c586-4f4b-a056-d535af6e93dc)
![rvU5SNZCGScO5AJK3RZQvByKhYs=](https://github.com/user-attachments/assets/8c042228-d39e-4089-b18f-f4d3e607bce2)

### After (with `overflow-x: visible;`):

![O8I=](https://github.com/user-attachments/assets/77641d1e-1e19-429e-822b-6d5646304c82)
![yajXPVLT0e2dKU1RjdN7UwHeLPQ=](https://github.com/user-attachments/assets/4259080a-ad23-4ba9-a467-dfdb529c478f)

**Comment by jeremystretch** [comment] 2024-08-22 12:47
Ha, ok. So that's not what I'd call a minor cosmetic change; I'd call that broken. Seems like we've identified the root cause but we'll need to come up with a workable fix.

Also:

```
.dropdown-toggle:after {
    transform: rotate(-45deg);
}
```

I've not dug into the CSS yet, but it's not clear to me what purpose this bit serves. If it contributes to the bug, it can likely be negated without any ill effects.

**Comment by abrahamvegh** [comment] 2024-08-22 13:40
Amazing work @coelho, I couldn’t figure this out at all!

Validating your fix, just disabling the transform was enough to solve the obvious performance issues for me on Safari.

The only oddity I noticed as a result was the navigation dropdowns were no longer rotated 45 degrees, but overall this seems like a pretty simple fix, and makes logical sense to me.

<img width="1728" alt="Screenshot 2024-08-22 at 9 37 51 AM" src="https://github.com/user-attachments/assets/84e785f1-42e1-4484-aa2b-778aa7e59895">

**Comment by arthanson** [comment] 2024-08-22 17:17
@abrahamvegh can you please take a look at PR #17246 and try the fix to see if it addresses the performance issue for you?

**Comment by abrahamvegh** [comment] 2024-08-23 14:19
Confirmed with production patch and testing, #17246 fixes the performance issue!

I will note HTML entity caret is not visually pleasing, but that sounds like a separate issue. 😅

**Comment by jeremystretch** [comment] 2024-08-23 15:51
> I will note HTML entity caret is not visually pleasing, but that sounds like a separate issue.

@abrahamvegh could you post a screenshot of what it looks like for you? Feels like this may be an OS/browser-dependent thing we'll need to avoid. :confused:

**Comment by abrahamvegh** [comment] 2024-08-23 15:55
> > I will note HTML entity caret is not visually pleasing, but that sounds like a separate issue.
> 
> @abrahamvegh could you post a screenshot of what it looks like for you? Feels like this may be an OS/browser-dependent thing we'll need to avoid. 😕
<img width="107" alt="Screenshot 2024-08-23 at 11 54 33 AM" src="https://github.com/user-attachments/assets/841b179f-9d1e-4066-8883-817721bddc96">
<img width="285" alt="Screenshot 2024-08-23 at 11 54 20 AM" src="https://github.com/user-attachments/assets/202880d5-bf49-42ed-bcf6-986ded3ededd">

**Comment by DanSheps** [comment] 2024-08-25 21:03
IMO, and this is just my opinion, while we can easily work around this with Arthur's fix, this really should be something that is tackled on the Safari end (it is not a NetBox bug in my view)

**Comment by coelho** [comment] 2024-08-25 21:12
@DanSheps While I agree this is a bug in Safari, it is a question of incentives.

- Does Apple have an incentive to quickly resolve a bug where Netbox is one of the only apps affected? Besides a matter of correctness, not really.
- Does Netbox have an incentive to allow Apple users (who may be paying 5 figures in major enterprises) to have a seamless experience? I do believe so.

It would be disappointing for potential customers of Netbox Labs to see the blame shifting that has occurred in this ticket.

**Comment by abrahamvegh** [comment] 2024-08-25 21:27
> IMO, and this is just my opinion, while we can easily work around this with Arthur's fix, this really should be something that is tackled on the Safari end (it is not a NetBox bug in my view).

@DanSheps while I would wholly agree with @coelho here, there is also the matter that this problem did not exist prior to 4.x, which in my opinion makes it a NetBox regression before it makes it anything else.

I will also add that having manually applied this patch to my production instance has considerably increased my quality of life. 😃

**Comment by DanSheps** [comment] 2024-08-26 01:55
> This argument is not convincing to me. You are basically saying "because it does not affect me, I am not concerned with other's user experience."

I am not saying we shouldn't be concerned with it but I am saying someone, who is not me because I don't use Safari or Apple products and cannot accurately describe the bug, should open a bug report with Safari to get it fixed there.  My whole point is that ultimately this is a Safari bug and should be fixed on their end.  That doesn't preclude us from merging our fix, but we shouldn't just not do something about the Safari piece as well, it is just that I cannot because I haven't observed the bug first hand.

**Comment by coelho** [comment] 2024-08-26 11:38
@DanSheps I agree. Thank you for your well worded reply and your civility 🥇

Possibly we should report to / check WebKit bug tracker? We'd need to make a minimal test case in order to file a bug, which might be substantially more effort than the PR.

**Closed** 2024-08-26 19:36 UTC
Labels: type: bug, status: accepted, severity: low
