### ISSUE TITLE
Inconsistencies in circuit connection/addressing indication

### ISSUE THREAD

**Issue by abrahamvegh** [netbox-community/netbox#4625] opened 2020-05-11 16:05 UTC
### Environment
* Python version: 3.7.3
* NetBox version: 2.8.3

### Steps to Reproduce
1. Create a Circuit
2. Create a Device with two Interfaces
3. Create and assign an IP address to each Interface (e.g. `203.0.113.1/24`, `198.51.100.1/24`)
4. Create Circuit Terminations for both sides of the Circuit in the same Site as the Device
5. Connect both sides of the Circuit to each of the Interfaces on the Device

### Expected Behavior
On the Circuit view, each termination should display the connected Interface, and the IP addresses present on that interface.

### Observed Behavior
In my test case, the A side displayed everything as expected, but the Z side did not show the connected device name or interface, nor the IP addresses. If I swapped the terminations on the Circuit view, the Z side then showed everything correctly, and then the A side shows nothing (other than the cable).

### Notes
In my test case, I use a single device and terminate the Circuit to two interfaces, but I noticed this issue in production circuits (between devices in different Sites with cables and front/rear ports between them, etc.) before creating the test case specifically to see if I was doing something wrong or if something was actually broken. There may be additional more complex behavior that is broken beyond the simplest concept I tested here.

**Comment by DanSheps** [comment] 2020-05-11 18:56
Duplicate of #4619

**Closed by DanSheps** 2020-05-11 18:56 UTC

**Comment by DanSheps** [comment] 2020-05-11 18:58
It looks like the root cause is it is looking form endpoint information, which is not populated on the termination anymore.
