### ISSUE TITLE
Show cluster as mandatory when adding a virtual machine via UI

### ISSUE THREAD

**Issue by empusas** [netbox-community/netbox#13914] opened 2023-09-27 12:51 UTC
### NetBox version

v3.6.3

### Python version

3.11

### Steps to Reproduce

This is just a little cosmetic, but bothers me for a while. The Cluster is not shown as mandatory field in the VM creation form.

### Expected Behavior

I would expect all mandatory fields marked bold and with a *

### Observed Behavior

In the VM creation form the cluster seems like an optional field.

**Comment by arthanson** [comment] 2023-09-27 15:23
It is a bit different in this case as either a site or cluster needs to be given (so cluster is optional if a site is given).  Perhaps some help text under those fields stating that might be useful.

**Comment by empusas** [comment] 2023-09-28 06:40
agree, but this little change would help users to understand.

**Comment by jeremystretch** [comment] 2023-10-02 12:52
@empusas I think you misunderstood @arthanson's point. The cluser field is **not** mandatory for virtual machines, because a VM may be assigned to either a cluster _or_ to a device. Displaying it as a mandatory field (akin to the name or status fields) would be misleading and confusing. So what specific change are you proposing?

(Also, reclassifying this as an enhancement as it's not a bug.)

**Comment by jeremystretch** [comment] 2023-11-06 18:22
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.

**Closed by jeremystretch** 2023-11-06 18:22 UTC
Labels: type: feature, status: revisions needed
