### ISSUE TITLE
`TemplateDoesNotExist` exception after adding `Tags` column to IP address view

### ISSUE THREAD

**Issue by tacerus** [netbox-community/netbox#8204] opened 2022-01-02 18:08 UTC
### NetBox version

v3.1.3

### Python version

3.9

### Steps to Reproduce

**To reproduce the issue on a fresh instance:**
1. Click IPAM -> "IP addresses" in the sidebar
2. Click "Add"
3. Fill the fields with arbitrary, compliant, values and click "Apply"
5. Click Other -> "Tags" in the sidebar
6. Click "Add"
7. Fill the fields with arbitrary, compliant, values and click "Apply"
8. Click IPAM -> "IP addresses"
9. Select the IP address created with Steps 1-3
10. Click "Select Add tags"
11. Select the tag created with Steps 4-6 and click "Apply"
12. Click "Configure Table"
13. Select "Tags" in "Available columns"
14. Click "Add", then "Save"

At this point, `/ipam/ip-addresses/` is no longer accessible, with the exception shown below being displayed.

**To regain access:**
1. Find "Editing 1 IP Address" in the browser history, and navigate to it
2. In case the browser displays the tag created with Steps 4-6 in the box next to "Add tags", click the "x" next to the tag
3. Click "Select Remove tags"
4. Select the tag created with Steps 4-6 and click "Apply"
_The following steps are optional, but recommended:_
6. Click "Configure Table"
7. Select "Tags" in "Selected columns"
8. Click "Remove", then "Save"

**Workarounds:**
A) Do not assign tags to IP addresses
B) Do not enable the "Tags" column

### Expected Behavior

The overview on `/ipam/ip-addresses/` should display the IP addresses with an added "Tags" column. This column should display the created tags in the rows of the IP addresses they were assigned to, and show "-" in the rows of IP addresses they were not assigned to.

### Observed Behavior

The application displays a Server Error page, with the following exception:

```
<class 'django.template.exceptions.TemplateDoesNotExist'>

utilities/templatetags/tag.html
```

**Comment by tacerus** [comment] 2022-01-02 18:14
This may or may not be related: #8187

**Comment by DanSheps** [comment] 2022-01-02 22:07
Duplicate of #8187

**Closed** 2022-01-02 22:08 UTC
Labels: type: bug
