### ISSUE TITLE
Scripts are not increasing counter for device components like power ports and inventory items

### ISSUE THREAD

**Issue by cichutkiii** [netbox-community/netbox#14446] opened 2023-12-06 10:14 UTC
### NetBox version

v3.6.4

### Python version

3.8

### Steps to Reproduce

1. create 1 random items for power ports and inventory items.
2. run script which will create items in inventory items and power ports
3. delete manually items 

### Expected Behavior

counter should count newly added items by script

### Observed Behavior

counter is not working while running script
And while removing items I'm getting to the situation when I have counter below 0

![image](https://github.com/netbox-community/netbox/assets/823614/ae6146ee-9796-4687-bf72-9ac6e59708b2)

**Comment by jeremystretch** [comment] 2023-12-06 13:37
> 2. run script which will create items in inventory items and power ports

Please share the script that someone else can run locally to reproduce the reported behavior.

**Comment by jeremystretch** [comment] 2023-12-26 14:48
I'm not able to reproduce the reported behavior on NetBox v3.6.7. It has likely been addressed in the latest release by #14081. Please try upgrading, and ask that this issue be re-opened if you find that the bug persists.

**Closed by jeremystretch** 2023-12-26 14:48 UTC
Labels: type: bug, status: under review

**Comment by rizlas** [comment] 2023-12-28 13:45
The bug persists. I just upgraded to v3.6.8 and inventory items count still wrong. I'm also updating via scripts.

```
def create_inventory_item(component: dict, parent: InventoryItem = None):
    nb_item, _ = InventoryItem.objects.get_or_create(
        device=self.device_object,
        name=component["name"],
    )

    self.obj_snapshot(nb_item)

    nb_item.description = component["description"]
    nb_item.part_id = component["part_number"]
    nb_item.serial = component["serial_number"]

    if parent:
        nb_item.parent = parent

    nb_item.tags.add(self.inventory_common_tag)

    nb_item.full_clean()
    nb_item.save()

    return nb_item
```

Even if I remove all the inventory items before creation, counter remains wrong.

`InventoryItem.objects.filter(device=self.device_object).delete()`

**Comment by kkthxbye-code** [comment] 2023-12-28 14:14
@rizlas - The issue is, at least in @cichutkiii example, is that the device is saved after the inventoryitem is added.

So a script like this (simplified from the earlier example) will make the count bug:

```
inv_role = InventoryItemRole.objects.get(name='Ethernet Card')
inv_item = InventoryItem(
   name = "nane",
   label = "label",
   device_id = device.id,
   serial = "serial",
   role = inv_role,
)

inv_item.full_clean()
inv_item.save()

# Everything is fine here

device.asset_tag = "test"
device.full_clean()

# This device is stale, as when the above inventory item was created, the device _inventory_item_count (or whatever it's called) was modified by netbox.
device.save() 
```

Instead the end would have to be:

```
device.refresh_from_db() # Get the non-stale device
device.asset_tag = "test"
device.full_clean()
device.save() 
```

I guess another option would be to use the `update_fields` argument to the save call, to omit updating the count fields.

This is not a bug in netbox, however it is bad practice and not intuitive to modify fields on other objects in a non-obvious way. I wouldn't count on it changing, so you have to update your scripts.

**Comment by rizlas** [comment] 2023-12-28 14:51
I wasn't aware of [refresh_from_db](https://docs.djangoproject.com/en/5.0/ref/models/instances/#refreshing-objects-from-database). Fine to me, make sense. But, I just tested your and the counter it still wrong.

> **_NOTE:_** inventory items counter isn't wrong in all netbox, but as of now, only for one device in the entire inventory.

This was my approach before testing your solution:

- Device creation, update his attributes and save
- Create other netbox objects (e.g. inventory items) referencing the entire device object (e.g. device=self.device_object)

After your suggestion:

- Device creation, update his attributes
- Create other netbox objects (e.g. inventory items) referencing the entire device object (e.g. device=self.device_object)
- Saving the object this way:

```
self.device_object.refresh_from_db()
self.device_object.full_clean()
self.device_object.save()
```

Nothing changed

**Comment by rizlas** [comment] 2023-12-28 14:56
Thats my situation, as you can see I've inventory items but no "Inventory Items" tab.

![image psd](https://github.com/netbox-community/netbox/assets/8522635/737ce9dd-ce81-4bb8-ac72-943d236f7e5d)
