### ISSUE TITLE
Reverse for 'clearcache_admin' not found

### ISSUE THREAD

**Issue by gfvh** [netbox-community/netbox#15965] opened 2024-05-06 14:05 UTC
### Deployment Type

Self-hosted

### NetBox Version

v3.7.1

### Python Version

3.11

### Steps to Reproduce

netbox admin url netbox.somedomain.com/admin gives this error:

> <class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'clearcache_admin' not found. 'clearcache_admin' is not a valid view function or pattern name.

Python version: 3.11.2
NetBox version: 3.7.1
Plugins: 
  netbox_attachments: 4.0.2
  netbox_ipcalculator: 1.1
  netbox_proxbox: 0.0.5
  netbox_qrcode: 0.0.11
  netbox_topology_views: 3.9.0
  
[netbox_admin.log](https://github.com/netbox-community/netbox/files/15221640/netbox_admin.log)

### Expected Behavior

admin web gui to open properly?

### Observed Behavior

Reverse for 'clearcache_admin' not found. 'clearcache_admin' is not a valid view function or pattern name.

**Comment by arthanson** [comment] 2024-05-06 14:27
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.7.8. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

I think this might possibly be related to one of the plugins you have installed, can you please comment out the plugins in configuration.py and see if that works.  If so you can add them back one at a time to see which is causing the issue.

**Comment by jeremystretch** [comment] 2024-05-06 14:31
FYI `clearcache_admin` appears to reference something in one of your plugins or an external dependency. It is not part of the code NetBox code base.

**Comment by gfvh** [comment] 2024-05-06 14:52
I found out that this is caused by django-clearcache package. I installed it with pip3 install django-clearcache to clear cache. Right now i did uninstall: pip uninstall django-clearcache. Issue is fixed. Admin url opens

**Comment by arthanson** [comment] 2024-05-06 15:01
closing

**Closed by arthanson** 2024-05-06 15:01 UTC
Labels: type: bug, status: revisions needed
