### ISSUE TITLE
VM creation via GUI or Script

### ISSUE THREAD

**Issue by c4lidos** [netbox-community/netbox#10088] opened 2022-08-22 13:16 UTC
### NetBox version

v3.3.0

### Python version

3.8

### Steps to Reproduce

go to https://netbox.ibi-berlin.de/virtualization/virtual-machines/add/  create an new VM.
or try to create an vm via community script
https://github.com/netbox-community/reports/blob/master/scripts/create_vm.py

### Expected Behavior

Should take the Site from the Device and/or Cluster

### Observed Behavior

**GUI**
The Selected cluster (xxx is not assigned to this site(none).
![netbox_vm_create_cluster (2)](https://user-images.githubusercontent.com/61190734/185928982-2fd31bf6-3aa6-4386-a044-c2aa327ccb2c.png)
**Skript:**
An exception occurred: ValidationError: {'cluster': ['The selected cluster (xxx is not assigned to this site (None).']}

Traceback (most recent call last):
  File "/opt/netbox-3.3.0/netbox/extras/scripts.py", line 460, in _run_script
    script.output = script.run(data=data, commit=commit)
  File "/opt/netbox-3.3.0/netbox/scripts/create_vm.py", line 58, in run
    vm.full_clean()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/base.py", line 1405, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'cluster': ['The selected cluster (xxx is not assigned to this site (None).']}

**Comment by jeremystretch** [comment] 2022-08-22 13:32
I've closed this issue because you have not provided suitable reproduction steps per the bug report template. You're welcome to revise your issue so that it meets out standards for acceptance, at which point you may request that it be re-opened.

**Closed by jeremystretch** 2022-08-22 13:32 UTC
Labels: type: bug

**Comment by c4lidos** [comment] 2022-08-23 07:40
I hope the report meet the requirements now. I looked in some other bug reports with less detailed steps and without screenshots.  Please advise if it still doesn't fit.
