### ISSUE TITLE
Images Preview Pop-Up Removed in 3.5.1?

### ISSUE THREAD

**Issue by glnengineer** [netbox-community/netbox#12627] opened 2023-05-16 12:01 UTC
### NetBox version

v3.5.1

### Python version

3.9

### Steps to Reproduce

* Create a site with the name testsite and slug testsite
* Go to the site and upload any image
* Hover over the image link

### Expected Behavior

An image preview should pop up.

### Observed Behavior

Nothing happens.

**Comment by kkthxbye-code** [comment] 2023-05-16 12:10
Caused by https://github.com/netbox-community/netbox/pull/12487

@abhi1693 - could you take a look.

**Comment by abhi1693** [comment] 2023-05-16 12:18
@kkthxbye-code I'm on vacation this week, but I suspect this will require changes to `ImageAttachmentTable` using a template code

**Comment by jeremystretch** [comment] 2023-05-16 12:20
Sorry, I missed this as well. We can probably just change the primary table column to a TemplateColumn that restores the pop-up on hover.

**Comment by abhi1693** [comment] 2023-05-25 17:44
So, when applying the template code to enable image preview, it works on the image attachment list page, but does not work when the table is called via hx calls. I'm not sure why that is at the moment.

**Comment by kkthxbye-code** [comment] 2023-05-25 17:48
@abhi1693 - Eventlisteners are lost when HTMX replaces the HTML. You probably have to add a call to initImagePreview here:

https://github.com/netbox-community/netbox/blob/bf1c191b2e9a52ecb122d3e4c456b9be3bcfa032/netbox/project-static/src/htmx.ts#L7

https://github.com/netbox-community/netbox/blob/bf1c191b2e9a52ecb122d3e4c456b9be3bcfa032/netbox/project-static/src/bs.ts#L151

**Comment by abhi1693** [comment] 2023-05-25 17:58
I have already tried that suggestion, it does not seem to be taking any effect. I even tried initializing the whole bootstrap functions via `initBootstrap` but still nothing changed.

**Comment by abhi1693** [comment] 2023-05-25 18:17
I've only been able to make partial change. I'll mark this as needs owner again, as I currently do not know from where to re-add the dependency.

**Comment by kkthxbye-code** [comment] 2023-05-26 10:52
@abhi1693 - Something like this seems to work:

```typescript
/**
 * Hook into HTMX's event system to reinitialize specific native event listeners when HTMX swaps
 * elements.
 */
export function initHtmx(): void {
  for (const element of getElements('[hx-target]')) {
    const targetSelector = element.getAttribute('hx-target');
    if (isTruthy(targetSelector)) {
      for (const target of getElements(targetSelector)) {
        target.addEventListener('htmx:afterSettle', initDepedencies);
      }
    }
  }

+  for (const element of getElements('[hx-trigger=load]')) {
+   element.addEventListener('htmx:afterSettle', initDepedencies);
+  };
}
```

If you want to give it another go. Not sure if this is a proper fix though, the entire re-init logic seems a little messy.

**Comment by abhi1693** [comment] 2023-05-26 11:09
I did some googling around and found that we can use `Set` to remove duplicate elements from being initialized. However, that goes out of scope for this issue. @kkthxbye-code Your solution does seem to work but in case if we want to improve the initialization of elements, that should be taken up as a separate FR.

**Closed** 2023-05-30 13:41 UTC
Labels: type: bug, status: accepted
