### ISSUE TITLE
Asterisk in DNS Name gives error

### ISSUE THREAD

**Issue by CloudZES** [netbox-community/netbox#9482] opened 2022-06-04 21:16 UTC
### NetBox version

v3.2.4

### Python version

3.10

### Steps to Reproduce

1. Go to IP Addresses under IPAM
2. Edit an existing IP address
3. Change DNS Name to include an asterisk and save
4. Receive error

### Expected Behavior

IP address should save with newly updated DNS name including an asterisk in it

### Observed Behavior

Given error "DNS Name | Only alphanumeric characters, asterisks, hyphens, periods, and underscores are allowed in DNS names."

**Comment by kkthxbye-code** [comment] 2022-06-05 21:17
I cannot replicate this on v3.2.4 with the info you have given. If we assume you tried to add the asterisk at any other path than the first character, then what you are seeing is intended.

Please see the discussion here: https://github.com/netbox-community/netbox/pull/8945

And the FR here: https://github.com/netbox-community/netbox/issues/8785

If you want to suggest a change to the current functionality, feel free to  create a feature request. I'll close this as this is not a bug with the current replication steps.

**Closed by kkthxbye-code** 2022-06-05 21:17 UTC
Labels: type: bug
