### ISSUE TITLE
Virtualisation Clusters not matching Scope for VLAN Groups

### ISSUE THREAD

**Issue by maznu** [netbox-community/netbox#6329] opened 2021-05-02 12:08 UTC
### NetBox version

v2.11.2

### Python version

3.7

### Steps to Reproduce

1. Create a Region "UK"
2. Create a VLAN Group "UK" with scope "UK"
3. Create a Virtualisation Cluster in Region "UK"
4. Look at how your Virtualisation Cluster doesn't have a Region (because they can only be in a Location)
5. Be sad that you can't assign Interfaces on VMs in the Cluster to VLANs from the "UK" VLAN Group

### Expected Behavior

* scope a Virtualisation Cluster to a Region (not just a Location)
* subsequently be able to choose VLANs from Groups in that Region

### Observed Behavior

* Virtualisation Cluster did not belong to any Region
* couldn't choose VLANs from Groups in that Region (in our case, actually had no VLANs to choose from when setting VM Interfaces as Access/Tagged)

**Comment by maznu** [comment] 2021-05-02 12:17
Actually this might be a slightly more generic problem: a VM Interface cannot be assigned to a VLAN that is a member of a VLAN Group at all?

**Comment by maznu** [comment] 2021-05-02 12:23
Of course, VLAN Groups _can_ be assigned the scope of a Virtualisation Cluster (or Cluster Group) but then:

* that VLAN Group isn't usable by any physical infrastructure (can't blend Devices and VMs)
* the Devices of the Cluster cannot have Interfaces which have Access/Tagged for those VLANs

**Comment by jeremystretch** [comment] 2021-05-03 15:23
> Look at how your Virtualisation Cluster doesn't have a Region (because they can only be in a Location)

Cluster cant be assigned only to sites. The region dropdown is present only to assist in the selection of a site. This is expected behavior.

> scope a Virtualisation Cluster to a Region (not just a Location)

Please submit a feature request proposing this citing your specific use case.

**Comment by jeremystretch** [comment] 2021-05-04 13:16
Closing this out since there's nothing to under the context of a bug report, but like I said please feel free to open a FR for the proposed change.

**Closed by jeremystretch** 2021-05-04 13:16 UTC
Labels: type: bug
