### ISSUE TITLE
Include snapshots in event data sent to scripts

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [netbox-community/netbox#16268] opened 2024-05-23 18:37 UTC
### NetBox version

v4.0.3

### Feature type

Change to existing functionality

### Proposed functionality

When you set up an event rule and send it to a webhook, the webhook data will include snapshots of pre and post change items of the object. However, when you change to script, you lose the snapshots that made some additional logic possible with webhooks.

I think it would be beneficial if data received to a script contained the same information as a webhook would receive.

### Use case

If you wanted to use pre-change data in a script, you'd have to get that prechange data yourself. Not the end of the world but an unnecessary step. My use case is when adding a tag to a device, it gets added to NAGIOS. The pre and post change fields determine exactly what I need to do without unnecessary API calls to nagios (Checking to see if device exists in nagios or not + other data in nagios)

### Database changes

None

**Comment by DanSheps** [comment] 2024-05-27 18:48
Duplicate of #14884

**Closed** 2024-05-28 20:51 UTC
Labels: status: duplicate
