### ISSUE TITLE
Search page opens up even is login should be required

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#11502] opened 2023-01-14 07:38 UTC
### NetBox version

v3.4.2

### Python version

3.10

### Steps to Reproduce

Without logging in, go to http://localhost:8000/search/ and notice the page opens up

### Expected Behavior

The page should redirect if login is required

### Observed Behavior

Search page opens up
![image](https://user-images.githubusercontent.com/5083532/212461663-fc49980c-179e-4e85-ad58-8733456ca1a4.png)

**Comment by abhi1693** [comment] 2023-01-14 07:38
@jeremystretch If this is accepted, I'd like to take this

**Comment by jeremystretch** [comment] 2023-01-18 20:15
I'm not able to reproduce this on v3.4.2. With `LOGIN_REQUIRED=True`, visiting `/search/` redirects me to `/login/?next=/search/` as a non-authenticated user.

**Comment by abhi1693** [comment] 2023-01-18 21:05
That's weird, I tried on the demo instance and I have the same issue. I believe login is required here

https://demo.netbox.dev/search/

**Comment by kkthxbye-code** [comment] 2023-01-18 21:13
> I believe login is required here

It is not, when you go to the demo site you get the frontpage with all the locks. That is the behavior when LOGIN_REQUIRE is set to False and no EXEMPT_VIEW_PERMISSIONS are set.

**Comment by abhi1693** [comment] 2023-01-18 21:17
I'll try this again tomorrow from my test instance. I may have made a mistake in the configuration that led to this page leak.

**Comment by jeremystretch** [comment] 2023-01-20 17:08
Seems like this is likely a non-issue so I'm going to close it, but @abhi1693 if you find anything new please comment here and I'll re-open it. Thanks!

**Closed by jeremystretch** 2023-01-20 17:08 UTC
Labels: type: bug, status: revisions needed
