### ISSUE TITLE
CSS or javascript bug on browser

### ISSUE THREAD

**Issue by jk-onnet** [netbox-community/netbox#8657] opened 2022-02-16 01:44 UTC
### NetBox version

v3.1.8

### Python version

3.9

### Steps to Reproduce

Having 100 VMs entry.
1. Select the 25 per page.
2. Select second page
3. Click on a virtual machine (e.g. vm48)
4. "Click to go Back" in browser (edge, google chrome)
css style disappear

### Expected Behavior

Normal data UI

### Observed Behavior

![Screenshot 2022-02-16 094134](https://user-images.githubusercontent.com/85537520/154180127-869a538d-37cc-4740-8454-70e7198ff103.png)

**Comment by jeremystretch** [comment] 2022-02-18 20:51
I'm not able to reproduce this on v3.1.8 in either Firefox or Chrome. Your browser seems to be display the HTMX response from paginating the table, but everything I've tried renders the complete page as expected. It may have something to do with your local cache settings.

**Comment by jeremystretch** [comment] 2022-03-24 15:09
Closing this as there's been no further response.

**Closed by jeremystretch** 2022-03-24 15:09 UTC
Labels: type: bug, status: under review
