### ISSUE TITLE
Clicking rack UI for devices results in attempt to resolve localhost

### ISSUE THREAD

**Issue by Smoot178** [netbox-community/netbox#4563] opened 2020-05-01 18:09 UTC
Brand new Netbox environment running on Ubuntu 18.0.4 LTS.

### Environment
* Python version: 2.7.17
* NetBox version: 2.8.1

### Steps to Reproduce
1. Open a rack in the web UI
2. Click an existing device on the "rack visual" UI on the right side.

The link should resolve something like the following:
http://dcim.domain.com:8085/dcim/devices/5/

![image](https://user-images.githubusercontent.com/2719585/80829349-f6d8d100-8bb4-11ea-8047-98a3bce78b59.png)

The link will attempt to resolve something like the following: http://localhost:8085/dcim/devices/5/

![image](https://user-images.githubusercontent.com/2719585/80829306-e294d400-8bb4-11ea-90e7-2585f683d06a.png)

**Comment by joel6890** [comment] 2020-05-01 19:39
We are seeing the same behaviour here since upgrading to Netbox 2.8.1. In our case, the link isn't `localhost` but the IP address of the netbox server itself. For example:

`http://10.50.5.50/dcim/devices/38/`

Rather than `https://netbox.example.com/dcim/devices/38/`

**Comment by jeremystretch** [comment] 2020-05-01 19:42
Duplicate of #4526. Please see my comment [here](https://github.com/netbox-community/netbox/issues/4526#issuecomment-618403170) for how to correct your configuration.

**Closed by jeremystretch** 2020-05-01 19:42 UTC
