### ISSUE TITLE
netbox-rq.service starts failed

### ISSUE THREAD

**Issue by Sivolen** [netbox-community/netbox#12420] opened 2023-05-01 22:38 UTC
### NetBox version

v3.5.0

### Python version

3.8

### Steps to Reproduce

1. Update the netbox for new version
2. Restart netbox and netbox-rq
3. Netbox rq starts failed 

### Expected Behavior

netbox rq starts

### Observed Behavior

Netbox rq starts failed 

May  2 09:33:24 netbox systemd[1]: netbox-rq.service: Scheduled restart job, restart counter is at 36.
May  2 09:33:24 netbox systemd[1]: Stopped NetBox Request Queue Worker.
May  2 09:33:24 netbox systemd[1]: Started NetBox Request Queue Worker.
May  2 09:33:29 netbox python3[3353]: Traceback (most recent call last):
May  2 09:33:29 netbox python3[3353]:   File "/opt/netbox/netbox/manage.py", line 10, in <module>
May  2 09:33:29 netbox python3[3353]:     execute_from_command_line(sys.argv)
May  2 09:33:29 netbox python3[3353]:   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
May  2 09:33:29 netbox python3[3353]:     utility.execute()
May  2 09:33:29 netbox python3[3353]:   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
May  2 09:33:29 netbox python3[3353]:     self.fetch_command(subcommand).run_from_argv(self.argv)
May  2 09:33:29 netbox python3[3353]:   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 279, in fetch_command
May  2 09:33:29 netbox python3[3353]:     klass = load_command_class(app_name, subcommand)
May  2 09:33:29 netbox python3[3353]:   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 48, in load_command_class
May  2 09:33:29 netbox python3[3353]:     module = import_module("%s.management.commands.%s" % (app_name, name))
May  2 09:33:29 netbox python3[3353]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
May  2 09:33:29 netbox python3[3353]:     return _bootstrap._gcd_import(name[level:], package, level)
May  2 09:33:29 netbox python3[3353]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
May  2 09:33:29 netbox python3[3353]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
May  2 09:33:29 netbox python3[3353]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
May  2 09:33:29 netbox python3[3353]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
May  2 09:33:29 netbox python3[3353]:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
May  2 09:33:29 netbox python3[3353]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
May  2 09:33:29 netbox python3[3353]:   File "/opt/netbox/netbox/core/management/commands/rqworker.py", line 3, in <module>
May  2 09:33:29 netbox python3[3353]:     from django_rq.management.commands.rqworker import Command as _Command
May  2 09:33:29 netbox python3[3353]:   File "/opt/netbox/venv/lib/python3.8/site-packages/django_rq/management/commands/rqworker.py", line 5, in <module>
May  2 09:33:29 netbox python3[3353]:     from rq import use_connection
May  2 09:33:29 netbox python3[3353]: ImportError: cannot import name 'use_connection' from 'rq' (/opt/netbox/venv/lib/python3.8/site-packages/rq/__init__.py)
May  2 09:33:30 netbox systemd[1]: netbox-rq.service: Main process exited, code=exited, status=1/FAILURE
May  2 09:33:30 netbox systemd[1]: netbox-rq.service: Failed with result 'exit-code'.

**Comment by abhi1693** [comment] 2023-05-01 22:44
Duplicate of https://github.com/netbox-community/netbox/issues/12415

**Closed by abhi1693** 2023-05-01 22:44 UTC
Labels: type: bug
