### ISSUE TITLE
Add PDF upload capability

### ISSUE THREAD

**Issue by mstoop71** [netbox-community/netbox#11020] opened 2022-11-24 10:49 UTC
### NetBox version

v3.3.7

### Feature type

Change to existing functionality

### Proposed functionality

Add the ability not to just upload images but also PDF or DWG. 

### Use case

Adding the option to add PDF and DWG will enhance the effectiveness for Netbox as the Single Source of Truth.

**Comment by kkthxbye-code** [comment] 2022-11-24 10:56
Hi! Thank you for your feature request. Netbox deliberately doesn't support anything but image attachments, the reasoning can be found here in the FAQ:

https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#user-content-why-does-netbox-support-only-image-attachments

Closing this as a duplicate of https://github.com/netbox-community/netbox/issues/1039

If you still want to use netbox as a document store, you can have a look at the following plugins:

https://github.com/jasonyates/netbox-documents
https://github.com/Kani999/netbox-attachments

**Closed by kkthxbye-code** 2022-11-24 10:56 UTC
Labels: type: feature
