### ISSUE TITLE
Rack device link failure

### ISSUE THREAD

**Issue by lmgonzalezl** [netbox-community/netbox#4669] opened 2020-05-20 10:37 UTC
**Environment**
Netbox version: 2.8.0

There is an error in the link of a device placed in a rack.
The link points to the local ip of the netbox instance (127.0.0.1) and not the IP or name of the system.

![image](https://user-images.githubusercontent.com/51785108/82436714-2c732a80-9a8e-11ea-8f02-612ee78d9125.png)

![image](https://user-images.githubusercontent.com/51785108/82436792-4d3b8000-9a8e-11ea-9475-fc9a4c17f208.png)

**Comment by jeremystretch** [comment] 2020-05-20 13:12
This is the fourth duplicate of #4526

**Closed by jeremystretch** 2020-05-20 13:12 UTC
