### ISSUE TITLE
Social auth user creation with email as name causes ModuleNotFoundError: no module named netbox.users

### ISSUE THREAD

**Issue by xTrekStorex** [netbox-community/netbox#10805] opened 2022-11-01 17:59 UTC
### NetBox version

v3.3.6

### Python version

3.9

### Steps to Reproduce

Using python social auth with Azure AD and setting `SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True`.
Login with non-existing user. 

### Expected Behavior

Non-existing user is created with email as username.

### Observed Behavior

`ModuleNotFoundError: no module named netbox.users`

Existing users with linked user-social-auth can login. 
Existing users still use name attribute for username (default social auth behavior).

When changing the `SOCIAL_AUTH_CLEAN_USERNAME_FUNCTION` setting from `'netbox.users.utils.clean_username'` to `'users.utils.clean_username'` (matching file structure in netbox folder) login / user creation works.

The setting was introduced in https://github.com/netbox-community/netbox/commit/cc00789d35a255e05ea80d9cdd138fe547c670ad

**Comment by kkthxbye-code** [comment] 2022-11-01 18:00
Duplicate of https://github.com/netbox-community/netbox/issues/10770

**Closed by kkthxbye-code** 2022-11-01 18:00 UTC
Labels: type: bug
