### ISSUE TITLE
Assigned untagged VLAN seems not to be removed correctly when 802.1Q Mode is deleted

### ISSUE THREAD

**Issue by anlu85** [netbox-community/netbox#5378] opened 2020-11-25 09:14 UTC
### Environment
* Python version: 3.7.3
* NetBox version: 2.9.9

### Steps to Reproduce
1. Create an interface with 802.1Q Mode = Access and assign an untaged VLAN
2. Update changes
3. Edit the interface and remove 802.1Q mode (with 'remove all items')
4. Read out the interfaces property 'untagged_vlan' with API or script

In Script / API-Call:
- Ports mode is 'null'
- **no untagged_vlan is assigned**

In Script / API-Call:
- Ports mode is 'null'
- **untagged_vlan is still assigned**
- Assigned untagged VLAN is not visible in web interface

**Comment by jeremystretch** [comment] 2020-11-25 13:49
Looks like  duplicate of #5360 (fixed in v2.9.10)

**Comment by anlu85** [comment] 2020-11-25 15:21
> Looks like duplicate of #5360 (fixed in v2.9.10)

Oh, you're right... Sorry for the repost.
(I just released I only checked for open issues before posting...)

**Closed** 2020-11-25 15:21 UTC
