### ISSUE TITLE
Umlauts in email addresses

### ISSUE THREAD

**Issue by Azmodeszer** [netbox-community/netbox#17207] opened 2024-08-19 09:21 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.0.9

### Python Version

3.11

### Steps to Reproduce

1. Create a contact.
2. Enter a mailbox containing an umlaut in the local-part, ex. `umläut@server.com`

### Expected Behavior

Contact is saved, since UTF8SMTP is a thing: https://www.rfc-editor.org/rfc/rfc5336#section-3.2

### Observed Behavior

Contact is not saved and email field is highlighted red. No additional explanation appears. ![image](https://github.com/user-attachments/assets/69c6b52b-43bb-41e9-a185-5acc3512fff3)

**Comment by jeremystretch** [comment] 2024-08-19 15:48
This is caused by [frontend validation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#validation); the form never actually gets submitted.

AFAICT this is native to the browser for `<input type="email">` elements. We're only checking against `validity.valid` on the field prior to form submission. Seems like this has been a [known bug](https://www.w3.org/Bugs/Public/show_bug.cgi?id=15489) in the specification for some time.

**Comment by jeremystretch** [comment] 2024-08-19 16:00
> No additional explanation appears.

Considering this from a higher level, maybe it would be best to just do away with this validation entirely, as marking a field as invalid without including an explanatory message is of limited value. Error messages are currently provided only via backend authentication (after submitting the form).

**Comment by jeremystretch** [comment] 2024-08-26 20:47
Discussed this with the other maintainers. The consensus was to ignore frontend validation for email fields specifically, but otherwise leave it intact (for now, at least) to avoid introducing unexpected behavior elsewhere.

**Comment by jeremystretch** [comment] 2024-08-26 21:06
Unfortunately, even if we disable our custom validation styling, the browser (Firefox and Chrome, at least) is quite adamant that this is not a valid email address.

![screenshot](https://github.com/user-attachments/assets/741b5aa1-8c78-4d26-b885-0efd70570e28)

As NetBox is not doing anything unique here - it's just a regular `<input type="email">` on the page - we'll have to defer to how the browser handles this validation. The only other option would be to declare the field as a regular, unformatted input without _any_ validation, which obviously would be problematic.

I'm going to close this out as it doesn't appear that we have any workable options, but I'm happy to re-open this if anyone comes up with something clever.

**Closed by jeremystretch** 2024-08-26 21:06 UTC
Labels: type: bug, status: accepted, severity: low
