### ISSUE TITLE
Allow wider search for adding ip to interfance

### ISSUE THREAD

**Issue by darkfiberiru** [netbox-community/netbox#3380] opened 2019-07-31 15:47 UTC
### Proposed Functionality
Add ability to search for IP address by description/tags when adding to an interface.
 
### Use Case
Currently our work flow involves searching for a systems IP globally after assigning it copying it and then pasting it into the search under assign IP when assigning it to an interface. We should be able to search the descriptions to select an IP.

This applies for both ip's moving across the interface and creating new IP's as the new IP option is very limited as it doesn't let you select a network and get the first free IP in that network instead you have to type in the exact IP you want to create.
### Database Changes

None 
### External Dependencies
None

**Comment by jeremystretch** [comment] 2019-10-15 13:05
Duplicate of #3009

**Closed by jeremystretch** 2019-10-15 13:05 UTC
