### ISSUE TITLE
RackType has no field named 'type'

### ISSUE THREAD

**Issue by kukabu** [netbox-community/netbox#17586] opened 2024-09-24 07:59 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.1.1

### Python Version

3.10

### Steps to Reproduce

1. Create the rack type
2. Search the rack type by any field

### Expected Behavior

Search results.

### Observed Behavior

<class 'django.core.exceptions.FieldDoesNotExist'>

RackType has no field named 'type'

Python version: 3.10.12
NetBox version: 4.1.1
Plugins: 
  netbox_reorder_rack: 1.1.1
  netbox_topology_views: 4.1.0

**Comment by jeremystretch** [comment] 2024-09-24 12:54
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v4.1.1. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by kukabu** [comment] 2024-09-25 02:36
Hello
I reproduce the bug on https://demo.netbox.dev/
Try https://demo.netbox.dev/search/?q=TestRack

**Comment by Hardi100** [comment] 2024-09-26 13:37
I know where the bug is at. If you assign the issue to me, i can create a pull request

**Comment by arthanson** [comment] 2024-10-03 14:29
This was better repro and fixed in bug #17671. Closing this issue.

**Closed by arthanson** 2024-10-03 14:29 UTC
Labels: type: bug
