### ISSUE TITLE
Power panel breadcrumbs return to site, not power panels

### ISSUE THREAD

**Issue by kbreit** [netbox-community/netbox#5745] opened 2021-02-03 16:29 UTC
### Environment
* Python version: 3.8.6
* NetBox version: 2.10.4

### Steps to Reproduce
1. Create a site
2. Create a power panel assigned to the site
3. Load the new power panel
4. The breadcrumb at the top should say "Power Panels / Site Name / Panel Name". Click the Site Name.

### Expected Behavior
I expected it to bring me to the Power Panels list and filtering all panels assigned to the site name.

### Observed Behavior
It brought me to the site details for that site (ex: `dcim/sites/sitename/`).

**Comment by DanSheps** [comment] 2021-02-03 18:54
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Closed** 2021-02-03 22:02 UTC
Labels: pending closure
