### ISSUE TITLE
Issues with prefix search filter (Mask length)

### ISSUE THREAD

**Issue by 3bruno** [netbox-community/netbox#7076] opened 2021-08-31 02:15 UTC
### NetBox version

v.3.0.0

### Python version

3.8

### Steps to Reproduce

It's possible to reproduce with beta demo:

1 - https://beta-demo.netbox.dev/ipam/prefixes/

2 - Filters;

3 - Choose some Mask length and click "Search" button.

### Expected Behavior

Search some prefixes with some Mask length filter.

### Observed Behavior

The complete exception is provided below:

<class 'TypeError'>

sequence item 1: expected str instance, int found

Python version: 3.8.10
NetBox version: 3.0.0-dev

**Comment by 3bruno** [comment] 2021-08-31 02:29
This error is happening in IP Address mask Length filter search too.

**Comment by jeremystretch** [comment] 2021-08-31 13:44
Duplicate of #7070

**Closed by jeremystretch** 2021-08-31 13:44 UTC
Labels: type: bug
