### ISSUE TITLE
Changing device when editing IP address doesn't reset interface field

### ISSUE THREAD

**Issue by Gelob** [netbox-community/netbox#5617] opened 2021-01-12 20:13 UTC
### Environment
* Python version: Python 3.6.8
* NetBox version: 2.10.3

### Steps to Reproduce
1. Create two devices with the same interface names (may not be required)
2. Assign an IP address to Device A
3. Edit the IP address and under Interface Assignment change the Device it is assigned to Device B
3. Click Update and get a Modified IP address modal but notice the assignment did not change to Device B.

### Expected Behavior
I expected the IP address to now be assigned to Device B instead of A. However the interface field under Interface Assignment doesn't refresh/reset when I change the device so the assignment stayed with Device A.

### Observed Behavior
The IP address assignment didn't change to Device B because the interface was still referencing device A

**Comment by DanSheps** [comment] 2021-01-13 15:12
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Closed** 2021-01-30 03:55 UTC
Labels: pending closure
