### ISSUE TITLE
Utilization threshold is wrong

### ISSUE THREAD

**Issue by alexandredpy** [netbox-community/netbox#11273] opened 2022-12-21 11:27 UTC
### NetBox version

v3.4.1

### Python version

3.9

### Steps to Reproduce

1. Go on IPAM > Prefixes

### Expected Behavior

The gauge should be fully filled in grey (100.0%)

### Observed Behavior

My subnet is an IPv4 /30, so 2 usable adresses. 2 IP addresses are currently assigned, so the subnet is 100% used. The utilization percentage is seen as 100,0% but the threshold is not correctly displayed.
The gauge is not totally filled in grey

See screenshot
![image](https://user-images.githubusercontent.com/18117508/208894700-d5537ec3-979e-4aa9-bc1e-bff87be0b0fc.png)

However, seems to work correctly on a /126 IPv6 subnet

**Comment by Bierfass** [comment] 2022-12-21 11:35
I can confirm this in our testing instance. It also applies to the rack utilization.

**Comment by jeremystretch** [comment] 2022-12-22 13:25
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment] 2022-12-22 13:27
Duplicate of #11271

**Closed by jeremystretch** 2022-12-22 13:27 UTC
Labels: type: bug, status: revisions needed

**Comment by aurus686** [comment] 2023-01-09 15:22
> Дубликат [№ 11271](https://github.com/netbox-community/netbox/issues/11271)

Thanks! Upgrading to version 3.4.2 helped!
