### ISSUE TITLE
Cable Trace and Circuit Termination for duplex patchcord ending

### ISSUE THREAD

**Issue by krancslawomir** [netbox-community/netbox#11982] opened 2023-03-15 12:30 UTC
### NetBox version

v3.4.5

### Python version

3.8

### Steps to Reproduce

**Location A:**
1. Create Fiber Optic Patch Panel (ODF A)
2. Create Rear Ports - 12 positions represents 12 fibers
3. Create Front Ports - 12 positions represents 12 ports  
4. Create Router device A with interfaces

**Location B:**
1. Create Fiber Optic Patch Panel (ODF B)
2. Create Rear Ports - 12 positions represents 12 fibers
3. Create Front Ports - 12 positions represents 12 ports  
4. Create Router device B with interfaces

**Circuits:**
1. Create example circuit 
2. Set Circuit Termination A -> Site Location A -> ODF A > Rear Ports 1, 2
3. Set Circuit Termination Z -> Site Location B -> ODF B -> Rear Ports 5, 6

**Connections:** 
1. Create Cable:
A Side: Location A -> Router device A -> interface ex. xe-0/0/1
B Side:  Location A-> Fiber Otpic Patch Panel (ODF A) -> Front Port 1, 2

And now there is an error: <class 'AssertionError'>

I have verified that you can do connection cable only for 1 Front Port which represents simplex fiber patchcord (1 port) .
But in my case i would like to use also duplex fiber patchcord which reprezents 2 ports.

**NetBox Error:**
![NetBox Error](https://user-images.githubusercontent.com/56762524/225308944-8964fc44-8da9-4e2f-bfe2-af9c98ba5a97.png)

**What I can achieve currently:**
![What I can achieve v1](https://user-images.githubusercontent.com/56762524/225309094-5759536f-1d7d-45e6-a755-1ece0a2792b1.png)
![What I can achieve v2](https://user-images.githubusercontent.com/56762524/225309104-d0756a09-4149-4e10-a0da-353cb0a2ff81.png)

### Expected Behavior

I would like to use also duplex fiber patchcord (2 ports).
I would like to use different ports on Fiber Optcs Patch Panel in different locations like this:
![What I want to achieve](https://user-images.githubusercontent.com/56762524/225309386-d53e1ffd-3ba4-4ad0-9fbc-5c464733591e.jpg)

### Observed Behavior

 <class 'AssertionError'>

**Comment by jeremystretch** [comment] 2023-09-26 18:51
I'm not able to reproduce this on v3.6.2. It was likely resolved in the course of some other work in a more recent release (unrelated to #13337). (Screenshot of the complete path below.)

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/4cfa6cb6-2724-4194-a516-159915dd103d)

**Closed by jeremystretch** 2023-09-26 18:51 UTC
Labels: type: bug, pending closure, topic: cabling, severity: medium

**Comment by krancslawomir** [comment] 2023-10-11 10:48
Hi, I confirm. I have installed latest version 3.6.3 and issue does not exist.
Thanks.
