### ISSUE TITLE
Unable to assign IP Address to interface with /api/ipam/prefixes/<id>/available-ips/

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#13876] opened 2023-09-24 19:40 UTC
### NetBox version

v3.6.2

### Python version

3.8

### Steps to Reproduce

1. Create a device Test1, with an interface named eth0. Take note of the interface ID.
1. Create a prefix 10.10.0.0/16, status active. Take note of the ID of the prefix.
2. Create an IP Address assigned to the interface from that prefix using the API endpoint /available-ips/
```
curl -X 'POST' \
  'https://demo.netbox.dev/api/ipam/prefixes/96/available-ips/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFTOKEN: egTrik2RSlpArnjvo76kTM4jYjZRkXEtvsxsV2ey9oVMmeAzBhAtifJEsT6c7QaI' \
  -d '[
  {
    "status": "active",
    "assigned_object_type": "dcim.interface",
    "assigned_object_id": 1736
  }
]'
```

### Expected Behavior

I expect the newly created IP Address to be assigned the interface specified.

### Observed Behavior

I get the following returned from the API:
```
[
  {
    "id": 194,
    "url": "https://demo.netbox.dev/api/ipam/ip-addresses/194/",
    "display": "10.10.0.3/16",
    "family": {
      "value": 4,
      "label": "IPv4"
    },
    "address": "10.10.0.3/16",
    "vrf": null,
    "tenant": null,
    "status": {
      "value": "active",
      "label": "Active"
    },
    "role": null,
    "assigned_object_type": null,
    "assigned_object_id": null,
    "assigned_object": null,
    "nat_inside": null,
    "nat_outside": [],
    "dns_name": "",
    "description": "",
    "comments": "",
    "tags": [],
    "custom_fields": {},
    "created": "2023-09-24T19:33:47.225091Z",
    "last_updated": "2023-09-24T19:33:47.225121Z"
  }
]
```

So the `assigned_object_type` and `assigned_object_id` is not populated as I expect it to be.

**Comment by jeremystretch** [comment] 2023-09-25 12:49
Potentially related to #13746

**Comment by arthanson** [comment] 2023-09-25 17:30
DUPE OF #13746

**Comment by arthanson** [comment] 2023-10-05 20:01
Closing as fixed by https://github.com/netbox-community/netbox/pull/13889

**Closed by arthanson** 2023-10-05 20:01 UTC
Labels: type: bug, status: under review
