### ISSUE TITLE
Source Contexts missing on virtual machines

### ISSUE THREAD

**Issue by D1StrX** [netbox-community/netbox#11832] opened 2023-02-26 10:51 UTC
### NetBox version

v3.4.5

### Python version

3.8

### Steps to Reproduce
(names and content don't matter)
1. Create a site
2. Create a virtual machine, and assign it to the created site
3. Create a device, and assign it to the created site
1. Create a config context, that applies to the created site (as long devices and virtual machines are targeted to compare the output)

**Config context example:**
Name: Network Config
Weight: 100
Description: Some description
``` json
{
    "name-servers": [
        "Example1",
        "Example2"
    ]
}
```

- Is active 
**Assignment**
Sites: Created site

Output should match something like this:
![image](https://user-images.githubusercontent.com/40062371/223462362-683e958a-5165-422a-8f18-41aaeed067d0.png)

![image](https://user-images.githubusercontent.com/40062371/223462741-352cba22-9658-4b8f-a50a-dec164a06cab.png)

### Expected Behavior

Virtual machines should also have the _Source Contexts_ populated, like devices do.

Also the documentation doesn't mention/cover the Source Contexts: https://docs.netbox.dev/en/stable/features/context-data/

### Observed Behavior

Both receive _Rendered Contexts_. Devices get their source contexts populated. Virtual machines don't.

**Comment by kkthxbye-code** [comment] 2023-02-27 07:40
> Create a config context, that applies to a region e.g. (as long devices and virtual machines are targeted to compare the output)

Virtual machines do not have a region field, so I think you are misunderstanding something. I tested with Tenant and the config context rendered fine for both device and virtual machine. Please revise your replication steps.

**Comment by jeremystretch** [comment] 2023-03-07 15:01
Closing this as there's been no reply from OP.

**Comment by D1StrX** [comment] 2023-03-07 15:10
@kkthxbye-code @jeremystretch sorry for not getting back. Hereby some screenshots. First one is on the Virtual Machine, the other a Device. Both have rendered contexts, while only Device has a source context.
![image](https://user-images.githubusercontent.com/40062371/223462362-683e958a-5165-422a-8f18-41aaeed067d0.png)

![image](https://user-images.githubusercontent.com/40062371/223462741-352cba22-9658-4b8f-a50a-dec164a06cab.png)

**Comment by kkthxbye-code** [comment] 2023-03-11 19:31
I still don't think this is enough for anyone to replicate it. Please make proper replication steps, which allows one to replicate it starting from an empty netbox instance.

**Comment by D1StrX** [comment] 2023-03-12 12:56
Edited the replication steps. Hopefully this is enough information

**Comment by jeremystretch** [comment] 2023-03-13 13:13
I'm still not able to reproduce this. Your screenshot shows far more objects than just site assigned to the ConfigContext object, which is likely where your problem lies.

**Comment by D1StrX** [comment] 2023-03-13 21:50
I thought it shouldn't matter, because in the end the objects match all requirements. But I understand now, like kkthxbye-code said, Regions, Site Groups, Locations aren't available fields for VMs. Only odd thing is that the exact opposite happens when only assigning it to a Site (VM got source context instead of rendered context):
Config context:
![image](https://user-images.githubusercontent.com/40062371/224838509-20cffb05-f32d-412e-8b4f-f39f2b64c08a.png)

Device:
![image](https://user-images.githubusercontent.com/40062371/224838571-599551f5-dbca-4762-8f5e-a43295952a99.png)

VM:
![image](https://user-images.githubusercontent.com/40062371/224838608-4b51e7a7-7aea-4e8e-afab-3be624f58a1e.png)

What perhaps fixes my perception, and not yet explained in the documentation (what I could've find), what does the Source Contexts add as extra information to the Config Texts tab? 
It is handy to have a clickable link to the config text.. but other than that?

**Comment by jeremystretch** [comment] 2023-05-04 14:48
Closing this out as no one has been able to replicate the described behavior and there have been no further updates. If anyone _is_ able to reproduce the reported behavior on the current stable release of NetBox, please submit a new bug report with detailed, concise steps for doing so and we will investigate. Thanks.

**Closed by jeremystretch** 2023-05-04 14:48 UTC
Labels: type: bug, status: revisions needed
