### ISSUE TITLE
Server error on bulk editing a custom field of date type

### ISSUE THREAD

**Issue by mmfreitas** [netbox-community/netbox#11417] opened 2023-01-06 15:18 UTC
### NetBox version

v3.4.2

### Python version

3.9

### Steps to Reproduce

1. Create a custom field {"name": "Installed_on", "label": "Installed on", "content_type": "DCIM > Device", "type": "Date"}.
2. Go to devices table and select multiple objects.
3. Try to update the new custom field with a date such as 2022-11-17.
4. A server error is thrown.

### Expected Behavior

Should be updated on all selected devices.

### Observed Behavior

![image](https://user-images.githubusercontent.com/91552302/211041344-c8e25683-af91-4803-a954-af4a9ffe28eb.png)

**Comment by kkthxbye-code** [comment] 2023-01-06 15:20
Duplicate of https://github.com/netbox-community/netbox/issues/11379

**Closed by kkthxbye-code** 2023-01-06 15:20 UTC
Labels: type: bug
