### ISSUE TITLE
Frustrating media_failure redirects

### ISSUE THREAD

**Issue by doc-sheet** [netbox-community/netbox#15806] opened 2024-04-22 15:51 UTC
### Deployment Type

Self-hosted

### NetBox Version

v3.7.5

### Python Version

3.11

### Steps to Reproduce

1. Block /static/ with adblock (the simplest way)
2. Open any page

### Expected Behavior

Maybe an error badge?

[Such redirects](https://github.com/netbox-community/netbox/blob/5d95d49268c2b19ad6f4850b0207897d8aa9e604/netbox/templates/base/base.html#L63) always frustrated me.
Most of the time issue related not to netbox installation but my network issues.
It also usually throws on some rarely used (by me) resources like netbox-print.css

Maybe it's time to replace redirect with something more friendly?
Furthermore Netbox could operate without js just fine and css issues are noticeable enough by itself.

### Observed Behavior

> Static Media Failure
> The following static media file failed to load: netbox-print.css 

etc

**Comment by jeremystretch** [comment] 2024-05-03 16:10
> Maybe it's time to replace redirect with something more friendly?

The redirects are these specifically to help the user recognize and troubleshoot the issue. From your report, they appear to be working as intended, so I'm going to close this.

> Most of the time issue related not to netbox installation but my network issues.

Removing the redirects would not resolve this issue for you; the application would still fail to fully load and would not be usable.

**Closed by jeremystretch** 2024-05-03 16:10 UTC
Labels: type: bug, status: needs triage
