### ISSUE TITLE
Failed jobs doesn't display Exception message in RQ Task view

### ISSUE THREAD

**Issue by a-belhadj** [netbox-community/netbox#17983] opened 2024-11-11 16:07 UTC
### Deployment Type

Self-hosted

### Triage priority

I'm a NetBox Labs customer

### NetBox Version

v4.1.6

### Python Version

3.12

### Steps to Reproduce

Go to : http://localhost:8000/core/background-tasks/<job_failed_id>/ the exception message isn't present

### Expected Behavior

See the Exception message

### Observed Behavior

No Exception message

**Comment by jeremystretch** [comment] 2024-11-12 14:45
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by pkumar2801** [comment] 2024-12-02 19:21
@jeremystretch I’ve also encountered this issue multiple times. It seems to occur during high memory-consuming tasks executed via the script. When the task fails due to resource constraints, the script's state in the UI continues to display as "running," even though it has actually failed on the worker side.

Upon investigating further and checking the logs in the Django RQ admin panel, the exception message is:
`work-horse terminated unexpectedly; waitpid returned`.

This indicates that the worker process terminates abruptly, but the task state is not properly updated in the UI to reflect the failure. It might be worth examining how task state synchronization is handled between the worker and the UI to address this discrepancy.

**Comment by jeremystretch** [comment] 2024-12-06 14:04
Closing this out as there's been no further response from the submitter.

**Closed by jeremystretch** 2024-12-06 14:04 UTC
Labels: type: bug, status: revisions needed, pending closure
