### ISSUE TITLE
Problem in the connection Power feed

### ISSUE THREAD

**Issue by RenatoPereira91** [netbox-community/netbox#10504] opened 2022-09-29 01:17 UTC
### NetBox version

v3.3.4

### Python version

3.10

### Steps to Reproduce

After connected one PDU via power port, it show the connection cable, but not load information about the Connected Device and Utilization in the Power Feed

![image](https://user-images.githubusercontent.com/102453125/192915684-511edfc0-9ee5-4553-827e-6a7cd2dfb350.png)

### Expected Behavior

Show information about device connected and utilization

### Observed Behavior

Not show information

**Comment by phurrelmann** [comment] 2022-09-29 07:20
probably a duplicate of #10460

**Comment by jeremystretch** [comment] 2022-09-29 12:12
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #10460 for further discussion.

**Closed** 2022-09-29 12:16 UTC
Labels: type: bug, status: duplicate

**Comment by RenatoPereira91** [comment] 2022-09-29 12:25
@jeremystretch 
Thanks for answer, I read the post but don't understood how fix the problem
