### ISSUE TITLE
Ports already "connected" needs to be greyed out, ie; not selectable.   

### ISSUE THREAD

**Issue by drikusb** [netbox-community/netbox#6808] opened 2021-07-25 23:35 UTC
### NetBox version

v3.0-beta1

### Feature type

Change to existing functionality

### Proposed functionality

In NetBox v2.11.x, you are unable to select ports that are already connected to other ports.
v3.0-beta1 allows the selection of already connected ports, though doesn't allow the "connection" of ports to continue...an error occurs as should.

Feature request is to grey out ports that are not considered available.
eg;

1. Create a device DEVICEA in any RU position with X number of rear ports
2. Create a device DEVICEB anywhere, another rack, same rack with X number of rear ports
3. Link DEVICEA rear-port 1 with DEVICEB rear-port1
4. When trying to link DEVICEA rear-port2 with DEVICEB rear-port2, rear-port1 should be greyed out which isn't.

 

### Use case

Saves time not having the ability to give n error because of the wrongly selected ports at transaction completion time.

**Comment by jeremystretch** [comment] 2021-07-29 14:40
> In NetBox v2.11.x, you are unable to select ports that are already connected to other ports.

Marking this as a bug, since the behavior in v2.11 is desired.

**Comment by jeremystretch** [comment] 2021-07-29 14:47
@thatmattlove Seems like the issue is here: https://github.com/netbox-community/netbox/blob/52c4d54481d7fd9138474cffdc9a6f8024718d69/netbox/project-static/src/select/api.ts#L38

DynamicModelChoiceField sets an attribute named `disabled-indicator` on its widget specifying the name of the API field (if any) that indicates whether the object should be disabled from selection. For example, in the cable connection form, we see:

```python
    termination_b_id = DynamicModelChoiceField(
        queryset=Interface.objects.all(),
        label='Name',
        disabled_indicator='_occupied',
        query_params={
            'device_id': '$termination_b_device',
            'kind': 'physical',
        }
    )
```

This manifests on the form field widget as:

```html
<select name="termination_b_id" ... disabled-indicator="_occupied">
```

If we can tweak the API TypeScript to infer `DISABLED_ATTRIBUTES` from the value of this attribute, it should fix this and any other such issues in other forms.

**Closed** 2021-07-30 08:26 UTC
Labels: beta, type: bug
