### ISSUE TITLE
Bulk import of prefixes fails when VLAN id is defined more than once

### ISSUE THREAD

**Issue by garryshtern** [netbox-community/netbox#14694] opened 2024-01-04 16:47 UTC
### Deployment Type

Self-hosted

### NetBox Version

v3.6.3

### Python Version

3.9

### Steps to Reproduce

Create two instances of the same VLAN
Try bulk import of a prefix with above vlan populated in vid field

### Expected Behavior

Use additional details in the import to distinguish between different vlan. Perhaps, tenant, site, etc. 

### Observed Behavior

Import fails with “record value <vlan> not unique.

**Comment by markkuleinio** [comment] 2024-01-05 16:24
This works for me on 3.7.0:

```
prefix,status,vlan,site
10.1.1.0/24,active,100,Site1
10.1.2.0/24,active,100,Site2
```
(Both sites have VLAN 100 separately)

<img width="751" alt="image" src="https://github.com/netbox-community/netbox/assets/25136274/e7c1f944-1fd6-49df-9641-ffe7c666cf02">

**Comment by jeremystretch** [comment] 2024-01-05 16:32
@garryshtern could you please expand on your reproduction steps above to specify **exactly** what objects your creating at each step, so that someone else can reliably replicate the behavior?

**Comment by garryshtern** [comment] 2024-01-07 19:20
I created two VLAN 100s under demo.netbox.com. Now, go here: https://demo.netbox.dev/ipam/prefixes/import/, and try to import the following: 
"prefix","tenant","site","vlan","status"
"1.1.1.0/24","Initech","DM-NYC",100,"active"

You should see an error: 
<img width="349" alt="image" src="https://github.com/netbox-community/netbox/assets/6483893/136f2549-fc8b-49df-9953-fdc6bada0979">

**Comment by abhi1693** [comment] 2024-01-07 20:23
Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment] 2024-01-24 13:53
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.

**Closed by jeremystretch** 2024-01-24 13:53 UTC
Labels: type: bug, status: revisions needed

**Comment by Ethanholle2783** [comment] 2024-02-05 13:35
I'm facing the same issue, can we reopen this ?
