### ISSUE TITLE
l2vpn - device/virtual-machine interfaces list - l2vpn termination connection column

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#10194] opened 2022-08-29 14:01 UTC
### NetBox version

v3.3.1

### Feature type

Change to existing functionality

### Proposed functionality

On interface tables it would be nice to be able to see if an interface has a connection to an l2vpn. 

### Use case

Right now if a device or vm interface has had an l2vpn termination added, it does not show in any way in the interfaces list. eg https://demo.netbox.dev/dcim/devices/16/interfaces/ 
similar functionality to the "connection" or "link peers" column would be useful

The same is also true re terminations to vlans on device. theres currently nothing in the vlans list to show if it has an l2vpn termination on it. eg https://demo.netbox.dev/ipam/vlans. this will probably be a separate for someone else to flesh out though

### Database changes

Im not sure if any are needed, its more about displaying existing data in list view

**Comment by DanSheps** [comment] 2022-08-29 14:51
Tagged this as needs owner, pretty trivial so if I don't get to it someone can do a PR for it.

**Comment by jeremystretch** [comment] 2022-08-29 15:01
I think this is a duplicate of #10034 but @DanSheps please re-open if I'm mistaken.

**Closed by jeremystretch** 2022-08-29 15:01 UTC
Labels: type: feature, status: needs owner
