### ISSUE TITLE
Available rear U's position is locked if there is a non full-depth device mounted to front position

### ISSUE THREAD

**Issue by MarcoMFreitas** [netbox-community/netbox#7385] opened 2021-09-28 15:32 UTC
### NetBox version

v3.0.3

### Python version

3.7

### Steps to Reproduce

1. Add a non full-depth device and set it to the front U's position of a rack
2. Try to add another non full-depth device to the rear of the same rack in the same U's position

### Expected Behavior

Expected the number in positions field to show available rear U's positions as it is possible to add a device in this position through the "add device" on the elevations page.

### Observed Behavior

When creating a non full-depth device and assigning it to the front U of a rack, the rear positions of this rack are locked when trying to add another non full-depth device.

**Comment by DanSheps** [comment] 2021-09-28 15:34
Duplciate of #7374

**Comment by DanSheps** [comment] 2021-09-28 15:34
Duplicate of #7374

**Closed by DanSheps** 2021-09-28 15:34 UTC
Labels: type: bug
