### ISSUE TITLE
IPAM quick search edit selected selects all IPAM addresses

### ISSUE THREAD

**Issue by amyers1616** [netbox-community/netbox#17210] opened 2024-08-19 19:06 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.0.8

### Python Version

3.12

### Steps to Reproduce

1. Go to IPAM > IP Addresses
![image](https://github.com/user-attachments/assets/5454aeb9-c8a3-431b-bdca-91878b67cdcc)
2. Use the quick search to narrow down the result set 
3. Select all using the checkbox next to the IP ADDRESS heading
4. Select new box in alert to **select all XXX IP addresses matching query**
![image](https://github.com/user-attachments/assets/fcb76414-e133-47bb-a63a-5f067637b94b)
5. Click [Edit Selected]
6. Selection changes to _all_ IP addresses in IPAM
![image](https://github.com/user-attachments/assets/932b6069-9a94-42ed-84ff-38dbdd89d703)

### Expected Behavior

When using the select all matching addresses in query, it is expected that only the matching XXX number of matches are selected, not the entire IPAM address space.

### Observed Behavior

All IP addresses are selected instead of only the ones from the quick search.

**Comment by arthanson** [comment] 2024-08-22 13:38
dupe of #16733 closing

**Closed by arthanson** 2024-08-22 13:38 UTC
Labels: type: bug, status: needs triage
