### ISSUE TITLE
Circuits not searchable by CPE Hostname

### ISSUE THREAD

**Issue by ataylor93** [netbox-community/netbox#9670] opened 2022-07-06 14:13 UTC
### NetBox version

V3.2.5

### Python version

3.8

### Steps to Reproduce

Not able to use the quick search or main search for CPE circuits. A little annoying searching for what circuit they are on when they go down in solarwinds.

![image](https://user-images.githubusercontent.com/108404623/177570719-afb3528f-0542-43f1-84f6-02407ed37773.png)
![image](https://user-images.githubusercontent.com/108404623/177570728-6d147e64-e6c5-4d21-97d9-20b9d2aa3626.png)

### Expected Behavior

Yield Search result

### Observed Behavior

No results

**Comment by kkthxbye-code** [comment] 2022-07-06 14:30
This is not a bug. The quick search field does not search custom fields, which `CPE Hostname` is. I'll close this, but feel free to create a feature request with a request for generic searching of custom fields in the quick search, however I think the intention might be captured by this feature request already https://github.com/netbox-community/netbox/issues/6003

**Closed by kkthxbye-code** 2022-07-06 14:30 UTC
Labels: type: bug
