### ISSUE TITLE
Add field 'Location' to the 'CircuitTermination' model

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#11721] opened 2023-02-10 07:56 UTC
### NetBox version

3.4.4

### Feature type

Data model extension

### Proposed functionality

When creating a 'Termination' in a Circuit, the highest detail for a 'Site' is 'Site.
I would like to see this extended with 'Location' and made it optional

Gui updates :
https://demo.netbox.dev/circuits/circuits/19/
Extend the 'Site' row with the location (if choosen)
![image](https://user-images.githubusercontent.com/74899468/218033491-45c8db7b-725e-4083-95d9-c750a0b1c9fc.png)

https://demo.netbox.dev/circuits/circuit-terminations/23/edit/?return_url=/circuits/circuits/19/
In the 'Site' part, add a dropdown for 'Location'
![image](https://user-images.githubusercontent.com/74899468/218033625-13ade254-e140-4a32-9098-89714d1fd7f0.png)

https://demo.netbox.dev/circuits/circuits/
Add the location to the 'Side A/Z' column view, or add a new columns 'Location A, Location B'
(I prefer the first)
![image](https://user-images.githubusercontent.com/74899468/218033709-2068756f-d1a0-4991-bc39-cb54ea0a7dc6.png)

### Use case

We have crossconnects that run between 2 buildings in one Location. Currently, these are stored as 'SiteA <-> SiteA'
With this added field, it can be differentiated as 'SiteA/Building1 <-> SiteA/Bullding2'

### Database changes

Add a new field 'Location' to the 'CircuitTermination' model

**Comment by gjvc** [comment] 2023-07-08 00:21
We have cross-connects that run between two cages (Location) in the same facility (Site) 

For netbox 2.5  I proposed [this](https://github.com/netbox-community/netbox/issues/2929) when Location was known as a "Rack Group"  For netbox 3.2  I proposed [this](https://github.com/netbox-community/netbox/issues/9604) to add Location to a circuit termination.

I'd be happy to create a PR for netbox 3.4 and/or 3.5 as appropriate.

**Comment by gjvc** [comment] 2023-07-08 00:21
We have cross-connects that run between two cages (Location) in the same facility (Site) 

For netbox 2.5  I proposed [this](https://github.com/netbox-community/netbox/issues/2929) when Location was known as a "Rack Group".  For netbox 3.2  I proposed [this](https://github.com/netbox-community/netbox/issues/9604) to add Location to a circuit termination.

I'd be happy to create a PR for netbox 3.4 and/or 3.5 as appropriate.

**Comment by KPTheProf** [comment] 2023-07-20 13:53
We have multiple sites where we have circuits terminating in different buildings, I think that this would be a useful update to be able to track the correct locations. We have a major WAN project starting where this would be of benefit to us. Do you have any idea of timescale as to when / if this will be implemented please?

**Comment by GoldyXXD** [comment] 2023-07-21 04:24
+1 for wanting to be able to specify Location on a circuit.

**Comment by george-cox** [comment] 2023-08-14 18:25
@GoldyXXD just to be clear, this is on the CircuitTermination at each end.  I can't see how a CircuitTermination is useful at a higher granularity.

**Comment by jwbensley** [comment] 2023-08-18 08:55
+1 this would benefit us too.

**Comment by jeffgdotorg** [comment] 2024-07-14 19:00
Flagging facial similarity between this issue and #9604

**Comment by jeremystretch** [comment] 2024-09-25 18:39
Duplicate of #9604

**Closed by jeremystretch** 2024-09-25 18:39 UTC
Labels: type: feature, needs milestone, status: backlog, complexity: high
