### ISSUE TITLE
Add custom fields to device types/module types

### ISSUE THREAD

**Issue by stovakor** [netbox-community/netbox#11074] opened 2022-12-01 17:19 UTC
### NetBox version

v3.3.8

### Feature type

New functionality

### Proposed functionality

Currently, when you create a custom field it will only appear after a device has already been created. You are unable to add the custom field to the device type or module type.

Please add the ability for custom fields to also show up on device type and module type's.

Steps to reproduce.
Create a custom field called 'btu' using model DCIM > power port.
When you edit a power port on a device or module you see the custom field.
When you create a device type or module type and add a power port to them, the custom field does not appear.

### Use case

In the above example, if you want to model the BTU thermal load of a power supply it will always be the same BTU load assuming the power supply is the same inside a module or a device.
Currently, to input the BTU value you would have to get all the way to the end of the device creation process and then edit the device or module and add the BTU value to the power port.

If the custom field appeared on the device type or module type power port, then you could input the value there once, and that value would carry over to each device or module that you create. (Similar to how maximum draw and allocated draw work now)

### Database changes

I don't believe any database changes are needed since the custom fields already exist. It's just a matter of making them appear on the device type and module type areas of NetBox.

### External dependencies

None.

**Comment by kkthxbye-code** [comment] 2022-12-08 11:09
Duplicate of https://github.com/netbox-community/netbox/issues/9243

**Closed by kkthxbye-code** 2022-12-08 11:09 UTC
Labels: type: feature
