### ISSUE TITLE
Persistent filters and default values  between pages

### ISSUE THREAD

**Issue by Torstein-Eide** [netbox-community/netbox#14157] opened 2023-11-01 07:48 UTC
### NetBox version

3.6.3

### Feature type

Change to existing functionality

### Proposed functionality

ref: #12556

I propose a drop down bar next to the search bar at top, with the following:

### organizational
|**options** |  |  |  
|  --------|  --------| -----------------|
|Clear      |  Regions |Tenancy group |
| load saved |Site groups|  Tenant         |
| toggle enable/disable |Site  | tag|
| |location | |
| | Rack ||  

### DCIM 

(If screen space use multiple columns, next to organizational )
(If screen is to small use button to show more)
(For filters and default values that only apply )

| | 
|-|
|Device Role |  
| Asset-tag | 
| | 
### IPAM
(If screen space use multiple columns, next to organizational )
(If screen is to small use button to show more)
(For filters and default values that only apply )

|  |
|-|
|VRF |
| VLAN group | 
| VLAN Site group |
| VLAN|
| VLAN /Prefix role|

- note: asset-tag, some site have a prefix for the tag, so helpful to not having to type a prefix. 
- 

### Use case

When work on multi-site or multi-tenant, it is easy to get overwhelmed of all the objects that take up the screen space, and constantly re-applying filter, over and over.

### Database changes

I don't see need for database change.

### External dependencies

I don't see need for  dependencies change.

**Comment by jsenecal** [comment] 2023-11-02 13:56
I think this is a duplicate of #13162

**Closed** 2024-03-02 04:01 UTC
Labels: type: feature, pending closure
