### ISSUE TITLE
Edit display columns not working

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#6178] opened 2021-04-16 13:11 UTC
### NetBox version

v2.11 beta on beta.netbox.dev

### Python version

3.7

### Steps to Reproduce

1. Go to a virtual machine
2. Go to the 'interfaces' tab, e.g. https://beta.netbox.dev/virtualization/virtual-machines/361/interfaces/
3. Click the Configure cog
4. From "available columns", select a field not currently shown, e.g. "parent interface"
5. Click the green button labelled "Add columns"

### Expected Behavior

The selected field to be added to the "Selected columns" fieldset.

### Observed Behavior

Nothing happens in the browser (Chrome 89, macOS 10.14)

If I open the developer console, I see no Javascript error and no AJAX activity.

**Comment by candlerb** [comment] 2021-04-16 13:12
Screenshot:
![image](https://user-images.githubusercontent.com/44789/115029300-c1a8ba00-9ebd-11eb-9651-b5dea2cb3111.png)

**Comment by jeremystretch** [comment] 2021-04-16 13:22
I'm not able to reproduce this. The field is moved normally under both Firefox 81 and Chrome 86 for me.

Is it an issue specific to this table, or does it not work for _any_ tables?

**Comment by jeremystretch** [comment] 2021-04-16 13:25
Okay, I take that back: It works fine locally but not on the beta demo instance. Let me dig into it more.

**Comment by jeremystretch** [comment] 2021-04-16 13:26
Whoops, that was my mistake when setting up the demo box. I had neglected to ensure static files were copied over as part of the redeployment process. Fixed now. Thanks for the report!

**Closed by jeremystretch** 2021-04-16 13:26 UTC
Labels: status: under review, type: bug
