### ISSUE TITLE
Clusters Section - Incorrect Hardisk Display Size

### ISSUE THREAD

**Issue by Ant0ni00x** [netbox-community/netbox#17609] opened 2024-09-26 06:41 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.1.1

### Python Version

3.12

### Steps to Reproduce

After creating Cluster Groups, Cluster Types and a Cluster, then creating a Virtual Machine, you'll see that the disk size displayed on the cluster page is not formatted correctly.

For example, I created two VMs, with total disk space size of 258.3GB. However, on the Clusters page, where the "Allocated Resources" card displays the total disk size for the cluster, the displayed disk size is 258300GB. 

![Cluster-Display-Issue](https://github.com/user-attachments/assets/64c32adf-e6de-42ac-9416-4f0d0737327f)

![VM-Disk-Sizing](https://github.com/user-attachments/assets/04e80659-b894-4019-85ee-991785d59ae3)

### Expected Behavior

Seems that this number should actually be 258.3GB if displaying in GB. If displaying the disk size in MB, I can then understand the reason for the formatting. The expected behavior is to have the same GB formatting for disk space on the Virtual Machine and the Cluster - "Allocated Resources" card.

### Observed Behavior

On the Clusters page, where the "Allocated Resources" card displays the total disk size for the cluster, the displayed disk size is 258300GB.

**Comment by jeremystretch** [comment] 2024-09-26 12:48
This is a duplicate of #17604. Please remember to search open issues before creating a new one.

**Closed by jeremystretch** 2024-09-26 12:48 UTC
Labels: type: bug, status: needs triage

**Comment by Ant0ni00x** [comment] 2024-09-28 00:03
Apologies.I know you guys are busy and don’t need the extra noise of redundant comments! My eagerness to feel helpful preceded the need to be more thorough.I’ll be more diligent in my search efforts if I ever see anything of significance again.Kind RegardsOn Sep 26, 2024, at 7:48 AM, Jeremy Stretch ***@***.***> wrote:﻿
This is a duplicate of #17604. Please remember to search open issues before creating a new one.
