### ISSUE TITLE
Incorrect total Disk Space allocated in the Cluster

### ISSUE THREAD

**Issue by lucafabbri365** [netbox-community/netbox#17595] opened 2024-09-24 22:03 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.1.1

### Python Version

3.10

### Steps to Reproduce

1. Create a **Cluster**
2. Create multiple **Virtual Machine**(s) (member of the cluster)
3. Add one or more **Virtual Disk** for each virtual machine
4. Total **Disk Space** reported under _Allocated Resources_ section of the cluster is not correct 

### Expected Behavior

I expect the total disk space reported in the cluster's allocated resources to be accurate (it should correspond to the sum of the disk sizes of all the virtual machines that are part of the cluster).

### Observed Behavior

I exported the list of all virtual machines in the cluster to a CSV file. Then, I calculated the total size of all disks: **161,527.01 GB**. However, the total **Disk Space** reported in the _Allocated Resources_ section of the cluster shows an incorrect value: **161,583,531 GB**.

_Note: Totals for **Virtual CPUs** and **Memory** are displayed correctly._

**Comment by arthanson** [comment] 2024-09-25 14:46
closing this as dupe of #17604

**Closed by arthanson** 2024-09-25 14:46 UTC
Labels: type: bug, status: needs triage
