### ISSUE TITLE
Device primary_ip not being removed when removing address from interface

### ISSUE THREAD

**Issue by juan-vg** [netbox-community/netbox#3458] opened 2019-08-28 10:09 UTC
### Environment
* Python version:  3.5.3
* NetBox version:  2.6.2

### Steps to Reproduce
1. Add an interface (let's call it 'I1') to a device ('D1'), and then add an IP address ('A1') to that interface 'I1'
2. Set the tuple (Interface-I1, IP-A1) as the primary_ip for the device 'D1'
3. Assign that IP address to a new interface ('I2') owned by a different device ('D2')
4. Try to set that new tuple (Interface-I2, IP-A1) as the primary IP for the device 'D2'

### Expected Behavior
As far as I can reassign the IP address to a new interface (which is completely logical), I should be able to set it as primary_ip on the new device.

### Observed Behavior
Response from the UI (device edit): Device with this Primary IPv4 already exists.
Response from the API (PATCH /api/dcim/devices/<device-D2_id>/): 

HTTP 500: 
```
duplicate key value violates unique constraint &quot;dcim_device_primary_ip4_id_key&quot;
DETAIL:  Key (primary_ip4_id)=(<IP-A1_id>) already exists.
```

**Comment by juan-vg** [comment] 2019-08-30 08:57
Hello @jeremystretch 

Yes, I'm performing that change (and the others) via the API

**Comment by juan-vg** [comment] 2019-09-02 13:55
Are you telling me that this behaviour only happens when using the API? Is the UI the one triggering the release? :(

**Comment by DanSheps** [comment] 2019-09-06 18:44
juan-vg,

You are removing the IP from the interface but otherwise leaving it in the database correct?  The current setup is a foreign key on the Device table pointing to the primary ip.

Instead of re-assigning to a new device, you should delete the IP and re-create it on a new device.  The UI can handle this gracefully as the UI generally requires more logic in the controllers whereas for the most part, with the API we run off of serializers so it doesn't take into account secondary events such as assigning an IP to a different device then wanting to set that IP as the primary.

If you want to do this, you should:

1. Delete the IP
2. Recreate it on the new device

or

1. Unassign the IP as primary
2. Attach it to the new device
3. Assign it as primary

I am going to look into possible ways to clean this up however.

**Comment by jeremystretch** [comment] 2019-10-09 20:12
To be clear, it is intended behavior to not let an IP be moved from device A to device B while being assigned as the primary IP for device A. The parent device/VM needs to be modified to remove the assignment as primary IP before the IP can be reassigned. However, there is currently no validation in place to prevent this (via the API), so I'm calling it a bug.

**Closed** 2019-10-09 20:22 UTC
Labels: status: accepted, type: bug
