### ISSUE TITLE
Add image attachments to circuits

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/netbox#7322] opened 2021-09-21 07:31 UTC
### NetBox version

v2.11.12

### Feature type

New functionality

### Proposed functionality

Add an option to add image attachments to circuits

When going to the circuit details page:
`https://<netboxip>/circuits/circuits/<circuitid>/`

A box with image attached are seen and additional information regarding how the links are terminated can be provided.

### Use case

It helps documenting better critical situations where circuit termination may not be easy to find. 

### Database changes

Add the image attachment fields to the circuit model

### External dependencies

none

**Comment by DanSheps** [comment] 2021-09-22 13:01
> ### NetBox version
> v2.11.12

Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.0.3. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by jcralbino** [comment] 2021-09-22 15:44
@DanSheps 
Thanks for you feedback.
I believe this is not working now , I would say it is a new added functionality not a bug .
I have seen similar request where we wanted to add image attachment to other objects

**Comment by jcralbino** [comment] 2021-09-22 15:46
https://github.com/netbox-community/netbox/issues/6708

**Comment by DanSheps** [comment] 2021-09-22 15:57
Sorry, still, are you running 3.0.3?

If so, we still won't be adding this for 2.11, you need to verify this is also not possible on 3.0.3 (demo instance is fine)

**Comment by jeremystretch** [comment] 2021-09-27 16:14
@jcralbino can you comment on #6708 in favor of adding support for circuits as well? Best to keep all related additions under the one issue. Thanks!

**Closed by jeremystretch** 2021-09-27 16:14 UTC
Labels: type: feature, status: revisions needed
