### ISSUE TITLE
Ability to attach other file types  PDF/DOCX/XLSX/CSV to  sites and other objects

### ISSUE THREAD

**Issue by warriorsoul15** [netbox-community/netbox#5783] opened 2021-02-10 18:03 UTC
### Environment
* Python version:  3
* NetBox version:  2.10.1

### Proposed Functionality
It would be very handy to not limit attachments to images, but also have the ability to upload PDF, CSV, and other file types especially when it comes to site documentation

### Use Case
For example we use commerical datacenters and we receive "onboarding guides" from them with process and procedure for nearly everything.  Being able to attach that directly in netbox and not have to host on an external link would be very handy.

### Database Changes
I think files are stored on the filesystem

### External Dependencies
none as far as I know although I dont know what lib you are using for the image uploads.

**Comment by jeremystretch** [comment] 2021-02-10 18:15
Duplicate of #3404, #1039. BCP is to store the files in a purpose-built store and link to them from NetBox using comments or custom links.

**Closed by jeremystretch** 2021-02-10 18:15 UTC
