### ISSUE TITLE
Rackgroup names should only be unique within a parent group

### ISSUE THREAD

**Issue by martink2** [netbox-community/netbox#5248] opened 2020-10-17 16:43 UTC
### Environment
* Python version: 3.6.9
* NetBox version: 2.9.3

After the upgrade to 2.9 we are trying to use the 
hierarchical rack groups to introduce a proper 
representation of our DC environment like:

DC1
-Cage1
--Row1
---Rack1
-Cage2
--Row1
---Rack1
--Row2
---Rack1
---Rack2

### Steps to Reproduce
1. In site A create rack group Cage1
2. In site A create rack group Cage2
3. In site A create rack group Row1 with parent Cage1
4. In site A create rack group Row1 with parent Cage2

### Expected Behavior
We would expect that the name of a group must only be unique within its parent group
as is allowed with racks (two racks in the same site can have the same name in different groups).

### Observed Behavior
Following error is given on creation of the second Row1:
```
Rack group with this Site and Name already exists.
Rack group with this Site and Slug already exists.
```

**Comment by jeremystretch** [comment] 2020-10-19 13:21
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Closed** 2020-10-30 13:38 UTC
Labels: status: revisions needed
