### ISSUE TITLE
tenants (in circuits list) sorted incorrectly

### ISSUE THREAD

**Issue by opericgithub** [netbox-community/netbox#7165] opened 2021-09-03 13:14 UTC
### NetBox version

v3.0b

### Python version

3.7

### Steps to Reproduce

open circuits list.
sort it by tenants. 

### Expected Behavior

tenants (in circuits list) should be sorted alphabeticaly.

### Observed Behavior

tenants (in circuits list) should be sorted alphabeticaly. instead, they are sorted first by tenant group, then alphabeticaly.
for example, I have tenant group "1" with tenants X, Y, Z, and tenant group "2" with tenants A, B and C.
in circuits list they are sorted as X, Y, Z, A, B, C, instead of A, B, C, X, Y, Z.

**Comment by DanSheps** [comment] 2021-09-03 15:51
This is consistent with the rest of the GUI.  Marking this as a feature, not a bug and it will be under review until we get more feedback.

**Comment by jeremystretch** [comment] 2021-09-03 16:59
This was already raised in #6988.

**Closed by jeremystretch** 2021-09-03 16:59 UTC
Labels: type: feature, status: under review
