### ISSUE TITLE
Cannot create Vlan-Group with site_id, also create vlan in vlan-group (with group option)

### ISSUE THREAD

**Issue by Vadims06** [netbox-community/netbox#4529] opened 2020-04-23 15:24 UTC
### Environment
* Python version: 3.6.8
* NetBox version: 2.8.0

Attempt to create vlan-group with **site** attribute using POST method.
Attempt to create vlan inside vlan-group using **group** attribute in POST method.
### Steps to Reproduce
1. Make POST request with '**site**' attribute for creating vlan-group with data = {'name': 'vlan_group_name', 'slug': 'vlan_group_name', 'site': site_id_of any site}. 
2. Make POST request to create vlan inside vlan-group using **group** attribute, e.x. data = {'vid': 1, "name": 'default, "site": site_id_of any site, 'group': vlan_group_id}

### Expected Behavior
1. Creation of vlan-group in site
2. Creation a vlan inside vlan-group

### Observed Behavior
I get the following error
&#x27;**UniqueTogetherValidator**&#x27; **object has no attribute** &#x27 them I make both POSTs

**Comment by DouglasHeriot** [comment] 2020-04-24 12:27
This is a duplicate of #4496, just fixed in the recent v2.8.1 release

**Closed** 2020-04-24 12:59 UTC
Labels: status: duplicate
