### ISSUE TITLE
Create clickable link from Tags view

### ISSUE THREAD

**Issue by robbagithub** [netbox-community/netbox#5110] opened 2020-09-09 06:31 UTC
### Environment
* Python version:  3.6.9 
* NetBox version:  2.9.2 

### Proposed Functionality
In the Tag view, after returning results for a particular set of tags, it would be very useful to have a link to return the items referenced by that tag by clicking the number of items in the view.

The area where I think the link should go is in the red rectangle on the screenshot below

![image](https://user-images.githubusercontent.com/22147754/92562735-c9fe9e00-f2b9-11ea-9d4f-344019f706e4.png)

### Use Case
The use is to quickly show these objects rather than navigating to the devices page, enter the tag value and search from there.

### Database Changes
Don't foresee any DB change required

**Comment by jeremystretch** [comment] 2020-09-09 13:37
Duplicate of #5057

**Closed by jeremystretch** 2020-09-09 13:37 UTC
