### ISSUE TITLE
Can't assign a VLAN that has no site assigned to a prefix that has a site assigned

### ISSUE THREAD

**Issue by schmittvictor** [netbox-community/netbox#9257] opened 2022-04-29 13:26 UTC
### NetBox version

v3.2.1

### Python version

3.8

### Steps to Reproduce

Assign a VLAN that has no site to a prefix that has a site

### Expected Behavior

Assign a VLAN that has no site to a prefix with a site.

### Observed Behavior

Can't assign a VLAN that has no site assigned to a prefix that has a site assigned.

The only way to do it is to first assign the VLAN and then assign the site to the prefix.

**Comment by DanSheps** [comment] 2022-05-02 17:17
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Closed by DanSheps** 2022-05-02 17:17 UTC
Labels: type: bug
