### ISSUE TITLE
Optional Hidden setting for Custom Fields

### ISSUE THREAD

**Issue by sol1-matt** [netbox-community/netbox#9456] opened 2022-06-01 07:12 UTC
### NetBox version

v3.2.1

### Feature type

New functionality

### Proposed functionality

Add a checkbox to custom fields `Hidden` that will hide the field in the UI, essentially rendering it read only from a user perspective. 

The field would appear, and be updatable, in the api.

Allow these fields to able to be modified in conjunction with Custom Validation.

eg: a device name gets custom validated according to the required spec (lowercase, [0-9,a-z] only and unique) and stored in the hidden custom field.

### Use case

Allows Netbox to maintain data related to a object without cluttering up the UI.

This would be useful for any external systems that currently use slugs to implement a replacement key to safely address and reference objects according to their needs meaning Netbox would not need to maintain slugs any more (#8113).

The combination of hidden custom field and functionality in custom validator to update the field value means the custom field becomes a unique key meeting the specific requirements of Netbox integrators that is validated at entry time and maintained by the source of truth.

### Database changes

New boolen field on `extras/custom-fields` `hidden`.

**Comment by kkthxbye-code** [comment] 2022-06-01 08:53
Duplicate of #9166 

If I misread the request let me know and I'll reopen.

**Closed by kkthxbye-code** 2022-06-01 08:53 UTC
Labels: type: feature

**Comment by DanSheps** [comment] 2022-06-01 13:33
Duplicate of #9166
