### ISSUE TITLE
Allow non-unique region names

### ISSUE THREAD

**Issue by jabehnken** [netbox-community/netbox#7950] opened 2021-11-29 22:18 UTC
### NetBox version

v3.0.9

### Feature type

Change to existing functionality

### Proposed functionality

Remove the uniqueness constraint on regions, so that multiple objects can be created with the same name. As an alternative to removing the uniqueness altogether, a combination of parent region, and region name could be used instead of region name alone.

### Use case

The need was discovered when abbreviating Canada and California using their standard ISO 2 letter code CA. When inputting the second region with the same name, an error is received indicating another region with the same name already exists. The error comes up twice if the slug is the same. While abbreviations may not be the best practice for use in Regions, the same issue occurs using city names. An example:

United States of America
  - Missouri
     - Springfield
  - Nebraska
     - Springfield
  - Ohio
     - Springfield

**Comment by DanSheps** [comment] 2021-11-30 15:51
We would need to change the enforcement of uniqueness, currently it is done in the database.

We should not have duplicate region names within the same parent region, so I think enforcing uniqueness on parent + region would be ideal.

One gotcha is that we would need to either do the check in code (thus allowing you to bypass it using raw database calls) or through a unique index that coaleses the two strings as each null is "different" when looking at the PoV of the database (parent=None, name="Springfield") and (parent=None, name="Springfield") are considered Unique because the parent is null

I am going to put this up for volunteers.

**Comment by jeremystretch** [comment] 2021-12-01 14:29
This change should be replicated to site groups as well, as they parallel regions.

**Comment by jabehnken** [comment] 2021-12-01 20:58
Is this a duplicate that may already be getting implemented in 3.1?

https://github.com/netbox-community/netbox/issues/7354

**Comment by DanSheps** [comment] 2021-12-01 21:10
You are absolutely correct.

**Comment by DanSheps** [comment] 2021-12-01 21:11
Duplicate of #7354

**Closed** 2021-12-01 21:11 UTC
Labels: status: duplicate, type: feature

**Comment by jeremystretch** [comment] 2021-12-02 00:11
I knew this sounded super familiar but couldn't find the other issue for some reason.
