### ISSUE TITLE
unable to assign FHRP group if interface has an IP address assigned

### ISSUE THREAD

**Issue by lanman9000** [netbox-community/netbox#15197] opened 2024-02-20 16:03 UTC
### Deployment Type

Self-hosted

### NetBox Version

3.7.2

### Python Version

3.8

### Steps to Reproduce

Create an FHRP group
Create a device
Create an interface on the device
Assign an IP address to the interface
Attempt to assign an FHRP group to the interface

### Expected Behavior

You should see the FHRP group you created show up in the drop down list for FHRP assingments

### Observed Behavior

The FHRP group assignment dropdown is empty.

If you remove the IP address from the interface, you are then able to successfully assign an FHRP group to the interface. You can then assign the IP address to the interface.
But, it seems this bug only presents itself if the interface already has an IP address assigned.

**Comment by jeremystretch** [comment] 2024-02-20 20:53
This is working as intended. Because the interface has an IP address assigned to it, NetBox returns only FHRP groups which have a related IP address assigned. For instance, if you assign the IP address 192.168.1.123/24 to the interface, an FHRP group with the IP address 192.168.1.1/24 will be listed as an option for assignment. This is done for convenience, so that the user doesn't have to search through potentially thousands of irrelevant groups.

If you add an IP address to the group created in step one in the same prefix as the IP address created in step 4, you'll see that the group is able to be assigned to the interface.

**Closed by jeremystretch** 2024-02-20 20:53 UTC
Labels: type: bug

**Comment by lanman9000** [comment] 2024-02-20 21:02
So why can't it also be allowed "for convenience" to add to FHRP groups in which the IP is not in the same prefix. You can certainly parse a list of FHRP groups that the in the same IP prefix and present only those in the initial clicking of the drop-down menu, but if I specifically type an FHRP group number into the filter/search box during the FHRP assignment, why can't I return those results?

Convenience works both ways.
