### ISSUE TITLE
Doesn't change time zone

### ISSUE THREAD

**Issue by Hidmink** [netbox-community/netbox#16456] opened 2024-06-09 14:26 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.0.5

### Python Version

3.12

### Steps to Reproduce

1. Change config file in '/opt/netbox/netbox/netbox/configuration.py' in SystemParametrs TIME_ZONE to any other timezone are not applied. 

### Expected Behavior

Applying settings TIME_ZONE in configuration file.

### Observed Behavior

Apply defaults - UTC.

**Comment by arthanson** [comment] 2024-06-10 14:46
@Hidmink can you please add to the description where the timezone is not being applied?  Is it in a display or when processing an event?

**Comment by kuhball** [comment] 2024-06-11 06:08
Just noticed this as well while migrating our prod instance. For us the timezone is not applied within the ui (f.e. changelog).

**Comment by PaulR282** [comment] 2024-06-11 12:00
Same problem here. The right time is displayed on the bottom right but it is UTC in the changelog

**Comment by shaderecker** [comment] 2024-06-11 12:44
I also noticed the issue for Scheduled Scripts.
The displayed time of our Netbox in the bottom right is CEST.
However once I schedule a script it is always scheduled two hours earlier than selected in the UI. So it is scheduled in UTC.

**Comment by arthanson** [comment] 2024-06-13 14:47
This looks like a dupe of #16143 this should be fixed in next release from change in #16323 . Closing

**Closed by arthanson** 2024-06-13 14:47 UTC
Labels: type: bug, status: revisions needed

**Comment by samk-acw** [comment] 2024-07-01 02:37
can this be reopened? https://github.com/netbox-community/netbox/pull/16323 appears to only have resolved the issue in table columns, the timezone is still inconsistent in multiple places in the interface:

For example, my server (running v4.0.6) is set to AEST and I took these screenshots around 12pm:

-  looking at an object change directly shows UTC:
![image](https://github.com/netbox-community/netbox/assets/55128650/12c2fc0f-2ae0-45cd-9b25-bb8cd547a95a)

- the created and updated timestamps on object views shows as UTC
![image](https://github.com/netbox-community/netbox/assets/55128650/ea62100e-8b59-4f53-8c93-5a921ec67733)

- running scripts show both UTC and local
![image](https://github.com/netbox-community/netbox/assets/55128650/f2abddd7-b990-4e45-83ff-fa38a3d48f08)

I think the issue is the isodate/isodatetime filters don't load any timezone preference
