### ISSUE TITLE
Render configuration templates natively on virtual machines

### ISSUE THREAD

**Issue by aauerswald** [netbox-community/netbox#13085] opened 2023-07-04 11:53 UTC
### NetBox version

v3.5.3

### Feature type

New functionality

### Proposed functionality

Please add the render configuration templates also to virtual machines, like it was also requested in the originally feature request [#11559](https://github.com/netbox-community/netbox/issues/11559)

### Use case

With these functionality and provisioning tools like Ansible we can simplify the deployment or configuration process also for virtual machines.

**Comment by abhi1693** [comment] 2023-07-04 12:25
Duplicate of #12461

**Closed** 2023-07-04 12:25 UTC
Labels: status: duplicate, type: feature
