### ISSUE TITLE
Show device description in rack elevation

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#14991] opened 2024-01-31 04:01 UTC
### NetBox version

v3.7.0

### Feature type

Change to existing functionality

### Proposed functionality

I'd like to have a user preference to show both the device name and description in rack elevation images.
Taking it a step further, you could define a custom format with any combination of fields.

### Use case

The way my devices are named is regex-friendly, but not easy for humans to read.  For example, set-top boxes are called STB001, STB002, STB003, etc.  I use the description field for the human-friendly names like **Apple TV (screen)**, **Apple TV (booth)**, **Roku**, etc.  This works great in my Grafana dashboards where I label everything with a combination of `description` and `location` tags.

My current rack elevation looks like this:

<img width="267" alt="image" src="https://github.com/netbox-community/netbox/assets/3991046/dd002c67-f064-4305-b973-24508f94a085">

The Netbox device selector dialog already does what I want, showing both fields:
<img width="590" alt="image" src="https://github.com/netbox-community/netbox/assets/3991046/e3f03730-cc6c-4ee2-8e39-cb66f70b806a">

**Comment by PieterL75** [comment] 2024-01-31 08:45
I had a similar propasal to display the assettag, but that got declines, because it was too specific.
So I created a new FR https://github.com/netbox-community/netbox/issues/14205, that could allow everyone to create custom racklabels and toasts

**Comment by DanSheps** [comment] 2024-01-31 16:10
Duplicate of #14025

**Closed by DanSheps** 2024-01-31 16:10 UTC
Labels: type: feature

**Comment by jeffgdotorg** [comment] 2024-06-06 16:08
Correcting the record:
Duplicate of #14205

**Comment by jeffgdotorg** [comment] 2024-06-06 16:09
Duplicate of #14205
