### ISSUE TITLE
Add Rack position (X,Y,Theta)

### ISSUE THREAD

**Issue by mrshahabian** [netbox-community/netbox#5044] opened 2020-08-24 15:03 UTC
### Environment
* Python version:  3.6.9 
* NetBox version:  2.8.9 

### Proposed Functionality
We need to add rack position to find them by their location in order to add them in an upstream visualizing application.

**Comment by jeremystretch** [comment] 2020-08-24 15:06
Duplicate of #114. You might consider implementing this as a plugin.

**Closed by jeremystretch** 2020-08-24 15:06 UTC
