### ISSUE TITLE
Reducing the amount of clicks required to create multiple Front Ports.

### ISSUE THREAD

**Issue by Chiniquy** [netbox-community/netbox#12559] opened 2023-05-11 08:21 UTC
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

When making multiple front ports, one used to be able to simply drag and select multiple rear ports to assign the front ports to. 
Some time during the past few weeks (I am not sure which exact version introduced the change) this behavior changed.

Today when making multiple front ports, such as in the attached image, one is required to manually click each and every rear port or rear port position to create the front ports. This has made the process of creating multiple front ports tedious and time consuming. 

I am suggesting to either reverse the change to allow the old click-and-drag selection of multiple rear ports, or to introduce new functionality inside the new selection tool to allow the selection of multiple rear ports without closing the selection tool - perhaps by holding shift (common in tools such as Excel and Word).

![image](https://github.com/netbox-community/netbox/assets/10709382/ac050ffa-47c7-4c6f-a98c-683494929eef)

### Use case

This change will reduce both the amount of clicks and the time required to create multiple front ports on devices.

**Comment by kkthxbye-code** [comment] 2023-05-11 08:54
Duplicate of https://github.com/netbox-community/netbox/issues/12550

Remember to search before creating an issue. It can also help checking the upcomming release notes:

https://github.com/netbox-community/netbox/blob/develop/docs/release-notes/version-3.5.md

**Closed by kkthxbye-code** 2023-05-11 08:54 UTC
Labels: type: feature
