### ISSUE TITLE
asset_tag sometimes not imported when first field in CSV import

### ISSUE THREAD

**Issue by duckw** [netbox-community/netbox#11928] opened 2023-03-08 10:45 UTC
### NetBox version

v3.4.5

### Python version

3.9

### Steps to Reproduce

On a device import, paste in the following CSV:

```
asset_tag,serial,device_type,location,manufacturer,device_role,status,site
473565,ABC9876BJ3G,C9200-48P,Row 1,Cisco,Access Switch,inventory,MDF
```

Delete object and try importing as follows instead:
```
serial,device_type,location,manufacturer,device_role,status,site,asset_tag
ABC9876BJ3G,C9200-48P,Row 1,Cisco,Access Switch,inventory,MDF,473565
```

### Expected Behavior

Asset tag is reliably imported each time.

### Observed Behavior

Asset tag is not imported on the first example, but is correctly imported on second example.

Note: In some instances it does import the asset tag but the examples above have been tested on the demo site.

**Comment by kkthxbye-code** [comment] 2023-03-08 10:51
Both work just fine for me. I assume you are giving incorrect replication steps (please try your own steps, copy/paste directly from this issue etc.) and your issue is actually a duplicate of this:

https://github.com/netbox-community/netbox/issues/11850

As I cannot replicate this, you will have to update the replication steps.

**Comment by duckw** [comment] 2023-03-08 11:05
You are right that this a duplicate.  Saving what I had on the clipboard off, I noticed the UTF-8 BOM was caught in the header from the Excel export.

If #11850 proposes the stripping of such, I'd like to suggest combining with my feature request #11929 to strip whitespace too.

**Comment by kkthxbye-code** [comment] 2023-03-08 11:07
Duplicate of https://github.com/netbox-community/netbox/issues/11850

**Closed by kkthxbye-code** 2023-03-08 11:07 UTC
Labels: type: bug, status: revisions needed
