### ISSUE TITLE
The Virtual Machines tab on a Site does not update

### ISSUE THREAD

**Issue by LucasCarter45** [netbox-community/netbox#16752] opened 2024-06-27 14:26 UTC
### Deployment Type

NetBox Cloud

### NetBox Version

v3.7

### Python Version

3.10

### Steps to Reproduce

1. Create a Site
2. Create a Virtual Machine and assign to the site
3. Go to the site and, under related objects, see Virtual Machines 

### Expected Behavior

On a Site, under Related Objects, Virtual Machines should update with the amount of virtual machines assigned to the site

### Observed Behavior

The Virtual Machines never changes from zero

**Comment by jeremystretch** [comment] 2024-07-01 13:45
> v3.7

This is not a complete NetBox version: Please specify the exact version of NetBox you are running when submitting a bug report.

I am not able to reproduce this on NetBox v4.0.6. If this was a bug, it has likely been fixed in a more recent release. If you can reproduce this on the latest stable release of NetBox and provide instructions for doing so, you are welcome to request that this issue be re-opened.

**Closed by jeremystretch** 2024-07-01 13:45 UTC
Labels: type: bug, status: needs triage
