### ISSUE TITLE
Rack layout hyperlink redirects to IP address not domain

### ISSUE THREAD

**Issue by danb223** [netbox-community/netbox#4599] opened 2020-05-07 13:59 UTC
### Environment
* Python version: 3.6.8
* NetBox version: 2.8.2

Open page which shows front and back of rack. Hyperlinks of devices refer to IP address of server rather than the domain. All other links within netbox show the domain in the hyperlink.
Example link shows as https://10.1.1.2/dcim/devices/26/ rather than https://domain.com/dcim/devices/26/

### Steps to Reproduce
Go to rack page, check hyperlink for devices in rack diagram.

### Expected Behavior
Link to be domain.com

Link instead reverts to IP of server unlike every other hyperlink within netbox.

**Comment by jeremystretch** [comment] 2020-05-07 14:02
Duplicate of #4526

**Closed by jeremystretch** 2020-05-07 14:02 UTC
