### ISSUE TITLE
support cyrillic at .cds export\import

### ISSUE THREAD

**Issue by TristisOris** [netbox-community/netbox#7247] opened 2021-09-10 16:12 UTC
### NetBox version

3.0.2

### Python version

3.8

### Steps to Reproduce

1. export devices with cyrillic fields to .csv (location, etc)
2. open .csv

### Expected Behavior

get a info.

### Observed Behavior

bad coding instead info.

`,,РќРРР¤,104,,,,`

**Comment by jeremystretch** [comment] 2021-09-10 16:21
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by TristisOris** [comment] 2021-09-10 17:39
- create a region, site, location with cyrillic names.
- add it to device
![изображение](https://user-images.githubusercontent.com/1270117/132894662-d96489c7-d1da-4fd0-8443-06b9fbfdc9d5.png)

no config changes. i have nothing to say more.

**Comment by jeremystretch** [comment] 2021-09-13 13:40
> i have nothing to say more.

Okay, closing this because you've not provided any sample content for someone else to use when replicating the reported behavior.

**Closed by jeremystretch** 2021-09-13 13:40 UTC
Labels: type: bug, status: revisions needed
