### ISSUE TITLE
Exception when sorting Services by Parent field

### ISSUE THREAD

**Issue by wfr1** [netbox-community/netbox#4654] opened 2020-05-18 07:28 UTC
### Environment
* Python version: 3.6.8
* NetBox version: 2.8.4

### Steps to Reproduce
1. Open following url: [https://master.netbox.dev/ipam/services/?sort=parent](https://master.netbox.dev/ipam/services/?sort=parent) or
2. Navigate IPAM -> Services and click on Parent to sort

### Expected Behavior
Sort by Parent Field.

### Observed Behavior

![Screenshot_2020-05-18 Server Error](https://user-images.githubusercontent.com/61692489/82185616-c8affc80-98e9-11ea-96bc-7e0ad93565b9.png)

<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword 'parent' into field. Choices are: created, custom_field_values, description, device, device_id, id, ipaddresses, last_updated, name, port, protocol, tagged_items, tags, virtual_machine, virtual_machine_id

**Comment by hoalex** [comment] 2020-05-18 10:22
Duplicate of #4644.

**Closed** 2020-05-18 13:01 UTC

**Comment by wfr1** [comment] 2020-05-18 13:28
Sorry, searched for this problem, but completely missed it. Thx for your continous effort.
