### ISSUE TITLE
'ImageDraw' object has no attribute 'textsize'

### ISSUE THREAD

**Issue by gablesm** [netbox-community/netbox#13173] opened 2023-07-13 03:29 UTC
### NetBox version

v3.5.5

### Python version

3.10

### Steps to Reproduce

1. click on devices
2. click on any established device

### Expected Behavior

the pre-established device details should appear

### Observed Behavior

error: 

<class 'AttributeError'>

'ImageDraw' object has no attribute 'textsize'

Python version: 3.10.6
NetBox version: 3.5.6

![image](https://github.com/netbox-community/netbox/assets/1297480/3f6e5d7b-03d7-49fe-9e64-0b1def782332)

**Comment by abhi1693** [comment] 2023-07-13 03:44
Duplicate of #13115

**Closed** 2023-07-13 03:44 UTC
Labels: status: duplicate
