### ISSUE TITLE
Bulk editing of interface VLAN assignments

### ISSUE THREAD

**Issue by jenslink** [netbox-community/netbox#2160] opened 2018-06-12 08:51 UTC
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.3
* NetBox version:  2.3.3 

### Description

It would be nice if you could assign a VLAN to several interfaces at once.  When going to the device view and selecting several interfaces and edit them I can change description, mode, ... but it would be nice so set the VLAN  as well.

**Comment by lampwins** [comment] 2018-07-03 01:50
Just realized we pulled bulk edit of 802.1Q settings at the last minute but we never opened an issue to add it back.

My initial thought is to use the existing 802.1Q workflow for individual interfaces to build a new bulk edit view specifically for this purpose. I don't see a good way to reuse the existing bulk object edit view and we certainly should reuse the existing 802.1Q workflow.

**Comment by morten-starvik** [comment] 2019-06-19 09:13
What happened to this feature request? The referenced issue just loops back to this one...

**Comment by Wax-Trax** [comment] 2019-06-27 19:58
I'd like to second this feature request. Thank you

**Comment by DanSheps** [comment] 2019-06-27 20:03
@morten-starvik The referenced issue is because that issue is a duplicate of this issue.

**Closed** 2019-09-06 17:45 UTC
Labels: status: accepted, type: ui
