### ISSUE TITLE
multiple mac address on one interface

### ISSUE THREAD

**Issue by ba31** [netbox-community/netbox#4394] opened 2020-03-21 12:41 UTC
It seems netbox interface does not support to capture multiple mac address on one interface. Is there any plan to onboard this feature ?

**Comment by DanSheps** [comment] 2020-03-22 13:55
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by DanSheps** [comment] 2020-03-22 13:56
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Closed by DanSheps** 2020-03-22 13:55 UTC
