### ISSUE TITLE
Cables remain after device is deleted

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#16727] opened 2024-06-26 00:04 UTC
### Deployment Type

NetBox Enterprise

### NetBox Version

v4.0.5

### Python Version

3.12

### Steps to Reproduce

1. Create a new device with interface and power port
2. Connect the interface and power port to some other device
3. Delete the device

### Expected Behavior

The power and ethernet cables should be deleted automatically

### Observed Behavior

Those 2 cables remain with one termination empty, so I have to go find and delete them.
<img width="602" alt="image" src="https://github.com/netbox-community/netbox/assets/3991046/0c181f49-61f7-4f41-bd90-087395c041d9">
<img width="597" alt="image" src="https://github.com/netbox-community/netbox/assets/3991046/8e6e23b5-593a-4383-87b3-0cc74597b306">

**Comment by jeffgdotorg** [comment] 2024-06-26 19:44
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #10769 for further discussion. In particular, note it's possible to filter the list of cables to show only ones that are unterminated, which should help in the hunt for ones that need culling.

**Comment by jeffgdotorg** [comment] 2024-06-26 19:44
Duplicate of #10769

**Closed by jeffgdotorg** 2024-06-26 19:44 UTC
Labels: type: bug, status: needs triage
