### ISSUE TITLE
Bug with tags section.

### ISSUE THREAD

**Issue by gaussk32** [netbox-community/netbox#5147] opened 2020-09-18 17:34 UTC
### Environment
* Python version: 3.8.2
* NetBox version: 2.9.3

    We have upgraded our netbox from version 2.8.3 to 2.9.3 after following the steps 
https://netbox.readthedocs.io/en/stable/installation/upgrading/
we found a problem with the tags section. Organization -> Tags
in the previous version 2.8.3 every Tag name shown on the list is a clickable element  when you click this element it shows every tagged element using this tag, sites, devices, ipaddresses, interfaces, etc.
In version 2.9.3 every element on the tags section  Organization -> Tags is not a clickable element is just a string.

### Steps to Reproduce
1. Upgrade the system with system from version 2.8.3 to 2.9.3
2. Also happens if you upgrade from version 2.8.3 to 2.9.2
3. Same if you make a fresh install. 

### Expected Behavior
Every element on section tags should be a clickable element. 

### Observed Behavior
Every element on tags sections is a string is not clickable.

**Comment by jeremystretch** [comment] 2020-09-18 17:41
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Comment by gaussk32** [comment] 2020-09-18 17:48
So if i want to search all the elements tagged with one tag i have to search in every section and filtering with the tag?
one search in regions, one search in interfaces, one search in devices, one search in ip addresses?
This is really inconvenient, i think this is a bug not intended behavior, because in all the previous versions every tag was  a clickable element.
Also with this upgrade all my previously created tags cannot be asigned to the devices, and if i go to devices section when i try to filter with one tags, none is shown in the drop down list.

**Comment by jeremystretch** [comment] 2020-09-18 17:55
Please see #5057. This is not a bug.

**Closed by jeremystretch** 2020-09-18 17:55 UTC
