### ISSUE TITLE
CSV Cables export does not reflect what webui shows

### ISSUE THREAD

**Issue by m384wwn** [netbox-community/netbox#4436] opened 2020-04-01 19:54 UTC
### Environment
* Python version:  python/eoan 2.7.17-1 amd64
* NetBox version:   (v2.7.11)

### Steps to Reproduce
1. Make sure you have cables.
2. Devices > Cables
3. Export
4. View CSV file

Column "termination_a_type" and "termination_b_type" should show device names like the webui shows.
--

### Observed Behavior
Column "termination_a_type" and "termination_b_type"  shows "dcim.interface" and "dcim.rearport" instead. 

--

**Comment by jeremystretch** [comment] 2020-04-02 13:46
Duplicate of #4429.

**Closed by jeremystretch** 2020-04-02 13:46 UTC

**Comment by m384wwn** [comment] 2020-04-02 16:07
I don't see how this is a duplicate at this has nothing to do with importing?
