### ISSUE TITLE
Return to circuit after editing termination

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#10599] opened 2022-10-07 10:15 UTC
### NetBox version

v3.2.9

### Python version

3.9

### Steps to Reproduce

1. Create a circuit
2. in the circuit page, create a termination (returns properly to the circuit)
3. in the circuit page, edit the termination and save

### Expected Behavior

The edit page returns to the circuit or site

### Observed Behavior

The edit page returns to the termination details, rather than the ciruit

**Comment by jeremystretch** [comment] 2022-10-07 19:42
> The edit page returns to the termination details, rather than the ciruit

I'm not able to reproduce this. Upon editing the circuit termination, I'm returned to the circuit view as expected. Additionally, there is no circuit termination detail view.

**Comment by PieterL75** [comment] 2022-10-07 20:53
How bizar. On the demo instance it also works as expected. Going to look further on the exact steps I take to get this behavior

P

**Comment by PieterL75** [comment] 2022-10-10 20:38
I'm still running v3.2.9 and not 3.3
in 3.2.9, the edit button has this : https://netbox/circuits/circuit-terminations/2/edit/
while in 3.3.5, the url says https://netbox/circuits/circuit-terminations/2/edit/?return_url=/circuits/circuits/3/

It was added here https://github.com/netbox-community/netbox/commit/a5124ab9c835896ff434812bf870d1add82a3afe#diff-b5dc17ee33380308d801286d162870c4173b3f2c0180ee510acdf895720537f6 by #8511 
but maybe the 
https://github.com/netbox-community/netbox/blob/develop/netbox/circuits/models/circuits.py#L216
get_absolute_url needs an update ?

**Comment by jeremystretch** [comment] 2022-10-14 12:18
@PieterL75 possibly; we can discuss that under a separate FR.

I'm goin gto close this issue as the reported issue cannot be reproduced on the current release AFAICT.

**Closed** 2022-10-14 12:19 UTC
Labels: type: bug, status: revisions needed
