### ISSUE TITLE
Wrong trace when multiple rear(multi position) cable.

### ISSUE THREAD

**Issue by joaolucasmacedo** [netbox-community/netbox#16571] opened 2024-06-14 00:13 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.0.5

### Python Version

3.10

### Steps to Reproduce

1. Create 2 devices with 2 module bays each. Each device is a fiber patch panel capable to accept fiber splice cassettes.
2. Create a module type (a fiber cassette) with 1 rear port with 12 position (to represent a fiber cable splice for 12 fibers), and 12 front ports (to represent 6 LC connectors).
3. Add 2 cassettes as modules on devices.
4. Connect 2 cables on both rear ports on devices. As 2 12 fiber cables connecting 2 fiber patch panels.
5. Connect any regular device's interface using one front (LC) port from one cassette and other from other cassette. Think if you need to use a pair of fibers to connect 2 switches thorough these 2 fiber patch panels but using different rear cables.

### Expected Behavior

To trace the 2 interfaces properly. 

### Observed Behavior

It says "Asymmetric path!" showing a non related switch's interface.

See 2 fiber patch panels with 2 cassettes each, "DIO X1" and "DIO X2".
Each cassette gives a 12 position rear port and 12 LC front ports.
The patch panels are connected by 2 12 fiber cables on both cassettes.
![image](https://github.com/netbox-community/netbox/assets/66760118/af70aab3-1223-4aae-815d-f17132b5c2e5)

Lets connect 2 switches, each on a different patch panel. 
![image](https://github.com/netbox-community/netbox/assets/66760118/a7285435-a3e5-427c-b3b8-2308ab2d529f)

The image above shows a switch "SW X1A" interface connecting to 2 LC ports, and the switch on the other side is using the same ports on the other patch panel by the same interface "GigabitEthernet1/0/4".
![image](https://github.com/netbox-community/netbox/assets/66760118/cc918e04-be65-48af-b0a0-d83af4883e1a)

The trace is not completed and the interfaces can't see each other.

![image](https://github.com/netbox-community/netbox/assets/66760118/ad6ea2bf-1aae-4f3f-92e2-5f0aab321d21)

Furthermore, if I use other single LC front port on each patch panel to connect interface "GigabitEthernet1/0/**1**" it show up on "Gi1/0/4" trace saying "Asymmetric Path!", and Gi1/0/1 is shown as Gi1/0/4 peer.

![image](https://github.com/netbox-community/netbox/assets/66760118/8ececd35-ad6f-4e4d-9e5c-c347e8e53e75)

![image](https://github.com/netbox-community/netbox/assets/66760118/0deb94de-c5a9-4d3a-b706-36eff491e784)

Is I delete the cables connecting both Gi1/0/1 interfaces and do the same with any other interfaces this last behavior does not show up.

**Comment by joaolucasmacedo** [comment] 2024-06-18 12:25
@arthanson I tested many scenarios and now I found it looks like  a bug. I did the steps as you said and everything looks fine, but then I tried using modules rather than direct rear ports.
You can see at:
https://demo.netbox.dev/dcim/interfaces/928/trace/

Below is what i think the repro is:
    Create 1 MODULE Type
        Cassete G2 12fo 6 LC
        1 rear port splice {module}
        12 front ports (LC port - splice {module} - [1-6][A-B])
    Create 2 patch panel devices (DIO, named DIO X1 and DIO X2) with 2 module bays (splice [1-2])
    Add 2 modules to each patch panels
    Connect DIO X1:splice 1 to DIO X2:splice 1 and DIO X1:splice 2 to DIO X2:splice 2
    Create 2 switches (Name SW X1A and SW X2A)
    Connect SW X1A G1/0/1 to DIO X1:"LC port - splice 1 - 1A" and DIO X1:"LC port - splice 1 - 1B"
    Connect SW X2A G1/0/1 to DIO X2:"LC port - splice 1 - 1A" and DIO X2:"LC port - splice 1 - 1B"
    View the trace
    Now,
    Connect SW X1A G1/0/2 to DIO X1:"LC port - splice 1 - 6B" and DIO X1:"LC port - splice 2 - 1A"
    Connect SW X2A G1/0/2 to DIO X2:"LC port - splice 1 - 6B" and DIO X2:"LC port - splice 2 - 1A"

If it is not clear, please let me know.

![image](https://github.com/netbox-community/netbox/assets/66760118/6f567852-7a4c-48ac-8349-97a015801096)

**Comment by DanSheps** [comment] 2024-06-18 19:46
Duplicate of #10602

**Closed by DanSheps** 2024-06-18 19:46 UTC
Labels: type: bug, status: revisions needed
