### ISSUE TITLE
Allow the grouping together of virtual interfaces into a LAG or virtual bond interface.

### ISSUE THREAD

**Issue by tomkivlin** [netbox-community/netbox#5384] opened 2020-11-25 16:40 UTC
### Environment
* Python version: 3.7
* NetBox version: 2.8.5

### Proposed Functionality
Allow the grouping together of virtual interfaces into a "LAG" or virtual bond interface.  Suggestions include defining a new interface type (e.g. bond) or allowing the use of parent LAG for virtual interfaces.

### Use Case
My use case is using Netbox configuration data to drive the configuration of machines in MaaS, which then deploys and configures the operating system deployed.  For example a server host might have the following physical interfaces:
- FLR1
- FLR2
- FLR3
- FLR4
- PCI1.1
- PCI1.2

There are also virtual interfaces in Netbox, e.g.:
- eno1
- eno2
- eno3
- eno4
- ens2f0
- ens2f1

Today, I can create a virtual interface of type LAG and then use that as the parent LAG for any of the physical interfaces, but if I try and group the virtual interfaces together - as I would when creating a Linux bond - I get the following error:
![image](https://user-images.githubusercontent.com/52716470/100255976-16ae5880-2f3c-11eb-8d06-6d503f96cd23.png)

### Database Changes
I don't know.

### External Dependencies
I don't know.

**Comment by tomkivlin** [comment] 2020-11-25 16:43
PS I did check but it looks like https://github.com/netbox-community/netbox/pull/5034/commits/f37997ac5433ac0f43ddc1457d4c6c88034d6990 still has this constraint in place.

**Comment by DanSheps** [comment] 2020-11-26 19:44
This should be addressed by #1519

Duplicate of #1519

**Comment by DanSheps** [comment] 2020-11-26 19:44
Duplicate of #1519

**Closed by DanSheps** 2020-11-26 19:44 UTC

**Comment by tomkivlin** [comment] 2020-11-26 20:00
> Duplicate of #1519

@DanSheps ok thanks. I wasn't sure as the example used in the latest comment was about the parent still being physical. If the intent of #1519 is to allow the following relationshis then that's fab!

- Physical interface1---virtual interface1
- Physical interface1---virtual interface2
-Virtual interface1 + virtual interface2 both children of bond0
- Bond0---bond0.100 virtual.interface

Ta
Tom
