### ISSUE TITLE
Clicking column header in Changelog causes panel to nest

### ISSUE THREAD

**Issue by salfers** [netbox-community/netbox#16312] opened 2024-05-28 09:13 UTC
### Deployment Type

Self-hosted

### NetBox Version

4.0.3

### Python Version

3.11

### Steps to Reproduce

1. Open main page / dashboard
2. Click on a column header of the changelog, e.g. "request id"

### Expected Behavior

Table is re-sorted accordingly.

### Observed Behavior

![grafik](https://github.com/netbox-community/netbox/assets/97662717/4d884dad-68ec-42c7-ac69-3c88c5a9686a)

**Comment by ITJamie** [comment] 2024-05-28 11:49
i noticed this this morning too. 
The changelog in the dashboard is sorting by the last sort method when your in the changelog list view. The dashboard changelog should always sort by latest IMHO and ignore sort savings from the changelog list view

**Comment by jeffgdotorg** [comment] 2024-05-29 14:16
Thanks for reporting a problem you've encountered in NetBox.

I've reproduced the problem in the lab and am moving along its status to `needs owner`. I'm assigning it a low severity since the _Operations -> Change Log_ UI is not similarly affected, but we'll put a relatively high priority on addressing it.

**Comment by jeffgdotorg** [comment] 2024-05-29 15:27
Upgraded severity to medium because this issue in fact impacts any dashboard widget that includes a sortable table.

**Closed** 2024-05-31 17:16 UTC
Labels: type: bug, status: accepted, severity: medium
