### ISSUE TITLE
 Set default manufacturer on module insert

### ISSUE THREAD

**Issue by shatt79** [netbox-community/netbox#13553] opened 2023-08-24 22:38 UTC
### NetBox version

v3.5.8

### Feature type

Data model extension

### Proposed functionality

**This was implemented with #9563  in v3.2.5 but hasn't been working.**

When inserting a module into a device, the manufacturer of the module should default to the same manufacturer as the parent device. Eg, if I'm inserting a module into a Cisco ASR-9010, then the manufacturer of the module should be set to Cisco by default.

### Use case

Saves time by not having to select the manufacturer of the module. The manufacturer of the module will almost always be the same as the manufacturer of the parent. The only exception being things like hard drive slots on servers and passive devices like modular distribution frames/patch panels. This is why the mfg field should only default to the parent's mfg and not be a read-only field.

**Comment by sleepinggenius2** [comment] 2023-08-25 14:39
I can confirm that this still works as expected in 3.4, but it looks like it was not carried through when the new object selector was introduced in 3.5. Seems more like a bug to me.

**Comment by jeremystretch** [comment] 2023-12-19 20:22
Reclassifying this as a bug per #9417

**Comment by arthanson** [comment] 2024-04-11 16:16
This is no longer an issue in NB 4, Manufacturer is auto-set and not shown in edit.  Closing

**Closed by arthanson** 2024-04-11 16:16 UTC
Labels: type: bug, status: accepted, severity: low
