### ISSUE TITLE
Modules with Frontport get error in v3.2 beta 2

### ISSUE THREAD

**Issue by rodewalder** [netbox-community/netbox#8978] opened 2022-03-26 17:20 UTC
### NetBox version

v3.2.0-beta2

### Python version

3.9

### Steps to Reproduce

1. Create a Module Type with Rear and Front ports
2. Add a module in a device module bay
3. Click create and you get "<class 'dcim.models.device_components.RearPort.DoesNotExist'>"

### Expected Behavior

The module create work with rear and front port. I use it for modular patchboxes. 

### Observed Behavior

Module Types with interface or only rear ports work, but if a module type has front port it fails

**Comment by jeremystretch** [comment] 2022-03-28 17:45
I'm not able to reproduce this on the current `feature` branch. It's possible that the bug has been resolved inadvertently in a recent change. If you are still able to reproduce the issue, please update your post above to include **exact** reproduction instructions.

**Comment by rodewalder** [comment] 2022-03-28 21:46
If I use for example as rear port {module}/mpo and as frontport {module}/mpo it runs into the error.
If I use the rear port without {module} it works.
There are a problem to setup the front and resr port connection when the module will be created. The right name for the rear port is not availible.

**Closed** 2022-03-31 13:24 UTC
Labels: type: bug, status: accepted, beta
