### ISSUE TITLE
Key Error when adding power feed

### ISSUE THREAD

**Issue by njegsn** [netbox-community/netbox#14222] opened 2023-11-08 21:36 UTC
### NetBox version

v3.6.4

### Python version

3.8

### Steps to Reproduce

1. Browse to power panels
2. Create power panel
3. Browse to power feeds
4. Add power feed
5. Click Create

### Expected Behavior

A new Power Feed should be created with proper attributes.

### Observed Behavior

<class 'KeyError'>

'site'

Python version: 3.11.4
NetBox version: 3.6.4
Plugins: None installed

**Comment by abhi1693** [comment] 2023-11-08 21:40
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by njegsn** [comment] 2023-11-08 23:48
Edited, but in terms of sufficient information, I say just about as much as this issue [https://github.com/netbox-community/netbox/pull/12171](12171). I'm not sure what else I should include.

**Comment by abhi1693** [comment] 2023-11-09 12:01
You have only mentioned that I should go to the page and click the create button but does not mention what attributes to select. Whether any optional attribute should be selected, if so, provide data to create it.

The steps to reproduce lacks detail in order for us to find what the issue is.

**Comment by jeremystretch** [comment] 2023-11-29 21:49
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.

**Closed by jeremystretch** 2023-11-29 21:49 UTC
Labels: type: bug, status: revisions needed
