### ISSUE TITLE
VLAN Groups not visible in site groups

### ISSUE THREAD

**Issue by chuegel** [netbox-community/netbox#14015] opened 2023-10-10 12:41 UTC
### NetBox version

v3.5.8

### Python version

3.9

### Steps to Reproduce

We want to assing a VLAN Group to multiple sites as these VLAN name/ids are the same on each of this site.
1. Create a site group
2. Create a VLAN Group: 
     - Min VLAN ID: 1000
     - Max VLAN ID: 1020
     - Scope: DCIM > Site Group
     - Site Group <assign group created in 1>
3. Add VLANs to this group and assign VLAN Group create in 2
4. Edit a site and add group created in 1
5. no VLAN Group is visible

Am I missing something?

### Expected Behavior

Assigned VLANS from  VLAN Group to site group should be visible

### Observed Behavior

see above

**Comment by DanSheps** [comment] 2023-10-11 14:27
If you are referring to the "VLAN Groups" display, that is for VLAN Groups specifically assigned to the site (Scope -> Site)

**Comment by DanSheps** [comment] 2023-10-11 14:27
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Closed by DanSheps** 2023-10-11 14:27 UTC
Labels: type: bug

**Comment by chuegel** [comment] 2023-10-12 05:40
@DanSheps thanks for your reply.
Well, no, basically we want to assign a group of defined vlans to a site group since those sites share the same VLAN IDs and names.
But if VLAN Group has a scope site group those sites in that group do not get the VLANs assigned

**Comment by DanSheps** [comment] 2023-10-12 12:17
I think you are missing the point, those sites don't have them assigned because the scope is the site group.

If you go to a device in one of those sites it will be visible still because the device the site is a member of is part of the site group, but you won't see it on the site detail itself because it is not directly assigned to the site.

If you need further assistance, please open a help discussion post.
