### ISSUE TITLE
Inventory items update error 'The fields device, parent, name must make a unique set.' via api

### ISSUE THREAD

**Issue by dsl81** [netbox-community/netbox#16165] opened 2024-05-16 12:33 UTC
[requests.txt](https://github.com/netbox-community/netbox/files/15403647/requests.txt)
### Deployment Type

Self-hosted

### NetBox Version

v4.0.2

### Python Version

3.11

### Steps to Reproduce

1. Create 2 devices. id1 (9) and id2 (957)
2. Create 2 inventory items on device with id2 by sending 2 requests:
```
curl -H "Authorization: Token $TOKEN" \
-H "Accept: application/json; indent=4" \
-H "Content-Type: application/json" \
https://netbox/api/dcim/inventory-items/ \
-X POST \
-d '{ "device" : "957","name" : "sfp"}'
```
3. get item_id1 (5492) and item_id2 (5493)
4. update items with data '{ "device" : "9"}'
```
% curl -H "Authorization: Token $TOKEN" \
-H "Accept: application/json; indent=4" \
-H "Content-Type: application/json" \
https://netbox/api/dcim/inventory-items/5492/ \
-X PATCH \
-d '{ "device" : "9"}'
```
same for item_id2 (5493)

### Expected Behavior

receive updated inventory items

### Observed Behavior
second PATCH request returns:
```
{
    "non_field_errors": [
        "The fields device, parent, name must make a unique set."
    ]
}
```

**Comment by dsl81** [comment] 2024-05-16 12:35
Moving item with identical names to one device works in gui.

**Comment by DanSheps** [comment] 2024-05-16 14:58
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v4.0.2 using raw API requests. Please re-confirm the reported behavior using raw API queries on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by dsl81** [comment] 2024-05-22 14:30
I updated issue with raw API requests. Also attached file with output. 
Hope it can be reproduced though my installation is not clean. Or i should include steps for creating devices?

**Comment by DanSheps** [comment] 2024-05-22 16:56
> I updated issue with raw API requests. Also attached file with output.
> Hope it can be reproduced though my installation is not clean. Or i should include steps for creating devices?

I am unable to reproduce this under normal circumstances.

**Comment by dsl81** [comment] 2024-05-23 14:13
I just made clean install and get the same issue with API. Could you please show how you move inventory items to one device with API?

**Comment by dsl81** [comment] 2024-06-06 06:15
What info can i provide to investigate the issue?

**Comment by dsl81** [comment] 2024-06-11 07:41
The behavior still presents in 4.0.5.

**Comment by DanSheps** [comment] 2024-06-11 15:59
So, I was able to reproduce this.

> I think i found the https://github.com/netbox-community/netbox/issues/13741 that introduced this behavior. After the https://github.com/netbox-community/netbox/issues/13837 it should be reverted. But it seems that in case of API it remained.

This was not the conclusion from the discussion at all, in fact the conclusion is that you should use the inventory items unique name within the system as the name in NetBox (example: an SFP in slot 1/1/8 on a Cisco 9300-48U, would be named "Te1/1/8" (that is the name that `show inventory` reports.  A PSU  on the same switch would be named "Switch 1 - Power Supply B" if you decide to use an inventory item for that.)

I also did some digging, as per Jeremy's comment:

> It is a model number, and is intended to be conveyed by the part ID field. You're free to use the fields however you like, but this would not be justification for removing the uniqueness constraint on the name field.

Further down:

> As there hasn't been any further discussion in recent months, I'm going to close this out as stale. We might revisit it in the future.

People wanted the uniqueness check to be reverted, but that doesn't mean us (the maintainers) are always going to do as the community wishes as there are other considerations beyond the communities desire (such as model integrity, search and filtering) which removing a uniqueness check would all impact.

I am going to close this out as this is not a bug and a currently intended feature.  You are free to open an enhancement request to request changes however we won't be removing the uniquenes check from this field but we could amend it with different criteria if there is an appropriate proposal with a supporting use case for it.

**Closed** 2024-06-11 16:00 UTC
Labels: type: bug, status: revisions needed, pending closure

**Comment by dsl81** [comment] 2024-06-13 13:53
I believe it was be discussed somewhere but the sfp can be moved from  slot 1/1/8 to  slot 2/1/7 and its name should not change in my opinion. 
Besides I can make identical inventory items with GUI. Why i can't do that in API?

**Comment by DanSheps** [comment] 2024-06-13 17:36
> I believe it was be discussed somewhere but the sfp can be moved from slot 1/1/8 to slot 2/1/7 and its name should not change in my opinion.

That is likely a bug itself.
