### ISSUE TITLE
Service Creation Comments Issue

### ISSUE THREAD

**Issue by abahney** [netbox-community/netbox#13767] opened 2023-09-14 17:00 UTC
### NetBox version

v3.6.1

### Python version

3.10

### Steps to Reproduce

1. Go to Services
2. Add Service
3. Select a Device
4. Select Custom (or template)
5. Input Details
> Name: Test
Protocol: TCP
Ports: 443
Comments: Anything
6. Click Create

### Expected Behavior

Service to be created with the comments included.

### Observed Behavior

The comments section is blank and also shows nothing in the change log.

Workaround: Edit the service after creation and input the comment.

**Comment by abhi1693** [comment] 2023-09-14 17:26
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Comment by abahney** [comment] 2023-09-14 17:50
I guess I'm confused as to why the Comments section exists during creating a Service?

![Service_Comments](https://github.com/netbox-community/netbox/assets/123212781/fb23db2d-e61e-43e5-b67f-587c4f4724d0)
![Service_Comments_not_included](https://github.com/netbox-community/netbox/assets/123212781/20936e63-6eb4-4052-a310-d60781f1c8ef)
![Service_Comments_not_included2](https://github.com/netbox-community/netbox/assets/123212781/41a32e2d-d5d2-4470-b585-c736d6e0246d)

**Comment by abhi1693** [comment] 2023-09-14 17:56
I'm sorry I misunderstood the issue.

**Comment by abahney** [comment] 2023-09-14 18:11
That's alright, I should of included the screenshots in the original post. I don't know much about the code, but it looks like it could have something to do with this.

https://github.com/netbox-community/netbox/blob/6939bf8aed8514cc5a9e8bc28a97ea90c61b7ebe/netbox/ipam/forms/model_forms.py#L724-L756

**Comment by jeremystretch** [comment] 2023-09-15 14:34
Thanks @abahney; you're correct about the form. The `comments` field is erroneously omitted from the form's field list.

**Closed** 2023-09-15 14:56 UTC
Labels: type: bug, status: accepted, severity: low
