### ISSUE TITLE
MACAddressField Class Broken

### ISSUE THREAD

**Issue by wz4** [netbox-community/netbox#14530] opened 2023-12-15 00:50 UTC
### Deployment Type

Self-hosted

### NetBox Version

v3.6.6

### Python Version

3.8

### Steps to Reproduce

MACAddressField class in utilities.forms.fields does not work. The widget is incorrectly assigned. Error occurs when loading form.

### Expected Behavior

Validate MAC Address field in forms.

### Observed Behavior

<class 'AttributeError'>

'CharField' object has no attribute 'attrs'

**Comment by jeremystretch** [comment] 2023-12-15 02:38
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by abhi1693** [comment] 2023-12-15 08:18
This is also a duplicate of #14260

**Comment by jeremystretch** [comment] 2023-12-26 14:40
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.

**Closed by jeremystretch** 2023-12-26 14:40 UTC
Labels: type: bug, status: revisions needed
