### ISSUE TITLE
Custom Field Choise: Dropdown menu error during device creation

### ISSUE THREAD

**Issue by opensourceXnetbox** [netbox-community/netbox#13383] opened 2023-08-04 15:48 UTC
### NetBox version

v3.6-beta1

### Python version

3.9

### Steps to Reproduce

1. Create a `Custom Field` with type `Selection` and content type `DCIM > Device`
2. Create a `Custom Field Choice`
3. Connect `Custom Field Choice` to `Custom Field`
4. Create a new device and focus on `drop-down menu`

### Expected Behavior

The drop-down menu

### Observed Behavior

* `selections` are visible for 1ms and the following error will be displayed:

![image](https://github.com/netbox-community/netbox/assets/110609354/8cb0ef52-5b22-4df0-9e01-6414f2b99ed2)

**Comment by abhi1693** [comment] 2023-08-04 16:03
Duplicate of #13363

**Closed** 2023-08-04 16:04 UTC
Labels: status: duplicate
