### ISSUE TITLE
ip address view shows 'oob_ip_id' missing attribute error

### ISSUE THREAD

**Issue by BenjaminBoehm** [netbox-community/netbox#13700] opened 2023-09-06 13:51 UTC
### NetBox version

v3.6.0

### Python version

3.11

#### Option1
1. I updated netbox from v3.5.8 to v3.6.0.
2. If I click on some ip addresses it shows the following error: 
![image](https://github.com/netbox-community/netbox/assets/16610938/7f5c9d8b-ad39-4755-a74d-56d62492bb11)
3. Currently I can't figure out why some are working and some showing this error message.

#### Option2
1. Create new ip address and assign as primary ip to vm
2. Save
3. Error from above is shown

### Expected Behavior

View details of every ip address

### Observed Behavior

Error message:

<class 'AttributeError'>

'VirtualMachine' object has no attribute 'oob_ip_id'

Python version: 3.11.4
NetBox version: 3.6.0
Plugins: None installed

**Comment by BenjaminBoehm** [comment] 2023-09-06 13:56
IP addresses that show this error are assigned as the primary IP of a VM.

**Comment by jeremystretch** [comment] 2023-09-06 14:25
Duplicate of #13619. Please remember to search closed bug reports before submitting new ones.

**Closed by jeremystretch** 2023-09-06 14:25 UTC
Labels: type: bug
