### ISSUE TITLE
Calculation of Power Utilization not Working (not cascaded)

### ISSUE THREAD

**Issue by RHuehne** [netbox-community/netbox#4815] opened 2020-07-02 13:24 UTC
### Environment
* Python version: ?? (using netbox-docker 0.24.1)
* NetBox version: 2.8.6

According to several posts here, the functionality of calculating the power Utilization should work now. In my case it does not. If I create a PDU Device (1 PowerPort <=> 8 OutletPorts) and connect a Server with 750W PSU to one of the outletPorts, I can see this on the connection, but there is no calculation done in "Power Utilization". It looks like the consumed watt values comming from the PowerOutlets are not linked to the PowerPort.

In our case, we need to have two PDU Devices: One in the rack, and one towards the UPS as the middle PDU splits up the 3 Legs from the UPS to single ones for the racks.

### Steps to Reproduce
1. Create a Uplink Device with PowerOutletPorts.
2. Create new Device (PDU) with 1 PowerPort (Connected to the Uplink Devices OutletPort1) associated (input/leg) with 8 PowerOutlets
3. Attach Device (e.g. a Server) with a PowerPort (Max 750W, allocated 500W) to PowerOutlet#1 on PDU Device

### Expected Behavior
On the PDU-Device, under Power Utilization, "Allocated", "Available" and "Utilization" have the cumulated values from each of its OutletPorts.

### Observed Behavior
"Allocated" is 0VA"
"Available" is "--"
"Utilization" is "--"

OutletPort Watts are not cumulated and pushed up to the PowerPort.

![02-07-_2020_15-12-21](https://user-images.githubusercontent.com/13745200/86364212-28831c80-bc78-11ea-93a7-31b06f321a7f.png)

**Comment by DanSheps** [comment] 2020-07-02 14:41
Duplicate of #3377

**Closed by DanSheps** 2020-07-02 14:41 UTC
