### ISSUE TITLE
Can't clear Device field Rack in UI

### ISSUE THREAD

**Issue by JulijusBertasius** [netbox-community/netbox#9713] opened 2022-07-13 12:19 UTC
### NetBox version

v3.2.6

### Python version

3.8

### Steps to Reproduce

1. In UI press any racked device edit button
2. Press x in rack field

I tried it on 2 different computers and 3 different browsers. Problems also happens on devices I tried in demo.netbox.dev.

### Expected Behavior

Rack field is empty

### Observed Behavior

Page freezes

**Comment by kkthxbye-code** [comment] 2022-07-15 11:56
Like #9734 this is also caused by #9696 - should be fixed in #9735.

I have no idea how it manages to freeze the browser, it might be a Chrome bug, as it doesn't happen in firefox. Seems to be related to setting focus on an element while it is being manipulated in another way.

**Comment by jeremystretch** [comment] 2022-07-15 12:17
I'm going to close this as covered by #9734, but please ask to have it reopened if you determine that #9735 does not address the problem.

**Closed by jeremystretch** 2022-07-15 12:17 UTC
Labels: type: bug, status: accepted
