### ISSUE TITLE
Prefix overflow by IP Address Bulk Create

### ISSUE THREAD

**Issue by fulhade** [netbox-community/netbox#5428] opened 2020-12-08 14:30 UTC
### Environment
* Python version: 3.7.3
* NetBox version: 2.9.10

### Steps to Reproduce
1. Create one or more prefix. Ex: 192.168.1.0/29, 192.168.1.8/29, 192.168.16/29 with option: Is a pool = uncheck
2. Create multiple IP address with Bulk Create: 192.168.1.[0-50]/29

### Expected Behavior
1. It should not be possible to create this range [0-50] with subnet mask /29. Or just not through Prefix menu. Perhaps something like: Create all usable IP address for this prefix?
2. Bulk Create should not be able to create network and broadcast address for Prefix specified as not pool

### Observed Behavior
I got 50 IP addresses. And 3 Prefix with network and broadcast addres. Also, prefix utilisation is 133% for this example.

**Comment by DanSheps** [comment] 2020-12-08 14:51
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

For further information, the IP address model mostly decoupled from the prefix model and likewise the functionality within most of these is also decoupled, such as prefixes and creation of addresses.

**Closed by DanSheps** 2020-12-08 14:51 UTC
