### ISSUE TITLE
View Elevations quit working in v2.10

### ISSUE THREAD

**Issue by jameswhite4684** [netbox-community/netbox#5462] opened 2020-12-15 16:50 UTC
### Environment
Python version: 3.8.5
NetBox version: 2.10.0

### Steps to Reproduce
1.  Upgraded from 2.9
2.  Navigate to "Rack Groups"
3.  Click "View Elevations

### Expected Behavior
View of all racks in the group

### Observed Behavior
Server Error page displayed with the below information.

"There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'rack-elevation' with keyword arguments '{'pk': ''}' not found. 2 pattern(s) tried: ['api/dcim/racks/(?P<pk>[^/.]+)/elevation\\.(?P<format>[a-z0-9]+)/?$', 'api/dcim/racks/(?P<pk>[^/.]+)/elevation/$']"

![NetboxServerError](https://user-images.githubusercontent.com/35677155/102245539-4d381d00-3ec3-11eb-8e11-8cbf70e9fc9c.PNG)

**Comment by jeremystretch** [comment] 2020-12-15 16:52
Duplicate of #5461

**Closed by jeremystretch** 2020-12-15 16:52 UTC

**Comment by jameswhite4684** [comment] 2020-12-15 17:02
Thank you, I tried looking for one but couldn't find.
