### ISSUE TITLE
Cant save "Interface Assignment", "NAT IP (Inside)" fields of ip address

### ISSUE THREAD

**Issue by encorer** [netbox-community/netbox#6946] opened 2021-08-12 14:33 UTC
### NetBox version

v2.11.10

### Python version

3.8

### Steps to Reproduce

1. Create cluster type in Virtualization -> Cluster Types
2. Create cluster in Virtualization -> Clusters
3. Create virtual machine in Virtualization -> Virtual Machines
4. Create any ip address (e.g. 192.168.0.150/32) in IPAM -> IP Addresses, set in this page below, Interface Assignment ->  Virtual Machine, my previously created Virtual Machine, click Create

### Expected Behavior

all filled fields must be saved

### Observed Behavior

The ip address is saved, but the assigned virtual machine is not. Same thing with "NAT IP (Inside)" fields of ip address page.

In debug mode see this error:

Exception while resolving variable 'disabled' in template 'django/forms/widgets/select.html'.
Traceback (most recent call last):
File "/opt/netbox-2.11.10/venv/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
current = current[bit]
TypeError: string indices must be integers

**Comment by jeremystretch** [comment] 2021-08-12 15:11
I'm not able to reproduce this on v2.11.10, either locally or using the public demo instance. Can you take a look through your steps to reproduce again?

**Comment by encorer** [comment] 2021-08-12 15:32
I understood. If you do not set the interface, then it does not save the virtual machine, but this item seems to be optional.

**Comment by encorer** [comment] 2021-08-12 15:50
I have another question, can you assign a virtual machine to the site?

**Comment by jeremystretch** [comment] 2021-08-12 15:55
> If you do not set the interface, then it does not save the virtual machine, but this item seems to be optional.

Correct: You must select a specific interface to which the IP address is being assigned.

> I have another question, can you assign a virtual machine to the site? Can't find a way to do this.

No; virtual machines must be assigned to clusters, and clusters can be assigned to sites.

Since this does not appear to be a valid bug report, I'm going to close it. For any other questions, please feel free to start a new [discussion](https://github.com/netbox-community/netbox/discussions/new).

**Closed by jeremystretch** 2021-08-12 15:55 UTC
Labels: type: bug, status: revisions needed
