### ISSUE TITLE
Can't save Device "Postion error"

### ISSUE THREAD

**Issue by rebortg** [netbox-community/netbox#11358] opened 2023-01-02 16:21 UTC
### NetBox version

v3.4.1

### Python version

3.10

### Steps to Reproduce

Open a Device, edit something (except the postion) and save it.
A error appears "Please insert a Number"

after change the postion to the correct one it worked.

Example on demo.netbox.dev
https://demo.netbox.dev/dcim/devices/37/edit/

### Expected Behavior

save the Device

### Observed Behavior

A error appears "Please insert a Number"

**Comment by kkthxbye-code** [comment] 2023-01-02 16:42
Duplicate of https://github.com/netbox-community/netbox/issues/11272

Will be fixed in the next release.

**Closed by kkthxbye-code** 2023-01-02 16:42 UTC
Labels: type: bug
