### ISSUE TITLE
Datasource passwords are displayed in plaintext in the changelog difference

### ISSUE THREAD

**Issue by mtbutler07** [netbox-community/netbox#13726] opened 2023-09-08 17:33 UTC
### NetBox version

v3.6.1

### Python version

3.10

### Steps to Reproduce

1. Create a new git data source
2. Populate the username/password fields
3. A changelog record is created displaying the password in plain text

![Screenshot from 2023-09-08 13-30-35](https://github.com/netbox-community/netbox/assets/33135168/55237b5c-88cf-4126-b795-975ee11f4fee)

### Expected Behavior

The password and other secret fields should be omitted or masked in the changelog difference

### Observed Behavior

The password was shown in plain text

**Comment by DanSheps** [comment] 2023-09-08 19:34
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Closed by DanSheps** 2023-09-08 19:34 UTC
Labels: type: bug

**Comment by mtbutler07** [comment] 2023-09-08 20:12
Hi @DanSheps! Displaying the passwords in plain text is intended? 
That doesn't seem to be consistent with the rest of the NetBox UI so it seemed like a bug to me.
Examples:
- Passwords are masked during user login
- User passwords are not visible from within the admin panel
- Salt and hashes are both masked in the admin panel

>Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

The observed behavior is flawed because credentials are being compromised when they could be omitted or masked like they are throughout the rest of the NetBox UI.

I'm more than happy to convert this to a feature request if that's the proper way forward. Just let me know.

**Comment by DanSheps** [comment] 2023-09-08 20:24
This is intended, as it is the change log.  No change log data is encrypted

**Comment by mtbutler07** [comment] 2023-09-08 20:45
Created FR https://github.com/netbox-community/netbox/issues/13729
