### ISSUE TITLE
Missing info on circuits terminations points

### ISSUE THREAD

**Issue by zacho112** [netbox-community/netbox#4714] opened 2020-06-04 11:43 UTC
* Python version: 3.6
* NetBox version: 2.8.4

### Steps to Reproduce
1. Add a new circuit
2. Add a termination point A (Add site + speed)
3. Add a termination point Z (Add site + speed)
4. Add a connection on termination point Z, select destination device + interface

### Expected Behavior
The interface on the device shows connection to the Circuit and vise versa.

### Observed Behavior
Both the interface and the termination point only shows connection to the cable, not the device/interface

This happened after a recent update from 2.7.7.

If I delete the termination point A, and edit the cable the missing info shows up.

Circuit:
`{
    "id": 12,
    "cid": "CID",
    "provider": {
        "id": 5,
        "url": "https://<netboxurl>/api/circuits/providers/5/",
        "name": "ISP",
        "slug": "isp"
    },
    "type": {
        "id": 4,
        "url": "https://<netboxurl>/api/circuits/circuit-types/4/",
        "name": "Point2Point",
        "slug": "point2point"
    },
    "status": {
        "value": "active",
        "label": "Active",
        "id": 1
    },
    "tenant": {
        "id": 8,
        "url": "https://<netboxurl>/api/tenancy/tenants/8/",
        "name": "ISP",
        "slug": "ISP"
    },
    "install_date": null,
    "commit_rate": null,
    "description": "",
    "termination_a": {
        "id": 14,
        "url": "https://<netboxurl>/api/circuits/circuit-terminations/14/",
        "site": {
            "id": 1332,
            "url": "https://<netboxurl>/api/dcim/sites/1332/",
            "name": "SiteA",
            "slug": "sitea"
        },
        "connected_endpoint": {
            "id": 18983,
            "url": "https://<netboxurl>/api/dcim/interfaces/18983/",
            "device": {
                "id": 872,
                "url": "https://<netboxurl>/api/dcim/devices/872/",
                "name": "sw_1",
                "display_name": "sw_1"
            },
            "name": "TenGigabitEthernet8/8",
            "cable": null,
            "connection_status": null
        },
        "port_speed": 10000000,
        "upstream_speed": null,
        "xconnect_id": ""
    },
    "termination_z": {
        "id": 38,
        "url": "https://<netboxurl>/api/circuits/circuit-terminations/38/",
        "site": {
            "id": 1318,
            "url": "https://<netboxurl>/api/dcim/sites/1318/",
            "name": "SiteB",
            "slug": "siteb"
        },
        "connected_endpoint": null,
        "port_speed": 10000000,
        "upstream_speed": null,
        "xconnect_id": ""
    },
    "comments": "",
    "tags": [],
    "custom_fields": {},
    "created": "2020-03-18",
    "last_updated": "2020-06-04T12:12:08.179384+02:00"
}`

Circuit termination:
`{
    "id": 38,
    "circuit": {
        "id": 12,
        "url": "https://<netboxurl>/api/circuits/circuits/12/",
        "cid": "CID"
    },
    "term_side": "Z",
    "site": {
        "id": 1318,
        "url": "https://<netboxurl>/api/dcim/sites/1318/",
        "name": "SiteB",
        "slug": "siteb"
    },
    "port_speed": 10000000,
    "upstream_speed": null,
    "xconnect_id": "",
    "pp_info": "",
    "description": "",
    "connected_endpoint_type": null,
    "connected_endpoint": null,
    "connection_status": null,
    "cable": {
        "id": 857,
        "url": "https://<netboxurl>/api/dcim/cables/857/",
        "label": ""
    }
}`

Cable:
`{
    "id": 857,
    "termination_a_type": "circuits.circuittermination",
    "termination_a_id": 38,
    "termination_a": {
        "id": 38,
        "url": "https://<netboxurl>/api/circuits/circuit-terminations/38/",
        "circuit": {
            "id": 12,
            "url": "https://<netboxurl>/api/circuits/circuits/12/",
            "cid": "CID"
        },
        "term_side": "Z"
    },
    "termination_b_type": "dcim.interface",
    "termination_b_id": 17127,
    "termination_b": {
        "id": 17127,
        "url": "https://<netboxurl>/api/dcim/interfaces/17127/",
        "device": {
            "id": 1094,
            "url": "https://<netboxurl>/api/dcim/devices/1094/",
            "name": "sw_2",
            "display_name": "sw_2"
        },
        "name": "Ethernet48",
        "cable": 857,
        "connection_status": null
    },
    "type": "",
    "status": {
        "value": "connected",
        "label": "Connected",
        "id": true
    },
    "label": "",
    "color": "",
    "length": null,
    "length_unit": null
}`

**Comment by fullgore** [comment] 2020-06-11 07:27
Exact same issue on upgrade from 2.7.10 => 2.8.5.

**Comment by keepworld** [comment] 2020-06-11 07:48
We observed a similar behavior when creating new circuits with both A/Z side connected to a device interface. (Existing circuits are fine)

Creating a new circuit with only A side connected to a device interface works okay.

As soon as Z side is connected infos are missing in the circuit view for Z side.
Also circuit termination isn't displayed on the device view (both sides), it's show that devices are directly connected (which is not the case).

**Comment by keepworld** [comment] 2020-06-11 07:54
Circuit A/Z Side :
![Screenshot 2020-06-11 at 09 51 17](https://user-images.githubusercontent.com/4347576/84359817-7486f800-abc9-11ea-97fa-1c8f6885c0ab.png)

Device view (physical interface):
![Screenshot 2020-06-11 at 09 51 39](https://user-images.githubusercontent.com/4347576/84359863-89fc2200-abc9-11ea-85b2-9d1a8cfbeb99.png)

**Comment by shdxiang** [comment] 2020-06-15 02:49
The same issue when 2.7.12 => 2.8.5.

**Comment by zacho112** [comment] 2020-06-15 12:49
I guess its the same issue as in https://github.com/netbox-community/netbox/issues/4619

**Comment by DanSheps** [comment] 2020-06-15 15:40
Duplicate of #4619

**Closed by DanSheps** 2020-06-15 15:40 UTC
