### ISSUE TITLE
Allow more granular filtering of webhooks

### ISSUE THREAD

**Issue by a-d-v** [netbox-community/netbox#4732] opened 2020-06-08 18:28 UTC
### Environment
* Python version:  3.8.3
* NetBox version:  2.8.4

### Proposed Functionality
Webhooks are a great way to notify external systems using RESTAPI of a NetBox object change, but cannot be filtered to be more specific than an object type. Would it be possible add some basic filtering to trigger only for a specific site and/or tenant for example?

### Use Case
* Globally distributed DHCP and/or DNS servers that would receive a notification to update records for the site handled by the server.
* Microsoft Teams/Slack notifications for objects in specific key sites or to different channels for different responsible parties.

### Database Changes
N/A
### External Dependencies
N/A

**Comment by jeremystretch** [comment] 2020-06-08 19:04
Duplicate of #4567

**Closed by jeremystretch** 2020-06-08 19:04 UTC
