### ISSUE TITLE
Use select2 for custom script ObjectVar fields

### ISSUE THREAD

**Issue by tkupari** [netbox-community/netbox#3516] opened 2019-09-19 10:32 UTC
### Environment
* Python version:  3.7.4 
* NetBox version:  2.6.3 

### Proposed Functionality

Use select2 to enable filtering in custom script ObjectVar dropdown.

### Use Case

Selecting a rack from a list of 300 racks

### Database Changes

no

### External Dependencies

no

**Comment by DanSheps** [comment] 2019-09-19 14:33
I think one thing to look at, would also be "widget=APISelect", because you can filter a rack with select2, but unless you add in the widget to perform the query, the list is going to be static.

**Comment by Grokzen** [comment] 2019-10-08 12:03
@DanSheps I tried to use ObjectVar with our IPAddress model that had 27k+ objects in it. The page almost crashed on my laptop. The APISelect solution must be there to work the same way as it does on the filter panels on the list views. Yes the current select box works for very small data sets, but bigger ones, no wai.

**Comment by tyler-8** [comment] 2019-10-29 20:51
This would be extremely useful. There are workflows that, even when using filtered QuerySets, could provide several thousand or more object choices. That would be a browser killer as @Grokzen noted.

**Comment by hSaria** [comment] 2020-01-13 11:20
I'm all for implementing this, but we'd need to address the issue with manually specifying the `api_url` of the APISelect-based widgets; someone is bound to put the wrong URL. Maybe we create an API URL attribute for every model to be used in the `data-url` attribute of the select field.

**Comment by hSaria** [comment] 2020-01-25 18:38
Could this be closed as it is a duplicate of #3766 (has more relevant information, I'd say)

**Closed** 2020-02-11 14:19 UTC
Labels: status: gathering feedback
