### ISSUE TITLE
Toggle suggested/Available prefixes in Child Prefix tab

### ISSUE THREAD

**Issue by cjreyn** [netbox-community/netbox#2365] opened 2018-08-16 12:23 UTC
### Environment
* Python version:  3.4.3
* NetBox version: 2.4.1

### Proposed Functionality
Currently, when clicking on the Child Prefix tab of a given prefix, it shows 'Active' and 'Available' prefixes. A button to show/hide the 'Available' prefixes would be useful.

### Use Case

Daily prefix view

**Comment by jeremystretch** [comment] 2018-08-16 13:04
Thank you for your interest in NetBox. We require that all issues be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/tree/develop/.github/ISSUE_TEMPLATE). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the appropriate template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!

**Comment by jeremystretch** [comment] 2020-01-02 15:14
Marking this as a duplicate of #2598 (#2598 has more detail)

**Closed by jeremystretch** 2020-01-02 15:14 UTC
Labels: status: accepted, type: ui
