### ISSUE TITLE
Add 'role' to Inventory Items

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#3087] opened 2019-04-18 14:53 UTC
### Environment
* Python version:  3.5.4
* NetBox version:  2.3.6

### Proposed Functionality

Add a "role" field to Inventory Items.

### Use Case

* To classify inventory items by function, e.g. "OS disk", "data disk", "hot spare"; and/or
* To classify inventory items by type, e.g. "motherboard", "CPU", "RAM", "NIC"

Inventory items already have Tags, but the idea of using Tags for this was rejected in #3082 

### Database Changes

Add a "role_id" column to Inventory Item, which references device role.  Make it nullable for backwards compatibility.

Probably want to add a new flag to `dcim_devicerole` to say whether it's usable on an inventory item (comparable to existing `vm_role` flag)

At this point it may also be worth having a flag to say whether the role is usable on Device (since I can imagine roles which are relevant to Inventory Item but not Device, and vice versa)

### External Dependencies

None

**Comment by a31amit** [comment] 2019-04-19 15:22
This will be very useful but there would be a need to filter them by role in inventory items list view

**Comment by mmahacek** [comment] 2019-04-19 15:57
Reading the request, I was initially in support of this, but have since grown mixed feelings.  I am abstaining from voting on this.  Not against this idea, but wouldn't expect to use it on my server.

**Comment by jeremystretch** [comment] 2019-04-27 03:33
> Add a "role_id" column to Inventory Item, which references device role.

Wouldn't InventoryItem roles and Device roles generally by mutually exclusive of one another? E.g. a "router" can't be an InventoryItem and a "hard disk" can't be a device.

**Comment by candlerb** [comment] 2019-04-27 07:56
I was just saying what you said more clearly: that in many (most? all?) cases, Inventory Item roles would not be relevant to Device, or vice versa.

So there could be a separate Inventory Item Roles list - but doing so would mean code duplication (e.g. for editing them, setting colours etc) and some menu clutter.

Are there any examples where the same role would apply to both?  Probably not.  Maybe "hot spare" - on a device that might be better managed by Status, although there isn't one exactly that matches that (there are "offline" and "planned")

**Comment by a31amit** [comment] 2019-04-27 18:25
Or this can be exposed only in ADMIN panel and Netbox Administrator can create them in advance.

**Comment by wols** [comment] 2019-06-05 20:18
My wish: add **Inventory** to 'Device Type - Status' = 'Parent/Child/**Inventory** status'

So I could map the following:
1. 'Add a new device type': select Manufacturer / `Power Supply` / Part number / 0U / Status **Inventory**
2. Go to (non-racked/racked server)  'Device - Inventory - Add Inventory Item'
3. 'Add a new inventory item': Name `Power Supply 1` / select Manufacturer / Part from step '1.' / Serial number
4. 'Add a new inventory item': Name `Power Supply 2` / select Manufacturer / Part from step '1.' / Serial number

...two Power Supplies added to the server inventory - no more CopyPaste `Part Numbers`.

**Comment by candlerb** [comment] 2019-06-06 10:53
I think what you want is instead to have Inventory Item Type (analagous to Device Type).  This seems like a reasonable idea to me.

Devices cannot contain other Devices as Inventory Items, they are completely distinct types of objects.

**Comment by a31amit** [comment] 2019-06-14 17:06
I believe making device roles to more generic could be good and another boolean similar to VM Role. 

As of now, Devices and VirtualMachines are different models but shares the same Device Roles. We could have something similar flag inventory_item which can be assigned only to inventory items. 

As in original request, it was proposed that roles could be a function or physical type.

**Comment by hSaria** [comment] 2020-01-02 18:04
@jeremystretch I think this ticket can be closed as it is a duplicate of #3333

**Comment by jeremystretch** [comment] 2020-01-02 18:12
@hSaria The two proposals are related but different. Similar to the difference between the DeviceRole and DeviceType models.

**Comment by hSaria** [comment] 2020-01-02 18:24
Ah. That makes more sense.

**Comment by ibivibiv** [comment] 2020-04-10 18:37
FYI, both the typing and the role have been implemented in a fork here:

https://github.com/nmereddi/netbox/commit/80943c7ab9e07570be44d5e384917ddc9e04c4e1

If we can get an actual issue up for this and get it accepted we can get this ball rolling?  If we are deadlocked then maybe we build out something else in a companion app?  I think it would be better to have this functionality built in rather than having to go around it just to track what a component inside a server is and its role?

**Comment by jeremystretch** [comment] 2021-12-23 16:31
> Can we have the 'Inventory' also made part of the 'Device template' ?

FYI @PieterL75 opened #8118 for this.

**Closed** 2021-12-27 16:07 UTC
Labels: status: accepted, type: feature
