### ISSUE TITLE
Detailed view of Tenants show unrelated contacts

### ISSUE THREAD

**Issue by jbakklund** [netbox-community/netbox#12763] opened 2023-05-31 00:50 UTC
### NetBox version

v3.5.2

### Python version

3.9

### Steps to Reproduce

1. Create some sites, tenants, and contacts.
2. Ensure that there are no contacts assigned to tenant number 1 at /tenancy/tenants/1/contacts/
3. Add contacts to site number 1 at /dcim/sites/1/contacts/
4. Navigate to /tenancy/tenants/1/contacts/

### Expected Behavior

No contacts should be listed.

### Observed Behavior

All contacts related to Site-ID 1 are listed under Tenant-ID 1.

**Comment by jbakklund** [comment] 2023-05-31 01:01
Looks like the same Contacts related to a specific Site-ID are misinterpreted as contacts for Circuit Provider with Provider-ID equal to the Site-ID.

**Comment by abhi1693** [comment] 2023-05-31 03:48
Duplicate of #12730

**Closed** 2023-05-31 03:48 UTC
Labels: status: duplicate
