### ISSUE TITLE
CSV upload silently ignores invalid columns

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#13200] opened 2023-07-18 09:28 UTC
### NetBox version

v3.5.6

### Python version

3.8

### Steps to Reproduce

Go to Interface Bulk Import (`/dcim/interfaces/import/`)

Paste in the following:

```
device,name,type,wombat
nuc1,blah,virtual,flurble
```

(where 'nuc1' is some existing device)

### Expected Behavior

Import to be rejected because of the unknown attribute/column "wombat"

### Observed Behavior

The import is silently accepted.

The same applies if you try to *modify* an existing interface, e.g.

```
id,wombat
451,flurble
```

where 451 is an ID of an existing interface.

It's not just for interfaces: the same can be seen when creating Devices

```
device_role,manufacturer,device_type,status,site,wombat
Server,Unknown,Patch Panel 24,active,Test,flurble
```

(assuming that the given device_role, manufacturer, device_type, site are all pre-existing objects)

**Comment by abhi1693** [comment] 2023-07-18 09:33
Duplicate of #11617

**Closed by abhi1693** 2023-07-18 09:33 UTC
Labels: status: duplicate
