### ISSUE TITLE
Model Internal Circuits

### ISSUE THREAD

**Issue by grbeneke** [netbox-community/netbox#9140] opened 2022-04-15 07:07 UTC
### NetBox version

v3.2

### Feature type

Change to existing functionality

### Proposed functionality

Allow the circuit model to represent a logical or physical circuit being delivered from the infrastructure modeled within NetBox.

A circuit endpoint would exist on an interface or front port (rather then connected to).

This could be simply for tracking demarcation points for circuit based services delivered to external parties but should also support the onward connection to infrastructure of tenants who may be modeled in the NetBox instance.

### Use case

Representation of L2VPN, E-LINE, OTN and other logical circuit-style services being delivered using the modeled infrastructure. These circuits typically exist between two endpoints and pass through many intermediate devices. They don't follow the physical infrastructure directly.

Associating a cable trace with a single circuit identifier based in modeled ports being the demarcation of the ends of the defined circuit. This is potentially more difficult as it complicates the cable trace logic with 2 parallel paths representing the same thing.

### Database changes

Unknown

**Comment by grbeneke** [comment] 2022-04-15 18:25
Seems that this has a lot in common with #8157

**Comment by DanSheps** [comment] 2022-04-16 14:24
Duplicate of #8157

**Closed by DanSheps** 2022-04-16 14:24 UTC
Labels: type: feature
