### ISSUE TITLE
Netbox assigns additionally old (deleted) interface to device

### ISSUE THREAD

**Issue by swgATpj** [netbox-community/netbox#9723] opened 2022-07-14 07:37 UTC
### NetBox version

v3.2.1

### Python version

3.10

### Steps to Reproduce

1. Creating new device + interface (f.e. with name 'intf01')
2. Deleting both
3. Creating new device + interface (f.e. with name 'intf02')

 
Also here is the code (snipped) I use with the pynetbox-api to create and assign an interface to an existing/new created device:

```
pyNetApi = pynetbox.api(
    '<my netbox-url>',
    token='<token>'
    )

intf = self.pyNetApi.dcim.interfaces.create(
                device = dev.id,
                name = name,
                type = intf_type,
                mac_address = mac,
                description = descr
)
```

### Expected Behavior

Assigned interface to device is only {'intf02'}

### Observed Behavior

Assigned interface to device is now {'intf01', 'intf02'}
Also the old (deleted) interfaces will added randomly to other devices, which never had assigned the interface.
There is nothing wrong with my code, checked already x-times.

**Comment by kkthxbye-code** [comment] 2022-07-14 08:09
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

Also as is written in the bug report template:

> If reporting a bug in the REST API, be sure to reconstruct the raw HTTP request(s) being made: Don't rely on a client library such as pynetbox.

**Comment by jeremystretch** [comment] 2022-07-15 12:50
> There is nothing wrong with my code, checked already x-times.

I suspect that if you share your code in a [discussion](https://github.com/netbox-community/netbox/discussions/new), you'll find that people are willing to help sort out the issue. However, this is not a bug in NetBox, so I'm going to close this issue.

**Closed by jeremystretch** 2022-07-15 12:50 UTC
Labels: type: bug, status: revisions needed

**Comment by swgATpj** [comment] 2022-07-21 10:56
> I suspect that if you share your code in a [discussion](https://github.com/netbox-community/netbox/discussions/new), you'll find that people are willing to help sort out the problem. However, this is not a bug in NetBox, so I'm going to close this issue.

Could be the issue on the database? Today I have noticed, that, as I runned my script, is also found an interface which isn't even existing anymore.

![Unbenannt](https://user-images.githubusercontent.com/104566558/180197125-379b2877-49be-4834-8af8-97cbd71e6ef9.PNG)
