### ISSUE TITLE
GlobalSearch: VLAN-ID only found with "exact match"

### ISSUE THREAD

**Issue by do9xe** [netbox-community/netbox#11353] opened 2023-01-02 09:06 UTC
### NetBox version

v3.4.1

### Python version

3.9

### Steps to Reproduce

1) globally search for any VLAN-ID documented in NetBox
2) default behavior is "partial match" and the VLAN object is not found
3) change match type to "exact match" and VLAN object ist found

### Expected Behavior

All options of the search should match the VLAN-IDs, not just the "exact match"

### Observed Behavior

no error raised

**Comment by kkthxbye-code** [comment] 2023-01-02 11:12
Duplicate of https://github.com/netbox-community/netbox/issues/11232

**Closed by kkthxbye-code** 2023-01-02 11:12 UTC
Labels: type: bug
