### ISSUE TITLE
GraphQL Tunnel termination - impossible to get termination host and tunnel interace

### ISSUE THREAD

**Issue by antoinekh** [netbox-community/netbox#15731] opened 2024-04-16 12:24 UTC
### Deployment Type

Self-hosted

### NetBox Version

3.7.5

### Python Version

3.11

### Steps to Reproduce

Impossible to get tunnel terminaison interface and host with graphql. The fields are missing.

### Expected Behavior

Something similare as the one on with restapi where I can know the terminaison device and interface.

```
{
    "id": 1,
    "url": "http://127.0.0.1:8000/api/vpn/tunnel-terminations/1/",
    "display": "gcp_lab_01: Termination 1",
    "tunnel": {
        "id": 1,
        "url": "http://127.0.0.1:8000/api/vpn/tunnels/1/",
        "display": "gcp_lab_01",
        "name": "gcp_lab_01"
    },
    "role": {
        "value": "peer",
        "label": "Peer"
    },
    "termination_type": "virtualization.vminterface",
    "termination_id": 1,
    "termination": {
        "id": 1,
        "url": "http://127.0.0.1:8000/api/virtualization/interfaces/1/",
        "display": "tunnel0",
        "virtual_machine": {
            "id": 1,
            "url": "http://127.0.0.1:8000/api/virtualization/virtual-machines/1/",
            "display": "vpni-partners-vdm_VM",
            "name": "vpni-partners-vdm_VM"
        },
        "name": "tunnel0"
    },
    "outside_ip": {
        "id": 4,
        "url": "http://127.0.0.1:8000/api/ipam/ip-addresses/4/",
        "display": "1.1.1.1/32",
        "family": 4,
        "address": "1.1.1.1/32"
    },
    "tags": [],
    "custom_fields": {},
    "created": "2024-04-11T13:57:31.595019+02:00",
    "last_updated": "2024-04-11T15:21:07.455983+02:00"
}
```

### Observed Behavior

I can have tunnel terminaison id BUT not virtual_machine, not name, no interface nor interface.

**Comment by arthanson** [comment] 2024-04-16 15:39
Thank you for opening a bug report. The described functionality is actually not a bug as the table renames some columns like termination_parent to HOST where GraphQL just uses the original names. Can you please re-open this as a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.yaml).

**Comment by arthanson** [comment] 2024-04-29 15:18
Closing, please re-open as a feature request.

**Closed by arthanson** 2024-04-29 15:18 UTC
Labels: type: bug, status: revisions needed
