### ISSUE TITLE
Interface cannot connect to Rear Port

### ISSUE THREAD

**Issue by jameswhite4684** [netbox-community/netbox#5353] opened 2020-11-16 22:36 UTC
Environment
Python version: 3.8.5
NetBox version: 2.9.7

Steps to Reproduce
Create or locate one device with at least one non-connected interface.
Create a device with two front ports mapped to a single rear port.
Connect interface to the rear port.

Expected Behavior
Interface connect to single rear port

Observed Behavior
Errors
Rear ports with multiple positions may only be connected to other pass-through ports

**Comment by DanSheps** [comment] 2020-11-17 01:07
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Comment by jeremystretch** [comment] 2020-11-17 13:37
This is indeed expected behavior in v2.9. However, the cabling model has been reworked in the upcoming v2.10 release and this will no longer be a constraint.

**Closed by jeremystretch** 2020-11-17 13:37 UTC
Labels: pending closure

**Comment by jameswhite4684** [comment] 2020-11-17 14:19
Thank you, I know it was possible before 2.9 so I just wasn't sure as I have other cables set that way prior to upgrading to 2.9.
