### ISSUE TITLE
Additional "Primary IP" assignment option for OOBM/IDRAC/ILO etc

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#9050] opened 2022-04-06 08:40 UTC
### NetBox version

v3.2.0

### Feature type

New functionality

### Proposed functionality

UI Changes:
- Create another checkbox for marking an IP as OOBM(Out Of Band Management)/ILO/DRAC/OPENBMC etc (specific term to be chosen). to the assignment view / edit ip view / edit device view

Config:
- maybe an option in the configuration.py to define if "Primary" ip is OS or is OOBM. 

Models:
devices / ipam- additional "primary" ip assignment. lets call this the secondary management ip for now

### Use case

Servers (and some newer switches) generally have two types of management. 

- BMC/OOBM/ILO/DRAC/OPENBMC - for directly managing the hardware health, installing new os's etc
- OS Management IP - the primary ip to connect to the OS / OS Mgmt context

Right now we have to assign one or the other as the "primary" ip. 
It would be really useful to have a "secondary" option to allow folks to decide on which suits them more.
For Dedi/Server rental companies the primary would probably be the DRAC/OOBM. 
For ISP's / Networking orgs it would probably be the OS Mgmt ip.

Example of newer networking gear coming with drac/ilo style oob mgmt (openbmc): https://www.edge-core.com/productsInfo.php?cls=1&cls2=5&cls3=181&id=334

**Comment by gleeblezoid** [comment] 2022-04-06 11:28
This would be super useful and seems like a really elegant small change.

**Comment by corriganalan** [comment] 2022-04-06 14:45
This would be great, putting more important info on the front device page.

**Comment by martinum4** [comment] 2022-04-06 16:43
https://github.com/netbox-community/netbox/issues/8864 this was already proposed, see my comments there on how to do it with custom links.
You could also work with Tags or services instead, if you want.

**Comment by jeremystretch** [comment] 2022-04-06 17:46
As noted under #8864, whether an IP address has been designated for our-of-band management depends on the interface to which it has been assigned. NetBox provides the option to designate an interface as a management interface via the `mgmt_only` boolean: Any IPs assigned to management interfaces can be considered management IPs.

It sounds like you want what has already been proposed under #8137, which would add to the device and VM models a new field designating a particular IP address for out-of-band management.

**Comment by ITJamie** [comment] 2022-04-06 18:00
That makes sense. Right now internally our teams are split on which is the correct primary ip to assign. The oob ip or the os management ip.
I personally view that the current primary ip is the os mgmt ip and that an oob would be another. 

While a computed custom field or link could be a way to work around this. It does feel a bit hacky vs extending the model to account for a pretty common usecase.


Tangent: It would be interesting to be able to attach different "services" to the primary ip vs the oobm ip.

**Comment by DanSheps** [comment] 2022-04-06 19:45
Duplicate of #8137

**Comment by DanSheps** [comment] 2022-04-06 19:45
We should keep all discussion under #8137.  I am going to close this out as a duplicate.

**Closed by DanSheps** 2022-04-06 19:45 UTC
Labels: type: feature
