### ISSUE TITLE
Allow ConfigContext mapping to DeviceType

### ISSUE THREAD

**Issue by vista-** [netbox-community/netbox#5222] opened 2020-10-08 17:37 UTC
### Environment
* Python version: 3.8.2
* NetBox version: 2.9.4 / develop

### Proposed Functionality
Config Contexts can be currently applied to specific Platforms (e.g. IOS/Junos), however, they currently do not allow between the distinction of different device models/types that use the same NOS.

It'd be nice if it was possible to apply configuration contexts to devices in the same role  with the differences between models in mind.

### Use Case
To give you an idea of what device-specific configuration contexts could be used for: devices of the same role might have a single RE or dual REs, might be old equipment that's not able to use specific features, or simply might have a quirk or two that should needs a different handling.

This feature would be the most useful for those (including yours truly) whose configuration management templates are full of `{% if device.model == 'something_or_other' %}` conditionals (and for the tidier types as well, who have group variables for specific types :)).

### Database Changes
A new field (device_types) needs to be added to the ConfigContext model.

### External Dependencies
None.

### Additional note
There is an implementation of this addition in [my fork's 'config-context-device-type' branch](https://github.com/vista-/netbox/tree/config-context-device-type). The addition of the device_type field was fairly straightforward and I'd expect more seasoned NetBox developers to implement it similarly. :)

**Comment by jeremystretch** [comment] 2020-10-08 17:54
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #3305 for further discussion.

**Comment by vista-** [comment] 2020-10-08 18:16
I'd like to digress on that config contexts and physical hardware have no relation; NetBox is frequently used as an inventory / source of truth for configuration management of network devices, and it seems to me that the main use of configuration contexts is to automate configuration generation.

Sadly, we don't live in an ideal world where each device acts the same way, and might require some additional quirks to properly configure. I'd love to be able to store toggles / additional configuration to work with the limitations (or additional capabilities) of different device types in my singular source of truth.

In my eyes, being able to distinguish between device types from a configuration perspective via NetBox would be useful, and would make me less dependent on non-NetBox-sourced configuration toggles, and given that my goal is to make NetBox _the_ source of truth in my network, it'd enable me (and not just me, I figure) to work towards that goal.

**Comment by jeremystretch** [comment] 2020-10-08 19:14
This wouldn't be as useful as you're assuming.

> devices of the same role might have a single RE or dual REs

Plenty of devices of the same model may have single or dual REs. This cannot be inferred from the device model.

> might be old equipment that's not able to use specific features

Sounds like a good use for platform assignment.

> or simply might have a quirk or two that should needs a different handling

Tags work wonderfully for addressing such corner cases.

**Comment by jeremystretch** [comment] 2020-10-14 20:35
Looks like this is actually a duplicate of #4833.

**Closed by jeremystretch** 2020-10-14 20:35 UTC
