### ISSUE TITLE
Can't go to cable by clicking on ID

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#9791] opened 2022-07-20 09:07 UTC
### NetBox version

v3.3.0-beta1

### Python version

3.9

### Steps to Reproduce

1. Go to a device with interfaces
2. Create a Cable connected to e.g. a FP
3. Click on the Cable ID in the Interface overview of the device

It also doesn't work if I click on the ID on any other page

### Expected Behavior

Cable page should be shown

### Observed Behavior

```
<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'cable_add' not found. 'cable_add' is not a valid view function or pattern name.

Python version: 3.9.5
NetBox version: 3.3.0-dev
```

**Comment by jeremystretch** [comment] 2022-07-20 12:34
I'm not able to reproduce this behavior. Please try again using a current copy of the `feature` branch. If you are able to reproduce this, please amend your post above to provide *exact* instructions for doing so.

**Comment by PaulR282** [comment] 2022-07-20 12:58
I think I found the problem: the current feature tag from the docker hub is v3.3.0-dev and not v3.3.0-beta1.

**Comment by DanSheps** [comment] 2022-07-21 13:42
Can you reproduce this on beta?

**Comment by PaulR282** [comment] 2022-07-21 13:55
> Can you reproduce this on beta?

Didn't have the chance to try the beta because I'm building an own image using the docker hub and the tags aren't up to date #9808

**Comment by jeremystretch** [comment] 2022-07-22 13:02
Sounds like this has likely already been resolved, so I'm going to close this. Happy to re-open if the issue resurfaces.

**Closed by jeremystretch** 2022-07-22 13:02 UTC
Labels: type: bug, status: revisions needed, beta
