### ISSUE TITLE
[GraphQL] Querying connected endpoints on device_list does not work

### ISSUE THREAD

**Issue by felixschndr** [netbox-community/netbox#16386] opened 2024-06-03 11:17 UTC
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.12

### Steps to Reproduce

Running this graphql query
```graphql
query getAllICPRouters {
  device_list {
    id
    interfaces {
      id
      connected_endpoints {
        ... on InterfaceType {
          id
        }
      }
    }
  }
}
```
throws the following error
```json
{
  "data": null,
  "errors": [
    {
      "message": "The type \"<class 'dcim.models.sites.Site'>\" cannot be resolved for the field \"connected_endpoints\" , are you using a strawberry.field?",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "device_list",
        3376,
        "interfaces",
        16,
        "connected_endpoints",
        0
      ]
    }
  ]
}
```

I wonder why this error appears as I am not querying anything about `Site`s.

----

Running the same query on version 3 (before the graphql change) does work.

---

Running the same query on a `device` instead of the `device_list` does work as well:
```graphql
query getAllICPRouters {
  device (id: 8874) {
    id
    interfaces {
      id
      connected_endpoints {
        ... on InterfaceType {
          id
        }
      }
    }
  }
}
```
```json
{
  "data": {
    "device": {
      "id": "8874",
      "interfaces": [
        {
          "id": "53320",
          "connected_endpoints": [
            {
              "id": "53315"
            }
          ]
        },
        {
          "id": "53321",
          "connected_endpoints": [
            {
              "id": "53317"
            }
          ]
        },
[...]
}
```

----

The error seems to be correlated to the `connected_endpoints` statement as this
```graphql
query getAllICPRouters {
  device_list {
    id
    interfaces {
      id
    }
  }
}
```
works.

### Expected Behavior

Return the wanted data

### Observed Behavior

The error `The type \"<class 'dcim.models.sites.Site'>\" cannot be resolved for the field \"connected_endpoints\" , are you using a strawberry.field?` was raised and no data was returned

**Comment by arthanson** [comment] 2024-06-04 16:52
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v4.0.3. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

@felixschndr I ran your query on my data and was able it worked as you can see in the screenshot - I have both connected and not connected endpoints.   It could potentially be something in your data, if you could possibly narrow it down and update this with a way for it to reproduce.

![Monosnap GraphiQL | NetBox 2024-06-04 09-33-55](https://github.com/netbox-community/netbox/assets/99642/0c54362b-e3e6-4d4d-b444-3fb4fdb61c13)

**Comment by jeremystretch** [comment] 2024-06-04 16:58
@felixschndr see if you're able to determine the specific interface on which it's failing, and what that interface is connected to. I wonder if the reference to site implies a circuit termination.

**Comment by felixschndr** [comment] 2024-06-10 07:25
Just a quick update: We will migrate to Netbox 3.7 in the next few weeks. After that we will take a closer look at which data causes the bug. Will keep you up-tp-date

**Comment by jeremystretch** [comment] 2024-06-10 12:04
@felixschndr ok, I'm going to close this issue in the meantime. Once you've updated it with information sufficient to resume investigation, we'll be happy to re-open it.

**Closed by jeremystretch** 2024-06-10 12:04 UTC
Labels: type: bug, status: revisions needed, topic: GraphQL
