### ISSUE TITLE
Connection field in dcim/interfaces/ behaves different from versions >= 3.3.x

### ISSUE THREAD

**Issue by Bierfass** [netbox-community/netbox#10421] opened 2022-09-20 15:26 UTC
### NetBox version

v3.3.4

### Python version

3.8

### Steps to Reproduce

1. Set up Netbox version 3.3.4 and 3.2.9
2. Create a device1 with 1 interface
3. Create a device2 with 1 front and rear port
4. Connect interface from device1 with front port of device 2
5. Compare the view from /dcim/devices/device1_id/interfaces/

### Expected Behavior

The last endpoint should be displayed in the _Connection_ field, regardless of the type (Front, Rear, Interface). According to my understanding the representation is more correct in the versions <=3.3. I could not find any related changelog, issue or discussion on that topic.

### Observed Behavior

In Netbox version 3.3 or higher the _Connection_ field is empty.

**Comment by Omripresent** [comment] 2022-09-20 17:04
I'm seeing a similar behavior running v3.3.4, while creating a new cable using a custom script
```python
cable = Cable.objects.create(
            a_terminations=[term_a],
            b_terminations=[term_b],
            type=type,
            color=color,
            status=status,
            tenant=tenant,
        )
```

If I manually edit and save (without any changes) the connection field of term A is populated.
I think there's a problem with the cable path tracing system but I can't point to the exact issue just yet.

**Comment by kkthxbye-code** [comment] 2022-09-23 05:22
@Omripresent - Your issue is not related to this issue.

[Please see my reply here for info on how to properly use the internal API for creating cables.
](https://github.com/netbox-community/netbox/discussions/10199#discussioncomment-3501406)

**Comment by jeremystretch** [comment] 2022-09-26 19:52
Marking this as a duplicate of #10460

**Closed by jeremystretch** 2022-09-26 19:52 UTC
Labels: type: bug
