### ISSUE TITLE
Adding a new model within a model

### ISSUE THREAD

**Issue by opensourceXnetbox** [netbox-community/netbox#15847] opened 2024-04-25 09:21 UTC
### NetBox version

v3.7.5

### Feature type

New functionality

### Proposed functionality

This feature will be affect all models to be created.

I would like to be able to create model dependencies directly in the model to be created. 

Current workflow via the GUI:

1. create device
2. create "Device role", "Device Type" and "Site" in a new browser tab
3. jump back to the device creation
4. select newly created models
5. complete the creation of the device

I wish the following workflow in the future:

1. create device
2. all dependency models or simply all models have a plus button for creating a model within a model
3. an overlay page pops up where I can make exactly the same settings as directly under the specific model
4. the new model can now be created
5. the new model is now directly preselected and I don't have to search for it
6. complete the creation of the device

Here are two design options:
Option 1:
![2024-04-25-netbox-add-button-1](https://github.com/netbox-community/netbox/assets/110609354/5a474d53-ac48-461c-b422-ca07eaff2011)

Option 2:
![2024-04-25-netbox-add-button-2](https://github.com/netbox-community/netbox/assets/110609354/23e1d00d-78ce-42c4-b2d2-4b3d105eeef7)

Popup:
![2024-04-25-netbox-add-button-popup](https://github.com/netbox-community/netbox/assets/110609354/97e3831a-a2dd-40c3-b928-a36587b08d0a)

### Use case

This feature affects all models with creation functionality. It helps to create new devices, sites and so forth, faster and with more overview. 

### Database changes

i don't think so

### External dependencies

i don't think so

**Comment by arthanson** [comment] 2024-04-25 14:48
Good suggestion, dupe of #5858 so closing this one.  Please see comments on that issue and any details you think might be missing.

**Closed by arthanson** 2024-04-25 14:48 UTC
Labels: type: feature
