### ISSUE TITLE
Not visible buttons to connect cable / Not visible hover on button "Connect cable"

### ISSUE THREAD

**Issue by radim-ek** [netbox-community/netbox#7223] opened 2021-09-09 07:32 UTC
### NetBox version

v3.0.0

### Python version

3.8

### Steps to Reproduce

In Device->Interface hover over green button "Connect cable" is not visible hoover text.

If you click on this button, you can not see all commands "Interface/Front Port/Rear Port/Circuit Termination" if you have only few Interfaces.

[https://imgur.com/a/aLsKi0B](https://imgur.com/a/aLsKi0B)

### Expected Behavior

See hover info
See all comands without needed to scroll.

### Observed Behavior

Not see because bad "Z-index"?

**Comment by tombe75** [comment] 2021-09-09 07:59
Duplicate of #7179 , should be solved in 3.0.2

**Comment by radim-ek** [comment] 2021-09-09 08:02
> 
> 
> Duplicate of #7179 , should be solved in 3.0.2

Thank you :) I try to search but didnt find that.

**Closed** 2021-09-09 08:02 UTC
Labels: type: bug
