### ISSUE TITLE
Platform for Device can only be selected if Platform does not have a Manufacturer.

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#9550] opened 2022-06-17 09:40 UTC
### NetBox version

v3.2.4

### Python version

3.10

### Steps to Reproduce

- Under Device, create a Platform with Manufacture and one without Manufacture. 
![image](https://user-images.githubusercontent.com/46369917/174271284-aef232c0-d4fb-4dbe-9014-75ea6ad3d43d.png)

- Create any other Manufacture e.g. APC

- Create a device
- First click on the Platform drop-down list. | Result: All platforms are listed.

![image](https://user-images.githubusercontent.com/46369917/174272233-8c781f33-c940-48d1-bba7-01c7946f4943.png)

Select any manufacturer e.g. APC | Result: Only the operating systems that do not have a Manufacture are listed.
![image](https://user-images.githubusercontent.com/46369917/174272405-b454e5df-06ca-4217-9719-520dee6473a7.png)

### Expected Behavior

Selection of the software platform should always be possible.

### Observed Behavior

Platform cannot be selected during decive if Platrom has specified a Manufacturer.

**Comment by cybarox** [comment] 2022-06-17 12:34
That's not a bug, that's by design. When you create a new device from the manufacturer cisco, the corresponding platforms are also displayed where cisco is set as the manufacturer.

So device manufacturer and platform manufacturer match each other. 

The other way around: If no manufacturer is set for platforms, these can apply to devices of every manufacturer.

**Comment by jeremystretch** [comment] 2022-06-17 12:57
@cybarox is correct; the assignment of a manufacturer to a platform is optional and needed only when it is desirable to restrict the assignment of a platform to devices "owned" by a specific manufacturer.

I'm going to close this out as there is no action to be taken.

**Closed by jeremystretch** 2022-06-17 12:57 UTC
Labels: type: bug

**Comment by LHBL2003** [comment] 2022-06-18 13:17
Ok, then I have misunderstood. I assumed that Windows 7, Windows 10, Server 2019, Server 2022 would be grouped together under Microsoft. :)

Therefore, the selection of VMs is unrestricted. Since there is no manufacturer here.

But then that was a thinking error on my part.

THX
