### ISSUE TITLE
logout results in an exception

### ISSUE THREAD

**Issue by whtkam** [netbox-community/netbox#13854] opened 2023-09-21 20:00 UTC
### NetBox version

v3.6.2

### Python version

3.8

### Steps to Reproduce

logout from netbox

### Expected Behavior

get to login page

### Observed Behavior

<class 'ValueError'>

Field 'object_id' expected a number but got 'chgftoee0s8s8u25n9bpjuprk3gm0pye'.

Python version: 3.9.11
NetBox version: 3.6.2
Plugins: 
  netbox_attachments: 3.0.0
  netbox_bgp: 0.11.0
  netbox_documents: 0.6.0
  netbox_ipcalculator: 1.1
  netbox_qrcode: 0.0.10
  netbox_topology_views: 3.7.0

**Comment by jeremystretch** [comment] 2023-09-21 20:02
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.6.2. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

I'd suggest starting by disabling the plugins you have installed.

**Comment by abhi1693** [comment] 2023-09-22 04:22
This is a bug due to the netbox attachment plugin and was fixed in v3.0.1.

**Closed** 2023-09-22 04:22 UTC
