### ISSUE TITLE
FHRP Group Assignment not possible

### ISSUE THREAD

**Issue by basti1508** [netbox-community/netbox#8435] opened 2022-01-22 15:29 UTC
### NetBox version

v3.1.6

### Python version

3.8

### Steps to Reproduce

1. Create an FHRP Group (eg. VRRP2, id 12)
2. Goto Virtual Machine Interface and hit "assign FHRP Group"
3. Group is not shown in the list

Furthermore if I assign an IP Address to the group which is not in the subnet of the VMs IP, the FHRP Group is not shown either.

### Expected Behavior

It should be possible to assign an FRHP group regardless of the virtual ip address.

### Observed Behavior

see above

**Comment by jeremystretch** [comment] 2022-01-24 20:25
> 1. Create an FHRP Group (eg. VRRP2, id 12)
> 2. Goto Virtual Machine Interface and hit "assign FHRP Group"
> 3. Group is not shown in the list

Your instructions do not reproduce the reported behavior. The group does appear if there is no IP address assigned to the interface, as expected. If there _is_ an IP address assigned, only FHRP groups with a related IP address assigned are displayed as options. This behavior is intended, and avoids the user from having to select from hundreds of potential groups.

**Closed by jeremystretch** 2022-01-24 20:25 UTC
Labels: type: bug
