### ISSUE TITLE
Swagger UI generates wrong Request URL

### ISSUE THREAD

**Issue by SignalR-Dev** [netbox-community/netbox#12465] opened 2023-05-04 07:12 UTC
### NetBox version

v3.5.0

### Python version

3.8

### Steps to Reproduce

1. Go to Swagger UI on the demo Page `https://demo.netbox.dev/api/schema/swagger-ui/#/status/status_retrieve`
2. Try
3. Execute

### Expected Behavior

Get Request with the URL https://demo.netbox.dev/api/status/

### Observed Behavior

Get Request with URL https://demo.netbox.dev/api**/api**/status/
which Results in an 404 

There is an additional /api in the path

**Comment by kkthxbye-code** [comment] 2023-05-04 07:20
Duplicate of https://github.com/netbox-community/netbox/issues/12410

**Closed by kkthxbye-code** 2023-05-04 07:20 UTC
Labels: type: bug
