### ISSUE TITLE
IP address creation is incosistent in automatic VRF/Tenant assignment

### ISSUE THREAD

**Issue by Kircheneer** [netbox-community/netbox#5800] opened 2021-02-12 09:43 UTC
### Environment
* Python version: 3.9.1
* NetBox version: v2.10.4

### Steps to Reproduce
1. Create a tenant 'Test'
2. Create a VRF 'Test'
3. Create a prefix '10.0.0.0/24' within the created tenant and VRF
At this point the inconsistency starts. When clicking on the green plus icon in the top right to add an IP address, the tenant and VRF are pre-filled. When clicking on the 'xyz IPs available' button in the table, they are not pre-filled.

### Expected Behavior
Pre-filled VRF and tenant for both buttons.

### Observed Behavior
Inconsistency. Pre-filling for green plus, no pre-filling for button in the table.

**Comment by DanSheps** [comment] 2021-02-15 17:35
Duplicate of #5703

**Closed** 2021-02-15 17:35 UTC
Labels: status: duplicate
