### ISSUE TITLE
ObjectVar Prefix.objects.all() not displaying any prefixes in custom scripts fields.

### ISSUE THREAD

**Issue by kerwbstomp** [netbox-community/netbox#4557] opened 2020-04-29 20:40 UTC
### Environment
* Python version: python3.6
* NetBox version: 2.7.12

### Steps to Reproduce
1. Create a custom script with ObjectVar  as follows:

```
    prefix_assignment = ObjectVar(
    description="Select Parent Prefix to be assigned.",
    queryset = Prefix.objects.all()
```

2. Place script in '/opt/netbox/netbox/scripts/'
3. Go to url "http://netbox.test/extras/scripts"
4. Click on script, click on ObjectVar field
5. Nothing drops down.

### Expected Behavior

A list of created prefixes would drop down in the ObjectVar field set with Prefix.objects.all()

Other objects query fine via the same syntax i.e VRF.objects.all(), Tenants.objects.all()

### Observed Behavior

No prefixes are observed in the drop down list 
Django queries from shell work fine

```
>>> Prefix.objects.all()
<PrefixQuerySet [<Prefix: 10.0.0.0/8>, <Prefix: 10.6.6.0/23>]>


>>> for prefix in Prefix.objects.all():
...     print (prefix.prefix, prefix.id)
... 
10.0.0.0/8 3
10.6.6.0/23 2
```

It also does not show prefixes when using filters or specifying a specific attribute, ie. 'id' or 'prefix', it seems to be only for Prefix queries.

**Comment by ctrowat** [comment] 2020-04-30 18:42
This is related to #4463, you have to use something like this to make them appear:

```
 widget=APISelect(
            api_url='/api/ipam/aggregates/',
            display_field='prefix',
        )
```

The problem is that the returned object doesn't contain a "name" field and so all the entries get ignored / collapsed to the empty value by the UI control.  Using the APISelect widget lets you specify the displayed field and then the control behaves better.

**Comment by jeremystretch** [comment] 2020-05-06 17:07
Marking this as a duplicate since the root issue has been raised already.

**Closed by jeremystretch** 2020-05-06 17:07 UTC

**Comment by kerwbstomp** [comment] 2020-05-20 16:53
> This is related to #4463, you have to use something like this to make them appear:
> 
> ```
>  widget=APISelect(
>             api_url='/api/ipam/aggregates/',
>             display_field='prefix',
>         )
> ```
> 
> The problem is that the returned object doesn't contain a "name" field and so all the entries get ignored / collapsed to the empty value by the UI control. Using the APISelect widget lets you specify the displayed field and then the control behaves better.

I am getting an error when using widgets on v2.7.12

<class 'NameError'>

name 'APISelect' is not defined

do i need to specifically import the widget in the custom script?
