### ISSUE TITLE
Tenants tag__ic does not filter

### ISSUE THREAD

**Issue by mostdaysarebaddays** [netbox-community/netbox#13929] opened 2023-09-28 14:17 UTC
### NetBox version

3.6.1

### Python version

3.8

### Steps to Reproduce

"__ic" filtering doesn't work on tenants - nothing is filtered - "__n" works fine to exclude

### Expected Behavior

Only return tenants with a certain word in their tag

### Observed Behavior

All tenants returned.

**Comment by arthanson** [comment] 2023-09-28 18:15
tags only support the base filter and __n.  The easiest way to see the supported filters is via the swagger docs (https://demo.netbox.dev/api/schema/swagger-ui/#/circuits/circuits_circuits_list) screenshot shown below for tags:
![Monosnap NetBox REST API 2023-09-28 11-12-36](https://github.com/netbox-community/netbox/assets/99642/07314304-b4d1-4bf4-897e-d5410212c943)

**Comment by arthanson** [comment] 2023-09-28 18:16
Closing as not a bug.

**Closed by arthanson** 2023-09-28 18:16 UTC
Labels: type: bug, severity: low
