### ISSUE TITLE
Autofill VRF when adding address through prefix

### ISSUE THREAD

**Issue by Lombra** [netbox-community/netbox#5846] opened 2021-02-21 11:35 UTC
### Environment
* Python version: 3.9.1
* NetBox version: 2.10.3

### Proposed Functionality
When adding a new IP address via a prefix (`/ipam/prefixes/<id>/ip-addresses/`) that is associated with a VRF, automatically select this VRF in the creation form. Similar to how adding devices via racks, or VLANs via VLAN groups, work.

### Use Case
When adding an an address via a specific prefix, logically you would do so with the intent of having the new address in the same VRF, so autofilling this seems sane to me. Not realising the current behavior, I have done this myself a few times and ended up with addresses in the global VRF, confusing me later.

### Database Changes
None.

### External Dependencies
None.

**Comment by DanSheps** [comment] 2021-02-22 18:40
Duplicate of #5703

**Closed** 2021-02-22 18:40 UTC
Labels: status: duplicate
