### ISSUE TITLE
'NoneType' object has no attribute 'pk'

### ISSUE THREAD

**Issue by aiv** [netbox-community/netbox#11006] opened 2022-11-23 07:14 UTC
### NetBox version

v3.3.5

### Python version

3.8

### Steps to Reproduce

1. Try to edit ip address assigned to virtual machine with nat on that ip

### Expected Behavior

Edit form

### Observed Behavior

```
<class 'AttributeError'>

'NoneType' object has no attribute 'pk'

Python version: 3.8.10
NetBox version: 3.3.5
```

and in logs:

```
Internal Server Error: /ipam/ip-addresses/2567/edit/
Traceback (most recent call last):
  File "/opt/netbox-3.3.5/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/netbox-3.3.5/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox-3.3.5/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/netbox/views/generic/object_views.py", line 302, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/utilities/views.py", line 90, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox-3.3.5/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox/netbox/netbox/views/generic/object_views.py", line 353, in get
    form = self.form(instance=obj, initial=initial_data)
  File "/opt/netbox/netbox/ipam/forms/models.py", line 420, in __init__
    initial['nat_cluster'] = nat_inside_parent.virtual_machine.cluster.pk
AttributeError: 'NoneType' object has no attribute 'pk'
```

**Comment by kkthxbye-code** [comment] 2022-11-23 08:18
Duplicate of https://github.com/netbox-community/netbox/issues/10997

**Closed by kkthxbye-code** 2022-11-23 08:18 UTC
Labels: type: bug
