### ISSUE TITLE
Webhook not send change tagged vlans with first try

### ISSUE THREAD

**Issue by brandelf68** [netbox-community/netbox#6294] opened 2021-04-27 20:26 UTC
### NetBox version

v2.11.2

### Python version

3.8

### Steps to Reproduce

1. Add webhook on updating dcim->interface to URL http://localhost:9001 without ssl verify, HTTP method: POST,
HTTP content type: application/json
2. Run on terminal session command "nc -4 -l localhost 9001"
3. Create device and component "interface"
4. Create one or more vlans
5.  Click "edit" interface on device.
6. Select mode "tagged".
7. Add tagged vlan or vlans
8. Press "update".

### Expected Behavior

Output JSON on terminal session with running netcat include data with the tagged vlans

### Observed Behavior

Output JSON on terminal session with running netcat not include recently added tagged vlans.
After second try to enter in "edit interface" dialog and press update without any change, output shows added tagged vlans.

**Comment by jeremystretch** [comment] 2021-04-27 23:57
VLAN associations utilize a many-to-many relationship, which requires two operations on the database. Incidentally, this just came up in #6284; please see my comments there for more background. The second webhook sent by NetBox will contain the VLAN assignments.

Also, FYI: You can run `manage.py webhook_receiver` locally on the NetBox server and point webhooks to `http://localhost:9000` for convenient testing.

**Comment by jeremystretch** [comment] 2021-05-04 13:38
Closing this out as effectively a duplicate of #6284; will focus discussion there.

**Closed by jeremystretch** 2021-05-04 13:38 UTC
Labels: type: bug
