### ISSUE TITLE
Netbox 'Platforms' Device Count not updated when adding Platform type

### ISSUE THREAD

**Issue by nathanaelpearson** [netbox-community/netbox#4906] opened 2020-07-27 12:47 UTC
Environment
Python version: 3.6.9
NetBox version: v2.8.8

Steps to Reproduce
Update a device with a platform created in the 'Platform' section.
navigate to the Platform List
View 'Devices' Column

Observed Behavior
Counter remains at 0, however when you click on the 0, it takes you to a list of devices with this 'Platform'.
Also found that a device that did have a previous platform and changed to a new one still shows in the previous platform column.

Resolution Steps
Only way to update the field is to delete the 'Platform' and recreate it.

**Comment by jeremystretch** [comment] 2020-07-27 13:21
This looks like essentially the same issue described in #3672: a limitation of the caching function. If you disable caching (by setting `CACHE_TIMEOUT=0` in `configuration.py`), does it resolve the issue? This would confirm that it's a caching issue.

**Comment by nathanaelpearson** [comment] 2020-07-27 14:33
> This looks like essentially the same issue described in #3672: a limitation of the caching function. If you disable caching (by setting CACHE_TIMEOUT=0 in configuration.py), does it resolve the issue? This would confirm that it's a caching issue.

HI, I have changed the Cache Timeout in the config to 0, restarted the Netbox service and restarted the server but still have the same issue.  The platform list shows 0 but when you click on the platform name it shows the device.

Kind regards

**Comment by jeremystretch** [comment] 2020-07-27 15:00
Sorry; this is a duplicate of #4894 and has been fixed for the next release. Apologies for not catching that earlier.

**Closed by jeremystretch** 2020-07-27 15:00 UTC
